### ISSUE TITLE
Can't Unassign licenses from multiple users

### ISSUE THREAD

**Issue by Robertschv** [MicrosoftDocs/microsoft-365-docs#10066]
**Unassign licenses from multiple users**

The Button to "Manage product licenses." is not there anymore.

Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d850211-99b4-faf7-09fc-4621919dd74b
* Version Independent ID: 9b294f13-b1e3-291e-25a1-75f7c5755b6c
* Content: [Unassign licenses from users - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/remove-licenses-from-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/remove-licenses-from-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/remove-licenses-from-users.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Robertschv Thank you for your feedback. I was able to test this in a couple of tenants and I could locate the manage product licenses

![image](https://user-images.githubusercontent.com/45987684/198256779-2d0b7fbf-2485-4239-9281-ddff8dae4d6c.png)


If you continue to have this problem, I recommend contacting support via the need help section on the admin center, so that a support engineer can work with you and fix it.

Hope this helps!

Thanks
Sri
