### ISSUE TITLE
RSS feed link not able to be used in Outlook

### ISSUE THREAD

**Issue by kdwatt15** [MicrosoftDocs/microsoft-365-docs#10085]
The link to this RSS feed is not able to be used in outlook. The suggested format provided by Outlook is "https://www.example.com/feed/main.xml". The URL provided at the link accessible from this page is https://endpoints.office.com/version/worldwide?allversions=true&format=rss&clientrequestid={client request ID}.

Is there a way to get a link that will work with both Outlook and Microsoft Power Automate so that we can be notified of changes to this RSS feed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
