### ISSUE TITLE
Enable Users to Protect

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#10110]
From here:
https://learn.microsoft.com/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#impersonation-settings-in-anti-phishing-policies-in-microsoft-defender-for-office-365

_"When you add internal or external email addresses to the Users to protect list, messages from those senders are subject to impersonation protection checks. The message is checked for impersonation if the message is sent to a recipient that the policy applies to (all recipients for the default policy; Users, groups, and domains recipients in custom policies). If impersonation is detected in the sender's email address, the impersonation protections actions for users are applied to the message (what to do with the message, whether to show impersonated users safety tips, etc.)."_

What impersonation protection checks are performed?  Over the years, I've seen customers think its email address looking the same, display name looking the same, customers have added combined display/emails and a mix of multiple other misconfiguration because this is not clear.

If for example internally I have a CEO named Jim Smith (jsmith@contoso.com) and our display names are Last, First (Smith, Jim) - and someone emails from jimsmith@gmail.com with display name of "Jim Smith" - should that hit this policy?  We need more explicit definitions to help customers build effective configurations.

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide#common-policy-settings)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@chrislehr, user impersonation protection checks a combination of the display name and the email address. It's a balancing act between explaining what's being checked and how vs. giving attackers a roadmap by being so clear.

The fundamental exercise of impersonation protection is identifying the users to protect (300 or less, so you can't use user impersonation protection on everyone, although mailbox intelligence has no such limitations). After that, it's monitoring hits using the [impersonation insight](https://learn.microsoft.com/microsoft-365/security/office-365-security/impersonation-insight) and reporting any false positives or false negatives to Microsoft.

So, to answer your question, yes, if your CEO is named Jim Smith and a Jim Smith sends email to a recipient who's protected by user impersonation protection, the messages might get flagged as an impersonation attempt. But prior history also is a factor: if that protected recipient and the other Jim Smith have an email communication history, messages from that Jim Smith won't get flagged as impersonation attempts.

**Comment by chrislehr** [comment]
300, 301, or 350 users?   I see all three represented here now.  Also, some guidance on adding multiple email/displaynames please?  In Pshell, you can add Jim Smith (jsmith@contoso.com) and Smith, Jim (jsmith@contoso.com) but then the Web UI shows that there are two entries and can only display one, and then future Web UI updates clobber the PowerShell settings.  The lack of guidance on what is best practices for adding items here leads to these customer admin frustrations and as a partner I have a hard time explaining to customers what Microsoft's expectations are when the documentation is light.  I understand the need for some secrecy around how it works, but customer best practices shouldn't need to be kept secretive right?  Should customer admins feel the need to add complicated display name deltas here, or is it safe to assume the AI is doing this for you?

**Comment by yogkumgit** [comment]
@chrisda Please comment

**Comment by chrisda** [comment]
Nothing new to add. For more clarification, you can try opening a support ticket and reporting back here with any information that can help improve the documentation.

**Comment by Soolkiki** [comment]
Please review ticket Case #:33459984. I tried bringing up that our CEO was being impersonated by some random email from an IP in another country. Microsoft marked the email as spoofing because it wasn't from a "valid" domain. Here was their explanation:

_According to the Article, it states that:
Domain impersonation is different from domain spoofing, because the impersonated domain is typically a real, registered domain. Messages from senders in the impersonated domain can and often do pass regular email authentication checks that would otherwise identify spoofing attempts (SPF, DKIM, and DMARC).

If we look at the message headers, they failed SPF, Dmarc etc which did not qualify to marked as impersonation._

Here's the thing: This is a highly specific situation. So, what I saw were some random domains trying to impersonate my high value users because the hackers didn't take the time to register and validate a real domain. It then delivered the malicious emails to the users quarantine for them to release to their inbox, effectively making the impersonation rule worthless.  Every other impersonation protection tool out there basically checks to see if the email and username in the headers are coming from my domain. If not, it's impersonation. How does the tool know? I told it to watch for the users I added to the list.

Microsoft's way still confuses users and takes power away from admins because you either shift a lot of work to the admin by requiring them to monitor and release normal-confidence spoofing emails which the users should be managing, or you risk users releasing emails from quarantine they think are from their CEO. 

Do you see where I'm coming from? I'm coming here since the ticket was absolutely worthless and the agent kept quoting this documentation to me, no matter my qualms with the implementation.

**Comment by chrisda** [comment]
@Soolkiki, according to [this article](https://learn.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined), spoofing protection is earlier in the filtering stack than user impersonation, so that's why the message was classified as spoof.

Whenever Microsoft filtering gets something wrong, you should always report the false positive/negative to Microsoft as described [here](https://learn.microsoft.com/microsoft-365/security/office-365-security/submissions-admin).

You should also consider using a different quarantine filter policy so users can't directly release messages that were detected as spoof. Maybe set the quarantine policy so users can _request_ release of those messages instead?

Anyway, that's all I have.

Thanks for the feedback.

Closing
