### ISSUE TITLE
The details on this page don't tell you how to configure the blocking to turn it off. This is a lengthy but detail free page.

### ISSUE THREAD

**Issue by shadcollins** [MicrosoftDocs/microsoft-365-docs#10111]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43299e41-87fe-d6f1-20f7-83791d8ef90b
* Version Independent ID: e5e69845-7040-f5b7-b922-e2d2fd9a7d5e
* Content: [Configuring and controlling external email forwarding in Microsoft 365. - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/external-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-email-forwarding.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by DMoenks** [comment]
The primary method to control external email forwarding is actually described in the second paragraph: Use outbound spam filtering in EOP. The paragraph also contains a link to [detailed instructions](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide) at the end.
The section _How the outbound spam filter policy settings work with other automatic email forwarding controls_ then describes interaction between outbound spam filtering and other features that impact mail flow, so that use cases can be mapped to a set of settings to achieve the desired outcome.

**Comment by msbemba** [comment]
@shadcollins Thank you for your feedback. The document talks about how to block, and there is another section that explains different use cases and the outcome in detail. 

![image](https://user-images.githubusercontent.com/45987684/199928112-46e2e530-12a0-4efd-943f-065a68dfc11c.png)
Hope this helps!

@yogkumgit  There are no changes required in the document as of now.
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @shadcollins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
