### ISSUE TITLE
Please add better steps

### ISSUE THREAD

**Issue by jt980** [MicrosoftDocs/microsoft-365-docs#10128]
Your instructions say "in the admin center" go to settings.  What admin center - Azure, Office, other?  Neither Azure nor Office have a "Settings" blade.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b13e4c14-5b0a-a4f6-1e65-7c79e49a0f10
* Version Independent ID: ec4223f2-8127-7605-07a0-306c4d412fed
* Content: [Managing user consent to apps in Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/misc/user-consent?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/user-consent.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/user-consent.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by DMoenks** [comment]
I would guess "admin center" refers to the [Microsoft 365 admin center](https://admin.microsoft.com), due to...

- the article being part of the documentation for **Microsoft 365 admin center**
- the link provided in the [Turning user consent on or off](https://learn.microsoft.com/en-us/microsoft-365/admin/misc/user-consent?view=o365-worldwide#turning-user-consent-on-or-off) section linking to the **Microsoft 365 admin center**

**Comment by msbemba** [comment]
@jt980 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10167

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jt980 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
