### ISSUE TITLE
Yammer

### ISSUE THREAD

**Issue by robinmeure** [MicrosoftDocs/microsoft-365-docs#1018]
When will the Yammer locations be available to choose from? I don't see them in my first release tenant yet. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e514aa-9f04-5cc9-93f6-9f5f2f614c2a
* Version Independent ID: dea1ab15-bc09-05c1-b48b-1a06c0b53b50
* Content: [Content Search in Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search)
* Content Source: [microsoft-365/compliance/content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@robinmeure I assume that you mean the corresponding mailboxes for a Yammer Group is showing up in the picker when you selecting mailbox locations to search?  You might also try searching all mailboxes in the org and then using the ItemClass keyword or the Type condition card, as documented here: https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search#searching-yammer-groups

Otherwise, please see this Message Center post: https://admin.microsoft.com/AdminPortal/Home#/MessageCenter?id=MC199232  This issue may be related to this.

**Comment by robinmeure** [comment]
No, I am referring to the Yammer conversations and Yammer networks as depicted in the picture of the locations.

________________________________

**Comment by markjjo** [comment]
@robinmeure To search for conversations in a specific Yammer group, you would have to enter the email address of that Yammer group as the content location to search. To search for docs in a Yammer network, you would have to enter the URL for the corresponding SharePoint site.
