### ISSUE TITLE
article refers to old azcopy version 8.1 which is no longer available

### ISSUE THREAD

**Issue by jsimsmsft** [MicrosoftDocs/microsoft-365-docs#10218]
article references requiring azcopy 8.1 which is no longer available.  download link is dead.
currently the latest azcopy 10.16.2 works, but requires different command syntax; ie "--recursive" instead of "/s", no more /source or /dest switches etc

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6e20438-8387-bf21-297c-9feb5efe1f1c
* Version Independent ID: ee6a90dd-4050-fa9f-70f4-795f8e7bc3ca
* Content: [Load non-Microsoft 365 data into a review set - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/load-non-office-365-data-into-a-review-set?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/load-non-Office-365-data-into-a-review-set.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/load-non-Office-365-data-into-a-review-set.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@jsimsmsft Thank you for your feedback. We have made changes to the document to reflect the latest AZCOPY version, this can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10455

Once the author approves, the changes will be live.

Meanwhile, the upload section on the review sets still reflects the old dest and source switches instead of recursive. This will need to be fixed by PG, so I'm CCing the author for the same.

CC : @robmazz 
Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@jsimsmsft closing it as per author's comment in PR. Thanks
