### ISSUE TITLE
Update AllowList Urls With 1DS For Office365

### ISSUE THREAD

**Issue by trevorNgo** [MicrosoftDocs/microsoft-365-docs#10213]
js.monitor.azure.com
Required to ensure partners allow 1ds telemetry for account manager control brought in from header.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252farticle%252f8548a211-3fe7-47cb-abb1-355ea5aa88a2&view=o365-worldwide#exchange-online)
* Content Source: [microsoft-365/includes/office-365-worldwide-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/includes/office-365-worldwide-endpoints.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by trevorNgo** [comment]
Closing #10214

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
