### ISSUE TITLE
License requirement for Inactive Mailboxes?

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/microsoft-365-docs#10230]
Please clarify the license requirement for ”Inactive Mailboxes”. The article gives you the inpression as long as you are licensed for Retention Policies hold you are fine.

However, the Modern Work Comparison PDF (https://aka.ms/M365EnterprisePlans) show that ”Inactive Mailboxes” is not available for Microsoft 365 F5 Compliance (which has Retention Policies and Litigation Hold).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b1290-00ae-8f23-1b41-5ca692e6d1c4
* Version Independent ID: ab2acdbd-a620-86de-8544-e655aa386b0a
* Content: [Learn about inactive mailboxes - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/inactive-mailboxes-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@JonesMikael  I'm not following how this article gives you the impression as long as you are licensed for retention policies you are fine - I couldn't find the word "license" anywhere on this page and because of the complications of licensing and how often they can change with new options, we have removed these references to ensure we don't inadvertently provide out of date information. Instead, this page and others for data lifecycle management show a link at the top of the page to the authoritative licensing information. If the licensing info you need isn't there, please leave a GitHub Issue on that page for the relevant team.
