### ISSUE TITLE
Can a KQL Query with multiple property value conditions or wildcard matching be used as an Asset ID condition in an Event Trigger for SPO or OneDrive?

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#10233]
Per Step 7 in referenced guidance below, if triggering an Event for SharePoint documents, a property:value pair is used (AssetID, or an equivalent field from your Content Type). 

Does the AssetID condition leverage KQL, and can this be a KQL query, or does it only need to be a single property:value pair?

[Step 7: Enter keywords or a query, or asset ID for SharePoint and OneDrive](https://learn.microsoft.com/en-us/microsoft-365/compliance/event-driven-retention?view=o365-worldwide#step-7-enter-keywords-or-a-query-or-asset-id-for-sharepoint-and-onedrive)

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Yes, although not indicated in the UI, you can use keywords and a query for both workloads. That's why the documentation says: 

"Now you narrow the scope of the content. You do this by specifying keywords or a query [applicable for both workloads]. For SharePoint and OneDrive content, you can also [= in addition to keywords & a query] do this by specifying asset IDs."
