### ISSUE TITLE
Access Customer Data of Microsoft Bookings power platform connector

### ISSUE THREAD

**Issue by luisafrancoj** [MicrosoftDocs/microsoft-365-docs#10243]
Hi there ! 
I have checked the documentation and I see that all triggers return AppointmentData, however, I need to access to CustomerData because I need to read through power automate the custom questions and answers.

 

How can I get the customer data when the appointment is created?

**Comment by msbemba** [comment]
@luisafrancoj Thank you for your feedback. I was not able to find a document that refers to accessing Customer Data of the Microsoft Bookings power platform connector. I'd recommend you provide this feedback on our Main feedback portal (https://feedbackportal.microsoft.com/), so that our Dev/Prodcut engineers will be able to review and respond with more information related to your query.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@luisafrancoj Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
