### ISSUE TITLE
Misleading content

### ISSUE THREAD

**Issue by Keith1233** [MicrosoftDocs/microsoft-365-docs#1024]
Under Create a mail flow rule to filter bulk email messages based on text patterns, some of the expressions look to be HTML code. There should be a note that Outlook will explicitly check the plain-text content in the subject and/or body and not in the underlying HTML code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37115a33-d073-cf0d-1506-2d2571cf1007
* Version Independent ID: 07dd4b19-c5a5-1fba-cbad-3650922d357f
* Content: [Use mail flow rules to configure bulk email filtering in Exchange Online Protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-transport-rules-to-configure-bulk-email-filtering#feedback)
* Content Source: [microsoft-365/security/office-365-security/use-transport-rules-to-configure-bulk-email-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-transport-rules-to-configure-bulk-email-filtering.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by VLG17** [comment]
@Keith1233 The article mentioned refers to server-side rules (created in Exchange Admin Center), so we need to think about the inspection that is done in the backend (Exchange Online) and not on the client-side (Outlook).

Keeping this in mind, Exchange Online does look at HTML code, but from my experience i have to say that it will be picky in terms of the syntax you have used for your Mail flow rule Regex.

If one of your Mail flow rules is not firing for HTML content, i recommend [opening a support ticket](https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online), so that the engineers can look at your syntax, test it and confirm if it should/should not be working, and why.

**Comment by mypil** [comment]
@Keith1233  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
