### ISSUE TITLE
Add information about the expected outcome when encryption is added at a later stage

### ISSUE THREAD

**Issue by flmihai91** [MicrosoftDocs/microsoft-365-docs#10269]
[Enter feedback here]
In the section below, it is documented what is the expected result when encryption settings are changed for a label for existing documents.
However, nowhere in our documentation we state what happens when encryption is introduced at a later stage (for a label that did not have any previous protection defined):
 - https://learn.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide#what-happens-to-existing-encryption-when-a-labels-applied

In this case, it would be really useful to document this.

Thanks and regards,

Florina Mihai
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd3497a-c02a-5fd6-12db-3a093f0fe17c
* Version Independent ID: 2ef81556-61b0-47ae-d8fc-3d9aa5240c51
* Content: [Apply encryption using sensitivity labels - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide&source=docs#what-happens-to-existing-encryption-when-a-labels-applied)
* Content Source: [microsoft-365/compliance/encryption-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. thanks

**Comment by cabailey** [comment]
That's a fair comment - I'll look at adding this because it's a common label deployment strategy to add encryption to existing labels later on. Like most label settings though, the behavior is no different in that it applies going forward (newly labeled items) and not retrospectively (to existing labeled items). To apply encryption to already labeled items, you would need to remove the label and reapply it. 

You can think of labels as being the delivery mechanism for settings that get applied when the label is applied. There is a quirk with encryption, however - because behind the scenes this uses right management templates when you use the "Assign permissions now" option. If you apply encryption with this option and then edit the permissions, you don't need to reapply the label because the underlying template is checked when the user authenticates to the service. There's existing documentation for this behavior so I'll link to that so it's more easily discoverable.

**Comment by cabailey** [comment]
Live now: https://learn.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels#editing-labels-to-newly-apply-encryption-or-change-existing-encryption-settings
