### ISSUE TITLE
Contradictory information

### ISSUE THREAD

**Issue by posixltd** [MicrosoftDocs/microsoft-365-docs#10265]
This page says "A higher value indicates the message is less desirable (more likely to resemble spam)"
However, Office 365 admin page https://security.microsoft.com/antispam
says "A higher bulk email threshold means more bulk email will be delivered"
That's contradictory.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed2861d-860e-5d27-9259-fb9db2187f4b
* Version Independent ID: 09ef5622-3a7e-30f9-00f9-4c5578f8e1ca
* Content: [Configure spam filter policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@posixltd, that is my subject area, but text on UI pages is a code thing, which we can't fix here. I'll attempt to clarify, but the UI sounds wrong (that other description has been in content for a really long time (years)).

**Comment by chrisda** [comment]
Actually, on second look, the two statements aren't contradictory. In fact, there's a third place that talks about this, which is the info flyout next to **Bulk email** threshold title in the same UI:

![image](https://user-images.githubusercontent.com/33166947/201780793-c5257227-48c3-4dd6-89b9-9b504c9256f3.png)

A higher BCS score indicates a greater likelihood that the message is bad. So, if you crank the BCL threshold up, bad bulk email that would have otherwise been blocked will be delivered (more bulk email will be delivered). If you crank the BCL threshold down, more good bulk email will be blocked (less bulk email will be delivered). This is all very similar to how the spam confidence level (SCL) operates (low=good; high-bad).

The Standard preset security policy uses a BCL threshold of 6, while the Strict preset security policy uses a BCL threshold of 5.

**Comment by posixltd** [comment]
Hi Chris,

Thank you for your quick and helpful reply.  I had to read it several
times, but now I think you are correct!

I wonder if there is a way to make it clearer.  I doubt I'm the only one
confused by that.

Kind regards,

Richard
--

Posix Limited
http://www.posix.uk
0753 717 3877

**Comment by chrisda** [comment]
@posixltd, would it help if we flipped that text in the UI around to say:

> A lower bulk email threshold means more bulk email will be blocked.

**Comment by posixltd** [comment]
Hi Chris,

Yes that is clearer to me.

Thank you!

Richard


--

Posix Limited
http://www.posix.uk
0753 717 3877
