### ISSUE TITLE
Is UDP endpoint really REQUIRED?

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/microsoft-365-docs#10270]
I raised an [issue #6584](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6584) that proposes to add UDP requirement. Now I confirmed the table on this page includes the UDP requirement on ID 1 as below.

![image](https://user-images.githubusercontent.com/6519947/201915330-0f5b5a42-5f7e-44bc-800c-9196cb35ce49.png)

However, it is confusing for customers since the endpoint is categorized as **Required**. As far as I know UDP/443 is for HTTP/3 and is intended for performance optimization. We had several questions from customers if UDP is really REQUIRED or not. 

### Proposal

- If UDP/443 is really REQUIRED, I would like to ask you to add some notes on how to use UDP.
- If UDP/443 is optional and for performance optimization, I would like to ask you to split ID 1 into two separate entries: the first is a requirement about TCP, which is REQUIRED; the second is a requirement about UDP, which is OPTIONAL.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I do own the article in question, but because all M365 endpoints data is autogenerated by the [**Microsoft 365 endpoints web service**](https://aka.ms/o365ipws), I have no way to resolve issues directly related to endpoints data.
Changes to IP addresses and URLs for M365 services must be submitted with the [**Office 365 Endpoints Portal**](https://endpoints.office.net/) by someone on the engineering team responsible for the feature. Once a change has been submitted, the revised data will be updated in the web service and [endpoints articles](http://aka.ms/o365ip) at the next monthly update window.
For instructions on how to submit a change and manage endpoints data, see the [**M365 Endpoints user guide**](http://aka.ms/endpointshelp). 
If you need help finding the product group associated with an endpoint, or of you have any permissions issues with the links above, please contact [endfeedback@microsoft.com](mailto:endfeedback@microsoft.com). 
-Kelley
