### ISSUE TITLE
Unable to sort by exposureImpact

### ISSUE THREAD

**Issue by sengle312** [MicrosoftDocs/microsoft-365-docs#10319]
`exposureImpact` is not a sortable field for the List Vulnerabilities endpoint, but it is an extremely useful field to sort on via the API. Additionally, this field IS sortable in the Vulnerability Recommendations table in the Security Center console.  
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 839aff5a-5f31-8453-2c59-0fefdd5741c7
* Version Independent ID: 643df190-bddc-33ef-d89f-5bd40040f8ff
* Content: [List all recommendations](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-all-recommendations?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-all-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-all-recommendations.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@sengle312 Thank you for your feedback.  Currently, exposure impact is not a sortable field for the List Vulnerabilities endpoint, If you would like to have that feature added, I'd recommend you provide feedback directly to our prodcut/Dev team via the main feedback portal ( https://feedbackportal.microsoft.com/) so that they can look into it and provide you more information.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@sengle312 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
