### ISSUE TITLE
Transfer Subscription payments to a non Admin person

### ISSUE THREAD

**Issue by CharlesYeomans** [MicrosoftDocs/microsoft-365-docs#10311]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 805a04c5-96c4-ee47-7746-3105e0b7fc45
* Version Independent ID: 9efa7447-6731-6435-d4fc-8ba81344e85a
* Content: [Understand subscriptions and licenses in Microsoft 365 for business](https://learn.microsoft.com/en-us/microsoft-365/commerce/licenses/subscriptions-and-licenses?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/licenses/subscriptions-and-licenses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/subscriptions-and-licenses.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by CharlesYeomans** [comment]
I am admin and have been using my card in the company to pay for subscription.  Now I want to transfer that to our accountants card, but they are not Admin, is there a way to do this, I have searched and I cannot find any answer.

**Comment by msbemba** [comment]
@CharlesYeomans Thank you for your feedback. You cannot assign Subscription payments to a non-Admin person. In order to handle payments for a subscription one needs to be at least a Billing administrator. more details about the role can be found here - https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide#commonly-used-microsoft-365-admin-center-roles

If you have trouble assigning the role, I'd request you to contact support via the need help section in the admin center, so that they can assist you in fixing it.

Hope this helps!

Thanks
Sri

**Comment by CharlesYeomans** [comment]
Thanks
Actually I finally figured it out, but didn't know how to cancel my feedback.
Sorry for wasting you time.
Brilliant that you respond so well, thanks
Charles
