### ISSUE TITLE
Customize name field in booking page

### ISSUE THREAD

**Issue by Franky-74** [MicrosoftDocs/microsoft-365-docs#10380]
How can I customize name field in the booking page like splitting in first name and last name?

**Comment by msbemba** [comment]
@Franky-74 Thank you for your feedback. This sounds like a technical question and needs to be routed to our Microsoft support team. You can create a support ticket via the help and support option on the Admin center so that a support engineer will be able to assist you.

Hope this helps!

Thanks
Sri
