### ISSUE TITLE
How do I get access to the Tenant Switcher

### ISSUE THREAD

**Issue by michaelfromslc** [MicrosoftDocs/microsoft-365-docs#10440]
This is great at telling me about the Tenant Switcher but tells me knowing about how to get to it. I have multiple Tenants that I manage. Through B2B I home Directory account has been added as a Guest user and Assigned the Global Admin Roll. I can Switch between tenants just fine in Azure but when it Comes to the 365 Admin Center, I am running into Brick walls. 

Please provide a Step by step to unlock the Tenant Switcher in the 365 Admin Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b378de4-ca71-a16b-6669-369e3e3ff9d4
* Version Independent ID: 1a1a6ec6-8c04-2172-7afa-49d268191687
* Content: [Manage multiple tenants - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/multi-tenant/manage?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/admin/multi-tenant/manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/multi-tenant/manage.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@michaelfromslc Thank you for your feedback. 

The tenant switcher option in the admin center should automatically appear if your account has GA rights on multiple tenants.

![image](https://user-images.githubusercontent.com/45987684/206160227-4ffd093f-af51-4d07-9ba8-b7ae021caa59.png)

If you do not see the tenant switcher it could be a bug on the tenant(s). I'd recommend you contact support via the help and support option so that they can fix it.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @michaelfromslc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
