### ISSUE TITLE
*.cdn.office.net removed from the WW endpoints list

### ISSUE THREAD

**Issue by samuelec** [MicrosoftDocs/microsoft-365-docs#10457]
*.cdn.office.net was removed from the WW endpoints list https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide with this commit:

[Uploaded file: office-365-worldwide-endpoints.md - 2022-08-30 08:00:0… · MicrosoftDocs/microsoft-365-docs@e92e080 (github.com)](https://github.com/MicrosoftDocs/microsoft-365-docs/commit/e92e080607118f451a5ff0c832c8ec03c201457d)

- 47 | Default<BR>Required | No | `*.cdn.office.net, contentstorage.osi.office.net` | **TCP:** 443
+ 47 | Default<BR>Required | No | `*.office.net` | **TCP:** 443, 80

However, the *.cdn.office.net is heavily used for CDN assets by a lot of properties in M365. *.cdn.office.net is still present in GCCH, DoD, Gallatin. Was this a typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the [**Microsoft 365 endpoints web service**](https://aka.ms/o365ipws), the content team cannot resolve issues directly related to this data. We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question.
If you do not have a TAM assigned to your organization, please contact Microsoft Support.
