### ISSUE TITLE
Additional URLS needed for Microsoft 365 Common and Office Online

### ISSUE THREAD

**Issue by tilarso** [MicrosoftDocs/microsoft-365-docs#10491]
There are additional URLs that need to be added in the common M365 section. Specifically, those surrounding Identity end-user management experiences: 
- myaccount.microsoft.com
- myapplications.microsoft.com
- myapps.microsoft.com
- myaccess.microsoft.com
- launcher.myapps.microsoft.com
- mysignins.microsoft.com
- mygroups.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@tilarso Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data.

We recommend that you escalate your inquiry to the engineering team associated with the endpoint in question.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@tilarso Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
