### ISSUE TITLE
Microsoft 365 for profile cards endpoints ID 130 is missing from this article. 

### ISSUE THREAD

**Issue by maykul** [MicrosoftDocs/microsoft-365-docs#10513]
Powerapps customer engagement apps uses profile cards to see user information inside apps. 

Based on https://learn.microsoft.com/en-us/power-platform/admin/enable-profile-card , need to whitelist endpoint for connectivity from a user's machine to Microsoft 365 for profile cards. But the endpoint list with ID 130 is missing from this article https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online

Please update endpoint list with ID 130 in this article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I do own the article in question, but because all M365 endpoints data is autogenerated by the [**Microsoft 365 endpoints web service**](https://aka.ms/o365ipws), I have no way to resolve issues directly related to endpoints data.
Changes to IP addresses and URLs for M365 services must be submitted with the [**Office 365 Endpoints Portal**](https://endpoints.office.net/) by someone on the engineering team responsible for the feature. Once a change has been submitted, the revised data will be updated in the web service and [endpoints articles](http://aka.ms/o365ip) at the next monthly update window.
For instructions on how to submit a change and manage endpoints data, see the [**M365 Endpoints user guide**](http://aka.ms/endpointshelp). 
If you need help finding the product group associated with an endpoint, or of you have any permissions issues with the links above, please contact [endfeedback@microsoft.com](mailto:endfeedback@microsoft.com). 
-Kelley
