### ISSUE TITLE
Update request Default Retention Settings

### ISSUE THREAD

**Issue by contributor-luis** [MicrosoftDocs/microsoft-365-docs#10547]
[Enter feedback here]

Hi, I was working on a hold case and after escalating this incident PG confirms that "Default keep only policy do not tag the items but are used for hold enforcement. Only Delete or KeepAndDelete policy tag the items in exchange", can we add this Note or Tip into this session for future visibility? 

https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-settings?view=o365-worldwide#settings-for-retaining-and-deleting-content

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 592d6717-d670-14a8-acbe-c648958ca208
* Version Independent ID: 9bc46fd9-50e1-1e58-4852-22068e2980ae
* Content: [Configure Microsoft 365 retention settings to automatically retain or delete content - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-settings?view=o365-worldwide#configuration-information-for-exchange-email-and-exchange-public-folders)
* Content Source: [microsoft-365/compliance/retention-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@contributor-luis  When you quoted "do not tag the items" does this refer to the user notification at the top of the email message?  Without more context, it's difficult to be sure.  But if that's the case, this is documented here because it's specific to Exchange and isn't applicable for all the other workloads that support retention settings: https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-exchange#user-notification-of-expiry-date 

"Users don't see this notification if the retention policy doesn't delete items (retain-only)."

It sounds like you might be internal to Microsoft, although not indicated in your GitHub profile. In future, please contact me direct for any doc feedback for the M365 retention docs. We can resolve issues much more efficiently that way.

**Comment by cabailey** [comment]
@contributor-luis  No update for a while & we have this covered in the documentation.  Looks like we can close this issue?

**Comment by contributor-luis** [comment]
Hi Carol

Sure, thanks for your help.

Regards

Luis Elias

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
