### ISSUE TITLE
How to get support on this topic

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/microsoft-365-docs#1062]
Hi,
I have some issues related to this feature and since it is in preview, O365 support team does not support it (this is what i have been informed when I had raised the issue with support team). So question is, who can provide support in this cae?
Issue: After enabling this preview, I am able to see sensitivity labels while creating new group in Teams, OWA, Azure AD admin center but when I create a Team site (group connected) via SPO home page or via SPO admin center then I do not see the sensitivity labels. Instead I see the old classification values configured for O365 Unified groups.
Another issue: I updated existing group classification value with a Sensitivity guid, but I do not see it updated in the group for e.g. Teams UI does not show the Sensitivity label but when I edit the Team then I can select the Sensitivity label.
Appreciate if someone can help me in resolving these issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **krowley**

**Comment by cabailey** [comment]
@prashant1380   Sorry to hear you've been having issues with this preview. My understanding has always been that public previews are eligible for technical support, whereas private previews are not (typically supported by the engineering team directly, rather than our Support teams). If instructions are published on docs.microsoft.com, it is a public preview - so I was surprised to hear you were told "O365 support team does not support it". I checked with the contacts from both engineering and support, with the confirmation that it is supported and the right way to get your issues investigated. The support engineers have been updated about this scenario, so please try filing a new support ticket in the admin center (https://admin.microsoft.com) and if necessary, refer them to this post and my name.

**Comment by prashant1380** [comment]
Thanks and I have now created a Ticket #:18268708. Lets see what response I get and will share the updates here.

**Comment by lightupdifire** [comment]
Hello @cabailey, @prashant1380 for my same case, with MS support I couldn't get support :) they say it is a preview and nothing can do now.

**Comment by prashant1380** [comment]
Yes, I know and the same happened to me. That's why i raised the issue here, but lets see if I get any positive response for my new ticket raised today.

**Comment by FilipBosmans** [comment]
I also followed up MS internally and yes we support this preview.

**Comment by markuspelto** [comment]
Has anyone got any feedback from support that could be added as known issues? My case is that I have enabled MIP labels for groups, synced AIP labels, enabled MIP in SharePoint, assigned MIP label for all groups and removed old classification. Teams works well, Outlook as well, but SharePoint has no sensitivity label selection. Also tried to republish MIP lables, but SharePoint still won´t show those. 

My next step is to open support case, but was wondering if there is something that tenant owner can do before support case?

**Comment by cabailey** [comment]
@markuspelto In your case, please do open a support case.  Because everything else is working for Teams, I'm wondering if the label selection on the SharePoint side isn't quite rolled out to all tenants - it is a new preview afterall.  So contacting Support is the way to go so they can check this for your tenant and enable it if necessary.  Since we now have confirmation on the support status for this preview, closing this issue.
