### ISSUE TITLE
Billing 

### ISSUE THREAD

**Issue by Linas08** [MicrosoftDocs/microsoft-365-docs#10642]
ther is no Billing option in the admin center?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df7c4647-3b29-0d9f-bd2d-9313fd3c8727
* Version Independent ID: ce4ffa1a-7717-958f-618c-2c7e470b379e
* Content: [View your bill or invoice](https://learn.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/view-your-bill-or-invoice?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/view-your-bill-or-invoice.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/view-your-bill-or-invoice.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Linas08 Thank you for your feedback. I was able to locate the billing option in the admin center

![image](https://user-images.githubusercontent.com/45987684/212070848-8bc2e9a5-2967-40c7-a75c-cf6579c12848.png)


If you continue to have trouble, I'd recommend contacting support via the need help section on the admin center, so that an engineer can work with you to fix the issue.

Hope this helps!

Thanks
Sri
