### ISSUE TITLE
Power Automate flow limitations for Retention Period Expired event trigger

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#10659]
Under the **Limitations for this scenario** section, once you select using Power Automate to implement disposition review of a label, does it also take away from the other 'out of the box' disposition review capabilities available for labels under the disposition tab, such as  -

- Would you still be able to see how many documents are pending disposition?
- Would you still be able to 'extend' the disposition date, or 'add reviewers' to existing disposition review? 

Or are those capabilities no longer available and might need be implemented (if desired) within the Power Automate flow itself? 

NOTE - There do not appear to be any Compliance APIs that let you 'extend' the disposition date of an item into the future  currently - so is this another limitation? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43c8da6b-a034-f4fc-db7e-e341f8adf4d5
* Version Independent ID: 43c8da6b-a034-f4fc-db7e-e341f8adf4d5
* Content: [Customize what happens at the end of the retention period - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-label-flow?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-label-flow.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-label-flow.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@kstat I'm having problems understanding your question.  Under the limitations section, there is no mention of disposition review because it's not relevant to this scenario?  As part of the label configuration, at the end of the retention period, you can't select a disposition review and run a Power Automate flow, it's one or the other.  See https://learn.microsoft.com/en-us/microsoft-365/media/retention-label-flow-configuration.png for reference.  The two compliance actions supported by the Power Automate flow are delete and relabel (not start a disposition review).

To extend the retention period, you can apply another label with that extended date.

**Comment by kstat** [comment]
Thanks, @cabailey. There is a paragraph on the page that says the flow could be used to start a customized disposition review process using an external integration / solution. While the approaches that can be used to implement an external disposition are outside of the scope of the article, the act of moving dispositions outside the Purview solution appears to take out some capabilities that are otherwise available as part of the built-in solution. The question was more to clarify / understand how the built-in disposition 'reacts to / works with' labels that might have their own external disposition process implement through a flow, and whether some of these qualify as limitations of this 'scenario' (with the assumption that scenario here implies anything to do with Power Automate at the end of a retention period, including disposition review as an example).
