### ISSUE TITLE
Adjustable timeslots not supported

### ISSUE THREAD

**Issue by crsleeth** [MicrosoftDocs/microsoft-365-docs#10690]
It seems highly inaccurate to say "Not all appointments are the same. Some take only a few minutes, while others can take hours or more." while Bookings still doesn't support adjustable timeslots (duration). All meetings have to be a set length of time. Multiple time slots cannot be selected. https://techcommunity.microsoft.com/t5/office-365/microsoft-bookings-how-to-make-adjustable-timeslots/m-p/168494

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93466e00-def6-6d4c-6705-04cb62a32945
* Version Independent ID: 4e862a20-81c3-991d-6d6f-343b99503408
* Content: [Set Bookings scheduling policies](https://learn.microsoft.com/en-us/microsoft-365/bookings/set-scheduling-policies?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/set-scheduling-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/set-scheduling-policies.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@crsleeth Thank you for your feedback. I agree that adjustable timeslots are a good feature, however, this needs to go to the dec/product engineer for a design change. I'd recommend you post this feedback on our main feedback portal ([Bookings · Community (microsoft.com)](https://feedbackportal.microsoft.com/feedback/forum/e9c7c7d1-011c-ec11-b6e7-0022481f8472)) so that a dev/product engineer can explain why this feature was not implemented or if this is in our roadmap.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@crsleeth Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
