### ISSUE TITLE
MEM instructions 

### ISSUE THREAD

**Issue by marcosmcampos** [MicrosoftDocs/microsoft-365-docs#10744]
Would it be possible to add instructions on how to enable the auditing using Microsoft Endpoint Manager (intune) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 060dad54-ac01-918a-f684-36464edf54c2
* Version Independent ID: f1a524a3-96a8-e112-3b83-adc9bb8af38f
* Content: [Host firewall reporting in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/host-firewall-reporting?WT.mc_id=EM-MVP-5004639&view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/host-firewall-reporting.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/host-firewall-reporting.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@marcosmcampos Thank you for your feedback. By default, auditing is enabled for all customers. It can't be disabled. You can use audit logs to track and monitor events in Microsoft Intune - https://learn.microsoft.com/en-us/mem/intune/fundamentals/monitor-audit-logs

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @marcosmcampos Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by marcosmcampos** [comment]
@msbemba I'm not sure this answers my question. How does your article relate to Host Firewall Reporting? How does that answer my request to add instructions on how to enable Host Firewall reporting with Intune ? The article where I posted this comment has instructions for GPO...I would assume it is obvious that some sort of instruction or comment should be added to clarify customers using Intune and how this could be enabled. If it is already enabled by default (is it really? there aren't any prerequisites?), that should be mentioned.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@marcosmcampos  I'm going to get the details from the author and Provide you an update.

Thanks
Sri

**Comment by msbemba** [comment]
Email sent to author  -2/1/23

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
