### ISSUE TITLE
Sensitivity Labels not supported in OWA mini (mobile)

### ISSUE THREAD

**Issue by JSanchez-EXO** [MicrosoftDocs/microsoft-365-docs#10782]
Hello,

I can't see any mention to OWA mini (the mobile browser version) not supporting Sensitivity Labels.
The new policy "Require users to add a label to emails" is bypassed if the user sends the email from OWA mini

Is expected the table on this article to publish this limitation?
Thank you in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2dd81b07-cfc4-2272-fa96-f6d053f7cb0e
* Version Independent ID: 2dd81b07-cfc4-2272-fa96-f6d053f7cb0e
* Content: [Minimum versions for sensitivity labels in Microsoft 365 Apps - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-versions?view=o365-worldwide#sensitivity-label-capabilities-in-outlook)
* Content Source: [microsoft-365/compliance/sensitivity-labels-versions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-versions.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
The only time I've heard this term is internally at Microsoft. You won't find it in any official documentation & I'm told the correct name is "Outlook in a mobile browser". 

No, it doesn't support sensitivity labels and the documentation lists what we do support, not list email clients that we don't support. That's standard for documentation because the list could never be complete, and any omissions could be construed as therefore supported. For example, sensitivity labels aren't supported by our Windows built-in Mail app, either. Sensitivity labels are supported with Outlook for Windows, Outlook for Mac, Outlook for iOS, Outlook for Android, and Outlook on the web. These are the "flavors" of Outlook in the table.

Since you're a Microsoft employee, please feel free to reach out to me on internal channels about the documentation for sensitivity labels rather than using GitHub Issues.

**Comment by JSanchez-EXO** [comment]
Hello Carol,

Thank you very much for your input, it's really appreciated
I agree with everything you mention
My apologies for reaching out this way, I understood it was the correct one
