### ISSUE TITLE
AAD Premium license is required and good if that was mentioned on this page

### ISSUE THREAD

**Issue by bybytaren** [MicrosoftDocs/microsoft-365-docs#1088]
According to https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-assign-sensitivity-labels
But on Office apps an AAD Premium is not required according to this page https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps#subscription-and-licensing-requirements-for-sensitivity-labels

So Sensitivity labels on Teams is only for organizations on M365 SKUs and O365 E3 need to invest in AAD premium. 
Is this how it is going to be in GA too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **krowley**

**Comment by KCCross** [comment]
I can't offer any real guidance about the eventual finalized GA configuration. We'll be relying on the product team directly to identify deltas between the public preview offering and GA. In the meantime, passing this on to the content owner so she's aware of the questions being asked. Thanks!

**Comment by cabailey** [comment]
Investigating - from the current documentation I agree it seems a customer with O365 E3/E5 can't use sensitivity labels with Office 365 groups without an Azure AD Premium subscription but I'm looking to confirm that before adding this to the page. Typically. licensing isn't set until GA.

**Comment by cabailey** [comment]
@bybytaren :  I now have some clarification on this: The underlying functionality to enable the preview and assign sensitivity labels to Office 365 groups uses Azure AD functionality.  This in turn has a technical requirement that there is at least one active license in the tenant for an Azure AD P1 license, which is why it was added to the Azure AD article, even though the feature is still in preview. 

After reviewing both articles, I can see considerable overlap that can cause confusion so both articles are going to be revised so there's a single source of truth. For example, the instructions to enable the preview will be removed from this page and instead, reference the Azure AD article where they currently have this technical requirement for the licensing check. When the feature goes GA, the licensing requirements (not just the technical requirements) will be clarified.

**Comment by mypil** [comment]
@bybytaren - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by cabailey so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by cabailey** [comment]
@bybytaren - both articles are republished now for this clarification.

**Comment by bybytaren** [comment]
Thank you for the care and attending to my need for clarification :)
Kind regards,
Eric
