### ISSUE TITLE
section "Inactive mailboxes and eDiscovery case holds" in simple wordd

### ISSUE THREAD

**Issue by franzmiltner** [MicrosoftDocs/microsoft-365-docs#10892]
The "Inactive mailboxes and eDiscovery case holds" section sounds like written by a bunch of lawyers. 
When I summarize like

1. use retention policies to hold when your aim is retention
2. use eDiscovery holds to hold, when it's about eDiscovery
3. keep your eDiscovery holds only as long as needed by the case and then actively release

is that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b1290-00ae-8f23-1b41-5ca692e6d1c4
* Version Independent ID: ab2acdbd-a620-86de-8544-e655aa386b0a
* Content: [Learn about inactive mailboxes - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide#inactive-mailboxes-and-ediscovery-case-holds)
* Content Source: [microsoft-365/compliance/inactive-mailboxes-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
@franzmiltner Thank you for your feedback. It's an impossible task to publish documentation that's perfect for everybody but we know from Support and others in the field that customers do use the wrong feature for the job, because they can, because there is a lot of overlap, and because it seemed to do what they needed. For these customers, a simpler explanation such as "use eDiscovery holds for eDiscovery purposes" wasn't sufficient. They wanted detailed information and precise guidance when to use one feature over another and why. For some customers, the details here weren't sufficient, which is why we also published the table in https://learn.microsoft.com/en-us/microsoft-365/compliance/retention#when-to-use-retention-policies-and-retention-labels-or-ediscovery-holds 

I can share that these details came from a number of people who weren't lawyers but had practical implementation knowledge of these features and an appreciation of what these customers needed. If you don't find these details helpful, please feel free to skip them.
