### ISSUE TITLE
How do I change the icon for the custom theme?

### ISSUE THREAD

**Issue by Maltavius** [MicrosoftDocs/microsoft-365-docs#10948]
I can't find any information at all about how to change the Icon shown in the Themes list
![image](https://user-images.githubusercontent.com/10133945/217771492-f938fff7-7f21-483f-a95e-b937fdd80b94.png)

We've made a custom theme for our University but the Organisational theme is just a blank white square.
How do we change that?
The documentation on the page that I'm reporting should contain this information but doesn't

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6c85cc-1680-588e-f520-bcafb1383d53
* Version Independent ID: ea446e6b-e094-dacd-54cc-e597b2f1354d
* Content: [Customize the theme for your organization - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/customize-your-organization-theme?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/customize-your-organization-theme.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/customize-your-organization-theme.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Maltavius Thank you for your feedback. I was able to follow the steps, where do you see these icons? As a user or as an Admin?

This document is only for Admins to be able to customize the themes.

Hope this helps!

Thanks
Sri

**Comment by Maltavius** [comment]
As an Administrator

**Comment by Maltavius** [comment]
I don't think you understand. The steps are fine. There are steps missing
though. How do you get an Icon to show up for the end users that isn't just
blank.

The icons are under the cogwheel om n www.office.com and under the Theme
menu. All the Microsoft provided themes have colorful icons but there isn't
a way to specify that for our organizational theme.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Maltavius Thank you for your feedback. I have tested this in multiple tenants but don't see a blank square on any of the tenants. Changing themes for a user is just about selecting them and then it automatically changes(https://support.microsoft.com/en-us/office/personalize-your-microsoft-365-experience-eb34a21b-52fa-4fbf-a8d5-146132242985)0.
 Since you don't see your customized theme, there could be a bug or an issue with the theme that can be fixed by the support team. So I'd recommend you contact support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Maltavius Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Maltavius** [comment]
THE THEME IS THERE, I CAN SEE THE THEME! THE THEME WORKS!

It's just that the ICON for the theme is a BLANK WHITE SQUARE, and I wonder how to change the BLANK WHITE SQUARE to an Icon that tells my users that this is the Organizational theme.
![bild](https://user-images.githubusercontent.com/10133945/222883594-31950e53-98df-4d6d-9a02-128df4059823.png)
You see? It's active and it's working. But HOW do I change the White Square to be something else? Our Logo for instance.

Instead of providing a link (that doesn't work) to a page that doesn't show how to set an Organizational theme. Provide a linkt to a page that shows someone setting an Organisational theme and if that selection is a white square or not.

**Comment by Maltavius** [comment]
You had 2 weeks to answer this  and gave me only 17 hours before you close the request.

**Comment by msbemba** [comment]
@Maltavius Sorry about that. I understand your concern, the white square just shows up on your tenant and is not common behavior. While testing in multiple tenants we see the actual image instead. This is exactly why there could be a bug or an issue with the theme in your tenant that can be fixed by the support team. So I'd recommend you contact support via the need help section on the admin center.

Thanks
Sri
