### ISSUE TITLE
No Microsoft Graph equivalent command provided for Set-MsolCompanySettings -AllowAdHocSubscriptions $false

### ISSUE THREAD

**Issue by Borgquite** [MicrosoftDocs/microsoft-365-docs#11048]
Under 'Use PowerShell and Azure AD to enable or disable all self-service sign-ups' you advise:

> You can use PowerShell commands to change the settings that control self-service sign-ups. To turn off all self-service sign-ups, use the MSOnline PowerShell module to change the MsolCompanySettings setting for AllowAdHocSubscriptions in Azure Active Directory. For the steps to turn off self-service sign-ups, see [Set MsolCompanySettings](https://learn.microsoft.com/en-us/powershell/module/msonline/set-msolcompanysettings).

However according to [this community notification](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/microsoft-entra-change-announcements-september-2022-train/ba-p/2967454?WT.mc_id=M365-MVP-9501) we need to migrate away from the MSOnline PowerShell module to Microsoft Graph before June 30, 2023. What is the path for system administrators who wish wish to disable all current and future self-service sign-ups after the MSOnline PowerShell module is deprecated?

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e05e10b-691c-2357-25f5-1a9e810c662d
* Version Independent ID: 0d789543-2033-d759-1fe9-69f24e458c13
* Content: [Manage self-service purchases and trials (for admins)](https://learn.microsoft.com/en-gb/microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Borgquite Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by sofbkeller** [comment]
This still hasn't been fixed. I realize that the Graph replacement date has been pushed back but I don't think it is acceptable to push graph and still require critical features use a EOL module.

**Comment by slueders-bag** [comment]
still no update here?

**Comment by yogkumgit** [comment]
@msbemba Please review and update. Thanks

**Comment by msbemba** [comment]
@yogkumgit  This needs to be reviewed by the author or Product team.

Thanks
Sri

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please help us in resolving this issue. Thanks

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
