### ISSUE TITLE
Password guidelines for administrators

### ISSUE THREAD

**Issue by Buhal-SL** [MicrosoftDocs/microsoft-365-docs#11187]
- Don't require character composition requirements. For example, *&(^%$

- Don't require mandatory periodic password resets for user accounts

It should te DO require!

**Comment by yogkumgit** [comment]
@Buhal-SL Please indicate which document you are referring to. Thanks

**Comment by Buhal-SL** [comment]
Sorry, my bad. It's here:
https://learn.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide
Section: Password guidelines for administrators

**Comment by msbemba** [comment]
@Buhal-SL Thank you for your feedback. These are some common approaches and have negative impacts. So the document is correct in stating 1) Don't require character composition requirements. and 2) Don't require mandatory periodic password resets for user accounts

The reason being:- 

1) Password expiration requirements do more harm than good because these requirements make users select predictable passwords, composed of sequential words and numbers that are closely related to each other. In these cases, the next password can be predicted based on the previous password. Password expiration requirements offer no containment benefits because cybercriminals almost always use credentials as soon as they compromise them.

2) Most people use similar patterns, for example, a capital letter in the first position, a symbol in the last, and a number in the last 2. Cybercriminals know this, so they run their dictionary attacks using the most common substitutions, "$" for "s", "@" for "a," "1" for "l". Forcing your users to choose a combination of upper, lower, digits, and special characters has a negative effect. Some complexity requirements even prevent users from using secure and memorable passwords and force them into coming up with less secure and less memorable passwords.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Buhal-SL Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
