### ISSUE TITLE
syntax error?

### ISSUE THREAD

**Issue by sir-wally** [MicrosoftDocs/microsoft-365-docs#1124]
`Set-SmimeConfig -SMIMECertificateIssuingCA (Get-Content ./LSG-CA-CHAIN.sst -Encoding Byte) `

Get-Content : Cannot process argument transformation on parameter 'Encoding'. 'Byte' is not a supported encoding name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26c3c174-0081-6f2a-c7a5-6a6c035eddd8
* Version Independent ID: 0ea791de-8374-6e8e-f0b4-9d45db5ec704
* Content: [Set up virtual certificate collection in Exchange Online to validate S/MIME - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-virtual-certificate-collection-to-validate-s-mime#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-virtual-certificate-collection-to-validate-s-mime.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-virtual-certificate-collection-to-validate-s-mime.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by sir-wally** [comment]
The correct syntax is `Set-SmimeConfig -SMIMECertificateIssuingCA (Get-Content ./LSG-CA-CHAIN.sst -AsByteStream` instead of -Encoding Byte. This is changed in recent versions of PS. Which makes sense since byte isn't really an encoding type.

**Comment by chrisda** [comment]
@sir-wally, what version of PowerShell are your using? v5.1 contains the Encoding parameter where Byte is a valid value. It appears that you're using v6.0 or v7.0, since AsByteStream was introduced in v6.0.

We support PowerShell Core yet for Exchange-related PowerShell. I know for a fact that v6.0 and v7.0 don't work with the [MFA module](https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell) or the new [EXO V2 module](https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2) (although support for the V2 module is likely in the works).

**Comment by sir-wally** [comment]
thanks @chrisda I found out MFA doesn't work with 6+ the long way (I was using azure cloud shell). Reverting back to a windows box with 5.1 got it working again.
