### ISSUE TITLE
Add disclaimer to not remove licenses manually in order to be in supported state

### ISSUE THREAD

**Issue by MSFT-SeanG** [MicrosoftDocs/microsoft-365-docs#11281]
Per previous discussions with engineering teams, it was found that manually removing the license from an active account that is on hold will then put this account out of a supported state for Retention purposes, leading to a **_disconnected_** mailbox, rather than an **_inactive_** mailbox.

Would like caution box (red callout) to this behavior, so that further unsupported workflows can be avoided, and customers can adequately retain data as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7108464d-597a-c79d-cac8-94e35d9dd3d0
* Version Independent ID: ba0d3744-707d-c506-47f4-83519022d4cb
* Content: [Create and manage inactive mailboxes - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/create-and-manage-inactive-mailboxes?view=o365-worldwide#create-an-inactive-mailbox)
* Content Source: [microsoft-365/compliance/create-and-manage-inactive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-and-manage-inactive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@MSFT-SeanG  I'll discuss this with the PM owner - I don't know that it's a valid callout to make because we always want licenses to be assigned for the features that require them. It's a basic principle of our software. If we add a caution here what happens when you remove a license for one feature, the expectation is that we add this for all features (or nothing bad happens).

**Comment by MSFT-SeanG** [comment]
Thanks @cabailey - the one thing that I think needs clarification is _manual license removal_ vs _deleting the account_.

Since the documentation calls out deleting the mailbox as a valid way to convert to an inactive mailbox, this oftentimes leads to confusion of "I thought removing licensing manually will delete the mailbox"

**Comment by cabailey** [comment]
@MSFT-SeanG  I'm going to close this issue & continue to have an internal discussion with the PG. Roberto did not want to add this to the article because it sets a bad precedent if we start to document what happens (or not) when somebody removes a license that's required for a feature. I did suggest updating our main licensing guidance with a warning because features not working when licenses are removed aren't restricted to this scenario. 

This article covers the valid ways to create an inactive mailbox - and removing a license isn't one of them. I appreciate this might be a common customer misunderstanding but I don't think adding a callout in this article is the way to solve this problem. By the time they read it (if they read it), chances are they have already removed the license. I think a better solution would be to prevent license removal if the mailbox is under hold - address the issue at source. That will obviously require coding but I think it's a better solution than a callout buried in documentation that they obviously didn't read in the first place.
