### ISSUE TITLE
Behaviour unclear for 'Users to protect', 'Domains to protect' and 'Trusted senders and domains' with multiple policies

### ISSUE THREAD

**Issue by Borgquite** [MicrosoftDocs/microsoft-365-docs#11304]
Hi,

For the following settings, the behaviour when multiple policies are required needs to be made clearer, please:
- Users to protect
- Domains to protect
- Trusted senders and domains

If we have multiple policies applied to different groups of users, are the above settings 'shared' between all policies, or do we need to configure each policy separately with the above settings?

Another way of saying it is that if we wanted to apply [recommended settings for Microsoft Defender for Office 365 security](https://learn.microsoft.com/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365) with different policies for different users (i.e. 'Standard' or 'Strict') depending on risk profiles, **but** we only need a single set of Users to protect, Domains to protect and Trusted senders and domains across the organisation, then should we:

1. Set up the above settings **once** in the 'Default' policy because the system merges the settings across all policies even if some policies *don't* apply to the user OR
2. Set up the above settings **once** in the 'Default' policy because the Default Policy always applies to all users even if there is another higher priority policy - because the system merges the settings across all policies that *do* apply to the user OR
3. Do we have to set up and maintain the above settings so that they are identical in **every** policy

(Basically, does the system make a single list of 'users to protect' etc from all policies and apply that to all users, or does it apply the list of 'users to protect' contained within each policy *only* to those users where the policy applies?)

(There is a brief note about multiple policies under 'User impersonation protection' but it does not make this point clear, and neither does [Order and precedence of email protection](https://learn.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined) which it links to. All it does say is that 'you can't specify the same protected user in multiple policies' which implies some sort of merging, but when I try it the system is quite happy to accept the same protected user in multiple policies so this statement needs clarification or removal.

I will say that 3 would be frustrating if that is how the system works - these sorts of settings should normally be configured globally, since it's hard to imagine a situation where it would be useful for 'users to protect', 'domains to protect' and 'trusted senders and domains' to be configured on a per-user basis - it is frustrating if we need to try to keep two separate lists identical. It means that for example it is necessary to add something **twice** to resolve an issue in the [Impersonation Insight](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-phishing-mdo-impersonation-insight?view=o365-worldwide), which is quite easy to miss.

Anyway for now it would just help for the operation of multiple policies in the current system regarding these settings to be made more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-phishing-policies-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-phishing-policies-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-phishing-policies-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by Borgquite** [comment]
(According to [Order and precedence of email protection](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined?view=o365-worldwide) 

'If a recipient is defined in multiple policies of the same type (anti-spam, anti-phishing, etc.), only the policy with the highest priority is applied to the recipient. Any remaining policies of that type are not evaluated for the recipient (including the default policy).'

This implies that option 3 is the case. But in this article, the statements 'You can't specify the same protected user in multiple policies' and 'Regardless of how many policies apply to a recipient...' imply that multiple policies **can** be applied to a single recipient (if not, the restriction that you can't you specify the same protected user in multiple policies is a problem). This is unclear.

'In each anti-phishing policy, you can specify a maximum of 350 protected users (sender email addresses). You can't specify the same protected user in multiple policies. So, regardless of how many policies apply to a recipient, the maximum number of protected users (sender email addresses) for each individual recipient is 350.'

**Comment by chrisda** [comment]
@Borgquite, you found one of the policy precedence topics that I was going to refer you to. The other one is [here](https://learn.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies#order-of-precedence-for-preset-security-policies-and-other-policies) where it talks about where Standard and Strict preset security policies fit in, which gives the complete picture.

The point from all of that is: the first anti-phishing policy that applies to a recipient (user vs. group vs. domain, regardless of how they're identified) is the one and only anti-phishing policy that's applied to that recipient for a particular inbound email message. There's no merging or "first anti-phishing policy A is applied, then anti-phishing policy B for the recipient of that message".

If you want the settings of a specific anti-phishing policy to be applied to a specific recipient, make sure that policy is the highest priority for that recipient. If you use Standard or Strict preset security policies or custom anti-phishing policies where a recipient is defined, the settings of the default anti-phishing policy don't matter, because a higher priority anti-phishing policy will ALWAYS be applied to a message for that recipient.

So, your potential options 1 and 2 are eliminated.

With the exception of "users to protect" (user impersonation protection), no settings in one anti-phishing policy affect or are related to the settings in another anti-phishing policy. For example, each policy can have the same list of "domains to protect" (domain impersonation protection) and the same list of "trusted senders and domains" (users/domains to exclude from user/domain impersonation protection).

As described in the topic, for some reason, you can't duplicate "users to protect" across multiple anti-phishing policies, and the maximum number of unique "users to protect" across all anti-phishing policies is 350: 350 unique users in one policy, 1 unique user in 350 policies, or any combination in between.

So, if you want the same list of "users to protect" to apply to all recipients in your organization, you have the following options:

- Use the Standard or Strict preset security policy (one or the other, not both) for all recipients.
- Don't use Standard or Strict preset security policies (turn them off) and use one custom anti-phishing policy for all recipients.
- Don't use Standard or Strict preset security policies (turn them off) or any custom anti-phishing policies. The settings of the default anti-phishing will apply to all recipients.

Does that make sense?

**Comment by chrisda** [comment]
@Borgquite, I sought clarification, and it appears the "you can't duplicate 'users to protect' across multiple anti-phishing policies" statement is not entirely correct. You <u>can</u> use the same users in user impersonation protection across multiple anti-phishing policies.

The problem is: you might get an error when you use the Defender portal to add a "user to protect" if that email address is already defined as a "user to protect" in another anti-phishing policy. This is apparently a Defender portal problem; no such issue with the corresponding TargetedUsersToProtect parameter on the New-AntiPhishPolicy or Set-AntiPhishPolicy cmdlets in Exchange Online PowerShell. By your own description, you didn't get the error yourself. The email address appears to be the key (each entry is the combination of a display name + an email address).

So, my previous explanation of how to use a common list of "users to protect" is wrong; you can use the same list of users in any and all anti-phishing policies.

I'll update the topic accordingly.

**Comment by chrisda** [comment]
@Borgquite, the problematic Note in the topic now says:

> [!NOTE]
> You can specify a maximum of 350 users for user impersonation protection in each anti-phishing policy.
>
> User impersonation protection does not work if the sender and recipient have previously communicated via email. If the sender and recipient have never communicated via email, the message can be identified as an impersonation attempt.
>
> You might get the error "The email address already exists" if you try to add a user to user impersonation protection when that email address is already specified for user impersonation protection in another anti-phishing policy. This error occurs only in the Defender portal. You won't get the error if you use the corresponding _TargetedUsersToProtect_ parameter in the **New-AntiPhishPolicy** or **Set-AntiPhishPolicy** cmdlets in Exchange Online PowerShell.

The updated topic should be visible on M 3/13 ~10:45AM PDT (GMT-7)

**Comment by Borgquite** [comment]
@chrisda Thank you, this is very helpful clarification:

> The point from all of that is: the first anti-phishing policy that applies to a recipient (user vs. group vs. domain, regardless of how they're identified) is the one and only anti-phishing policy that's applied to that recipient for a particular inbound email message. There's no merging or "first anti-phishing policy A is applied, then anti-phishing policy B for the recipient of that message".

Two points come out of this:

- I'm unclear regarding the wisdom behind the fact that 'Users to protect', 'Domains to protect' and 'Trusted senders and domains' are per-policy settings, not 'Global settings' like the Tenant Allow/Block List or global settings for other threat policies.  What's the thinking behind this? It seems to create unnecessary complexity when it's not needed.
- Thanks for updating the 350 user wording (I can't see it yet but don't think your deadline has passed). It will certainly help to clear up this article.

The first point is a design decision so I understand you might not be able to change it but as I said it is mostly inexplicable to me ;)

**Comment by chrisda** [comment]
@Borgquite, I can really speak to why the "trusted senders and domains" list to skip user impersonation protection is per policy. All I can say is: anti-phishing policies are old, while the Tenant Allow/Block List is much newer, and is the wave of the future.

Not many EOP/MDO security policies have global settings; most settings are per-policy. Safe Attachments has a couple of global settings (i.e., turning Safe Attachments for SharePoint, OneDrive, and Teams). So does Safe Links, which consists of the the "Block the following URLs" list.

**Comment by Borgquite** [comment]
Hi @chrisda OK no worries - it's just a pain if you're using Standard and Strict policies (as recommended) to maintain both entries.

Appreciate all your answers here, can see the updated wording now. Please feel free to close this!
