### ISSUE TITLE
Safe Sender list only stops "?" from appearing, "via" tag still appears

### ISSUE THREAD

**Issue by arourke** [MicrosoftDocs/microsoft-365-docs#1136]
The article says that senders in the safe sender list won't get the unverified sender treatment. I've added a particular domain to this list and, while there is no longer a "?" where the email picture should be, a "via" tag still appears. This article implies that both the "?" and "via" are part of the "unverified sender" feature. Therefore, both of these should be removed when I add the domain to the safe sender list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c7c32e-6f64-353b-0822-f6c7b4072998
* Version Independent ID: 1a0d4ab3-c309-daa2-7855-93257071c29e
* Content: [Unverified Sender - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/unverified-sender-feature)
* Content Source: [microsoft-365/security/office-365-security/unverified-sender-feature.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/unverified-sender-feature.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by brumbarlow** [comment]
Is it possible to turn off the Via / Normal sender notification in Outlook. (OWA does not show this), so is Outlook Specific. This is to support a Tenant to Tenant Migration

**Comment by MaratMussabekov** [comment]
Hello @arourke,
it looks like this article has a mistake, and domains added in safe sender list are not bypassing spoofing check.
As it is stated in [this article](https://docs.microsoft.com/archive/blogs/tzink/how-to-securely-add-a-sender-to-an-allow-list-in-office-365):
"It is difficult to prevent your users from using Safe Senders, they are a valuable feature. However, as currently implemented by Office 365, they are vulnerable to spoofing because they are simple string matches. Fortunately, as per above, we are making a change to not respect a user's safe sender if it fails authentication."
Thank you

**Comment by mypil** [comment]
@arourke - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/ead564547302d7fb295be3a0294a4b70672059e2. 


Thank you for your contribution to make the docs better! Much appreciated!
