### ISSUE TITLE
Lacking mention of the Microsoft-Reporting email addresses

### ISSUE THREAD

**Issue by glr0221** [MicrosoftDocs/microsoft-365-docs#11403]
Hello Microsoft,

Way back 2020, there was a set of articles that allowed end users or third party tools to submit emails for analysis. This was done by : 

1.  Attaching the email-for-analysis attached to a blank email. 
2. Formatting the subject based on the classification of mail (junk/phish/clean)
3. Sending the report to three distinct email addresses (junk@office365.microsoft.com, phish@office365.microsoft.com, not_junk@office365.microsoft.com.)

Is this reporting mechanism still supported? If so, why is the "third-party reporting" does not have these details. 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User reported settings - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@glr0221, I think the point of the current submissions experience is to track submissions on the Submissions page in the Microsoft 365 Defender portal at <https://security.microsoft.com/reportsubmission>.

Reporting messages directly to those email addresses would almost certainly not be tracked on the Submissions page.

If sending messages directly to those email addresses was still supported, those methods would still be described in content. Until a couple of years ago, there was a row in the table in [this topic](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft) and a separate topic that talked all about it:

> |[Manually submit messages to Microsoft for analysis](https://web.archive.org/web/20201207214418/https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis?view=o365-worldwide)|Manually send attached messages to specific Microsoft email addresses for spam, not spam, and phishing.|

The fact that the topic is gone speaks volumes.

**Comment by glr0221** [comment]
Thank you @chrisda . 

I would like to confirm my understanding on the responses : 
1. Reporting directly to those special addresses will not be tracked by the submissions page. Correct? 
2. The fact that it is not described in the document means it is not supported anymore? Or is not just supported by the submissions dashboard?
3. Side question : What does 'Original Verdict' on the submissions portal mean? 

Also, I found this documentation related to our [topic on reporting to MS directly](https://support.microsoft.com/en-us/windows/protect-yourself-from-phishing-0c7ea947-ba98-3bd9-7184-430e1f860a44#:~:text=Note%3A%20If%20you're%20using,the%20headers%20on%20the%20message.). Is this doc still relevant? Or should be archived? 

Thank you and my apologies for the number of questions I am throwing your way.

**Comment by chrisda** [comment]
@glr0221:

1. Correct.
2. I just tried sending a message to junk@office365.microsoft.com and phish@office365.microsoft.com and they didn't immediately bounce back as undeliverable, so that means they're still working. But, related to question 1, the submissions aren't tracked on the Submissions page, so we're not going to tout that as a recommended method.
3. Original Verdict is an indicator that the message has been submitted to Microsoft (either by a user from Outlook or an admin from the Submissions page). Admis are free to resubmit messages from the Submission page, in which case the verdict might change.

OK?

**Comment by glr0221** [comment]
Thank you @chrisda . This makes a ton of sense. 

PS : Last question, for emails received in the submissions mailbox, are they automatically processed/analyzed by Microsoft? Or the admins have to manually submit them? 

Thank you again. And closing this ticket.

**Comment by glr0221** [comment]
@chrisda Sorry for another round of questions : 
_if you have user reported settings configured to deliver to the reporting mailbox and Microsoft, then messages are analyzed by Microsoft._ 

The above applies for Miscrosoft's reporting button correct? If we are using a 3rd party reporting tool then we cannot set this option correct? Is there anyway to allow the auto-sending of emails from the submissions mailbox, to microsoft for analysis?

Thank you.

**Comment by chrisda** [comment]
@glr0221, third party tools will work just as well as Microsoft reporting tools as long as they follow the required submission format as described [here](https://learn.microsoft.com/microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox#message-submission-format-for-third-party-reporting-tools).

Otherwise, I'm sure any third party reporting tool can be configured to send user reported messages to the reporting mailbox. If the tool doesn't follow the formatting requirements, the reported messages will even show up on the **User reported** tab of the Submissions page, but they're always classified as phishing, which can be a problem if users are reporting messages as spam or phishing.

**Comment by glr0221** [comment]
Thank you @chrisda . I understand. We are currently doing that. The other question is if there is a way for the emails inside the submissions dashboard to be automatically submitted to Microsoft for analysis. Thank you very much and my apologies for all these questions.
