### ISSUE TITLE
Automatic labeling licensing

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/microsoft-365-docs#11621]
According to https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance automatic labeling is not allowed in Office 365 E3 nor M365 Business Premium.

However, I have tried with an O365 E3 tenant as well as a M365 BP tenant and automatic labeling options are working.

@pamelaar

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Automatically apply a sensitivity label in Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide#how-to-configure-auto-labeling-for-office-apps)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@JMCA2  I don't believe there's anything on this page that covers whether the required licenses for auto-labelling are enforced or not. Instead, you'll see that information generically covered at the top of the licensing page that you referenced, saying it's not always possible to enforce licensing but you should still acquire licenses for any user that you intend to benefit from the service.

If you have feedback about the licensing statements, please open a GitHub Issue for the licensing page rather than here.

**Comment by JMCA2** [comment]
Done. I've opened https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/812

Thanks
