### ISSUE TITLE
Update to section - Information about the label properties for import table for RetentionDuration 

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#11708]
In the section - Information about the label properties for import 
The RetentionDuration description states that This property specifies the number of days

Can you add a note note to state that the calculations are based on 365 days in a year and do not take into account leap years. Therefore you may wish to add addition days to the RetentionDuration to factor in the extra days for leap years.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Use file plan to manage retention labels - Microsoft Purview (compliance)](https://learn.microsoft.com/en-gb/microsoft-365/compliance/file-plan-manager?view=o365-worldwide#information-about-the-label-properties-for-import)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Investigating this one!

**Comment by cabailey** [comment]
@nikki-c  After some investigation I can confirm that the number of days you specify is what's stored and used for the retention period. In the UI where it's displayed as days/months/years, for easier human consumption, the months assume 30 days and the years assume 365 days - as documented here: https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-settings#retaining-content-for-a-specific-period-of-time

If the exact number of days are important to you, calculate and specify them accurately. That's what will be used as the retention period.  However, because items aren't permanently deleted immediately at the end of the retention period (but instead, become eligible for deletion) and there's a 7-day timer, the odd day out or so isn't going to have a noticeable impact for the vast majority of cases. 

If you need more information about how retention works and the backend timings, we have a "Learn about retention for .." for each workload.  For example, for SharePoint: https://learn.microsoft.com/microsoft-365/compliance/retention-policies-sharepoint
