### ISSUE TITLE
Dynamics 365 table is missing

### ISSUE THREAD

**Issue by timothybohte** [MicrosoftDocs/microsoft-365-docs#1173]
The Dynamics 365 table is missing in the Audited activities section. I'm especially looking for how to get the log data concerning Export to Excel from Dynamics 365 (CRM). I understand that it's possible to get that data, but it's not included in the standard search reports. Please clarify how the create a custom report especially for that. This is very important because of GDPR regulations in Europe. Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#microsoft-power-apps-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@timothybohte I'll try to give a quick answer that I hope is helpful; otherwise, I would suggest you open a ticket with Microsoft Support.

The Dynamics auditing schema has changed a bit (see the Activities dropdown list) in the audit log search UI. It shows that all activities are deprecated except for one called "All Dynamics activities" (the corresponding operation name is "CrmDefaultActivity".which is just that: selecting it returns all Dynamics activities that match your search criteria.

So you have to look at the detailed information in the audit record to help you answer your questions. This is the AuditData field documented here: https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#view-the-details-for-a-specific-event

I think that info about the activities performed is in  the ObjectId and Message properties in the audit record. Depending on the activities, there may be other useful info in the Fields property.

So you might consider doing this:

1. Run an audit log search and choose all. Dynamics 365 activities.

2. Export the results by downloading all  results, as documented here: https://docs.microsoft.com/en-us/microsoft-365/compliance/export-view-audit-log-records

3. Format the exported audit logs by following this step: https://docs.microsoft.com/en-us/microsoft-365/compliance/export-view-audit-log-records#step-2-format-the-exported-audit-log-using-the-power-query-editor

This will enable you to transform the JSON AuditData object to separate columns so that you can use Excel to filter on them. 

In the mean time, we're looking into documenting the Dynamics audit schema which will describe the properties/fields in the audit records for Dynamics.

HTHs

3.
