### ISSUE TITLE
While Logging in through the command prompt , Getting the errror

### ISSUE THREAD

**Issue by SatishGarapati** [MicrosoftDocs/microsoft-365-docs#1174]
Error In Command Prompt
Error performing request: Get https://api.cf.eu1.mindsphere.io/v2/info: proxyconnect tcp: dial tcp 127.0.0.1:3128: connectex: No connection could be made because the target machine actively refused it.

Kindly Help me in Resloving the Issue

![image](https://user-images.githubusercontent.com/31762197/73589243-a55b7000-44f9-11ea-821e-cf68ee61f27d.png)

**Comment by mypil** [comment]
@SatishGarapati - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by SatishGarapati** [comment]
@mypil  I was trying to login to Cloud Foundry through command prompt. By the way i did get you could you please eloborate it.

**Comment by mypil** [comment]
@SatishGarapati -  Can you please share what specific issue you have and for which Microsoft doc? Or are you having some technical issues which requires technical support?

If you have some issues with a particular MS doc, we would really appreciate if you are able to help by providing the MS doc link and more details as to what should be edited and/or included. 

Thank you!

**Comment by SatishGarapati** [comment]
@mypil  When I am trying to Login to Cloud Foundry through the command prompt.I set the proxy though i am getting the error FYI Kindly refer through the image placed first query. I am not sure that the error is related to MS doc link or not. tel me how to check the error is related to MS doc link or not.

Thanks You for the response @mypil

**Comment by mypil** [comment]
@SatishGarapati -Please be informed that this repo is intended for Microsoft 365 related docs.  It appears that your issue is not related to any MS docs. I would suggest that you try to search for Cloud Foundry support so they can help with your technical concern. I found this link (https://www.cloudfoundry.org/help-support/) while researching online but I'm not sure if that is the right support site. 

I hope you will get the resolution for your issue. Thank you!
