### ISSUE TITLE
OneNote

### ISSUE THREAD

**Issue by slstruik** [MicrosoftDocs/microsoft-365-docs#1182]
Why is OneNote missing from sensitivity labels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@slstruik Thanks for your interest in sensitivity labels!  Sensitivity labels aren't supported for OneNote, which is why you don't see a reference to them in the documentation. You can make product requests and suggestions on the Office 365 Security & Compliance UserVoice site (https://office365.uservoice.com/forums/289138-office-365-security-compliance) and for this, I recommend using the recently added category of "Information Protection".
