### ISSUE TITLE
ITAR Compliance with my Sharepoint site

### ISSUE THREAD

**Issue by Eazytech8** [MicrosoftDocs/microsoft-365-docs#1183]
[Enter feedback here]

Kindly update us with a precise step to make our Sharepoint site ITAR compliant
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade86bc-56c3-ebc0-7a47-f5f835777b8c
* Version Independent ID: 3cdf7eb2-1653-f339-0685-cac32030dd82
* Content: [International Traffic in Arms Regulations (ITAR) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-itar)
* Content Source: [microsoft-365/compliance/offering-ITAR.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-ITAR.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@Eazytech8 - thanks for your feedback, can you be more specific? Have you contacted your Microsoft account representative with specific questions? Please let me know so I can try to fully answer your question about this guidance. Thanks!

**Comment by joinimran** [comment]
@Eazytech8 As @robmazz already requested, if there are any specifics that you are looking for or there is any specific information that you need to be available in the document please do share so that we can better help you and make the document more useful. 

Thanks.

**Comment by Eazytech8** [comment]
Hi,

Thank you for the feedback.

I read the article till the end and I could not simply understand how to
get a SharePoint site to be ITAR compliant. The docs suggested I should
contact support.

What I am requesting in a nutshell is a clear steps/ procedures I need to
take to ensure my SharePoint site is ITAR compliant using Microsoft tools.

I look forward to hearing from you

**Comment by robmazz** [comment]
@Eazytech8 - thanks for the clarification. Yes, as per the the instruction in the topic - you need to contact your Microsoft account representative if you need help with ITAR support for your SharePoint site. Customers must sign additional agreements formally notifying Microsoft of their intention to store ITAR-controlled data, so that Microsoft may comply with responsibilities both to our customers and to the US government. This topic does not provide step-by-step instructions for compliance across our cloud services (of which SharePoint is one), but rather, covers the areas of responsibility for Microsoft and the next steps that the customer should take towards ITAR compliance. The next step is to reach out directly to your Microsoft account representative for assistance with your specific SharePoint site compliance needs for ITAR. Thanks!
