### ISSUE TITLE
Create Defender device groups via API

### ISSUE THREAD

**Issue by dt-flo** [MicrosoftDocs/microsoft-365-docs#11879]
Is it possible to create those device groups via API? We need to create a lot of device groups and it's taking a lot of time doing it manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a0f4a32-b5d6-82b6-f42a-9664d9be8f5a
* Version Independent ID: e64468af-9eda-5fad-9d39-f837e70c1123
* Content: [Create and manage device groups in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-groups?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machine-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine-groups.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@dt-flo Thank you for your feedback. Here are the functions that can be performed in MDE using API -https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-list?view=o365-worldwide

Unfortunately, I do not see this option yet. However, you can leave your feedback on our main feedback page - https://feedbackportal.microsoft.com/ so that our Dev/Product engineers can help.

Hope this helps!

Thanks
Sri

**Comment by dt-flo** [comment]
> @dt-flo Thank you for your feedback. Here are the functions that can be performed in MDE using API -https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-list?view=o365-worldwide
> 
> Unfortunately, I do not see this option yet. However, you can leave your feedback on our main feedback page - https://feedbackportal.microsoft.com/ so that our Dev/Product engineers can help.
> 
> Hope this helps!
> 
> Thanks Sri

Thanks for the info.
