### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by USAGonzo00** [MicrosoftDocs/microsoft-365-docs#1190]
Per the statement "Although mailbox audit logging on by default is enabled for all organizations, only users with E5 licenses will return mailbox audit log events in audit log searches in the Security & Compliance Center or via the Office 365 Management Activity API."  Does this also cover the advanced compliance add on license, or does it only work with the E5 "all up?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing#feedback)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by Matt-C22** [comment]
No information here regarding the new logging feature "MailItemsAccessed" which replaces "MessageBind".

Replaced in our scripts MessageBind with MailItemsAccessed and we now receive the following error message: "Auditing of MailItemsAccessed event is only available for users with appropriate license. Please visit the documentation to know more about this."
Where is this documentation and what type of licensing is required, since this appears to not be included in the E5 plan or AAD premium?

Thanks

**Comment by markjjo** [comment]
@USAGonzo00 Yes, Office 365 Advanced Compliance add-on and Microsoft 365 E5 Compliance add-on also cover this.
