### ISSUE TITLE
MailItemsAccessed license requirements and information missing in this document

### ISSUE THREAD

**Issue by Matt-C22** [MicrosoftDocs/microsoft-365-docs#1195]
No information here regarding the new logging feature "MailItemsAccessed" which replaces "MessageBind".

Replaced in our scripts MessageBind with MailItemsAccessed and we now receive the following error message: "Auditing of MailItemsAccessed event is only available for users with appropriate license. Please visit the documentation to know more about this."
Where is this documentation and what type of licensing is required, since this appears to not be included in the E5 plan or AAD premium?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by markjjo** [comment]
@Matt-C22 Thanks for asking about this. Yes, MailItemsAccessed has replaced MessageBind. Searching on this new activity does require that the user whose mailbox your auditing requires an E5 license for the user the user your auditing. Mailbox auditing has to be enabled by default (at the org level of for the individual mailbox). I assume your script is running either Search-MailboxAuditLog or Search-UnifiedAuditLog. You might try running Search-UnifiedAuditLog at the command line and include RecordType=50. We plan to publish documentation next week about this and other new auditing features (I'll try to remember to respond to this issue with links to new documentation). Otherwise, you might consider opening a support ticket with Microsoft Support.
