### ISSUE TITLE
Bifurcation of the capabilities

### ISSUE THREAD

**Issue by iftikhariqbal** [MicrosoftDocs/microsoft-365-docs#12006]
The page has a note on the top which says "You won't be able to configure all the options referenced on this page if a [Teams Premium license](https://learn.microsoft.com/en-us/MicrosoftTeams/enhanced-teams-experience) isn't found for your tenant." 

Can you clarify which require Teams Premium and which do not within the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7476556-f95b-5e2f-2301-46cc3d52b71c
* Version Independent ID: b7476556-f95b-5e2f-2301-46cc3d52b71c
* Content: [Use sensitivity labels to protect calendar items, Teams meetings, and chat - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-meetings?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-meetings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-meetings.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@iftikhariqbal  Since this is a licensing question, you'll find it answered in the authoritative licensing page (link at the top of the page) as well in the product itself - specifically, this section: https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-22
