### ISSUE TITLE
Page is wrong

### ISSUE THREAD

**Issue by KevJBU** [MicrosoftDocs/microsoft-365-docs#12228]
Exchange O365 is sending mail from 40.95.63.80 however the closes range is 40.96.0.0/13 which does not cover the mentioned IP.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by KevJBU** [comment]
Further information, thus far we have resolved this problem by manually adding 40.95.63.0/22 and 40.95.96.0/22 to the allow list on our firewall. The closest matches to these are 40.92.0.0/15 which doesn't get has high as 40.95 and 40.96.0.0/13 which is higher than these IP ranges.

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by yoelsusanto** [comment]
On `2023-05-31 17:07 UTC`, we also started receiving email traffic from IP not defined in the SPF. Initially we reject these emails but we ended up relaxing the allowed IP list after we received a lot of complaint. Our investigation shows that these IPs have `40.95.xxx.xxx` pattern and they belong to the [high-risk delivery pool](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/outbound-spam-high-risk-delivery-pool-about?view=o365-worldwide).

We are initially not sure if this is a newly introduced system or not. However, we found [support case](https://techcommunity.microsoft.com/t5/exchange/exchange-online-send-mail-through-high-risk-delivery-pool/m-p/31640) that dates back to 2016. In addition to that, there is also a [page](https://social.technet.microsoft.com/wiki/contents/articles/36402.exchange-online-troubleshooting-high-risk-delivery-pool.aspx) describing about the high-risk delivery pool that dated back to 2016. Therefore, I don't think it is a new system but I suspect there was some recent change that may have caused this.

It would be helpful if there is a communication channel where we can keep track of such changes instead of knowing from customer complaints.

**Comment by tiburd** [comment]
We appreciate your feedback. This page is automatically generated from a database so we can’t manually update the page. However, if you suspect there is an error in this list of URLs and IP addresses or have questions, please contact Microsoft Support.
 
To contact Microsoft 365 Support:

- Sign in to Microsoft 365 admin center with your Microsoft 365 admin account, and select **Support** > **Help and support**, enter your question, and then select **Contact support**. 

- If you're an admin on the account, you can call 800-865-9408 (toll-free, US only).
