### ISSUE TITLE
MIssing French Canadian translation

### ISSUE THREAD

**Issue by olivjat** [MicrosoftDocs/microsoft-365-docs#12243]
Hello,
This article: https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations?view=o365-worldwide&source=docs
Is missing a French Canadian translation

**Comment by msbemba** [comment]
@olivjat Thank you for your feedback. Are you referring to Translation or migration from France tenant to Canada?

Thanks
Sri

**Comment by olivjat** [comment]
I am looking at the actual translation of the article.
Having it translated into French when reaching the Fr-ca or fr-fr pages.

**Comment by msbemba** [comment]
@olivjat Thank you for your quick response. We currently donot have this content in french. Once it is ready and made available, the note at the top of the document which currently states "Ce contenu n’est pas disponible dans votre langue. Voici la version anglaise." will not appear. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@tiburd Please help. Thanks

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [331502](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/331502) (internal link).

I'm closing this issue because the Global Services team will handle it from here.

**Comment by tiburd** [comment]
Reported as resolved.
