### ISSUE TITLE
No idea which M365 products have the referenced "Defender for Office 365" included

### ISSUE THREAD

**Issue by jimbotechsys** [MicrosoftDocs/microsoft-365-docs#12252]
No mention of which M365 products include "Defender for Office 365" nor to any products have that exact description for anything related to Defender. There is "Defender for Business" on M365 Business Premium and a variety of Defender versions listed for E5. I cannot tell if this is included in our subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Version Independent ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-about?view=o365-worldwide&viewFallbackFrom=o365-worldwide%3FWT.mc_id%3D365AdminCSH_globalsearch)
* Content Source: [microsoft-365/security/office-365-security/safe-links-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jimbotechsys, I recently added the following statement to the 'What do you need to know before you begin' section of most _procedural_ articles for Defender for Office 365 features:

 > - For more information about licensing requirements, see [Licensing terms](https://learn.microsoft.com/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#licensing-terms).

That link has the following note:

> [!NOTE]
> Office 365 E5, Microsoft 365 E5 Security, and Microsoft 365 E5 include Microsoft Defender for Office P2 licenses, and Microsoft 365 Business Premium includes Microsoft Defender for Office 365 P1 licenses.

It didn't occur to me to add licensing information to _conceptual_ articles, because I thought the Applies To links at the top of the article were good enough.

It sounds like the target Applies To article ([Microsoft Defender for Office 365 plan 1 and plan 2](https://learn.microsoft.com/microsoft-365/security/office-365-security/defender-for-office-365)) needs some kind of call-out or similar reference.

Would you agree?

**Comment by jimbotechsys** [comment]
It was not obvious to me this was a conceptual piece and thought it was pertinent documentation because I was led to the post through the M365 Admin Center while searching for Safe Links information. I was exasperated that I could not easily or quickly determine whether our exorbitant E3 subscription includes any sort of Safe Links protections. I have since learned it doesn't. I fully believe that, since Business Premium has P1 and E5 has the full Defender, E3 should have P2 _included_! Call me crazy.
