### ISSUE TITLE
Auto-Apply retention policies not applied to SPO sites Folders?

### ISSUE THREAD

**Issue by riohedfield** [MicrosoftDocs/microsoft-365-docs#12321]
Hi,
I hope you're doing well, there is bit of confusion that I would like to clear about this article, I hope you can help me with that.
A Microsoft Purview > Records Management > Retention policy, of type "Auto-Apply", with "Apply Label to content that contains specific, words or phrases, or properties" that is supposed to apply a 1 day retention label, applied to SPO sites (Sharepoint Classic and communication sites + Microsoft 365 Group Mailboxes & sites), the documentation isn't clear about what is going to be labeled and what is not supported in a SPO site. 
As per my testing, files are being labeled but not folders and subfolders and their content. 
The question is: Are folders supported by Records Management Retention policy of Type: Auto-Apply? will these folders and their content be labeled?
Please update the documentation to become clearer and specific.

BR
Ribo
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a4716f6-31db-306c-2804-56591e3af7e6
* Version Independent ID: 8dfc13ff-3b6a-ba25-2911-db7a3dcd2e8a
* Content: [Automatically apply a retention label to Microsoft 365 items - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/apply-retention-labels-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-retention-labels-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-retention-labels-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Retention settings are always applied at the item level, and this isn't specific to auto-labeling.  You'll find detailed information of what's included for retention policies and retention labels that apply to SharePoint here: https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#whats-included-for-retention-and-deletion

As confirmed by your tests, this section includes "Retention settings from both retention policies and retention labels do not apply to organizing structures that include libraries, lists, and folders." 

If you want to apply a retention label to a folder, so that content under that folder inherits the label, you'll need to manually apply it: https://learn.microsoft.com/en-us/microsoft-365/compliance/create-apply-retention-labels?view=o365-worldwide#applying-a-default-retention-label-to-all-content-in-a-sharepoint-library-folder-or-document-set
