### ISSUE TITLE
Can we please add the SMTP endpoint for GCCH

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/microsoft-365-docs#12348]
smtp.office365.us.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9f2948-6ae1-f907-836b-07f108ddf828
* Version Independent ID: 9a9f2948-6ae1-f907-836b-07f108ddf828
* Content: [Office 365 U.S. Government GCC High endpoints - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@J227668 Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data.
We recommend you contact the engineering team associated with the endpoint in question. 

Hope this helps!

Thanks
Sri
