### ISSUE TITLE
Manage library settings in Microsoft Syntex in libraries: How can i disable this option? it's added to all libraries. 

### ISSUE THREAD

**Issue by pereirautv** [MicrosoftDocs/microsoft-365-docs#12379]
Hi, 
How can i disable this option? 
Since this roll out i have this option in all libraries in the tenant, 
even libraries that don't have syntex model.
Don't want the ability to apply syntex to all libraries.

**Comment by yogkumgit** [comment]
@chuckedmonson Please help us in resolving this issue. Thanks

**Comment by chuckedmonson** [comment]
Investigating. Will get back to you. Thank you.

**Comment by chuckedmonson** [comment]
@pereirautv -- This is a new library setting for managing Syntex models. It will show in all libraries if you have a Syntex per-user license or pay-as-you-go enabled. It cannot be hidden, but it is only functional if there is one or more libraries applied to the library (otherwise it's an available, but not operational setting). Thank you.
