### ISSUE TITLE
Update Safe Links Article

### ISSUE THREAD

**Issue by fesimoes-MS** [MicrosoftDocs/microsoft-365-docs#12380]
Hi team,

Could you please update the article below about Safe Links with the information that Safe Links is able to detect malicious QR Codes in phishing emails:
Safe Links in Microsoft Defender for Office 365
https://learn.microsoft.com/microsoft-365/security/office-365-security/safe-links-about

I've been using the link below, since it has an official Microsoft response, but I believe the best location where this information should be is at learn.microsoft.com:
https://feedbackportal.microsoft.com/feedback/idea/c10d3f79-9aad-ed11-a81b-000d3a0450e3

The reason why I'm requesting that is because my customers are recently asking if EOP/MDO for O365 are able to detect QR Code attacks, since there have been several attacks like this one.

If you can also insert the information if EOP by itself is able to detect it, or if MDO for O365 license is required (since it has Safe Links in it).

Thanks!

**Comment by chrisda** [comment]
@fesimoes-MS, I added a reference to QR codes in the Safe Links article you referenced.

Safe Links is a Defender for Office 365 thing, so there's nothing to talk about in EOP content.

Thanks for the feedback.

Closing

**Comment by sharchitect** [comment]
I'm interested to understand whetehr defender for office is able detect malicious QR codes or not. On the 26th September, the documentation here contained a reference to this stating "...protects your organisation from malicious links, including QR codes, that are used in phishing and other attacks....". At some point since then the reference to QR codes has been removed. Since this is a significantly increasing tactic by bad actors, customers really need transparency on this point.
