### ISSUE TITLE
Subnet 13.107.6.156/31 for office.com is not listed anymore in the page.

### ISSUE THREAD

**Issue by nissac1** [MicrosoftDocs/microsoft-365-docs#12442]
I see that the subnet  "13.107.6.156/31", is no longer listed, however it is still an office.com IP.

sasi@rsasidharan-z01:~$ ping [office.com](http://office.com/)
PING [office.com](http://office.com/) (13.107.6.156) 56(84) bytes of data.
64 bytes from 13.107.6.156 (13.107.6.156): icmp_seq=1 ttl=116 time=22.2 ms
64 bytes from 13.107.6.156 (13.107.6.156): icmp_seq=2 ttl=116 time=22.9 ms
64 bytes from 13.107.6.156 (13.107.6.156): icmp_seq=3 ttl=116 time=22.0 ms
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@nissac1 Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data.
We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.

Thanks
Sri
