### ISSUE TITLE
Link to Exchange Online PowerShell Request

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/microsoft-365-docs#12509]
Would it be possible to add a link to the PowerShell commands needed to access the Exchange Online area in the instructions?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4babe398-9d2b-60ab-603b-4b564159ae3b
* Version Independent ID: 4babe398-9d2b-60ab-603b-4b564159ae3b
* Content: [Configure spam filter policies](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-policies-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-policies-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-policies-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rconiv, are you referring to the Exchange Online PowerShell connection instructions?

There's a link to the connection instructions in the 'What do you need to know before you begin?' section. But I can see the point that the link is really far away from the actual procedures themselves. But would the ten PowerShell procedure sections each need a link to the connection instructions? For example, 

> To view existing spam filter rules, use the following syntax:

Would become something like:

> To view existing spam filter rules, [connect to Exchange Online PowerShell](https://learn.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) and use the following syntax:

**Comment by rconiv** [comment]
Yes it was those instructions and wish there was a way to shorten it.  It takes longer just to get connected to the Exchange Online then to do anything in it.

Glad they have cleaned up that website some.  It was confusing with the instructions having the release and preview instructions.

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by chrisda** [comment]
Added link to 'connect to Exchange Online PowerShell' in each PowerShell procedures section as requested.

Thanks for the feedback.

Closing
