### ISSUE TITLE
Microsoft Graph Change Notifications public cloud IP range is not in sync to setup firewall restrictions for inbound traffic to receive change notifications.

### ISSUE THREAD

**Issue by sapinderpalsingh** [MicrosoftDocs/microsoft-365-docs#12582]
While implementing change notifications for O365 mail boxes, we used the given list for whitelisting inboud traffic, but still notifications were not getting delivered. On investigating the issue with product team it was found that the IP list shared on this page is not the updated one.

It will be nice to publish the latest Public Ips which customers can use for whitelisting.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Other endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@sapinderpalsingh Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data.
We recommend that you escalate your inquiry to the engineering team associated with the endpoint in question. 

Hope this helps!

Thanks
Sri
