### ISSUE TITLE
Common Attachment Filters

### ISSUE THREAD

**Issue by Dusted1969** [MicrosoftDocs/microsoft-365-docs#12819]
I had an issue with Common Attachment Filters (CAF) and it was only after a call to support that I discovered/realised the preset policies mange these completely and overrule any CAF settings changed in the Default policy.  I had permitted DOCM files (dont shoot me - we have users sending them everywhere) in the Default policy but these were still getting stopped by the Standard Preset Policy which was enabled.

It may be beneficial to call that out explicitly in the policy settings section:

https://learn.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies#policy-settings-in-preset-security-policies

I had read this page before logging my call and although it makes a bit more sense to me now what happened with my issue, if reference to CAFs was specifically included then it would have saved me and you some time.  It may be useful for someone else in future.

Ta!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f1cf3-a121-3c6e-9380-79440f4c6671
* Version Independent ID: 9b1bc5d1-8ecc-d0f9-092e-325c6acff4fe
* Content: [Preset security policies](https://learn.microsoft.com/en-gb/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide#appendix)
* Content Source: [microsoft-365/security/office-365-security/preset-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/preset-security-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Dusted1969, you raise an interesting point.

Fundamentally, any and every setting that's available in the default policy or custom policies for the following protection features will also suffer the same fate (because policies for those features are part of the Standard/Strict preset security policies, which are always applied first):

- Anti-malware
- Anti-spam
- Anti-phishing
- Safe Links
- Safe Attachments

I would find it a bit non sequitur if we called out only the file types to block in anti-malware policies (why mention only that specific setting?). Instead, this is what I did:

- I beefed up the description in the [Policy settings in preset security policies](https://learn.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies#policy-settings-in-preset-security-policies) section (changes in bold):

  > Fundamentally, you can't modify the individual policy settings in the protection profiles. **Customizing the corresponding default policy or creating a new custom policy has no effect due to the [order of precedence](https://learn.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies#order-of-precedence-for-preset-security-policies-and-other-policies) when the same user (recipient) is defined in multiple policies (the Standard and Strict preset security policies are _always_ applied first).**

- In the 'What do you need to know before you begin?' section in the configuration articles for each of the aforementioned policy types, I added the following TIP below the bullet about default settings. For example:

  - For our recommended settings for anti-malware policies, see [EOP anti-malware policy settings](https://learn.microsoft.com/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md#eop-anti-malware-policy-settings).

    > [!TIP]
    > Settings in the default or custom anti-malware policies are ignored if a recipient is also included in the [Standard or Strict preset security policies](https://learn.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies). For more information, see [Order and precedence of email protection](https://learn.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined).

  or

  - For our recommended settings for Safe Links policies, see [Safe Links policy settings](recommended-settings-for-eop-and-office365.md#safe-links-policy-settings).

    > [!TIP]
    > [Exceptions to Built-in protection for Safe Links](https://learn.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies#use-the-microsoft-365-defender-portal-to-add-exclusions-to-the-built-in-protection-preset-security-policy) or settings in custom Safe Links policies are ignored if a recipient is also included in the [Standard or Strict preset security policies](https://learn.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies). For more information, see [Order and precedence of email protection](https://learn.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined).

OK?

**Comment by Dusted1969** [comment]
Thats a great way to approach it - thanks for the reply.
