### ISSUE TITLE
Anti-spam outbound policy: Automatic forwarding recommendation

### ISSUE THREAD

**Issue by rafaelborter** [MicrosoftDocs/microsoft-365-docs#12859]
There are two different recommendations for the option "Automatic forwarding" in the "Anti-spam outbound policy (Default)".

[EOP outbound spam policy settings](https://learn.microsoft.com/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365#eop-outbound-spam-policy-settings):

> Automatic forwarding rules (AutoForwardingMode): Automatic - System-controlled (Automatic)

Microsoft Secure Score (Microsoft 365 Defender)
Ensure all forms of mail forwarding are blocked and/or disabled
Set Automatic forwarding rules dropdown to Off - Forwarding is disabled and click Save

Which recommendation should be chosen now. The one from the web or from the SecureScore?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rafaelborter, the two values are (now) functionally the same. **Automatic - System Controlled** = **Off**.

When the feature was first introduced ~2 years ago, it was implemented in a non-impacting state where **Automatic - System Controlled** meant **On** (no restrictions on automatic external forwarding, which was the behavior before the feature was introduced, because there was no way to restrict it). After about a year and with the appropriate warnings (Message Center etc.), **Automatic - System Controlled** was changed to mean **Off** (restrictions on automatic external email forwarding).

What I can do (and I thought I did at some point) is add a comment to that row in the table to explain that **Automatic - System Controlled** = **Off**. The situation is explained in other articles:

- [Control automatic external email forwarding in Microsoft 365](https://learn.microsoft.com/microsoft-365/security/office-365-security/outbound-spam-policies-external-email-forwarding)
- [Near the bottom of Step 5 in Use the Microsoft 365 Defender portal to create outbound spam policies](https://learn.microsoft.com/microsoft-365/security/office-365-security/outbound-spam-policies-configure#use-the-microsoft-365-defender-portal-to-create-outbound-spam-policies)

**Comment by yogkumgit** [comment]
@rafaelborter Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
