### ISSUE TITLE
Allow Entries Not allowed in TABL, consider reducing number of allowed entries

### ISSUE THREAD

**Issue by jkerai1** [MicrosoftDocs/microsoft-365-docs#12946]
You are not allowed to Add allow entries for senders or URLs to TABL whether its via GUI or Powershell, should the allow amount not be reduced and the block amount increased?

For any Allow entry written by microsoft anyway is removed after 30 days

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbb3daf4-fa28-88d9-4543-89d8ff5ead5d
* Version Independent ID: bbb3daf4-fa28-88d9-4543-89d8ff5ead5d
* Content: [Manage allows and blocks in the Tenant Allow/Block List](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by jkerai1** [comment]
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/55988027/e1cc20a4-ce1d-4742-bf08-bc3f7fc25aa3)

**Comment by jkerai1** [comment]
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/55988027/dcdce620-d03e-4ee3-a586-d1ada29fbc55)

**Comment by msbemba** [comment]
@jkerai1 Thank you for your feedback. The current limit for allowed entries is 500. But I agree with you on the idea of increasing the block list and reducing the limit in the allow list. I'd recommend you provide the feedback directly on our feedback portal -https://feedbackportal.microsoft.com/  so that our product team can review it and provide you an update once the changes are made.

Hope this helps!

Thanks
Sri
