### ISSUE TITLE
Additional Records

### ISSUE THREAD

**Issue by MurtazK** [MicrosoftDocs/microsoft-365-docs#1301]
Are these records available or documented? 5-7-16-17-34-39-43-46-48-51-57-58-59-60-61-63-65-67

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d18ff7-80de-a4d1-41a3-3601f09d3442
* Version Independent ID: dc3327c1-5c78-53ee-6ecb-18b274ddcdbd
* Content: [Detailed properties in the Office 365 audit log - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@MurtazK Are you actually getting audit records with these RecordType enum values? If so, please respond with which ones are generating audit records. Or are you just asking because these enum values aren't listed?

The short answer is some of these enum values are for features that haven't release or for activity that isn't being ingested into the unified audit log.

Also, if you're an Microsoft employee, please ping me internally. Thanks.

**Comment by markjjo** [comment]
Closing
