### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by pmcgrath66** [MicrosoftDocs/microsoft-365-docs#1302]
Is there a way to have a notification automatically sent to people when a Data Investigation is created? This is something we want automated and for it only to be changed by a Global Admin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09539c9-e275-d939-4142-22778724fa31
* Version Independent ID: f11a5861-65ed-ecb8-5bff-a4cbb1602c0a
* Content: [Overview of Data Investigations (Preview) in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/overview-data-investigations?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/overview-data-investigations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/overview-data-investigations.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@pmcgrath66 You can create a custom alert policy for the CaseAdded activity and configure notifications to be sent when the policy triggers an alert. For example, you can run the following command in Security & Compliance Center PowerShell:

New-ProtectionAlert -Name "User creates a compliance case" -Category Others -NotifyUser admin@contoso.onmicrosoft.com,sarad@contoso.onmicrosoft.com -ThreatType Activity -Operation CaseAdded -Description "Custom alert policy to track when compliance cases are created"  -AggregationType None

A few caveats:

- An alert and notification will be triggered when different types of cases are created. In addition to a data investigation case, this includes an eDiscovery case, Advanced eDiscovery case, insider risk management case, etc. You'll have to look at the alert details to see the case type.
- You can use other values for Category and you can use the Severity parameter to specify a different severity level.
- I don't think you can create the above alert policy in the UI because the "CaseAdded" activity isn't an option in the activities picker list.
- Audit records are also logged when new compliance cases are created. You can search for them in the audit log search UI using the "Created eDiscovery case" activity.

HTHs

More info:

https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/new-protectionalert?view=exchange-ps

https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide

https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-ediscovery-activities-in-the-audit-log?view=o365-worldwide#ediscovery-activities

**Comment by pmcgrath66** [comment]
We will try this. Thank you.

Patrick McGrath
SharePoint Administrator
[Open Dealer Exchange]
31440 Northwestern Hwy.  |  Suite 250  |  Farmington Hills, MI 48334
Office: 313.349.0052  |  Cell: 734.644.4635  |  Fax: 313.749.0990
pmcgrath@opendealerexchange.com<mailto:pmcgrath@opendealerexchange.com>
www.opendealerexchange.com
Follow Us: LinkedIn<http://www.linkedin.com/company/open-dealer-exchange-llc>
