### ISSUE TITLE
AllowClickThrough + DisableURLRewrite = ?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#13128]
Hello,

If we enable "Let users click through to the original URL" (AllowClickThrough), when "Do not rewrite URLs, do checks via Safe Links API only" (DisableURLRewrite) is also selected, does the former still apply?  In other words, with "Do not rewrite URLs, do checks via Safe Links API" enabled, is there even a webpage where a "Proceed anyway" link could be shown?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@JeremyTBradshaw, I'm told that the **Do not rewrite URLs, do checks via Safe Links API only** doesn't affect the availability of the block page if a user clicks on a bad link; the setting just skips wrapping the link. Whether or not the user can click through to the original link is still controlled by the **Let users click through to the original URL** setting.

OK?

**Comment by JeremyTBradshaw** [comment]
Hi @chrisda that's perfect, thank you very much.  I will refer to this issue for the current client and may do a PR later to update the explanation of the API approach.

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by JeremyTBradshaw** [comment]
Meant to close it upon @chrisda 's last update.
