### ISSUE TITLE
Unable to allow permission for 'Permanent protection' during onboarding on Xiaomi, MIUI 14

### ISSUE THREAD

**Issue by KayChengTJ** [MicrosoftDocs/microsoft-365-docs#13131]
Previous workaround doesn't work now:
[Unable to allow permission for 'Permanent protection' during onboarding on some OEM devices](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/android-support-signin?view=o365-worldwide#unable-to-allow-permission-for-permanent-protection-during-onboarding-on-some-oem-devices)

**Device:** Redmi Note 12 T PRO
**OS:** MIUI 14.0.5

Please give me a new workaround or fix the issue ASAP.
If you think it is a bug, create a work item to the owning team. THX

**Comment by msbemba** [comment]
@KayChengTJ Thank you for your feedback. The Defender team is working on a permanent fix and we will update the document when the fix is ready. We have also updated it in the Note. Meanwhile, If you'd like to get more details on the fix, you can contact Microsoft support via the need help section so that they can escalate it to the product group and provide an update.

Hope this helps!

Thanks
Sri
