### ISSUE TITLE
Bad guidance around sending infrastructure identification in Domain Pair syntax section

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#13150]
I'm referring to this purple note block section:

>  Note
> 
> You can specify wildcards in the sending infrastructure or in the spoofed user, but not in both at the same time. For example, *, * isn't permitted.
> 
> If you're using a domain instead of the IP address or IP address range in the sending infrastructure, the domain needs to match the PTR record for the connecting IP in the Authentication-Results header. You can determine the PTR by running the command: ping -a <IP address>. **_We also recommend using the PTR Organization Domain as the domain value. For example, if the PTR resolves to "smtp.inbound.contoso.com", you should use "contoso.com" as the sending infrastructure._**

Going with Contoso.com instead of smtp.inbound.contoso.com is, to me, extremely liberal to the ENTIRE contoso.com domain.  That could represent an infinite number of sending infrastructures.

Please elaborate what is the logic here with this guidance?  It should be removed unless it is logical and reasonable.  What does it mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9b787f-def1-bbc5-48ca-42180f9560d2
* Version Independent ID: 3d9b787f-def1-bbc5-48ca-42180f9560d2
* Content: [Allow or block email using the Tenant Allow/Block List](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure?view=o365-worldwide#domain-pair-syntax-for-spoofed-sender-entries)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by dhairyya** [comment]
contoso.com does not include smtp.inbound.contoso.com. 
the guidance regarding *,* is there to state that the system does not allow wildcards across both domain sending infrastructure and user at the same time inside spoofed sender entries of Tenant Allow block List.

**Comment by JeremyTBradshaw** [comment]
When I re-read the quoted text, I do not get the message that you've stated.  It's two entirely different topics.  It intentionally mentions it is recommended to use the "organization" domain instead of the longer subdomain FQDN.

I don't have any issues with the point you've raised, I just don't think that's what the text is saying.

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by JeremyTBradshaw** [comment]
Well isn't this convenient for this particular one?  Mmmhmm.   OK.
