### ISSUE TITLE
Issue with Lighthouse Permissions for Creating Alerts

### ISSUE THREAD

**Issue by jreinhardtproarch** [MicrosoftDocs/microsoft-365-docs#13186]
In this article, @gregdod has found, that https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-overview-of-permissions?view=o365-worldwide#permissions-in-the-partner-tenant does not list that create or view alerts requires global administrator in the partner tenant. However, the link https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-create-manage-alert-rules?view=o365-worldwide indicates that global admin is required. We're seeing evidence that people who do not have global administrator roles are able to create alert rules. So, what is the issue? Is one or two of these out of date?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2ae106d-e97e-3dfb-2701-6967bdbaa69c
* Version Independent ID: b2ae106d-e97e-3dfb-2701-6967bdbaa69c
* Content: [Overview of permissions in Microsoft 365 Lighthouse - Microsoft 365 Lighthouse](https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-overview-of-permissions?view=o365-worldwide)
* Content Source: [microsoft-365/lighthouse/m365-lighthouse-overview-of-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lighthouse/m365-lighthouse-overview-of-permissions.md)
* Service: **microsoft-365-lighthouse**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by yogkumgit** [comment]
@SKjerland Please help us in resolving this issue. Thanks

**Comment by SKjerland** [comment]
@jreinhardtproarch - Thanks for bringing this to our attention! I'm waiting for one of our Lighthouse product managers to confirm the permission requirements. Once they respond, I'll let you know, and then I'll update the articles accordingly.

**Comment by SKjerland** [comment]
@jreinhardtproarch - The Lighthouse product team confirmed that global admin permissions ARE required in order to create alert rules. Partners without global admin perms should not be able to create alert rules. The team has opened a bug to investigate and fix this issue. In the meantime, I'll go ahead and update [https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-overview-of-permissions?view=o365-worldwide#permissions-in-the-partner-tenant](https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-overview-of-permissions?view=o365-worldwide#permissions-in-the-partner-tenant) so it's consistent with [https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-create-manage-alert-rules?view=o365-worldwide](https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-create-manage-alert-rules?view=o365-worldwide). Thanks again for bringing this to our attention!
