### ISSUE TITLE
CloudAppEvents  column IsAdminOperation

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/microsoft-365-docs#13202]
Hello,

the description for the column "IsAdminOperation" currently reads:
> Indicates whether the activity was performed by an administrator

However in our tenant, events with ActionType "Get-QuarantineMessage" or "Delete-QuarantineMessage" get  a value of 1 for "IsAdminOperation" even though regular users are accessing their quarantined mails. They are not admins.
Can you please clarify if the current description for the column is correct?
Under which conditions does an Cloudappevents event get an "IsAdminOperation" value of 1?

<br class="Apple-interchange-newline">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 000c78a4-4a72-75aa-9c2f-4f7dbeab5aea
* Version Independent ID: 4414f9d1-1e81-c316-f98f-502f94232b12
* Content: [CloudAppEvents table in the advanced hunting schema](https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-cloudappevents-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-cloudappevents-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-cloudappevents-table.md)
* Service: **defender-xdr**
* Sub-service: **adv-hunting**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@schmurky Please help us in resolving this issue. Thanks

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by schmurky** [comment]
hello, accdg to the PM, 1 means it is indeed an admin operation. the best way to go about changing this is to open a support ticket
