### ISSUE TITLE
Allows active users to change their name and avatar ?

### ISSUE THREAD

**Issue by tientv2019** [MicrosoftDocs/microsoft-365-docs#13244]
I can't find a setting that allows users to change their name and profile picture. office 365 A1 Please help!

**Comment by msbemba** [comment]
@tientv2019 Thank you for your feedback. Changing the name is usually done by the admins, however, if you are having trouble changing the profile picture, I'd recommend you contact support via the need help section on the admin center. So that our support engineer can contact you to fix this.

Hope this helps!

Thanks
Sri
