### ISSUE TITLE
DR copies not explained

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/microsoft-365-docs#13269]
The FAQ page (https://learn.microsoft.com/en-gb/microsoft-365/syntex/backup/backup-faq) talks about DR copies
>Why don’t DR copies suffice for my backup?
>DR copies protect only the current state of content, not prior points in time. Microsoft 365 Backup provides additional benefit by giving you a way to restore data back to a healthy state in the past with fast RTO to with short RPO intervals.

It isn't really clear what is meant by this. On the overview page there is 1 mention of BCDR. I think:

1. Expand the acronym to Disaster Recovery
2. Explain what a DR copy is, as it is to ambiguous - I'm assuming you are talking about the DR that the M365 has is place under it's current Service Description, not anything the customer has done or a feature of the new M365 Backup service

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28d71470-f267-75df-06ce-bb07724b6475
* Version Independent ID: 28d71470-f267-75df-06ce-bb07724b6475
* Content: [Frequently asked questions about Microsoft 365 Backup (Preview) - Microsoft Syntex](https://learn.microsoft.com/en-gb/microsoft-365/syntex/backup/backup-faq)
* Content Source: [microsoft-365/syntex/backup/backup-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/backup/backup-faq.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@thommck -- Thank you for your inquiry. I'll follow up with the product team and update accordingly. Thanks again.

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by chuckedmonson** [comment]
Disaster recovery information added.
