### ISSUE TITLE
Still can't figure out Bookings and how to restrict booking dates to a few months in the future

### ISSUE THREAD

**Issue by syarnellYIrsch** [MicrosoftDocs/microsoft-365-docs#13279]
[Enter feedback here]
All I wanted to do was say I did not really understand the page I was viewing from Microsoft.  It did not seem to address any issues of relevance for me and I must confess to not really understanding it.   I'm trying to use Bookings but nothing about it seems intuitive to me.  I can't change the availability of permissible dates, e.g.,  I'll try to find other options

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: adb53eb7-85a1-6aa0-dfd1-e2b54586008a
* Version Independent ID: 5532470a-a47d-e3bd-4e74-02b2c822cae1
* Content: [Microsoft Bookings](https://learn.microsoft.com/en-us/microsoft-365/bookings/bookings-overview?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-overview.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by msbemba** [comment]
@syarnellYIrsch Thank you for your feedback. For How to questions and technical problems, we recommend you to create a support ticket via the need help section on the admin center, so that our support team can assist you in fixing them.

Hope this helps!

Thanks
Sri
