### ISSUE TITLE
Outdated Documentation Steps

### ISSUE THREAD

**Issue by kbar-mnx** [MicrosoftDocs/microsoft-365-docs#13286]
Hello, 

I was attempting to setup a DKIM record for a M365 Tenant using this article, however it should be noted that there is an outdated step which it is quite confusing and non-user friendly to find the answer to.  See my screenshot below:

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/153117055/3a0bb204-338c-478c-812b-b860cbd06fb2)

This step no longer applies as the "Create DKIM keys" button no longer exists, and you actually have to try to enable DKIM without the keys for it to give an error which contains the keys. See the below screenshots:

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/153117055/8a55ac8f-1123-4a7c-b245-283977fd02ef)
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/153117055/1d448843-873a-4e2e-8230-492e429f8bd4)

This should be corrected in the article or in the portal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/email-authentication-dkim-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/email-authentication-dkim-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/email-authentication-dkim-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
