### ISSUE TITLE
Instructions wrong for Microsoft 365 Mobile

### ISSUE THREAD

**Issue by Fifteen15Studios** [MicrosoftDocs/microsoft-365-docs#13314]
The instruction in the section titled "Disabling the Feed in Microsoft 365 Mobile" do not work. I have tried this every way possible, and the feed is still available in the Microsoft 365 app in both Android and iOS. Please update these instructions to something that actually works, and/or maybe provide screenshots of how to configure this properly.

All of the other instructions on this page worked for me, but this part is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33a72984-2f32-2e55-3e40-c47d7376d733
* Version Independent ID: 33a72984-2f32-2e55-3e40-c47d7376d733
* Content: [Overview of the Microsoft Feed](https://learn.microsoft.com/en-us/microsoft-365/ms-feed/m365-feed?view=o365-worldwide#disabling-the-feed)
* Content Source: [microsoft-365/ms-feed/m365-feed.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/ms-feed/m365-feed.md)
* Service: **microsoft-365-business**
* GitHub Login: @temanteleary
* Microsoft Alias: **teleary**

**Comment by dstrome** [comment]
Thanks for taking the time to submit feedback about our content. We’ve implemented a new system to make it easier for you to provide feedback. As a result, we’re no longer accepting feedback in this repository via GitHub Issues so this issue is being closed. For more information about the new system, please visit [https://learn.microsoft.com/office/new-feedback](https://learn.microsoft.com/office/new-feedback).
