### ISSUE TITLE
as8p194mb2000.eurp194.prod.outlook.com

### ISSUE THREAD

**Issue by MasterOwnerETcorps** [MicrosoftDocs/microsoft-365-docs#13321]
https://as8p194mb2000.eurp194.prod.outlook.com/git.status

**Comment by dstrome** [comment]
Thanks for taking the time to submit feedback about our content. We’ve implemented a new system to make it easier for you to provide feedback. As a result, we’re no longer accepting feedback in this repository via GitHub Issues so this issue is being closed. For more information about the new system, please visit [https://learn.microsoft.com/office/new-feedback](https://learn.microsoft.com/office/new-feedback).
