### ISSUE TITLE
Listing future retirement date

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#1366]
"Devices that are out of compliance" section states that device future retirement date is list on the MMD portal. I can't see that anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2c9bf7d-827d-5c9c-9753-ab3613eeb952
* Version Independent ID: 889b6ae7-3283-0597-569d-ac178ff2289d
* Content: [Microsoft Managed Desktop product lifecycle - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/device-lifecycle?view=o365-worldwide#devices-that-are-out-of-compliance)
* Content Source: [microsoft-365/managed-desktop/service-description/device-lifecycle.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/service-description/device-lifecycle.md)
* Service: **m365-md**
* GitHub Login: @jaimeo

**Comment by jaimeo** [comment]
I'll engage some SMEs for you on the question of the Portal, but in the meantime, the Device list topic (https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/device-list?view=o365-worldwide) is always a reliable source for the retirement dates.

**Comment by jaimeo** [comment]
@jwmurraycmu can you investigate and advise on this report that the MMD portal (I assume aka.ms/mmdportal) should be showing a device retirement date list but isn't?

**Comment by jwmurraycmu** [comment]
@jaimeo, we actually display the device's age on the MMD portal. This is is because devices each have individually separate retirement dates which is 3 years after it's initially registered. On the device list page we show the retirement date for the model across the ecosystem, meaning no new devices of that model will be allowed to be registered after that date. 

All of that said, ceaton001 is correct - we should update this content from referencing "retirement date" to "device age".

**Comment by jaimeo** [comment]
This is fixed.
