### ISSUE TITLE
need script utilizing modern MFA connection

### ISSUE THREAD

**Issue by norrben** [MicrosoftDocs/microsoft-365-docs#1428]
please give an example of the same script utilizing accounts with MFA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b759021-39d7-0383-2f50-b5b813217f97
* Version Independent ID: 5f5dfeab-1160-3994-2cb8-1ca7c67e3ff2
* Content: [Use a script to add users to a hold in an eDiscovery case in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@norrben Thanks for the inquiry. No, it's not possible to use a script to logon when MFA in enabled/required.  With MFA you need to provide that second authentication factor as you logon.

Here's a couple of GitHub issues where this issue is discussed:
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4483 
https://github.com/MicrosoftDocs/office-docs-powershell/issues/4371

I understand there may be a workaround (for Exchange Online, not sure about SCC PowerShell) using an Azure feature is called Trusted IPs: https://docs.microsoft.com/azure/active-directory/authentication/howto-mfa-mfasettings#trusted-ips 

After you set up trusted IPs, then then when the user/script connects to SCC/SPO PowerShell, MFA isn't required; you just enter your username and password.
