### ISSUE TITLE
Need instructions for devices that need be re-registered or needs an update from the Home edition.

### ISSUE THREAD

**Issue by cmanhoff** [MicrosoftDocs/microsoft-365-docs#1462]
This document  ignores devices that have Windows Home but need to be updated to Windows Business or Enterprise.  Are we supposed to buy an upgrade from Home to Pro so we can then turn around and upgrade from Pro to Businerss?

Also ignored is that the user has the device registered under a personal Microsoft and it needs to be reregistered to hiw work account email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8e657e-2aa7-230d-0d9d-675c0200ac18
* Version Independent ID: 2028f003-2624-2bd3-34ea-6022d495e2c6
* Content: [Set up Windows devices for Microsoft 365 Business users - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/set-up-windows-devices?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/business/set-up-windows-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/set-up-windows-devices.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sureshd868** [comment]
Let's first start with the assumption that you're considering this upgrade for a Commercial entity.

If they have a Windows 7/8/8.1 Home licensed devices, they should be able to upgrade it to Windows 10 Home at no cost (right now) using the free upgrade to Win 10.

Unfortunately, this document clearly states that you need at least Win 10 Pro as the pre-requisite to upgrade to Win 10 Biz. According to the Microsoft Product Terms -English version (See under the Windows Section, pg 43, Item 2.8 ) , "Customers in Australia, Canada, Iceland, Japan, New Zealand, Norway, Switzerland, USA, or any country in the European Union may license the Windows 10 Home to Pro Upgrade for Microsoft 365 Business in any quantity up to the number of its Microsoft 365 Business subscriptions."

If your customer doesn't reside in one of these countries, then the best bet is to:
1. Do the Win 7 home upgrade to Win 10 Home.
2. Use a Microsoft account belonging to the business and purchase the Win 10 Home to Pro Upgrade from the Microsoft Store on each device.
3. Let the Upgrade download and restart the machine before verifying that it's now at Win 10 Pro.
4. Run an elevated command prompt run "c:\windows\System32\sysprep\sysprep.exe /generalize /oobe /reboot" in order to reset the Security identifiers of the OS, remove all previous user profiles and restart the computer.

The system will restart with that new car smell, and ask you the typical new device questions, including the one that asks if you're going to sign in using a Microsoft account or a work account.

At this point you should have the M365 Business account ready and setup to be used to sign into the machine.

**Comment by mypil** [comment]
@cmanhoff - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by Sureshd868 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by magicmike73** [comment]
We have exactly the scenario Sureshd868 has described: "Customers in Australia, Canada, Iceland, Japan, New Zealand, Norway, Switzerland, USA, or any country in the European Union may license the Windows 10 Home to Pro Upgrade for Microsoft 365 Business in any quantity up to the number of its Microsoft 365 Business subscriptions."

We have bought the SKU but the activation key does not work. Can I get someone from Microsoft to assist asap?

**Comment by Sureshd868** [comment]
> We have exactly the scenario Sureshd868 has described: "Customers in Australia, Canada, Iceland, Japan, New Zealand, Norway, Switzerland, USA, or any country in the European Union may license the Windows 10 Home to Pro Upgrade for Microsoft 365 Business in any quantity up to the number of its Microsoft 365 Business subscriptions."
> 
> We have bought the SKU but the activation key does not work. Can I get someone from Microsoft to assist asap?

Try https://www.microsoft.com/Licensing/servicecenter/Help/Contact.aspx to see if you can get support to activate the key.
