### ISSUE TITLE
Options to report junk, phishing

### ISSUE THREAD

**Issue by prontohostau** [MicrosoftDocs/microsoft-365-docs#1469]
After running the powershell Set-OwaMailboxPolicy -Identity "OwaMailboxPolicy-Default" -ReportJunkEmailEnabled $false
The options are still there. Even the powershell output shows that Report Junk Email Enabled is false.

Can you confirm that this option will not be removed by running the powershell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2ad21c-ef11-92f5-02ab-0bd40a175276
* Version Independent ID: 1e21f43a-1c2d-b335-935f-f796ae31f779
* Content: [Turn off junk email reporting in Outlook on the web - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/turn-off-junk-email-reporting-in-outlook-on-the-web?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/security/office-365-security/turn-off-junk-email-reporting-in-outlook-on-the-web.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/turn-off-junk-email-reporting-in-outlook-on-the-web.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@prontohostau Thank you for your feedback. The options to report Junk and Phishing will be always available.  In your situation after disabling the report to junk option, users can still mark messages as junk, phishing, and not junk, but the user can't report them to Microsoft.

This is added in the section https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop?view=o365-worldwide&source=docs#how-do-you-know-this-worked

Hope this helps!

Thanks
Sri

**Comment by chrisda** [comment]
@prontohostau, I've been looking into this.  Apparently, disabling junk email reporting does not affect the Junk/Not junk actions you see in the Outlook on the web ribbon or when you right-click on a message. They're always present, because that same selection also moves messages into or out of the Junk Email folder. Disabling junk email reporting removes that intermediate dialog that asks you if you want to report the message to Microsoft:

![image](https://user-images.githubusercontent.com/33166947/78071170-dfa68980-7351-11ea-8200-bbc234698bd3.png)

I tested this in Exchange Online, Exchange 2019, Exchange 2016, and Exchange 2013. The UI is a bit different between versions, but it has the same affect.

I updated the topic with relevant updates.

Thanks for the feedback.

Closing
