### ISSUE TITLE
Search if  a document library have been synced to a PC

### ISSUE THREAD

**Issue by ceejey01** [MicrosoftDocs/microsoft-365-docs#1554]
In audit logs, several files were deleted by sharepoint/system. No retention/deletion policy. How can I check if the particular document library was ever synced to a PC. I believe this will help in investigating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ceejey01 Please see these sync-related auditing activities: https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#synchronization-activities

You might also try to using the "File, folder, or site" box in the audit log search UI with the name/URL of the document library or a document in that library.

Otherwise, you can consider opening a support ticket with MS Support.
