### ISSUE TITLE
Conflicting settings?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/microsoft-365-docs#1612]
Hi,
When you assign the 1 month, 1 year, and Never policies and direct them all at the "Personal" tag, does that create 3 separate tags that a user can pick from to assign to emails or how do those settings work together since they are 3 different settings but all as a Personal tag?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Set up an archive and deletion policy for mailboxes in your Office 365 organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@kelemvor33 The answer to your first question is yes. If you add those 3 personal tags to a retention policy, then those tags are available to users assigned that retention policy. But only one personal tag can be assigned to an email message as any one time. So tags with different retention periods won't come into conflict because only one tag can be assigned to a mail item at any one time. For more info, see https://docs.microsoft.com/en-us/Exchange/security-and-compliance/messaging-records-management/retention-tags-and-policies
