### ISSUE TITLE
provide more indepth details.

### ISSUE THREAD

**Issue by vaskotoo** [MicrosoftDocs/microsoft-365-docs#1661]
Could we get more clarity about the terminology used in the article:
1. What "intentional activity" means for office usage?
2, How accurate and up to date the data is for `Last activity date (UTC) ` ?

For example:
`Last activity date (UTC) is the latest date an intentional activity was performed by the user. To see activity that occurred on a specific date, select the date directly in the chart.`

Based on that information, my expectation is : 
If I open excel on my computer today, 24-48 hours from today I get that data reflected in the report.

But the reality is:
I have been opening excel multiple times within the last couple weeks, but the report states my last activity was 1 month ago.

Answering these 2 questions , would help me as an admin to understand the report results better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7957baf3-919b-fa91-073c-d71672282268
* Version Independent ID: 418a59f1-83bd-ff70-fbff-c3980f083ff8
* Content: [Microsoft 365 Reports in the admin center - ProPlus usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft365-apps-usage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/microsoft365-apps-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/microsoft365-apps-usage.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@vaskotoo Thank you for your feedback. 

1)Intentional activity means the user opens an office app on purpose or deliberately. There could be users who opened a file earlier and left as is.

2)The data in each report usually covers up to the last 24 to 48 hours. If there is a discrepancy in the report, I'd recommend you contact support via need help option in the admin center to troubleshoot.

Hope this answers your questions. As such there is no changes required in the document at the moment, however if you feel modifications are needed, please let us know via the feedback section.

@yogkumgit We can proceed with closing this as there is no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @vaskotoo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
