### ISSUE TITLE
Converting in Hybrid mode

### ISSUE THREAD

**Issue by it-cairnmillar** [MicrosoftDocs/microsoft-365-docs#1693]
I see a minor issue with this process when in Hybrid mode. You say to move the mailbox back to on premise. We have no on-premise mailboxes and no on-premise mailbox databases. Moving a mailbox that we want to convert to a shared mailbox would directly breach the license agreement that we have on our Hybrid where we are provided with a key for Exchange 2016 as long as we do not create any local mailboxes, otherwise we have to pay for a complete Exchange license for what is basically a management instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b3fbbe-fde3-fd52-f9cd-d8fca56a1494
* Version Independent ID: 73d71ee8-579d-78b5-a8cd-48d7ec51ebb8
* Content: [Convert a user mailbox to a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by JeremyTBradshaw** [comment]
@it-cairnmillar  that's a great point, only this need to move mailboxes back to on-premises for the conversion is no longer a thing, as long as you have an Exchange 2016 CU10 or newer server to use PowerShell from.

We now can do Set-RemoteMailbox <Id> -Type Shared

https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/set-remotemailbox?view=exchange-ps (see the -Type parameter section)

**Comment by it-cairnmillar** [comment]
@JeremyTBradshaw, thanks for your input, it is appreciated. However, this does not work in our scenario.
"You can only use Shared on a mailbox that was originally created in Exchange Online. If the mailbox was originally created in on-premises Exchange and then migrated to Exchange Online, you need to migrate the mailbox back to on-premises Exchange, convert the mailbox to a shared mailbox in on-premises Exchange, and then migrate the shared mailbox to Exchange Online." The account in question is a migrated mailbox. So back to the issue with licensing....

**Comment by UserAdminDEUS** [comment]
I can ulr e mail alise already taken

**Comment by UserAdminDEUS** [comment]
Request Id: 5a388bbf-0fd3-4d75-b7b2-55c69a857700 
Correlation Id: 09b30f50-4ae3-4c22-b3f0-3e88fe8da396 
Timestamp: 2020-04-30T02:33:32Z 
Message: AADSTS50020: User account 'pabstshawn@gmail.com' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application 'b9c392b1-7049-4d6c-86bf-9bb91214900d'(Microsoft Learning Identity Service) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by msbemba** [comment]
@it-cairnmillar I'm discussing this with the author and will get back to you shortly.

**Comment by mypil** [comment]
@cmcatee-MSFT @Sirkkuw - Can you please share your insights on this issue?

Thank you.

**Comment by Sirkkuw** [comment]
I think this might not be for either of us. This is more for the Exchange team. Try @SerdarSoysal - someone on his group should be able to help.

**Comment by markjjo** [comment]
@it-cairnmillar We checked with Support and Product Marketing and they said that this scenario is not in violation of the license because the mailbox is not hosted on premises but is migrated back and forth. This has to be done because the on-premises is the "source of authority" in terms of the directory service. Moving the mailbox back to on-premises, making a config change and then moving it back to the cloud would not be considered “hosting mailboxes on the servers used to connect to Microsoft 365" in a hybrid deployment.

We have updated the topic with this info, which should be live by tomorrow.

"This recommended solution is not in violation of the licensing agreement for hybrid environments because the existence of the user mailbox on-premises is only temporary. You would be in violation of your license if you maintained the user mailbox or shared mailbox in your on-premises organization and did not move it back to the cloud."
