### ISSUE TITLE
what admin roles are needed?

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/microsoft-365-docs#1704]
Are their limits to what can be seen based on admin role assigned?   What admin roles are needed to use Advanced hunting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bd75f06-75c8-c8f2-e2b4-0d48c714276f
* Version Independent ID: 621789df-ce3f-d985-9a93-77a46a18a9b8
* Content: [Overview of advanced hunting in Microsoft Threat Protection - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/advanced-hunting-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/advanced-hunting-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/advanced-hunting-overview.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by msbemba** [comment]
@scottsa-msft Thank you for your feedback.  Since this option is a part of Microsoft security center you need to be a Global Administrator, Security Administrator, Security Operator, or Security Reader in Azure Active Directory to access the Microsoft 365 security center.

The access level is different for each role and the same can be found at https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles


I have created a PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1806 to add a note to the document about the admin roles needed to access this feature.

Thanks
Sri

**Comment by mypil** [comment]
@scottsa-msft - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/1d9c243c5bd0642821da8d733aac28de06dd0864. 


Thank you for your contribution to make the docs better! Much appreciated!
