### ISSUE TITLE
Just want to purge a Recoverable Items folder (except for the last month's items)

### ISSUE THREAD

**Issue by sjbj18463** [MicrosoftDocs/microsoft-365-docs#1742]
i can't seem to craft the Search against Just the Recoverable Items folder for things more than 32 days old.

Litigation hold was enabled in error a few months ago and i need to clear down users' Recoverable Items folders

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the Recoverable Items folder of cloud-based mailboxes on hold - Admin Help - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@sjbj18463 A few alternative suggestions. For all of these, you'll have to make sure that no other type of hold is placed on the mailbox or nothing will be permanently deleted.

- Why not just remove the Litigation Hold and then run the Managed Folder Assistant on the affected mailboxes? If the deleted item retention period has expired for items that were on hold, then those items should be marked for permanent deletion (as long as there's no other type of hold on the mailbox).

- Use the Search-Mailbox -SearchDumpsterOnly -DeleteContent command in EXO PowerShell. You can include the date range in the query parameter. The retirement of this cmdlet has been postponed to July 2020 because of the public health situation, so this would be available to use right now. See https://docs.microsoft.com/en-us/Exchange/security-and-compliance/recoverable-items-folder/clean-up-deleted-items

- See [this github issue](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1774). I haven't tested this but you might be able to peform a target collection to obtain the folderid for the Recoverable Items folder/subfolder and then include that in the search query for New-ComplianceSearch.

Another option is open a ticket with MS Support. 

Hope this is helpful.
