### ISSUE TITLE
Something missing?

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/microsoft-365-docs#1760]
Under the header "How retention labels work with retention label policies," there is a bullet under the second figure that seems to be missing something or simply has a typo:

"When you publish retention labels, they're included in a retention label policy. Retention label names are immutable, which means that they and cannot be edited after they're created."

"...which means that they and...." ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Overview of retention labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels?view=o365-worldwide#how-retention-labels-work-with-retention-label-policies)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@ferrety2006  Hi, thanks for reporting this.  It is indeed just a typo that we all missed until now. I'll make sure it gets fixed with a pending revision.  Should read "When you publish retention labels, they're included in a retention label policy. Retention label names are immutable, which means that they cannot be edited after they're created"
