### ISSUE TITLE
Limitations: Cannot find documentation specifying limits/maximums for Labels

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/microsoft-365-docs#1761]
Regarding Retention Labels, I've yet to find a section within the documentation to specifies the:
1. Max # of Retention Labels a single tenant can have
2. Max # of Policies a single tenant can have
3. Max # of labels allowed within a Policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Overview of retention labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@ferrety2006  To my knowledge, there aren't any limits for retention labels and their policies (unlike retention policies), which is why you can't find these limits documented.  But I'll check to make sure.

**Comment by cabailey** [comment]
@ferrety2006 Just as well I checked because I discovered the 10,000 max limit number we document for retention policies actually apply across all policies - not just retention policies but also auto-apply retention policies, retention label policies, DLP policies, eDiscovery holds. I'll certainly look to document this in the near future but for now, you have your answer. Technically, there's no limit to the number of retention labels but in practical terms the maximum number will be limited by usability for retention label policies (users having to scroll through too many labels) and admin overheads for maintenance purposes.
