### ISSUE TITLE
ATP Plan 2 licence for all users ?

### ISSUE THREAD

**Issue by philippebac** [MicrosoftDocs/microsoft-365-docs#1829]
Do all domain users need to have an ATP Plan 2 licence to use the investigation tool ? or only admin users ?

**Comment by mypil** [comment]
@philippebac - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by philippebac** [comment]
@mypil - The document used is : https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-air Thank you 👍

**Comment by denisebmsft** [comment]
@philippebac thank you for raising this good question. Office 365 ATP Plan 2 license should be assigned to all users. Security administrators and security operators must have the license assigned in order to view and use the automated investigation capabilities. In addition, end users should be assigned Office 365 ATP Plan 2 licenses so that they show up in reports and remediation actions. There's also the part that Office 365 ATP policies must be defined and in effect. I've added all of this to the article, and you should see the changes on the live site later today. Thanks again for raising this question!
