### ISSUE TITLE
Get-InboxRule "includehidden' isn't available for EXO

### ISSUE THREAD

**Issue by ThijsLecomte** [MicrosoftDocs/microsoft-365-docs#1836]
In the Get-InboxRule documentation it says that the includeHidden parameter is only for on-prem Exchange(https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-inboxrule?view=exchange-ps#parameters)

Why is it recommended to utilize it here than?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bec871b-790f-6826-b8f8-d1b7830c49ab
* Version Independent ID: 460db4e8-7f93-60a3-4889-f2d8f08fc75f
* Content: [Configure junk email settings on Exchange Online mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ThijsLecomte, I confirmed the IncludeHidden switch is available on the Get-InboxRule cmdlet in Exchange Online, yet it doesn't work (it throws a weird error), so it's effectively unavailable as you and the cmdlet reference topic describe. So, I removed the Get-InboxRule command from this topic.

Thanks for the feedback.

Closing

**Comment by ThijsLecomte** [comment]
But if you remove it, how are we able to verify that the spam rule works as it should?

**Comment by chrisda** [comment]
As described in the topic, Get-MailboxJunkEmailConfiguration shows whether the Junk E-mail Rule is enabled on the mailbox (Enabled: True = enabled, Enabled: False = disabled), and you use Set-JunkEmailConfiguration to enable or disable it. You don't modify the Inbox rule directly.

Using `Get-InboxRule -IncludeHidden` is just another method to verify whether the Junk E-mail Rule  is enabled or disabled. So, instead of two verification methods as in on-premises Exchange Server, there's only one verification method available in Exchange Online.
