### ISSUE TITLE
Mention delay between activity happened and email notification is sent

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1950]
Hello,

with activity alerts there were some hours of delay between the moment when an activity happened and when the email notification is sent. If this is the same for alert policies, this delay should be mentioned as it's important to know about. This seems to be a known limitation of this feature and doesn't seem to be a bug. Please verify if alert policies have the same kind of delay and if yes, mention it in the documentation.

Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance centers - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@GiantCrocodile For activity alerts (which as you know are deprecated) the delay may be due to the same SLA when events are ingested to unified audit log after they occur (30 minutes or 24 hours) See https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#before-you-begin). I also imagine there could be an intermittent delays in the mail pipeline, either outbound or inbound.

I will investigate if similar SLA exists for the email notifications for alert policies and update topic if necessary.
