### ISSUE TITLE
Licensing Information

### ISSUE THREAD

**Issue by SeCossio** [MicrosoftDocs/microsoft-365-docs#1952]
Please include the license SKU required to take advantage of this feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09539c9-e275-d939-4142-22778724fa31
* Version Independent ID: f11a5861-65ed-ecb8-5bff-a4cbb1602c0a
* Content: [Overview of Data Investigations (Preview) in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/overview-data-investigations?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/overview-data-investigations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/overview-data-investigations.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@SeCossio Because Data investigations is in public preview, there is no SKU requirement. When it's eventually released to General Availability, I assume it will require an E5 subscription because many of the features in Data investigations are similar to those in [Advanced eDiscovery](https://docs.microsoft.com/microsoft-365/compliance/get-started-with-advanced-ediscovery?view=o365-worldwide).
