### ISSUE TITLE
Licensing for Archive

### ISSUE THREAD

**Issue by mbender-ith** [MicrosoftDocs/microsoft-365-docs#1959]
Could this article please elaborate more clearly whether a (paid) license is required in order to be able to maintain and restore mailbox (and mailbox archive) for an employee which has left the company. Imagine the user with an active EXO P2 had retention policies in place which moved "all" e-mails to the archive with a hold time of 2years. Now the employee leaves the company, but for compliance reasons the company wants to be able to restore mails from his (archive) mailbox during these 2 years (without the need to export the mails and store the export file locally).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7108464d-597a-c79d-cac8-94e35d9dd3d0
* Version Independent ID: ba0d3744-707d-c506-47f4-83519022d4cb
* Content: [Create and manage inactive mailboxes - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-and-manage-inactive-mailboxes?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/create-and-manage-inactive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-and-manage-inactive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@mbender-ith After the mailbox is made inactive, you have the option to recover it (convert it to an active mailbox) or restore it (copy contents from inactive mailbox to a different active mailbox). Please see:

- Recover - https://docs.microsoft.com/en-us/microsoft-365/compliance/recover-an-inactive-mailbox

- Restore - https://docs.microsoft.com/en-us/microsoft-365/compliance/restore-an-inactive-mailbox

You should also note that an archive policy (and MRM retention policy that moves items to the archive mailbox) is not processed/ignored on inactive mailboxes. So, items won't be moved to the archive; they will just remain in the primary mailbox. See https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide#inactive-mailboxes-and-exchange-mrm-retention-policies

An EXO Plan 2 license (or EOA license) is only needed to make a mailbox inactive. After the mailbox is made inactive (by deleting the corresponding user account) that license can be re-used for a different user. At this time, there's not on-going license requirement. If you recover an inactive mailbox, you'll have to assign a license to the new active mailbox. For a restore, the active mailbox that you copy items to has to be licensed (though doesn't necessarily need an EXO Plan 2).

**Comment by mbender-ith** [comment]
@markjjo Thank you very much for your elaborate response. Please allow for one further clarification question:

Imagine that the mailbox had EXO P2, retention policies enabled. Now mailbox is set to inactive and license is re-assigned to another user. I still do not understand how long the contents of the mailbox (and particularly its archive mailbox) will be restorable / recoverable.

In other words, if I want to be able to restore / recover the contants of the mailbox (and its archive mailbox) until 2 years after setting the mailbox is set to inactive, would this require any license to the "inactive" mailbox, to prevent data from being deleted before that date.

**Comment by markjjo** [comment]
@mbender-ith The short answer is "no", no license is required to prevent data from being deleted before the date an any hold applied to the mailbox.

An inactive mailbox will persist indefinitely (dare I say forever) **or** until you [remove the holds](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-an-inactive-mailbox?view=o365-worldwide) that are placed on the mailbox. As long as the inactive mailbox exists, you can recover or restore it. 

The Managed Folder Assistant will continue to process the inactive mailbox and expire items who retention duration have expired. So items who retention period expires (and that is the retention period defined in the hold that was placed on the mailbox before it was made inactive) are permanently removed. So whether or not items get purged from an inactive mailbox doesn't depend on licensing. It depends on the hold assigned to the inactive mailbox. Note that you can change the [hold duration](https://docs.microsoft.com/en-us/microsoft-365/compliance/change-the-hold-duration-for-an-inactive-mailbox?view=o365-worldwide).

As I previously mentioned, in active mailboxes, an MRM archive policy will not move items to the archive mailbox; they will remain in the primary mailbox. Also, it doesn't require any kind of licensing to restore/recover items from an inactive mailbox. In fact you can't license it because it's inactive.

If it was me, I would use Litigation Holds to make inactive mailboxes. I would either use an indefinite hold or specify a duration that was in compliance with any mail retention regulations my company had to adhere to. I have to say, inactive mailboxes are a great thing that Microsoft provides to customers.

Hope I answered your questions.

**Comment by mbender-ith** [comment]
Thank you very much for your elaborate response
