### ISSUE TITLE
Save problems after GA

### ISSUE THREAD

**Issue by burma-shave** [MicrosoftDocs/microsoft-365-docs#1966]
The doc describes a limitation when saving using the desktop and mobile apps:
"Users can experience save problems after going offline or into a sleep mode when instead of using Office for the web, they use the desktop and mobile apps for Word, Excel, or PowerPoint. For these users, when they resume their Office app session and try to save changes, they see an upload failure message with an option to save a copy instead of saving the original file."

Is this still an issue now that this feature is GA? If so, does it only apply to labels that encrypt? Is there anywhere I can track this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@burma-shave  Yes, this is still a potential issue at G and it is specific to labels that apply encryption, but changes mentioned could be content changes, or label changes.  You can track the issue by monitoring this section because I delete items when I get confirmation from engineering that they are resolved. Alternatively, you might like to start a new UserVoice entry to register your interest and monitor that way: https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip
