### ISSUE TITLE
Web Only Access - Reduce your attack surface and ease administration

### ISSUE THREAD

**Issue by toddjohnson39** [MicrosoftDocs/microsoft-365-docs#1974]
Can you please provide specifics on how the CA policy restricting access to Web Only is able to  "reduce your attack surface and ease administration"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4945844-0f8f-2691-1092-0025cc19c683
* Version Independent ID: adc60afc-fb2a-dd5c-9217-6e074abc8dc0
* Content: [Create a secure guest sharing environment](https://docs.microsoft.com/en-us/microsoft-365/solutions/create-secure-guest-sharing-environment?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/create-secure-guest-sharing-environment.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@toddjohnson39 Thank you for your feedback. Allowing guests to use web-only means the customer session token is revoked after they are done and they need to log in every time they access the services. This is safe if the customer's computer is infected and tries to use applications use the existing token which doesn't expire for 90 days if using a desktop client that supports modern auth (Mainly because we do not know if the device the guest is using is complaint) 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @toddjohnson39 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
