### ISSUE TITLE
DLP within code snippets.

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#2014]
Hello. Looks like code snippets in Teams chat are not being analyzed by Teams DLP. Is this by design? If so can it be documented here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebaab3f7-d1d4-c649-efe8-f24913da4f3e
* Version Independent ID: c5710ebf-0ca5-ab46-c490-64ebc308defe
* Content: [Data loss prevention and Microsoft Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-microsoft-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-microsoft-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @Larryngolog 
This is not expected behavior, please open a ticket with Microsoft support.

- Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.
