### ISSUE TITLE
Classic vs Unified features in Compliance centre

### ISSUE THREAD

**Issue by pctsltd** [MicrosoftDocs/microsoft-365-docs#2019]
In the new compliance centre for unified labelling
- there is no option to hide a label in the compliance centre like there was in Azure. 
- there is also no functionality to enable "custom permissions" like there was in Azure. 
- there is also no functionality to "show the bar" like there was in Azure.

Was this functionality removed from the compliance centre? If this is by design this should be documented. 

If its not by design, please update the documentation to outline how one activates these features?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Learn about sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@pctsltd  It can be confusing when you're moving from one implementation to another, I know.  I'll see if I can help to unravel these in turn.

1. There is no option to hide a label in the compliance centre like there was in Azure.

By hide, do you mean disable? This option isn't needed in the compliance center because labels are not assigned to all users by default - as they are in the Azure portal when you use Azure Information Protection labels. There, the Global policy applies to all users in the tenant. In the compliance center, no labels apply to users by default, you have to create a label policy, add labels, and assign users.  So the equivalent of hiding a label in the compliance center is to not include it in a label policy for users.  You'll find more information about the differences in implementation here: https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#label-settings-that-are-not-supported-in-the-admin-centers

2. There is also no functionality to enable "custom permissions" like there was in Azure.

Are you talking about the Azure Information Protection policy setting "Make the custom permissions option available to users"?  This setting is specific to Azure Information Protection clients only.  For the unified labeling client and Office apps, this option is no longer supported (see https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#features-not-planned-to-be-in-the-azure-information-protection-unified-labeling-client).  For the unified labeling client and File Explorer, it's enabled by default but can be disabled with PowerShell (https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#disable-custom-permissions-in-file-explorer).

3. There is also no functionality to "show the bar" like there was in Azure.

This is another setting that's specific to only the Azure Information Protection clients (so not relevant to built-in labeling on Windows, Mac, iOS, Android, or the web).  For the unified labeling client you can display this bar as another PowerShell configuration: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#display-the-information-protection-bar-in-office-apps

The advanced settings that you can configure with PowerShell only aren't obvious when you use the wizards in the compliance center, I know.  But they are included in the instructions (https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide),

If you are used to using the Azure portal to configure policy and labels settings for the Azure Information Protection classic client, and now moving to the compliance center and the Azure Information Protection unified labeling client, I recommend you take advantage of the comparison tables for the labeling centers (https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#label-settings-that-are-not-supported-in-the-admin-centers) and the clients (https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#compare-the-labeling-clients-for-windows-computers).

**Comment by cabailey** [comment]
Questions are addressed, so closing. However, let me know if you have clarifying questions about the information provided, or open a new GitHub Issue for new documentation feedback.
