### ISSUE TITLE
Instructions for OneDrive

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2036]
[Enter feedback here]

What syntax must be used to add a users OneDrive to an Auto-label policy. Everything I try give me an error.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Apply a sensitivity label to content automatically - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide#how-to-configure-auto-labeling-policies-for-sharepoint-onedrive-and-exchange)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@DeanGross You might be running into a known permissions issue.  Nir's recommendation on Yammer to contact Support is good advice so they can check this.

**Comment by cabailey** [comment]
@DeanGross I've added into the instructions the standard syntax, an example, and a link how to get URLs for OneDrive accounts that you can then copy/paste.  Admittedly, this would be a lot easier if you could select from a list rather than having to type in, and engineering is looking into this. However, it would help to add a UserVoice post for this request to help bump priority - use this link: https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip?category_id=385018
