### ISSUE TITLE
Retained Phantom Mailboxes do not show up in Active Mailboxes

### ISSUE THREAD

**Issue by Mlavieri** [MicrosoftDocs/microsoft-365-docs#2073]
Unlike online mailboxes when a retention policy is applied to a Phantom Mailbox and the account is deleted the mailbox does not appear in the Inactive Mailbox section in the Compliance Center. Additionally, these accounts are no available to place on Holds or resolve using Content Search. 

In Content Search you can use the participant action to return Teams Chats however there is now way to put a hold on this content at this in the UI that I could find. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0bb4d7-d9fa-ae92-d3ca-246147d1434a
* Version Independent ID: 7ba20db3-55e2-3d29-2d6c-6f68a6b577a8
* Content: [Searching cloud-based mailboxes for on-premises users - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Mlavieri First of all I think you should open a ticket with MS Support to investigate these issues/questions.

Having said that, engineering says that an inactive mailbox would be created if you deleted the on-premises user (and that deletion is synced to AAD). They also said that on-premises users whose identities are synced to AAD should be returned in the user picker to assign a retention policy or eDiscovery hold to. How did you apply the retention policy on the on-premises user before the account was deleted? Also note that to be licensing compliance, the on-premises user would need an EXO Plan 2 license, which is the requirement to make any mailbox inactive.

Also, I'm a little confused about a few things:

1. "...these accounts are no available to place on Holds" If by accounts you mean the on-premises user whose account was deleted, then this would be expected behavior. You can't place a hold on an "inactive mailbox".

2. Have you tried using the Get-Mailbox -InactiveMailboxOnly command in EXO PowerShell? Curious if it will return the inactive shadow mailbox.

3. Have you tried using the New-ComplianceSearch -IncludeUserAppContent command in SCC PowerShell to search the inactive phantom mailbox? 

4. Not sure I understand what you mean by "put a hold on this content". I assume that you are searching the inactive phantom mailbox, whose content is already on hold because a retention policy was applied to it before you deleted the on-premises user.

**Comment by Mlavieri** [comment]
Thanks again Mark, there may have been a licensing issue when we were testing this all out but the tenant has EXO Plan 2, I'll follow up with a ticket if we see that issue again. With regards to your other notes: 

1. I was not aware that an Inactive Mailbox could not be placed on hold which in all honestly renders the less of my questions moot. The scenario that I was attempting to solve for is when there is a Global Retention policy applied to all Teams Chats for the tenant and an employee leaves the firm and on a later date there is a litigation matter where that user's data needs to be put on hold. The Retention Policy would retain that chat until the end of the the retention policy but the litigation hold may end up being longer than that retention policy. While there are other ways to solve for this we were hoping it could be accomplished via a hold. 
2. The mailbox does not appear with the EXO command
3. Even in compliance search or holds I am unable to search the mailbox
4. Yes the phantom mailbox had a retention policy assigned to it before it was deleted, I believe this is related to the first point about not being able to place an Inactive Mailbox on hold or an issue with the licensing which is causing the deleted phantom mailbox not to show up but I can follow up with a specific ticket. 

Thanks for the answer and your help on this!
