### ISSUE TITLE
What does happen if Record versioning is not available?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#2079]
Hello,

what does happen if Record versioning is not available (e. g. no E5 license assigned) but records will be edited and thus a new version gets created? Will be the previous version lost? Is editing just not possible without Record versioning?

Thank you for clarifying!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Learn about records - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/records?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@GiantCrocodile Thank you for drawing my attention to the fact that this article had a licensing statement in it - will be removed in line with the other documentation pages for retention and records management.  Instead, use the link at the top of the page for a single and authoritative source of information for the latest updates.

If you follow this licensing link at the top of the page, you will read how licensing isn't always enforced, but that doesn't mean it's not required.  And when you refer to the licensing spreadsheet (PDF or Excel), you'll see that records management and records versioning requires an E5 license or equivalent.  To edit content that's been declared a record, it must first be unlocked, which then uses record versioning.  If in doubt about what licenses you need, please check with your Microsoft Account Manager or equivalent support channels. We can't comment on what will happen if you use a feature that you're not licensed to use because this isn't a supported scenario.

**Comment by GiantCrocodile** [comment]
Hi @cabailey! Thank you for fixing the license info.

I'm aware that bypassing a license requirement isn't legal nor supported. That's now what I'm asking. I'm asking what will happen in case of an user doing this by being unaware of the license requirements: Does he/she get a proper error message or will this end in a license violation which an admin can't prevent?

**Comment by cabailey** [comment]
@GiantCrocodile  We can't answer questions on what will happen if a feature is used without correct licensing.  As with all unsupported scenarios, you're welcome to test but the results might change later down the line.  There have been requests for improvements in the product around licensing enforcement and information, and this is something that engineering is looking into so I encourage you to add your feedback to UserVoice, this category: https://office365.uservoice.com/forums/289138-office-365-security-compliance?category_id=379531

**Comment by GiantCrocodile** [comment]
@cabailey I see. Thank you for your help and feel free to handle this issue as resolved.
