### ISSUE TITLE
Mapping file has a 500 item limit

### ISSUE THREAD

**Issue by moditpro365** [MicrosoftDocs/microsoft-365-docs#2120]
I ran into this issue today and it should be noted here or on the FAQ page. When using this process, there is a limit of 500 items per mapping file. I have automated the collection of PSTs across our enterprise as well as the mapping file creation due to the number of files we have. Knowing this info would be beneficial to others as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86b2796-06fa-dfa7-bc0b-1a5760a396a0
* Version Independent ID: f9bfdc36-9c52-697f-f608-6e327d7c3c09
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@moditpro365 Thanks for the heads up. I'll look into updating documentation. Curious, when did the error surface in the workflow? When the csv is validated when you're creating the import job or after the import job was created and the import process started? If the latter, were PST file for the first 500 users in the csv file imported? And I assume the fix is to create multiple csv files/import jobs for max of 500 users for each csv file/job?

**Comment by moditpro365** [comment]
Post upload during the mapping file validation. And yes, I ended up splitting the file contents up into two files. Once I did that, both mapping files validated successfully.

**Comment by markjjo** [comment]
@moditpro365 Ok, thanks for following up. I will add this limit to the documentation, probably in Step 4 and maybe in Step 5 where the csv file is validated.
