### ISSUE TITLE
Clarify scope of sensitivity labels with site and group settings enabled

### ISSUE THREAD

**Issue by bwinkler-draeger** [MicrosoftDocs/microsoft-365-docs#2125]
Can you please clarify what is meant by "_You're now ready to create or edit sensitivity labels that **you want to be available** for sites and groups._".
From my understanding only sensitivity labels with site and group settings configured should be available when creating / editing a group. But after enabling the preview, all sensitivity labels available to a user (even the ones without any site and group configuration) appear in the dropdown during the creation of a Team or a group in Outlook. This does not apply to SharePoint Online.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bwinkler-draeger Yes, this goes back to the statement in the Important callout "Gradually rolling out to tenants: Only labels with the site and group settings will be available to select when users create teams, groups, and sites. If you can currently apply a label to a container when the label doesn't have the site and group settings enabled, only the label name is applied to the container."

It will take some time for all group-supporting endpoints to support this design, but that's the plan and because you can now see this with SharePoint, you can see how it's moving in this direction.  There are a lot of backend dependencies in this solution and not all changes can go live at the same time.
