### ISSUE TITLE
MS Teams files Retention - info review 

### ISSUE THREAD

**Issue by imanboukly** [MicrosoftDocs/microsoft-365-docs#2126]
Hi, 
As I understand to retain MS Teams files we should apply SPO retention.
as per 
https://docs.microsoft.com/en-us/microsoftteams/retention-policies

https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide

what do you mean by saying: ( when do we apply Office 365 group instead? Is the following correct? 

Your retention policy can retain content in SharePoint communication sites, team sites that aren't connected by Office 365 groups, and classic sites. Team sites connected by Office 365 groups aren't supported with this option and instead, use the Office 365 groups locations.
https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide

May be doc need updating 

Pls review and let me know
best regards,
Iman Boukly

**Comment by cabailey** [comment]
@imanboukly I've checked that the statement is correct and looking into making clarifications in the docs when to use the Office 365 groups option.

**Comment by cabailey** [comment]
This section is now updated: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#how-to-configure-a-retention-policy-for-sharepoint-and-onedrive  

Because Teams can contain files, the retention behavior for this content is handled by SharePoint and OneDrive.  However, when you configure the retention policy, if your site is backed by a Microsoft 365 group, you actually need to select the "Office 365 groups" location.  Not intuitive, I know but the more recently updated documentation has this clarification.
