### ISSUE TITLE
Errror while adding custodian or hold with one drive location 

### ISSUE THREAD

**Issue by bharav** [MicrosoftDocs/microsoft-365-docs#2149]
Hi Team 

I am always getting the below issue as soon as i add location as one drive for both custodian and hold
![image](https://user-images.githubusercontent.com/13413188/84352889-c59fe780-abdb-11ea-8a5d-f9fc82e161aa.png)

**Comment by markjjo** [comment]
@bharav I assume you're trying to create a hold or add location to a hold in Core eDiscovery or Advanced eDiscovery v2, correct? Assuming the URL is correct and the OneDrive accounts exist, it's possible (as per the error) that a search permissions filter might be preventing you from doing this or other permissions related issues. See [this topic](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-compliance-boundaries?view=o365-worldwide) for info about search permissions filtering and compliance boundaries.

Otherwise, please open a  ticket with MS Support to investigate.
