### ISSUE TITLE
EXO license for on-prem users

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/microsoft-365-docs#2153]
The info says:
_To store Teams chat data for an on-premises user in a cloud-based mailbox, the user must be assigned a Microsoft Teams license and an Exchange Online Plan license in Office 365_

If a new user is given an EXO license before an on-prem mailbox is provisioned, wont this be an issue? What if the new user goes to http://outlook.office365.com/ before an on-prem mailbox is provisioned? A cloud mailbox will be provisioned and accessible to the user next to the on-prem mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0bb4d7-d9fa-ae92-d3ca-246147d1434a
* Version Independent ID: 7ba20db3-55e2-3d29-2d6c-6f68a6b577a8
* Content: [Searching cloud-based mailboxes for on-premises users - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@bartvermeersch I assume system will enable a shadow mailbox (and not regular user mailbox) for on-premises user (because the scenario should support both Exchange hybrid deployments and hybrid deployments without on-premises Exchange; the key prerequisite for the Teams scenario is that on-premises user is sync'd to the cloud).  But I would suggest that you test this and if results are different that you expect, please open a ticket with MS Support to investigate.

The creation of user object in the cloud-based Azure AD happens by syncing from on-premises AD (the master) to cloud-based Azure Ad. Maybe your business workflow can ensure that on-premises mailbox is provisioned before that user is sync'd to AAD?
