### ISSUE TITLE
Add link to Limitation section 

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/microsoft-365-docs#2157]
It would be good to have a link on this page in the limitation section to the Known issues with sensitivity labels so it is easier to find. - https://support.microsoft.com/en-us/office/known-issues-with-sensitivity-labels-in-office-b169d687-2bbd-4e21-a440-7da1b2743edc#ID0EBBAAA=Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide&source=docs#limitations)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Padavid  While I understand the request, the known issue you ran into for Excel is a (hopefully temporary) problem with the app rather than a limitation of the service support for sensitivity labels  - the focus of this page and the scope of the limitations section. 

There are links to the known issues for sensitivity labels from the page "Use sensitivity labels in Office apps" (https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps), which includes Office on the web.  The end user documentation is also referenced in "Get started with sensitivity labels" (https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-sensitivity-labels). If we added the references to this page as well, there's an argument they should be added to every page we have for sensitivity labels, which leads to documentation bloat - people then lose the ability to focus on what's different and specific on each page.  However, I'll monitor and revise if necessary.
