### ISSUE TITLE
Why are SPO sites connected to M365 Groups not supported for retention via the SPO location?

### ISSUE THREAD

**Issue by ferringer** [MicrosoftDocs/microsoft-365-docs#2184]
From a technical perspective, there is nothing that prohibits me from adding an SPO site connected to an M365 Group to a retention policy by listing it using the SharePoint site location option instead of the O365 Group location option in the policy creation wizard. I am able to create the policy, and it appears that the site's content are now being retained by that policy. 

But this article explicitly states that this is not a supported state. Why is that the case? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention policies for SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#how-to-configure-a-retention-policy-for-sharepoint-and-onedrive)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@ferringer I've asked about this - the key thing is, although there's nothing in the product that prevents you from adding these sites for the SharePoint location and it might work, it's not supported.  You'll welcome to use it on the understanding that it might not work and you wouldn't be able to open a support ticket for a not-supported configuration.  We've had reports from customers that it didn't work, and to help set expectations, added a sentence that these sites would be "ignored".  But clearly that's not always the case based on your experience.  We don't usually document what happens if you do something that we say isn't supported, so I've removed that "ignored" statement now.  The support statement remains, however.
