### ISSUE TITLE
BCC:user@contoso yields no results

### ISSUE THREAD

**Issue by kevinblumenfeld** [MicrosoftDocs/microsoft-365-docs#2277]
The documentation clearly outlines the use of bcc: All my tests show this is not the case.  To: and CC: work fine.
Thank you for having a look at why this is occurring.  

https://protection.office.com/contentsearchbeta?ContentOnly=1
Same with New-ComplianceSearch and the old gui experience https://protection.office.com/contentsearch

![image](https://user-images.githubusercontent.com/28877715/86045626-d93fb080-ba19-11ea-9f70-ec251f732f6f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@kevinblumenfeld Please see this topic: https://docs.microsoft.com/en-us/microsoft-365/compliance/preserve-bcc-and-expanded-distribution-group-recipients-for-ediscovery?view=o365-worldwide

"Recipients addressed using the Bcc field of a message: Bcc recipients are stored in the message in the sender's mailbox, but not included in headers of the message delivered to recipients." I'll look into adding a note about this to the Bcc property in the searchable email properties table.

Topic also talks about expanded distribution group recipient information being stored after a mailbox is placed on hold.

Otherwise, you could open a ticket with MS Support to investigate. Thanks for the heads up.
