### ISSUE TITLE
Need to add information to handle SPO and ODfB

### ISSUE THREAD

**Issue by SeCossio** [MicrosoftDocs/microsoft-365-docs#2380]
Is it possible to include guidance for SPO and ODfB (and possibly Teams as well?) Spillage management is not relegated to email only

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eab6813-2ac7-7ab4-50f1-454a350163ba
* Version Independent ID: f63bf91f-494a-dbb1-2262-35d44e586519
* Content: [eDiscovery solution series Data spillage scenario - Search and purge - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-spillage-scenariosearch-and-purge?redirectSourcePath=%252fen-us%252farticle%252fediscovery-solution-series-data-spillage-scenario-search-and-purge-d945f7dd-f62f-4ca7-b3e7-469824cfd493&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-spillage-scenariosearch-and-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-spillage-scenariosearch-and-purge.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@markjjo Please help us and answer this issue. Thanks

**Comment by markjjo** [comment]
@SeCossio Thanks for feedback. Good point. The reason that deleting items in SP and OD really isn't discussed is because the New-ComplianceSearchAction -Purge command only deletes mailbox items. I'll look into adding something about SP and OD and link to the GDPR topic that I mention below.

Until then, we do document this process in the context of deleting data in response to a GDPR data subject request. Please see: https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-dsr-office365?view=o365-worldwide#deleting-documents-in-sharepoint-online-and-onedrive-for-business
