### ISSUE TITLE
500 limit for encryption labels

### ISSUE THREAD

**Issue by ksgopal4** [MicrosoftDocs/microsoft-365-docs#2421]
Hi, great article, but I was wondering if the limit of 500 encryption label is due for increase at any time. We potentially need encryption labels per project (ie each label defines a project specific set of who is allowed to access). We will probably very soon run out of labels in this case. Any thoughts welcome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Learn about sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@ksgopal4  No, this technical restriction has been there for a while now and I'm not aware of any plans to increase it.  If this is becoming problematic for you, I suggest you raise this with your Microsoft Technical Account Manager and/or raise it on the MIP UserVoice site - probably this category for rights management (since it's not limitation of sensitivity labels but the backend rights management service): https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip?category_id=385012
