### ISSUE TITLE
Can you explain more on how to perform the relevance training in Advanced edisocvery? This article is not very clear and all links lead to classic advanced edisocvery portal

### ISSUE THREAD

**Issue by bubhat** [MicrosoftDocs/microsoft-365-docs#2423]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b333a4bc-5d18-e680-636f-19da864cbaa6
* Version Independent ID: 2878aac9-73a3-2037-ec78-494534262ba7
* Content: [Use the Relevance module to analyze data in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/using-relevance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/using-relevance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/using-relevance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@bubhat Thanks for feedback. The reason we point to the classic AeD documentation is also because we redirect to the actual classic AeD Relevance experience and UI. We're working to update the Relevance experience in AeD v2 and when we do the documentation will be updated accordingly. I'll try to remember to comment on this issue when the roadmap is updated with this work.
