### ISSUE TITLE
Unable to find Windows 10 Upgrade Card

### ISSUE THREAD

**Issue by rayjgraham** [MicrosoftDocs/microsoft-365-docs#254]
Sirkku, 

I followed your suggestion..."But you can still find it, if in the admin center you flip off the preview mode, and on the home page click the big + sign to add a card, and you can find it in the list. ".... but still did not find the upgrade card. I look forward to your followup. appreciate the help!
thanks,
Ray

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d66a7a3-2230-d907-5ff3-b3f7ed8c166a
* Version Independent ID: e437b87d-0845-bb6f-3b0b-8d9fd2b3013a
* Content: [Upgrade Windows devices to Windows Pro Creators Update](https://docs.microsoft.com/en-us/microsoft-365/business/upgrade-to-windows-pro-creators-update)
* Content Source: [microsoft-365/business/upgrade-to-windows-pro-creators-update.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/upgrade-to-windows-pro-creators-update.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
You can go here to download it:
https://www.microsoft.com/software-download/windows10

or more specifically:
Upgrade to Windows 10 Pro here: 
 https://go.microsoft.com/fwlink/?LinkID=836951 
This link is intended for PCs with a Windows 10 license 
Need help? Read about it: 
https://support.microsoft.com/products/windows?os=windows-10 


I will update the topic once I verify from the product team that this is by design, and I should just give the links.
