### ISSUE TITLE
Upload the Larger Graphic/Image - It's Too Small to Read

### ISSUE THREAD

**Issue by haoewqopi** [MicrosoftDocs/microsoft-365-docs#2543]
Please upload a larger version of the graphic on this page. When I click on it, it won't expand...text is too tiny to read as-is. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18267b13-4890-4196-16e8-e183ece73d70
* Version Independent ID: 64887e62-4187-cb6e-fbb3-ff7e12a18841
* Content: [Secure email recommended policies - Microsoft 365 Enterprise - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/secure-email-recommended-policies?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/secure-email-recommended-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/secure-email-recommended-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by msbemba** [comment]
@haoewqopi Thank you for your feedback. I checked and found that the Graphic on the page is at the best size possible due to the fact that it has multiple tabular columns to show. Breaking that in two images doesn't help so I'd recommend You open the image on a new tab to Zoom in and the quality of the graphic will not be impacted. Hope this helps!


@yogkumgit The graphic is at the best size possible and there is no change required in the document as such. Please close this issue.
Thanks
Sri

**Comment by haoewqopi** [comment]
Thanks - it would be easier for your readers to do it the way a similar graphic was done on the page below, however:

https://docs.microsoft.com/en-us/microsoft-365/enterprise/identity-access-policies?view=o365-worldwide

**Comment by msbemba** [comment]
@haoewqopi Thank you for your feedback. I have added a link to open image in a larger size as shown in the other document. Hope this helps!

This can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2556

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @haoewqopi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
