### ISSUE TITLE
Unclear wording in the "Start retention when an event occurs" page

### ISSUE THREAD

**Issue by FranNev** [MicrosoftDocs/microsoft-365-docs#2548]
Hi,

I'd like to have some explanation about the sentence: "Product Lifetime is the event type; a specific product reaching end of life is an event. **When an event of that event type occurs**—in this case, when a product reaches its end of life—**you create an event** that specifies:"

Could the wording "When an event of that event type occurs" be simplified to "When this type of event occurs" or "When this event type occurs"?

And does "you create an event" mean that the user gets a notification which prompt him/her to create an event? Or is it some kind of advice, like "You should create/log an event type (in the system) in order to process the kind of event you have to regularly deal with."?

Thanks for your help and best regards,

François
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad33cc1-dc5f-d9f9-ee8e-b103839945ef
* Version Independent ID: 1bc3101d-afe8-2056-3cda-6a86a209c460
* Content: [Start retention when an event occurs - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/event-driven-retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/event-driven-retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@FranNev This is quirky wording when you read it, I know - but it reflects the technical implementation when you configure a retention label for event-based retention.  It always feels backward to me, that you create the event type first for the label, and then create an event afterwards for that event type.  But that's the way it's implemented, which is why your proposed wording wouldn't be accurate.  

There's the actual "real-life" event (independent of the retention feature), such as a product reaches its end of life.  Then the retention feature has 2 entities that you must create/configure:
1. An event type (in this example, calling it "Product Lifetime"), which must exist to configure the retention label for event-based retention. 
2. An event that triggers the start of retention for the retention label already configured and applied.  

The retention feature can't know when the real-life event happens - so something external to the feature (an admin or an automated process) must create the entity we're calling the event in the M365 compliance center.  To understand this better in context, see https://docs.microsoft.com/en-us/microsoft-365/compliance/auto-apply-retention-labels-scenario?view=o365-worldwide.

**Comment by FranNev** [comment]
@cabailey Thank you so much for this explanation! This is way much understandable for me. Much appreciated. Have a nice day.
