### ISSUE TITLE
Step 5

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/microsoft-365-docs#2598]
Step 5 needs elaborating.

**Now you're ready to actually delete items in the Recoverable Items folder by using the New-ComplianceSearch and New-ComplianceSearchAction cmdlets in the Security & Compliance Center.**

You link to an article on the new commands. However this link does not detail how to use the new commands to only delete items in the recoverable items. I have been unable to find out how to achieve the same result with the new commands as the old. Please can someone detail how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the cloud mailbox on hold Recoverable Items folder - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide#step-5-delete-items-in-the-recoverable-items-folder)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@win2000b Thanks for question. Please see this github issue that offers a solution to do this: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2434

The key is to use the script [in this topic](https://docs.microsoft.com/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide) to get the folder id of the Recoverable items folder and then use that property:value in a search query so that it only returns items in the Recoverable Items folder. Then you can use the New-ComplianceSearchAction -Purge cmdlet to delete the items. 

We'll be updating this topic to document the prescribed solution discussed in github issue #2434
