### ISSUE TITLE
Confusing and contradictory statements

### ISSUE THREAD

**Issue by crshovrd41** [MicrosoftDocs/microsoft-365-docs#2654]
Hi,

This paragraph contains contradictory statements: 
"**_Users can't open encrypted files using Office on the web_**. When sensitivity labels for Office files in SharePoint and OneDrive are enabled, **_users can use Office on the web to open encrypted files_**, with some limitations that include encryption that has been applied with an on-premises key (known as "hold your own key", or HYOK), double key encryption, and encryption that has been applied independently from a sensitivity label."

The article then goes on to say that the only way for multiple users to edit encrypted documents is to use Office on the web. 

Can you help clear this up? Can we use Office on the web for encrypted documents or can we not?

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd3497a-c02a-5fd6-12db-3a093f0fe17c
* Version Independent ID: 2ef81556-61b0-47ae-d8fc-3d9aa5240c51
* Content: [Restrict access to content using sensitivity labels to apply encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide#considerations-for-encrypted-content)
* Content Source: [microsoft-365/compliance/encryption-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@crshovrd41 The quoted text isn't a standalone paragraph.  The full context from this list is: "If your organization hasn't enabled sensitivity labels for Office files in SharePoint and OneDrive: ...Users can't open encrypted files using Office on the web."  Followed by, "When sensitivity labels for Office files in SharePoint and OneDrive are enabled, users can use Office on the web to open encrypted files, with some limitations that include ..."

There isn't a simple yes/no answer to "Can we use Office on the web for encrypted documents or can we not?"  The answer is yes you can, after you have enabled sensitivity labels for Office files in SharePoint and OneDrive, but not for all encrypted files.  If you use only Office on the web to apply the encryption with sensitivity labels, then you don't need to worry about the scenarios that can result in being unable to open encrypted files. If the other ways don't apply to you, then you're all set. If they do apply, then you need to be aware of them, which is why they are included in this documentation.
