### ISSUE TITLE
Password Policies Parameter

### ISSUE THREAD

**Issue by M88X** [MicrosoftDocs/microsoft-365-docs#2686]
When setting the password to expire for a specific user, what are some of the parameters that we can use except -PasswordPolicies None? Can we set number of days for example 90 or 100 etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f52c6916-7e79-9a9c-b7a6-47041ddb81e3
* Version Independent ID: 43c9b873-d354-d814-3065-1e8832361b86
* Content: [Set an individual user's password to never expire - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@M88X Thank you for your feedback. The other parameters that we can use for -PasswordPolicies are

* DisablePasswordExpiration
* DisableStrongPassword (Allows weaker passwords than the default policy to be specified)

 However, for a password to expire in a certain number of days you need to use the Set-MsolPasswordPolicy cmdlet which updates the password policy of a specified domain or tenant.


Example 1: Update validity period and notification for the current domain

PS C:\> Set-MsolPasswordPolicy -ValidityPeriod 60 -NotificationDays 14
This command updates the tenant so that all user's passwords expire after 60 days. The users receive notification 14 days prior to that expiry.

Example 2: Update validity period and notification for a domain

PS C:\> Set-MsolPasswordPolicy -ValidityPeriod 60 -NotificationDays 14 -DomainName "contoso.com"
This command updates the policy on the domain contoso.com so that users' passwords expire after 60 days. The users receive notification 14 days prior to that expiry.

You can find more information about this cmdlet at https://docs.microsoft.com/en-us/powershell/module/msonline/set-msolpasswordpolicy?view=azureadps-1.0

Hope this helps!

@yogkumgit There is no changes needed in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @M88X Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
