### ISSUE TITLE
What is a Tag..

### ISSUE THREAD

**Issue by mattspierce** [MicrosoftDocs/microsoft-365-docs#2730]
[Enter feedback here]

When creating an outbound spam filter the applies to dialog allows for a domain, user, or member of.  The value request a Tag.  Could you better define what a tag is?  This is assumed to be a group but a security group doesn't work.   What type of group is needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure outbound spam filtering - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mattspierce, I see what you're saying.

![image](https://user-images.githubusercontent.com/33166947/91883115-d3906200-ec38-11ea-96fe-251deefd53e1.png)

I'm guessing the 'Add a tag' text is an effort be generic and use one text string for all conditions, instead of separate strings for "Add a sender domain", "Add a sender", and "Add a group".

This is explained in the topic in Step 7 for creating a new outbound spam policy:

- **The sender domain is**: Specifies senders in one or more of the configured accepted domains in the organization. Click in the **Add a tag** box to see and select a domain. Click again the **Add a tag** box to select additional domains if more than one domain is available.

- **Sender is**: Specifies one or more users in your organization. Click in the **Add a tag** and start typing to filter the list. Click again the **Add a tag** box to select additional senders.

- **Sender is a member of**: Specifies one or more groups in your organization. Click in the **Add a tag** and start typing to filter the list. Click again the **Add a tag** box to select additional senders.

Does this make sense?

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @mattspierce Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
