### ISSUE TITLE
Are Billing Profiles only available in certain circumstances?

### ISSUE THREAD

**Issue by LeonardPeris** [MicrosoftDocs/microsoft-365-docs#2738]
I see no option to add or modify a billing profile on my tenant. No default billing profile is present either.
After contacting Microsoft Support, I was advised that Billing Profiles are available only to users who have purchased their licenses or subscriptions from Microsoft Approved Resellers or from Microsoft Partners.

The current documentation doesn't mention this adequately in the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9acd5a2f-9048-c5d2-0455-69f80f5e469e
* Version Independent ID: a832f7d9-57be-0742-7eca-7a47b34f85ec
* Content: [Manage billing profiles](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-billing-profiles?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-billing-profiles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-billing-profiles.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@LeonardPeris Thank you for your feedback. I have added the Information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2771. Once this is approved by the author you will see the changes in the document.

Thanks
Sri

**Comment by LeonardPeris** [comment]
Unfortunately, the PR doesn't state that Billing Profiles are **unavailable for Microsoft Direct Customers**, neither does the messaging/micro-copy in the admin-portal say the same.

**Comment by msbemba** [comment]
@LeonardPeris Billing Profiles are available for Microsoft Direct customers. What type of account do you have? Is it Home or commercial?

Thanks
Sri

**Comment by Mister-Edward** [comment]
HI @msbemba, I'm here because I was just told by Microsoft Support that Billing Profiles are only available to those who have an Azure subscription.   I was not told what  @LeonardPeris was told at all.   I have a commercial non-profit account, I buy licenses for Office365 and other add-on licenses including communication credits and calling plans.  I came to this page to try to find a way to combine my invoices in certain ways and to have them emailed to someone without assigning them a billing admin role.  I don't see any indication here or in the admin portal that billing profiles wouldn't be available for a customer like me, or only to people with Azure subscriptions, so if that's the case, this page needs some updates.   I'm not sure I even believe it though, after seeing the variance in what microsoft support is saying.

**Comment by LeonardPeris** [comment]
Hey @msbemba.

I have a Microsoft 365 Business tenant. It has Microsoft 365 Business, Basic, Standard & Premium (all three) licenses active. I signed up / purchased for the service directly from microsoft.com

You can have a look at my support tickets with Microsoft 365 Business Admin Support 21615222‎ & 21677763‎.
 
> I don't see any indication here or in the admin portal that billing profiles wouldn't be available for a customer like me, or only to people with Azure subscriptions, so if that's the case, this page needs some updates

I agree with @Mister-Edward, this document MUST reflect the scenarios in which billing profiles are available. And the same must be mentioned in the admin portal.

**Comment by msbemba** [comment]
@LeonardPeris and @Mister-Edward  Thank you for your feedback. I'll work with the author/engineering team and update you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@cmcatee-MSFT I have tested this myself that we could not create a billing profile. Both the Customers have contacted Microsoft support– who claim this is only available if there is an azure subscription tied to the tenant. I could not find more information about this online or on other Microsoft documents. If you could take this up to PG and get more information that will be helpful in modifying the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please reply to this query. Thanks.

**Comment by Mister-Edward** [comment]
Microsoft Customer Support told me this, more recently:  "Because of the upgrade from old admin portal to new admin portal, there are still some issues that our backend team haven't handled well. I’ve escalated this hot issue to our team manager to pay more attention to" and "For your request about creating a billing profile , it’s because of our system design, I have escalated this hot issue to our team manager to resolve, but it may need some time to upgrade."

**Comment by msbemba** [comment]
Thank you @Mister-Edward for the update.

**Comment by cmcatee-MSFT** [comment]
@yogkumgit Still investigating. Waiting on product team response.

**Comment by cmcatee-MSFT** [comment]
@Mister-Edward and @LeonardPeris I've talked to the product team and have confirmed the following:

- Billing profiles are only available if you bought your subscription directly through Microsoft Sales. They aren't available for customers who bought their subscription through the products web site or on the **Purchase services** page in the Microsoft 365 admin center.
- Also, billing profiles are not exclusive to Azure subscriptions.
- Finally, it isn't possible to combine invoices in the way you're describing, or to have them emailed to someone who doesn't have the **Billing admin** role.

I'm in the process of updating the article to reflect this information.

Hope this helps to clarify.
