### ISSUE TITLE
Default behavior for DKIM and Microsoft 365 - "period of time"

### ISSUE THREAD

**Issue by Staja** [MicrosoftDocs/microsoft-365-docs#2791]
Under "Default behavior for DKIM and Microsoft 365" it states:

> Also, if you disable DKIM signing after enabling it, after a period of time, Microsoft 365 will automatically apply the default policy for your domain.

How long is that period of time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Staja Thank you for your feedback. I'm currently testing this and will update the document accordingly.

Thanks
Sri

**Comment by msbemba** [comment]
@MSFTTracyP The document states that if you disable DKIM signing after enabling it, after a period of time, Microsoft 365 will automatically apply the default policy for your domain. However, it doesn’t state what that time is. I disabled DKIM signing last Friday and it has still not applied default policy for my test domain. Could we get this information (the exact amount of time it takes for M365 to automatically apply the default policy) so that the document can be updated?

Thanks
Sri

**Comment by yogkumgit** [comment]
@MSFTTracyP Please reply to this query. Thanks.

**Comment by tiburd** [comment]
Because this issue was submitted almost two years ago, and there are no comments from the submitter or the author, we will close this issue.

FYI: @yogkumgit
