### ISSUE TITLE
Integration with PIM

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2941]
[Enter feedback here]

Please put some information about the fact that these roles are not currently available in Azure AD PIM. 
Also please work with the PIM team to get them added.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb98e0ff-d34c-75bc-0ade-7dc70fc7f4bd
* Version Independent ID: 5172471f-e514-bcde-16e0-d8d8090a892a
* Content: [Get started with insider risk management - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-configure?view=o365-worldwide#step-1-required-enable-permissions-for-insider-risk-management)
* Content Source: [microsoft-365/compliance/insider-risk-management-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-configure.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We have added a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2984

We have also Created User voice for the same so that these roles can be added to PIM  https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/41487934-insider-risk-management-role-in-pim

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
