### ISSUE TITLE
Licensing Requirements and availabilty in sovereign clouds

### ISSUE THREAD

**Issue by SeCossio** [MicrosoftDocs/microsoft-365-docs#2976]
[Enter feedback here]

Would like to see the licensing required to apply compliance boundaries and also the roadmap for availability in GCC, GCCH and DoD (if not there yet)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ffb84a4-0c98-3fc2-8963-4c809efaa149
* Version Independent ID: 305dd7b2-382e-a0da-40b5-1457e6b625bd
* Content: [Set up compliance boundaries for eDiscovery investigations - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-compliance-boundaries?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-compliance-boundaries.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-compliance-boundaries.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@SeCossio Thanks for the inquiry. As per our offline thread, users (whose data might be searched by eDiscovery managers in a compliance boundary scenario) have to be assigned an EXO license and and an SPO license (for OneDrive provisioning). Also, there user's mailbox must be 10 MB or larger, otherwise the user is not processed when syncing the compliance attribute to their OneDrive account. I'll add these prerequisites to the topic. 

And as per our conversation, compliance boundaries are available/supported in all the GOV clouds.
