### ISSUE TITLE
Restrictions table modification

### ISSUE THREAD

**Issue by brenle** [MicrosoftDocs/microsoft-365-docs#2992]
The table under "Compare restrictions for what actions are allowed or blocked" should have a column for Exchange.  While the notation indicates Exchange follows the same as "record-locked" column, there are certain things that are specific to SharePoint/OneDrive that don't translate to Exchange, such as "container admin".  Having a separate column for Exchange would be more explicit and help clarify the experience across the affected products, thus preventing confusion, even if it is very similar to the 'record-locked' column.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Records Management in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/records-management?view=o365-worldwide#compare-restrictions-for-what-actions-are-allowed-or-blocked)
* Content Source: [microsoft-365/compliance/records-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records-management.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Thanks for your feedback! Although updated recently for regulatory records, this table has been published since July and at that time, the consensus was that adding another column for Exchange that had essentially duplicate information or not applicable didn't add much value and made it harder to see the differences.  I'll continue to monitor and update if we get similar feedback from customers.
