### ISSUE TITLE
Spear Phishing (Credentials Harvest) sites detected by browsers

### ISSUE THREAD

**Issue by noraisk** [MicrosoftDocs/microsoft-365-docs#3026]
I am reporting built-in browser detection about phishing sites from your provided listing at "Attack Simulator in ATP". 
1) Please remove detectable ones from the listing or replace with new ones
2) Please consider development where customer can add its own bought domain for such use case.

1. Attackers on portal.hardwarecheck.net may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers or credit cards). Learn more
2. Attackers on portal.prizegiveaway.net may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers or credit cards). Learn more
3. Attackers on portal.prizesforall.com may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers or credit cards). Learn more
4. Attackers on portal.salarytoolint.net may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers or credit cards). Learn more

Detected by:
1) Chromium - Version 85.0.4183.121 (Official Build) snap (64-bit)
2) Microsoft Edge - Version 85.0.564.63 (Official build) (64-bit)

**Comment by msbemba** [comment]
@noraisk Thank you for your feedback. Could you please provide us with the document that you are referring to?

**Comment by noraisk** [comment]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator

and those urls needs to be fixed or cleaned up in real attack simulator as well.

**Comment by msbemba** [comment]
@noraisk Thank you for your feedback. I'll test and update the document if need be.

Thanks
Sri

**Comment by noraisk** [comment]
Another detail: attack tool sent phished emails are getting to default O365 junk.

**Comment by msbemba** [comment]
@noraisk  This is more of a feature request/Product bug than a document change. Especially the ones that you have reported like the emails going to the junk folder while trying to simulate. There are two ways to get this to the attention of the product group

1)Feedback option in the admin center - Sends the feedback directly to the concerned team, however, the fix is not immediate.
2)Need Help option in the admin center - Creates a support ticket which then can be passed on to the relevant team if this is found to be a product bug.

Hope this helps!

@yogkumgit There are no changes in the document as such as this is more of a product bug/change in feature.

Thanks
Sri

**Comment by noraisk** [comment]
Current documentation doesn't say that the simulator output might get caught by it's own built-in spam filter. The simulator is supposed to bypass all spam detection rules to educate employees. There are not so many people who work with their junk folder as normal inbox. 

So it has to be bug otherwise the product is useless.

I can share it via feedback or official support request in the future. Atleast this misbehaviour information is now shared via public comment even if its not known by product team itself.

I will be glad if the reported detectable URL-s are cleared out from the documentation.

**Comment by msbemba** [comment]
@noraisk I completely understand your situation. This product is supposed to send the email to the inbox and not junk, so this either a misconfiguration or a product bug. 

@chrisda Can we remove the detectable URL-s below? Let me know so that I can create a PR accordingly.

portal.hardwarecheck.net
portal.prizegiveaway.net
portal.prizesforall.com 
portal.salarytoolint.net

Detected by:

Chromium - Version 85.0.4183.121 (Official Build) snap (64-bit)
Microsoft Edge - Version 85.0.564.63 (Official build) (64-bit)

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrisda Please reply to this query. Thanks

**Comment by DaniHalfin** [comment]
Hi @noraisk ,
URLs detectable by non-Microsoft browsers can be manually allowed through configurations in the respective browsers.
For any Microsoft browser, these URLs should be allowed, and if you're seeing them detected, please open a support ticket so that we can investigate the issue.
Additionally, for mail going to junk directly, this is again something we would not expect to happen, so would ask you to open a support ticket to investigate.
Thanks for bringing this to our attention.

**Comment by noraisk** [comment]
Are you talking seriously right now? If you simulate an attack for educational purpose you don't make public campaign in your organization about it even in IT. The less people know it the better.

**Comment by DaniHalfin** [comment]
Hi again @noraisk ,
For the URLs, we make them well known ahead of time so that they can be allowed, ahead of time, for any future campaigns.
Detection mechanisms are likely to block such URLs due to their nature and that is a good thing. If we could avoid detection, so could attackers.
I hope this provides some clarity.

**Comment by yogkumgit** [comment]
@denisebmsft @chrisda @msbemba Thank you very much for the contribution and sharing this explanation. @noraisk Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
