### ISSUE TITLE
Dear Team, I would like to know that if Microsoft is still firm with the dates. And what will happen to the clients who have not updated themselves to the TLS 1.2. Thanks Sudhakar

### ISSUE THREAD

**Issue by s3kumar6** [MicrosoftDocs/microsoft-365-docs#3079]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec089a7-8f7b-d4d9-a763-e8abd73fb2c9
* Version Independent ID: 41ba8999-f0ea-5847-afad-8620dd83492a
* Content: [TLS 1.0 and 1.1 deprecation for Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @WorkShay
* Microsoft Alias: **shmehta**

**Comment by msbemba** [comment]
@s3kumar6 Thank you for the feedback, Sudhakar.

I think there is some confusion of terms here. So I’ll use the term studio definitions as that’s what we rely on publicly. 
End support – “The date when Microsoft no longer provides automatic fixes, updates, or online technical assistance.” 
Deprecate – “The stage of the product lifecycle when a feature or functionality is no longer in active development and may be removed in future releases of a product or online service.” 
Disable - “To make an entity nonfunctional.” 

Essentially deprecate = end support + disable 

Microsoft 365 publicly ended support a few years ago. While we still had TLS 1.0/1.1 calls in our services and systems, if someone had a problem with TLS 1.0/1.1, our feedback was (should’ve been) upgrade to TLS 1.2. The use of the term “deprecate” is purposeful because not all teams will be “disabling” TLS immediately. This is a very similar message, but nuanced as it still allows for the occasional usage of TLS 1.0/1.1 to go through. As I believe you’re aware, internally we have set dates for DoD and GCC-H of Jan1 – July 15. What this means is that all TLS 1.0/1.1 calls in DoD and GCC-H are already unsupported will start getting removed in future releases of products and services within M365 starting Jan. Customers have been told that things will break starting Jan 1 if they use those protocols and to upgrade. In regards to “standard O365”, that date is Oct 15. Customers should have been using TLS 1.2 to connect to O365 since 2017 when we first ended support, but now they have been warned that using TLS 1.0/1.1 in places where it used to work will no longer work. So yes, customers should be connecting using TLS 1.2+ asap because things will start to break by Oct 15. There is no finer-grained timeline. 


Hope this helps!

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @s3kumar6 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by s3kumar6** [comment]
> @s3kumar6 Thank you for the feedback, Sudhakar.
> 
> I think there is some confusion of terms here. So I’ll use the term studio definitions as that’s what we rely on publicly.
> End support – “The date when Microsoft no longer provides automatic fixes, updates, or online technical assistance.”
> Deprecate – “The stage of the product lifecycle when a feature or functionality is no longer in active development and may be removed in future releases of a product or online service.”
> Disable - “To make an entity nonfunctional.”
> 
> Essentially deprecate = end support + disable
> 
> Microsoft 365 publicly ended support a few years ago. While we still had TLS 1.0/1.1 calls in our services and systems, if someone had a problem with TLS 1.0/1.1, our feedback was (should’ve been) upgrade to TLS 1.2. The use of the term “deprecate” is purposeful because not all teams will be “disabling” TLS immediately. This is a very similar message, but nuanced as it still allows for the occasional usage of TLS 1.0/1.1 to go through. As I believe you’re aware, internally we have set dates for DoD and GCC-H of Jan1 – July 15. What this means is that all TLS 1.0/1.1 calls in DoD and GCC-H are already unsupported will start getting removed in future releases of products and services within M365 starting Jan. Customers have been told that things will break starting Jan 1 if they use those protocols and to upgrade. In regards to “standard O365”, that date is Oct 15. Customers should have been using TLS 1.2 to connect to O365 since 2017 when we first ended support, but now they have been warned that using TLS 1.0/1.1 in places where it used to work will no longer work. So yes, customers should be connecting using TLS 1.2+ asap because things will start to break by Oct 15. There is no finer-grained timeline.
> 
> Hope this helps!
> 
> @yogkumgit There are no changes required in the document and the issue can be closed.
> 
> Thanks
> Sri

Thanks for the response. Is there a way we can get some regular updates on the status. How can we determine that TLS 1.0 or 1.1 has been deprecated. Any response will be greatly appreciated.
