### ISSUE TITLE
Checking health status requires signin

### ISSUE THREAD

**Issue by Michael-Ashe** [MicrosoftDocs/microsoft-365-docs#3091]
[Enter feedback here]
Currently, our organization is experiencing outages. I'm unable to sign in at all, and the directions on this page tell you to sign in and go to the admin pages. I'm an admin, but can't get to this. I get that you're probably trying to personalize the info, but some generic info that's available outside of being signed in, would be useful. We're tying to figure out what and how to message our corporate staff, but cannot get useful info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d8b9c3-7ff2-d3b7-a0ce-0310171c71d5
* Version Independent ID: 7b45c0a3-94ca-b749-50e4-7d4cbf204764
* Content: [How to check Microsoft 365 service health - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-service-health?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-service-health.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-service-health.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@Michael-Ashe Thank you for your feedback. That is a valid point that you bring up. My suggestion would be to use the below two options

1) Setup email communication under preferences so that you can receive email notifications about the service health, which can be forwarded to your staff(note that only two addresses can be added here)
2) You can also use the Microsoft 365 Admin app on your mobile device to view Service health, which is a great way to stay current with push notifications.

This is also available in the document. Hope this helps!

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by Michael-Ashe** [comment]
To be clear, my feedback wasn't that the document needed changing, but that there were no workable alternatives. Authentication wasn't working for me, so I'm not sure how I could have accessed those other resources. In the middle of an outage, getting information quickly is what would be helpful.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Michael-Ashe. Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
