### ISSUE TITLE
No email to confirm delist from blocklist.

### ISSUE THREAD

**Issue by dzirnhelt** [MicrosoftDocs/microsoft-365-docs#3092]
I followed the instructions to apply for being delisted from the blocklist.  We bought a dedicated IP from SendGrid 2 weeks ago.  Now we're seeing only hotmail/outlook emails bounce as blocked.  The IP we send from (SendGrid) is different from the IP we receive email at, which is a pop we setup so we can receive replies to the emails we send out.  I've tried twice to get the confirmation email and there is no sign of it in spam/trash or any other folder.

Is there another way to confirm our IP is clean & safe?

Sincerely,
Dave@Rate-My-Agent.com
50% of profit pledged to worthy causes!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390d461b-7fce-d4ac-1c90-97b7b81dc0c2
* Version Independent ID: 9f8c7285-627f-13c6-1c7a-88fa7e14ed86
* Content: [Remove yourself from the blocked senders list - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?redirectedfrom=MSDN&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@dzirnhelt Thank you for your feedback. It may take up to 24 hours or results can vary widely before restrictions are removed. After the IP address is removed from the blocked sender's list, email messages from that IP address will be delivered to recipients who use Microsoft 365. So, make sure you're confident that email sent from that IP address won't be abusive or malicious; otherwise, the IP address might be blocked again. If the restrictions are not removed, it is important you report this to the support team via the need help button on the admin center, so that they can investigate and help or escalate.

Hope this helps!

@yogkumgit There are no changes required in the document as such. This issue can be closed.

Thanks
Sri

**Comment by dzirnhelt** [comment]
Thanks very much Sri.
ᐧ

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dzirnhelt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
