### ISSUE TITLE
List of countries is unsorted in German

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#3118]
Hello,

the list of countries in this article is unsorted for the German translation of this article. This make it difficult to find your country without using your browser's search function. Please make sure that the list is correctly sorted in translations as it is in the original English article.

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
* Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
* Content: [Microsoft 365 data locations - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by TinaMcN** [comment]
@GiantCrocodile thank you for letting us know about this.  We are investigating how to fix this sort order issue.  FYI @OfficeGlobal

**Comment by TinaMcN** [comment]
@GiantCrocodile the sort order in the German article is fixed now, thanks again for reporting it.

**Comment by GiantCrocodile** [comment]
Thank you for your work and the work of your team @TinaMcN!

**Comment by TinaMcN** [comment]
@GiantCrocodile as you have previously provided excellent feedback on the German Docs content I wanted to let you know that we are starting a pilot project to enable community Editing (PR's) and Feedback (Issues) on the German Microsoft Teams content https://docs.microsoft.com/de-de/microsoftteams/teams-overview.   We have a German linguist on standby to review any suggestions during December and January.  Currently the Issues feature has been enabled.  We have a technical glitch enabling the Editing feature (clicking on Beirbeitan currently 404s) but it should be fixed in a few days.   If you have any time to look at the translation quality of the German Teams content we would love to get your feedback.  Note that the content is a mixture between human translated and partially-machine-translated articles - the MT ones have a purple banner at the top.  The editing feature will only be enabled on the human translated articles.  If you know of anyone else that might be interested to help us out feel free to share.
Best wishes
Tina
Localization manager for Docs content for Teams, M365, Windows, SharePoint, Exchange, Edge, Surface etc.

**Comment by GiantCrocodile** [comment]
@TinaMcN Thank you for the information. The 404 issue is gone now and I just tried it!

**Comment by TinaMcN** [comment]
@GiantCrocodile thank you so much, this is really helpful.  The German linguist and I are figuring out the process on our end and hope to review your suggestion in the next couple of days.
