### ISSUE TITLE
Interaction with norton av

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#320]
Please add instructions on how to handle getting mdm policies enabled if running Norton av.  My Mdm policies still aren’t working after I joined pc while norton was installed - blocking bitlocker, full defender and windows 10 business upgrade

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b63155-715a-14bf-c3bb-31b52ffcf8ec
* Version Independent ID: d274ba6f-50f2-a4ff-5981-f53561b7e438
* Content: [Get started with Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/microsoft-365-business-overview)
* Content Source: [microsoft-365/business/microsoft-365-business-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/microsoft-365-business-overview.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by VLG17** [comment]
@gkens "after I joined pc while norton was installed" - you mean Azure-AD join? Do you have Auto-Enroll enabled in Intune? The antivirus installed on the PC does not have any impact what so ever on this process.

Are you having issues with the mandatory compliance policy (which marks the device as compliant or not) or an optional MDM policy which you created? I assume the latter.

I would recommend opening a support ticket from the Azure Portal (or any Intune blade), so that a support engineer can look at the affected policy and check why it's not working.

**Comment by mypil** [comment]
@gkens - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
