### ISSUE TITLE
please add troubleshooting

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#323]
need to add troubleshooting for what happens when win 10 business upgrade didnt happen and, if in progress, show that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8e657e-2aa7-230d-0d9d-675c0200ac18
* Version Independent ID: 2028f003-2624-2bd3-34ea-6022d495e2c6
* Content: [Set up Windows devices for Microsoft 365 Business users](https://docs.microsoft.com/en-us/microsoft-365/business/set-up-windows-devices#feedback)
* Content Source: [microsoft-365/business/set-up-windows-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/set-up-windows-devices.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Sirkkuw** [comment]
thank you for your feedback - please check out this:
https://support.microsoft.com/en-us/help/4027322/windows-update-troubleshooter

I will link that to the docs.

**Comment by mypil** [comment]
@gkens - Thank you for submitting feedback.

From our understanding, the issue has been answered by Sirkkuw. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by gkens** [comment]
That did not resolve the issue as it say to run if I get a particular error code - I received no error code

**Comment by VLG17** [comment]
@gkens as stated for https://github.com/MicrosoftDocs/microsoft-365-docs/issues/321, please refference the below articles for troubleshooting steps or contact Microsoft support, so that specialized support engineers can look at your specific issue:

https://docs.microsoft.com/en-us/windows/deployment/upgrade/resolve-windows-10-upgrade-errors
https://docs.microsoft.com/en-us/windows/deployment/upgrade/troubleshoot-upgrade-errors
https://support.microsoft.com/en-us/help/10587/windows-10-get-help-with-upgrade-installation-errors

**Comment by mypil** [comment]
@officedocsbot close
