### ISSUE TITLE
Very helpful but needs more

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#326]
This is a great bridge from the high level 365 business admin to intune

Please also indicate which 365 business device setting requires windows 10 business upgrade, how that ties to intune, and how to troubleshoot if it doesn’t work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3bdeba6-de08-d374-cf95-6b83bf21e81f
* Version Independent ID: 10cac9c3-602e-bfa3-3519-5d4cb52b1d24
* Content: [How do protection features in Microsoft 365 Business map to Intune settings](https://docs.microsoft.com/en-us/microsoft-365/business/map-protection-features-to-intune-settings#feedback)
* Content Source: [microsoft-365/business/map-protection-features-to-intune-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/map-protection-features-to-intune-settings.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@gkens - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@gkens The definition of Windows 10 Business gives us the answer : "Windows 10 Business is a set of cloud-services and device management capabilities that complement Windows 10 Pro and enable the centralized management and security controls of Microsoft 365 Business."

So in order to take advantage ot the centralized management and security controls of Microsoft 365 Business you need Windows 10 Business. And if you want to go into detail and see what are these servicies and capabilities exactly, you can find this information in the Microsoft 365 Business Service Description - https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-service-description

The link with Intune, generally speaking, is having MDM capabilities (Windows, MacOS, iOS and Android), MDM Auto-enrollment, MAM for Office Apps, deploy device profiles and security configuration, etc.

**Comment by gkens** [comment]
Dear Sir or Madam,

It would be helpful to see my original comment along with your response.

I think I can summarize all of your responses as “our docs are fine just as they are, no changes needed.  Talk to support if you need help”

As such, I will probably stop trying to make them better by leaving comments as I am not feeling encouraged by your responses thus far.

Glenn Kime
Principal
Enspired IT of Ann Arbor
734-228-7077

**Comment by mypil** [comment]
@gkens - Thank you for your response. Is there something within this article that you suggest to be added or edited? If yes, please share the appropriate text and where it should be placed, so we can have @VLG17 create a Pull Request to get it added.

Otherwise, if your issue is more of a feature request or for user feedback, you can submit via User Voice - **https://office365.uservoice.com**

For troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a support ticket- **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

Please understand that this site is a product documentation site and not a support nor a feature request site. I hope this gets you pointed in the right direction. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
