### ISSUE TITLE
It is not clear to me what log information is available under an E3 licence.

### ISSUE THREAD

**Issue by jackwghugheslm** [MicrosoftDocs/microsoft-365-docs#3295]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027a1632-76a4-9e87-8376-c10ddfc3e116
* Version Independent ID: 10c72509-5d4a-25d3-caf8-361474f68cd8
* Content: [Advanced Audit in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit?view=o365-worldwide#faqs-for-advanced-audit)
* Content Source: [microsoft-365/compliance/advanced-audit.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/advanced-audit.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jackwghugheslm The only differences between E3- and E5-licensed users are these:

1) Audit records for activities performed by E3 users are retained only for 90 days. 
2) The 4 crucial events that are documented in the Advanced Audit topic **are not** logged for E3 users.
3) Audit log retention policies **do not** apply to E3 users.

Otherwise, any information logged in audit records for E3 and E5 users is the same.

Hope this helps.
