### ISSUE TITLE
Enabling the feature - how long does that take?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#3357]
How long does it normally take to enable sensitivity labels for SharePoint and OneDrive?
My Global Admin went to the compliance portal, saw the "yellow box" on the information protection tab (which I did not see as Compliance Administrator) and clicked "turn on now".
Immediately the yellow notification disappeared, but still we see the notice "first complete these steps to enable the feature."
Does this take a while? (Documentation suggests it's immediate). Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@andrePKI  Thanks for bringing this to my attention.  After checking, yes it seems being a global admin is required to see this yellow bar & "Turn on" because behind the scenes, it's making a SharePoint reconfiguration at the tenant-level.  I'm updating the docs today to reflect this requirement.

It should take effect fairly quickly but I'm also adding it can take up to 15 minutes.

I suspect the "first complete these steps to enable the feature" is referring to a different notification - the one to enable sensitivity labels for containers.  At the moment, you can't enable this from the UI but we're looking into this, so it's information only for a separate feature that requires configuration in Azure AD.

**Comment by andrePKI** [comment]
@cabailey Carol thank you for your prompt and clear responses!
