### ISSUE TITLE
Assign labels to AAD groups??

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#3359]
This documentation is a maze. I get lost the whole time.
"1. Because this feature uses Azure AD functionality, follow the instructions from the Azure AD documentation to enable sensitivity label support: Assign sensitivity labels to Microsoft 365 groups in Azure Active Directory."
Now, do I just need to execute the one step to enable label support? Or do I also need to create groups (use existing) to assign labels to as described in the referenced doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#enable-this-preview-and-synchronize-labels)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@andrePKI Yes, this is a challenge because to use the feature in Microsoft 365, you must first enable a setting in Azure AD.  We link over to the Azure AD documentation because they own this and can change their instructions.  In fact, this happened in the past when we copied their instructions for an easier end-to-end procedure to follow, and didn't realize when they made technical changes and of course, our instructions no longer worked.  That's why we now link to the authoritative source.

If you are a Microsoft 365 customer who wants to use sensitivity labels with SharePoint, Teams, and Outlook on the web, I recommend you follow the order we suggest on this page:
1. Enable sensitivity labels for containers and synchronize labels
2. Configure sensitivity labels for groups & site settings
3. Apply these sensitivity labels to containers as needed 

As I mentioned in my other post, we're looking into making this process a whole lot easier to configure by having a "Turn on" button in the compliance center that will take care of #1 for you.
