### ISSUE TITLE
Temporary licensing backfill issue

### ISSUE THREAD

**Issue by maximumdave** [MicrosoftDocs/microsoft-365-docs#3387]
This document references "temporary licensing backfill issue" but I cannot find out what this exactly means. It also reference the "previous FAQ" but again it is not clear on which FAQ it is referring to. Please update this article with more clarification on these two issues. The 10 year audit license becomes available in early 2021 so it would be great to have this clarification as soon as possible so organizations can plan appropriately. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027a1632-76a4-9e87-8376-c10ddfc3e116
* Version Independent ID: 10c72509-5d4a-25d3-caf8-361474f68cd8
* Content: [Advanced Audit in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/advanced-audit.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/advanced-audit.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@maximumdave Thanks for catching this. We will remove the references to previous FAQ and licensing backfill issue. It's not applicable anymore and doesn't impact an organization's ability to plan for the 10-yr retention of audit records. For 10-yr audit log retention, you just need to make sure that the users whose audit records you want to retain for 10 yrs are appropriately licensed, and to implement audit log retention policies to retain records for 10 years.

Licensing backfill was as issue when we first released Advanced Audit back in Feb. 2020. It meant that Advance Audit package may not have been rolled out to an organization when it was first released. Earlier versions of this topic had an FAQ item that addressed this and had steps to mitigate it for uses by unassigning and then reassigning the Adv Audit app for an E5 user in the M365 admin center. Since this is no longer necessary to do, we removed the FAQ; however as you cited, we didn't remove the reference to it. If you're curious about the mitigation (again, it's no longer necessary) you can view the view the history of this topic in github (see PR submitted on Sept 18th, title "updated adv audit FAQs as per marketing and PM").

Thanks again for the heads up.
