### ISSUE TITLE
Page design has changed, cannot locate information

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/microsoft-365-docs#3395]
Looking for section on creating tags.  Due to the new Compliance Management page I cannot follow the guide as presented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Set up an archive and deletion policy for mailboxes in your organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mntorq** [comment]
Nevermind, missed a step.
The Exchange portal is important, but I don't know why it's controlled here and not under Compliance Management, etc as these are the new portals that MS is recommending to use for everything.

**Comment by markjjo** [comment]
@mntorq At this time, the only way to move items to the archive mailbox (e.g. by creating an archive policy) is to use MRM retention tags and retention policies in Exchange Online (there is no way to do this in the new portals). For this article, maybe the best thing would be to change Step 2, and navigate directly to the the EAC (e.g. 1: Go to the Exchange admin center at https://outlook.office.com/ecp instead of starting from the SCC, even though the SCC is left open from Step 1. Let me know if this might be less confusing. Thanks!
