### ISSUE TITLE
ATP Anti-Phishing Policy 'Users to protect' Limit Change

### ISSUE THREAD

**Issue by kirknall** [MicrosoftDocs/microsoft-365-docs#3403]
Hello M365 Docs,

Referencing https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/364 and several meetings, including PFE configuration and security audits.

This documentation page now states that the 60 'Users to protect' limit is **per tenant** and not **per policy** as it had been in the past,

This config received Microsoft's blessing as recently as July of this year.

When did this change? Why did this change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kirknall, I'm pretty sure the '60 users' limit has been mentioned in the UI for some time, but it's unclear if anything has changed. In other words, the '60 users' limit might have always been 60 users for all policies in the organization. It's only recently that we've clarified.

**Comment by kirknall** [comment]
It is mentioned in the UI, in each of the 9 policies we have. There is no indication anywhere that entering users into subsequent policies are basically useless.  The documentation also did not mention this until relatively recently.

We have had 2 different field engineers review this and confirm it should work as configured.

"Oh sorry, you've only been protecting 60 of those 560 user for the past 2 years" is not a clarification. This is beyond a clarification, this is a significant reduction of ATP's impersonation protections as sold to us.

**Comment by chrisda** [comment]
@kirknall, I've just been informed that the recent 'max 60 protected users' updates are incorrect. The correct maximum is 60 protected users per policy, but you can't specify the same protected user in more than one policy.

I've updated the topic accordingly

**Comment by kirknall** [comment]
Excellent. Thank you!

**Comment by ianwright1984** [comment]
The facts informing the comments here are correct, however, the conclusions are incorrect due to a missing piece of information.  Technically, yes, you can cover more than 60 users in different policies, but those would not all apply to different recipients.  Policy A can have one set of 60 users to cover for user impersonation protection, and Policy B can have another set of 60 users, but the recipient of an email can only have either Policy A or Policy B apply to them, based on which one they match in the "applied to" section of the policy, and if more than one policy matches the "applied to," then only the policy with the highest priority (lowest number) will apply.  This is covered in other policy documentation that states "No two policies can have the same priority, and policy processing stops after the first policy is applied."  This means that while it is technically correct to say that more than 60 users can be listed by having multiple policies, only 60 users can effectively be covered for any given recipient.  For most organizations, this means you will only cover 60 at max, and only in rare circumstances will organizations apply a different set of 60 to different recipients.  For example, if one O365 tenant had many subsidiaries sharing the same tenant, then one anti-phish policy might have 60 VIP's from subsidiary A applied to recipients from subsidiary A, and a different 60 VIP's from subsidiary B applied to recipients from subsidiary B, where there is no crossover of recipients between subsidiaries A and B.  But most O365 tenants are one company with one set of VIP's and one set of recipients needing that protection, and therefore have an effective limit of 60.

**Comment by chrisda** [comment]
@ianwright1984, I hear you, and I understand what you're saying. I attempted an update. Feel free to make changes.
