### ISSUE TITLE
Auto Labeling not working in outlook web

### ISSUE THREAD

**Issue by cshailaja** [MicrosoftDocs/microsoft-365-docs#3415]
We are using auto labeling capability though label settings and as per the condition its suppose to auto label the email/file if US SSN number is found in it.
AIP service is auto labeling the mails sent through Outlook client but when I send any SSN in email using outlook on web, it does not auto label it.

Any help would be appreciated.

**Comment by yogkumgit** [comment]
@cshailaja Please mention which document you are referring to. Thanks

**Comment by cshailaja** [comment]
I am sending sensitive info (SSN) in the mail body, not using any document.

**Comment by denisebmsft** [comment]
@cshailaja, what @yogkumgit means is, to which article(s) does your question apply? This information will help us route the issue to the correct writer/team.

**Comment by cabailey** [comment]
I suspect might be referring to this scenario for sensitivity labels: [Apply a sensitivity label to content automatically](https://docs.microsoft.com/microsoft-365/compliance/apply-sensitivity-label-automatically)

@cshailaja:  If that's the case, it's worth remembering that Outlook on the web uses built-in labeling, so the detection and application of a sensitivity label can be slightly different from the Azure Information Protection client.  If you haven't already, I recommend checking the following two resources and if the SSN isn't detected when you save a draft of the message (when the detection happens rather than on send), open a support ticket for investigation:

- https://support.microsoft.com/en-us/office/automatically-apply-or-recommend-sensitivity-labels-to-your-files-and-emails-in-office-622e0d9c-f38c-470a-bcdb-9e90b24d71a1#ID0EAAGAAA=Web
- https://support.microsoft.com/en-us/office/known-issues-with-automatically-applying-or-recommending-sensitivity-labels-451698ae-311b-4d28-83aa-a839a66f6efc#ID0EAACAAA=Office_for_the_web

**Comment by yogkumgit** [comment]
@cabailey Thank you very much for sharing this explanation. @cshailaja Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
