### ISSUE TITLE
404 Not Found Error

### ISSUE THREAD

**Issue by CPapas** [MicrosoftDocs/microsoft-365-docs#3427]
Trying to access the Azure HIPAA HITRUST blueprint sample fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545aa0d-ba68-3113-413b-0c0b176b08bd
* Version Independent ID: bb2ce8e1-7f40-e5ed-60c4-f8bb0912661d
* Content: [Health Insurance Portability and Accountability (HIPAA) & HITECH Acts - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-hipaa-hitech?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-HIPAA-HITECH.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-HIPAA-HITECH.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@CPapas Thank you for your feedback. The Blueprint document is available at https://docs.microsoft.com/en-us/azure/governance/blueprints/samples/hipaa-hitrust-9-2 and the same has been fixed in the document as well. 

Hope this helps!

@yogkumgit There are no changes required to this document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @CPapas Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
