### ISSUE TITLE
Use PowerShell to apply a sensitivity label to multiple sites

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#3450]
Hello,
About PowerShell, for step 5, should it be:

$sites | ForEach-Object {Set-SPOTenant $_.url -SensitivityLabel $Id}
Or:
$sites | ForEach-Object {Set-SPOSite $_.url -SensitivityLabel $Id}
?

According to the Set-SPOTenant:
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps
There is no support for "-SensitivityLabel"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@lightupdifire  The command on this page has been confirmed as correct by engineering, and I've flagged the missing parameter on the PowerShell documentation.  If you run the command and it doesn't work, please open a Support ticket. You might also want to open a GitHub Issue on the PowerShell page to be informed when it's updated.

**Comment by AndersRask** [comment]
@cabailey the command still is not showing at the documentation. It would be nice if it was added!
Also it is a bit of a mystery what the first default parameter is, since the parameter is not specified and documentation is not updated:

`$sites | ForEach-Object {Set-SPOTenant **$_.url** -SensitivityLabel $Id}`

By checking the definition of the cmdlet (`gcm set-spotenant | select -expand parameters | % { $_.GetEnumerator() } | sort key`)  i found out that the parameter is called -Sites and actually accepts pipebind, so a better syntax would be:

`$sites | Set-SPOTenant -SensitivityLabel $Id`

I would also recommend using singular form -Site not -Sites as implied in the "Best practices" document made by yourself :)
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-powershell-1.0/ee156811(v=technet.10)?redirectedfrom=MSDN#EMAA

**Comment by cabailey** [comment]
@AndersRask  After more investigation, it seems the PowerShell cmdlet documentation won't be updated because this is considered a feature rather than a new parameter for Set-SPOTenant.  Instead, this page is the authoritative reference.  Please see the comment from the PM owner (SanjoyanM ) in https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4611 : "this syntax should work perfectly and is correct."  

I'm told we have many customers running it successfully, so if it's not working for you as it's currently documented here, it warrants investigation from a support engineer.

**Comment by AndersRask** [comment]
The code works, but it was unclear what parameter was used for Url, so I clarified this and showed a better and simpler syntax using pipe bind 😊

Regarding 

> because this is considered a feature rather than a new parameter for Set-SPOTenant.

That makes no sense whatsoever. If it is an available parameter it should be documented both in Docs and in cmdlet itself (using Get-Help)?
