### ISSUE TITLE
Please provide bulk update steps

### ISSUE THREAD

**Issue by greg4168** [MicrosoftDocs/microsoft-365-docs#3473]
The article describes using Powershell to add entries to a mailbox safe senders list but does not describe doing that across the entire organization.  If a safe sender is to be added, is there a single setting or would we need to loop the same command for every mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bec871b-790f-6826-b8f8-d1b7830c49ab
* Version Independent ID: 460db4e8-7f93-60a3-4889-f2d8f08fc75f
* Content: [Configure junk email settings on Exchange Online mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@greg4168, Set-MailboxJunkEmailConfiguration is a one-at-a-time cmdlet, so it would be a loop. You can use either Get-Content and a static list of mailboxes or some type of filter (Get-Mailbox -Filter "Department -eq 'Finance'").

I'm not sure if want to add those instructions to the topic.

**Comment by greg4168** [comment]
Hi Chris -

Thanks for responding.  I'm struggling with it because to set a single safe
senders update for all users could take a week if done mailbox-by-mailbox
so was hoping there was something like a tenant safe senders list or
something like that.

Thanks again

**Comment by chrisda** [comment]
Well, let's look at intent. If you need to safe list the same messages for a bunch of senders in your organization, then something else is going on. The individual safe senders list is really for individual exceptions, meaning many people in your org might get this message, but the majority of them are OK with the spam filter verdict; only a few noisy individuals insist that these messages are good, so you allow an an exception for those few.

Submitting the messages as 'not spam' is a better approach in the long run, because the machine learning will eventually figure out that the messages really aren't spam.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @greg4168 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
