### ISSUE TITLE
DKIM Key Rotation Temporarily Disabled Date

### ISSUE THREAD

**Issue by nmball** [MicrosoftDocs/microsoft-365-docs#3492]
Hi,

The document has a caution stating the auto rotation of keys will be disabled until August 2020 (This has now passed).   It isn't clear if this is still the case, could the document be updated to reflect when auto rotation will be enabled or have the caution removed to show that they are now autorotated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
Typically Microsoft automatically rotates your DKIM keys. I'll confirm with the author and update this accordingly.

**Comment by msbemba** [comment]
@MSFTTracyP I see that Typically Microsoft automatically rotates your DKIM keys once in 48 hours. The caution seems to be invalid in the document. Shall we proceed with removing the date mentioned for auto rotation? Or is this still valid?

CC: @yogkumgit 
Thanks
Sri

**Comment by MSFTTracyP** [comment]
Ah! The advice was that customers could choose to follow Rotate-DkimSigningConfig until auto-rotation was 'enabled again by August 2020'. I'd advise always using Get-DkimSigningConfig to verify your own keys. That part of the document will be corrected (especially since the limit no longer applies) as soon as workload permits, but there is definitely no need for a customer to wait for that correction if key verification is needed. PowerShell commands that will help customers tackle the question of verifying key rotation already exist.

I'm taking a note to remove that Caution from documentation. Thanks for reporting this one!

**Comment by msbemba** [comment]
Thank you @MSFTTracyP . @nmball The caution has been removed from the document.

@yogkumgit The document is updated and the issue is good to be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @nmball Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
