### ISSUE TITLE
Feedback for this Product link incorrect

### ISSUE THREAD

**Issue by joehanna** [MicrosoftDocs/microsoft-365-docs#3526]
This page is for the Microsoft 365 admin mobile app. When I click the feedback "For this Product" button at the bottom, I am redirected to a Windows 10 feedback page instead of one for the Microsoft 365 Admin Mobile App.

**Comment by yogkumgit** [comment]
@joehanna Please specify which document you are referring to. Thanks.

**Comment by joehanna** [comment]
Docs page URL: https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-mobile-app?view=o365-worldwide

"This Product" button at the bottom in the "Sub and view feedback for" section links to the Windows 10 feedback page:
https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app

**Comment by msbemba** [comment]
@pebaum The Feedback link on this page -  https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-mobile-app?view=o365-worldwide is redirecting to Feedback on windows 10 instead of the Admin app. Could you help us fix this link in the backend?

Thanks
Sri

**Comment by lhcole** [comment]
Hi @joehanna At this time the Admin mobile team is accepting feedback only via email, which is why the This product link goes to a generic Windows 10 topic at this time. If you want to submit feedback feel free to use one of the links in the topic or send email here: If you're having issues using the Admin mobile app on iOS or Android, email us at feedback365@microsoft.com to let us know. Thank you!
