### ISSUE TITLE
Query of PowerShell step in section How to enable sensitivity labels for containers and synchronize labels

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#3560]
In the section 'How to enable sensitivity labels for containers and synchronize labels' it mentions that the sensitivity labels need to be synced with Azure AD and to run the following command Execute-AzureAdLabelSync

When you go view the for Execute-AzureAdLabelSync https://docs.microsoft.com/en-us/powershell/module/exchange/execute-azureadlabelsync?view=exchange-ps 

it states 
'This cmdlet is required if you were using sensitivity labels before September 2019.'

Does that mean if you have not used sensitivity labels before this whole section 'How to enable sensitivity labels for containers and synchronize labels' is no not required 

Can this section of the page be updated if this step is only required if you were using sensitivity labels before September 2019.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@nikki-c : My recollection is that running this cmdlet is definitely needed if you had sensitivity labels before September 2019, but we also identified other scenarios that might require running this cmdlet, so as a safeguard against possible issues we included it as a one-time command everybody should run.  Checking with engineering whether this is still the case.

**Comment by nikki-c** [comment]
If you need to run the  Execute-AzureAdLabelSync  in all situations can the PowerShell cmdlet page Execute-AzureAdLabelSync https://docs.microsoft.com/en-us/powershell/module/exchange/execute-azureadlabelsync?view=exchange-ps be updated to remove 'This cmdlet is required if you were using sensitivity labels before September 2019.'

**Comment by cabailey** [comment]
@yogkumgit  I haven't had confirmation that the other scenarios are no longer relevant but I will continue to ask. In the meantime, I recommend we close this.  The cmdlet description for Execute-AzureAdLabelSync is accurate because it says when you definitely need to run it, and this was the original purpose of the cmdlet.  In our instructions on this page, we tell customers to run it for that reason, and as a precaution in case any of the scenarios apply to them.  The explanation provided is accurate:: "to ensure your sensitivity labels can be used with Microsoft 365 groups", Even though it might not be required for all customers, it's a one-time command that could save a lot of time in troubleshooting.  I'm reluctant to update this page to say run it only if you were using sensitivity labels before September 2019 unless I have confirmation those scenarios no longer apply. But equally, it's not accurate to update the cmdlet description to say "you need to run the  Execute-AzureAdLabelSync in all situations".

**Comment by yogkumgit** [comment]
@cabailey Thank you very much for sharing this explanation. @nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
