### ISSUE TITLE
Message Center - Can Messages be downloaded?

### ISSUE THREAD

**Issue by RKD993** [MicrosoftDocs/microsoft-365-docs#3588]
We would like to be able to download Message Center messages into a SharePoint List for the use of documentation team members and trainers. Obviously it would be ideal if one could filter before exporting the messages but that isn't essential.  In a perfect world one could connect to Message Center and import them straight into SharePoint.

Thanks
Russell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f3771a-247c-4f85-992a-e671285c70bd
* Version Independent ID: f3c2890a-2470-9349-ff77-924cf8566365
* Content: [Manage messages in Message center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-messages?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-messages.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@RKD993 Thank you for your feedback. I checked and found no direct way to download message center messages. You can post this as a feature request on our UserVoice platform(https://office365.uservoice.com/forums/273493-office-365-admin/category/94710-message-center) so that the product team can consider this. 

Having said that you can also sync the messages to the planner if that helps, https://techcommunity.microsoft.com/t5/microsoft-365-blog/sync-message-center-posts-to-microsoft-planner/ba-p/1403447

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@RKD993  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
