### ISSUE TITLE
A Disclaimer is Not an organization wide signature

### ISSUE THREAD

**Issue by bruceburge** [MicrosoftDocs/microsoft-365-docs#3642]
> Organization-wide signatures are called "disclaimers,"

This is in accurate, the article this is in, is "Create organization-wide signatures and disclaimers" then the article makes the assertion they are the same thing, when clearly everyone has a different expectation of a signature than a static lump of text insert at the end of all messages every time.

This article, is basically attempting to side step the issue that  "organization-wide signatures " are not supported by office 365, and attempt to make the assertion that a disclaimer is the same thing.  It may be an alternative but it isn't the same thing.

Its OK, that its isn't supported, Just say that it isn't but this is unhelpful, this article was used to day as reference that "office 365 does support organization wide emails", and results in an end product that will not meet the expectation, and isn't consistent with other providers.

Please reconsider the approach at how this is written so that it does not draw false conclusions for those coming across the document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a984a46-1f7b-6ef1-71f3-c5df6c142c01
* Version Independent ID: 4fab7da3-c9ae-0136-c693-ae99c1090f40
* Content: [Create organization-wide signatures and disclaimers - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/create-signatures-and-disclaimers?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/create-signatures-and-disclaimers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/create-signatures-and-disclaimers.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@bruceburge Thank you for your feedback. We have added the limitations under https://docs.microsoft.com/en-us/microsoft-365/admin/setup/create-signatures-and-disclaimers?view=o365-worldwide#limitations-of-organization-wide-signatures

Which states the following

You can't do the following when managing email signatures in Microsoft 365:

Insert the signature directly under the latest email reply or forward

Display server-side email signatures in users' Sent Items folders

Embed images in email signatures

Skip lines which contain variables that couldn't be updated (e.g. because the value wasn't provided for a user)

To gain these and other capabilities to manage email signatures, use a third-party tool. Please do an internet search for email signature software. A number of these providers are Microsoft Gold Partners and their software provides these capabilities.

If the signature does not fall into any of the above categories, you can still use the Org wide signatures (disclaimer) option while creating the transport rule.

Hope this helps!
Thanks
Sri

**Comment by bruceburge** [comment]
I saw that, but calling a disclaimer a signature isn't accurate.

The stipulations you add make that clear, where this clearly becomes a
problem is when you have multiple people in org, in an email thread.

So thanks for your reply, but telling me how a cat isn't a dog, and saying
that if the ways they are different don't exist, then you can call it a cat
a dog isn't helpful.

**Comment by msbemba** [comment]
@bruceburge To set an org-wide signature you use the disclaimer feature in the transport rule. That is why it is mentioned that way.  As said in the TIP"Organization-wide signatures are called "disclaimers," regardless of what they include. For example, they can just be a signature, or also include your address, legal disclaimer, or other information you want."

CC: @twernermsft 

Thanks
Sri

**Comment by bruceburge** [comment]
... Yeah, the guy before you literally said they same thing, that doesn't
make it a signature.

I don't feel like this is really going anywhere, so feel free to close
this.

**Comment by yogkumgit** [comment]
@bruceburge Thank you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
