### ISSUE TITLE
Is this Feature available in the GCC Moderate environment?

### ISSUE THREAD

**Issue by rstraker** [MicrosoftDocs/microsoft-365-docs#3717]
Need clarification on whether this capability is available in the GCC Moderate environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f80e220-5525-c0db-39b7-1e3dd9b18f51
* Version Independent ID: 4d24fad7-028e-4f72-f28f-9f8d982cab1e
* Content: [Set up attorney-client privilege detection in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/attorney-privilege-detection?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/attorney-privilege-detection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/attorney-privilege-detection.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@rstraker  My understanding is that Advanced eDiscovery has been rolled out to GCC government cloud. Attorney-client privilege  detection would be included.

**Comment by rstraker** [comment]
The option does not show in my GCC Tenant.  I do have Advanced eDiscovery just not the Attorney-client privilege setting.

Bob

**Comment by markjjo** [comment]
@rstraker Can you send a screenshot of the Advanced eDiscovery landing page and state how you are accessing Advanced eDiscovery? I guess it's possible that you are using Advanced eDiscovery v1 (classic) in which case you wouldn't have access. Attorney-client privilege is available only in v2. If you are using v2 and it's not there I would suggest you open a ticket with MS Support. Here's a little bit more info about Advanced eDiscovey v1 vs. v2: https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement?view=o365-worldwide#advanced-ediscovery-v10

**Comment by rstraker** [comment]
Ok, below is the Advanced eDiscovery landing page, then the case page where I’m clicking on the Configure Global Analytic
Settings and the option is not there

[cid:image001.png@01D6D228.526083B0]


[cid:image002.png@01D6D228.526083B0]

[cid:image003.png@01D6D228.5BC63710]

**Comment by markjjo** [comment]
@rstraker Thanks for adding screenshots, but I can't see them. But no problem, because it sounds like you have v2 because the "Configure Global Analytic Settings" option is displayed. I just took a look at the documentation (sorry, I should have done this before) and under "Step 1: Turn on attorney-client privilege detection" it states:

"A person who is an eDiscovery Administrator in your organization (a member of the eDiscovery Administrator subgroup in the eDiscovery Manager role group) must make the model available in your Advanced eDiscovery cases."

So, are you a member of the eDiscovery Administrator subgroup in the eDiscovery Manager role group? 

![image](https://user-images.githubusercontent.com/36746813/102130439-b9544b80-3e05-11eb-9de7-1eeac7ad8235.png)


If not you'll need to either ask to be added or ask someone who is an eDiscovery Administrator to enable the attorney-client privilege module. Note that this is a one-time task and applies to all cases in the organization.

Here's a topic on assigning eDiscovery permissions. This has to been done at https://protection.office.com/permissions. You might also not have permissions to assign eDiscovery permissions. If that is the case, a global admin in your org would need to do that. https://docs.microsoft.com/en-us/microsoft-365/compliance/assign-ediscovery-permissions?view=o365-worldwide

If you are a member of the eDiscovery Administrator subgroup in the eDiscovery Manager role group and you still can't enable the module, you should contact Microsoft Support.

**Comment by rstraker** [comment]
Yes, I am the eDiscovery Administrator and eDiscovery Manager.

Bob
