### ISSUE TITLE
Not exactly accurate "Default" policy for Safe Links

### ISSUE THREAD

**Issue by hbwheat** [MicrosoftDocs/microsoft-365-docs#3720]
Hello, 

While researching these PowerShell items I do not think this is entirely accurate description, and can mislead someone into not going to the correct place to edit the default Safe Links policy for the entire Organization. Organization wide default policy does configure Safe Links.

> There's no built-in or default Safe Links policy. To get Safe Links scanning of URLs, you need to create one or more Safe Links policies as described in this article

There is a "Default" via the "AtpPolicyForO365" covering the entire organization. However, you cannot query the parameters set by the "Default" via "Get-SafeLinksPolicy". You must use the "Get-AtpPolicyForO365". This can lead to misleading and confusing documentation compared to what is exposed in the UI. The UI shows a "Policies that apply to the entire organization" and a "Default" that is editable in the "/SafeLinksConverged" page. While the Safe Links documentation does not express or link to the "Default" configuration for the Organization.

I recommend updating the description of the Safe Links Policy default to something like..: 

> There's no built-in default Safe Links policy.* To get Safe links scanning of URLs, you need to create on or more Safe Links policies as described in this article. 

> * Organizations with ATP enabled can configure a "Default" policy with a scope for the entire Organization. Use the *-[AtpPolicyForO365](https://docs.microsoft.com/en-us/powershell/module/exchange/get-atppolicyforo365?view=exchange-ps) commandlets, or you use the "Policies that apply to the entire organization" settings under Safe Links in the Security & Compliance Center to configure the "Default" policy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1541da6f-af9a-05d5-fa34-b1a5df61424f
* Version Independent ID: 88e111ed-67f7-41bc-d823-863ee7ea2a2e
* Content: [Set up Safe Links policies in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hbwheat, I hear you. The situation is very confusing with Safe Links, and I did a bunch of work recently to clarify.

The statement that "there is no default Safe Links policy" is accurate, regardless of what the UI in the EAC, and (to a lesser extent) the Security & Compliance Center say. I think the SCC does a better job by hiding the Safe Links settings that aren't configured in Safe Links policies behind a Global Settings button. (the Block list and the Office 365 app Safe Links settings).

Taking a step back, "policies" for protection features follow a specific theme/structure:

- In PowerShell, there are separate policies and rules for the feature. The policy controls the settings you would expect for the feature. The rule controls who the policy is applied to (recipient filters by email address, domain, or group membership). In the EAC/SCC UI, the two are munged together as a policy, and you can't see the distinction.
- In all features except Safe Links and Safe Attachments, there's an 'always on' default policy that has no corresponding rule because it applies to every recipient in the org, and the policy has an unmodifiable priority value of Lowest, which means it's always applied last.
- You can create custom policies in the UI (or policy-rule in PowerShell) with recipient filters that define who the policy is applied to. You can enable/disable custom policies and set their priority values to determine which policy is applied first.
- From a feature perspective, there's no difference between a default policy and custom policies for the feature (the available features are exactly the same).

Using that criteria, Get/Set-Get-AtpPolicyForO365 isn't really a policy, especially since it contains settings for features like [Safe Documents](https://docs.microsoft.com/microsoft-365/security/office-365-security/safe-docs) that have nothing to do with Safe Links or Safe Attachments. It certainly isn't a default Safe Links policy or a Safe Attachments policy, even though it contains settings that apply to both.

Coincidentally, the offending "Policies that apply to the entire organization" text is in the process of being updated to "Settings that apply to the entire organization" (at least, I asked for the update recently).

**Comment by hbwheat** [comment]
@chrisda ,
Thank you for the response and clarification! I completely missed the note there as I was searching for "Default" on Safe Links page. In that, I was searching for the word "Default" and why it was listed in the UI but clearly stated there were no defaults and not knowing where else to look.

I like the wording change from "Policies" to "Settings" there as that's clearer of where I needed to go look. I certainly didn't understand the distinction between "Organizational Settings" and "Safe Links Policies" when the wording is "Policies..." and it's listed under the Safe Links UI for policies. (that could just be me though... :-) )
