### ISSUE TITLE
TLS Confusion

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#3806]
Hello. I'm a bit confused on if TLS is used to encrypt email by default in Exchange or not.  In the second section, it states "In the service, encryption is used in Microsoft 365 by default; you don't have to configure anything. For example, Microsoft 365 uses Transport Layer Security (TLS) to encrypt the connection, or session, between two servers."  If this is true, then why would we need OME, IRM, or S/MIME.  Or create a mail rule to enforce TLS, if TLS is already used by default?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21613e57-8909-5adc-26ea-14e0a4771d3b
* Version Independent ID: dcd08c8d-4786-abbd-bd9d-47ad6d2117e6
* Content: [Email encryption in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/email-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/email-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/email-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@Canis-Lupis Thank you for your feedback. 

We recommend using TLS in situations where you want to set up a secure channel of correspondence between Microsoft and your on-premises organization or another organization, such as a partner. Exchange Online always attempts to use TLS first to secure your email but cannot always do this if the other party does not offer TLS security. 

 For Exchange Online, we use TLS to encrypt the connections between our Exchange servers and the connections between our Exchange servers and other servers such as your on-premises Exchange servers or your recipients' mail servers. Once the connection is encrypted, all data sent through that connection is sent through the encrypted channel. However, if you forward a message that was sent through a TLS-encrypted connection, that message isn't necessarily encrypted. This is because, in simple terms, TLS doesn't encrypt the message, just the connection.

If you want to encrypt the message you need to use an encryption technology that encrypts the message contents LIke OME, IRM etc.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
The connection is private (or secure) because symmetric cryptography is used to encrypt the data transmitted. The email is not encrypted but just the connection.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Canis-Lupis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
