### ISSUE TITLE
"unsubscribe.bulkmailer.com" example is both listed as correct and incorrect

### ISSUE THREAD

**Issue by PatrickMessierGoC** [MicrosoftDocs/microsoft-365-docs#3827]
In the section https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/troubleshooting-mail-sent-to-office-365?view=o365-worldwide#ensure-that-email-message-content-is-transparent-and-traceable

The "unsubscribe.bulkmailer.com" example is both listed as correct and incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95417878-bc32-8b18-9900-6ad4f10da2a9
* Version Independent ID: 30cd3f4e-9c51-f2fa-b6c0-036756f6b99e
* Content: [Troubleshooting mail sent to Microsoft 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/troubleshooting-mail-sent-to-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/troubleshooting-mail-sent-to-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/troubleshooting-mail-sent-to-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@PatrickMessierGoC, I think I see what's going on (although it took me a minute):

The 'correct' redirects/links are correct because they all use the same domain (bulkmailer.com). The 'incorrect' redirect/links are incorrect because they all use different domains. The fact that bulkmailer.com appears under 'incorrect' isn't so important; what's important is bulkmailer.com is different than excite.com is different than yahoo.com. This aligns with the statement in the previous paragraph:

> ... If you have a lot of advertising or Unsubscribe links or Update the Profile links, they should all point to the same domain. ...

I added some clarifying text to Correct (all domains are the same) and Incorrect (all domains are different).

Thanks for the feedback,

Closing
