### ISSUE TITLE
Microsoft Defender ATP

### ISSUE THREAD

**Issue by ChrisWitmore** [MicrosoftDocs/microsoft-365-docs#383]
Is Microsoft Defender ATP required as part of the solution?   If so, why isn't it mentioned explicitly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb38c4a-21b3-4906-267f-79d7d9e31ac6
* Version Independent ID: 42d74946-a041-f05d-d909-c14c981000f3
* Content: [Prerequisites for Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-ready/prerequisites#feedback)
* Content Source: [microsoft-365/managed-desktop/get-ready/prerequisites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-ready/prerequisites.md)
* Service: **m365-md**
* GitHub Login: @jaimeo

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ChrisWitmore - There are URLs from several Microsoft products that need to be in the allowed list so that Microsoft Managed Desktop devices can communicate with those Microsoft Services. This includes the Windows Defender Advanced Threat Protection (ATP). Please refer to the _Endpoints allowed - other Microsoft products_  ([Windows Defender ATP endpoints](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-atp/configure-proxy-internet-windows-defender-advanced-threat-protection#enable-access-to-windows-defender-atp-service-urls-in-the-proxy-server)) section of this related documentation - [Network configuration for Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-ready/network).

I hope this information helps to answer your query. Thank you for your valuable feedback in helping us improve the docs.

**Comment by mypil** [comment]
@officedocsbot close
