### ISSUE TITLE
DMARC reports

### ISSUE THREAD

**Issue by bertrandpons** [MicrosoftDocs/microsoft-365-docs#3835]
Hello,

You mention "the reports generated through DMARC will provide the numbers and sources of messages that pass these checks, and those that don't. You can easily see how much of your legitimate traffic is or isn't covered by them, and troubleshoot any problems."

Could you please indicate where we can see those reports?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide#step-3-set-up-dkim-for-your-custom-domain)
* Content Source: [microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@bertrandpons Thank you for your feedback. In order to receive DMARC aggregate reports an organization needs to create a DMARC record and publish it into the DNS. If you already have the record published, check for the record that contains an RUA tag (tag: rua=mailto:example@somedomain.com). This email address will be the endpoint for the DMARC reporting organization to send the DMARC aggregate report to.

Hope this Helps!

@yogkumgit There are no changes required in this document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bertrandpons Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
