### ISSUE TITLE
please clarify if data is or isn't deleted with overlapping subscription

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/microsoft-365-docs#3846]
I have two subscriptions like this (actually i have many like this, but lets use this as an example:
![image](https://user-images.githubusercontent.com/11369180/103700608-92e38500-4f59-11eb-8783-8d9cdf224472.png)

This came about because it is a commercial offer meaning subscription cannot be extended once it is expired.
So one has to activate a new subscription (the UI doesn't let one do anything else)

The license are assigned to the same 4 users (so a user has an expired license and an active license for the same product, each from a different subscription).

When the expired subscription is auto deleted what happens to user data?
If I manually delete the expired subscription what happens to the user data?

Also note in this case if i manually delete the subscription it cannot be reactivated as the document states.

My assumption / hope is data is retained, but this doesn;t seem documented anywhere...,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adb403b-fded-7b9c-c093-915ca9bb348d
* Version Independent ID: df08fc6b-a752-084b-448a-a253db2a40d5
* Content: [Close your account](https://docs.microsoft.com/en-US/microsoft-365/commerce/close-your-account?view=o365-worldwide#step-3-delete-all-disabled-subscriptions)
* Content Source: [microsoft-365/commerce/close-your-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/close-your-account.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@scyto Thank you for your feedback. When you change plans/subscriptions within the 30day period and the plan has the same data-related services, or to a higher version, it ensures  that users don't lose data related to those services during the switch. This document pertains to closing the accounts/tenant so you don't see this information. More information about Subscription status can be found at https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires?view=o365-worldwide


To answer your question

When the expired subscription is auto-deleted what happens to user data? Nothing Happens to the data as they have an active license assigned for the same services.
If I manually delete the expired subscription what happens to the user data?  Nothing Happens to the data as they have an active license assigned for the same services.

There could be other reasons why you are not able to reactivate a deleted subscription and I would recommend you contact Microsoft Enterprise commerce support via the need help link so that they can provide you more information pertaining to the tenant and subscriptions.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @scyto Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
