### ISSUE TITLE
Feed back about "important" Section

### ISSUE THREAD

**Issue by JensStolle** [MicrosoftDocs/microsoft-365-docs#3887]
You have a notice saying "The steps below assume that no other Outlook Web App (OWA) mailbox policies have been created in your organization." marked as important in the page. It would be great if it was explained why this is important. While the information on how to create and apply the Mailbox Policies are clear I am afraid to cause problems doing so because of this section. Can you please explain a little more detailed?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba164b8e-a574-0744-ce02-23bda994e505
* Version Independent ID: 05018469-d6f8-0eb5-956c-730991912f8b
* Content: [Turn Microsoft Bookings on or off](https://docs.microsoft.com/en-us/microsoft-365/bookings/turn-bookings-on-or-off?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/turn-bookings-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/turn-bookings-on-or-off.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@JensStolle Thank you for your feedback.  A mailbox can only have one Outlook on the web mailbox policy applied to it. So That is why this is important. We have heard issues from customers stating that they created a new policy and applied but their old custom policy stopped working. 

For more information on outlook on the web mailbox policies, you can visit - https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/outlook-web-app-mailbox-policies


Hope this clarifies and helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JensStolle Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
