### ISSUE TITLE
Unclear as to what is being accessed

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#3898]
Step 4 states, "Email messages that were accessed are identified by their internet message Id." However, there isn't an internet message ID in the audit records.  There is an ItemInternetMessageID; is that the same thing?  If so, should it be blank? The audit we ran came back with non-synced, but MailAccessType:Bind records and not throttled results.  However, I see no internet messageIDs and ItemInternetMessageID is blank.  

Also, the picture at the bottom of the page cannot be zoomed so is hard to read.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea44342-2111-160b-9806-d03e3ee00b1b
* Version Independent ID: ec9c9bc5-cfab-420a-c4c3-20184a7112ad
* Content: [Use Advanced Audit to investigate compromised accounts - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/mailitemsaccessed-forensics-investigations?view=o365-worldwide#use-mailitemsaccessed-audit-records-for-forensic-investigations)
* Content Source: [microsoft-365/compliance/mailitemsaccessed-forensics-investigations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/mailitemsaccessed-forensics-investigations.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Canis-Lupis In examples of MailItemsAccessed audit records, I see "Items" and "InternetMessageId" properties in the AuditData JSON object. No instances of ItemInternetMessageID. Possible that these are for mailbox items that are not email messages. Would suggest you open a ticket with MS Support.

As for the screeshot at bottom of page. I can't do anything about its size or your ability to zoom. But I will add the PowerShell command from the screenshot so that you can run it in your own environment to display the output.

**Comment by markjjo** [comment]
You might also check to see if the audit record identifies the folder where these items are located?

**Comment by Canis-Lupis** [comment]
Yes, I can see the folders where the items were located and it looks like a list of the items accessed but the list isn't in English nor by InternetMessageID so I have no idea what they refer to.

________________________________
