### ISSUE TITLE
A way to apply sensitive labels to M365 groups

### ISSUE THREAD

**Issue by yahookevin** [MicrosoftDocs/microsoft-365-docs#4027]
Hi Team,
This is more of a technical query with PNP PowerShell. Please redirect me to the concerned team if this is not the right place.
Is there a way to apply sensitive label to Office 365 group via PowerShell?
I've automated the process of creating SP team sites and want to apply Sensitive labels via PowerShell to the M365 group that gets created.
Many thanks,
Kevin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Since M365 groups are an Azure AD feature, I think you could ask your question on the following page to get to the right people: https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-assign-sensitivity-labels  In Next steps I see they have a link to "Manage groups using PowerShell commands" but it doesn't include this information.

However, I asked internally & was pointed towards MSGraph and the assignedLabels property from
https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta#properties   Hope this helps!

**Comment by yahookevin** [comment]
Thanks @cabailey for your response.
The shared Links help, but I didn't find the way to assign a sensitive label to the group. Using assignedLabels, I can Get the values but not Post or update a group.
