### ISSUE TITLE
Meetings and external users

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4083]
The rules supplied in the section Meetings and external users for guest users and external users joining from another Microsoft 365 tenant also apply to Teams chats and calls

All Teams chats and calls are stored as compliance records in the Guest users shadow mailbox 

Federated users in a call or chat would retain the compliance records in their own tenant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have added this information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4103

Thanks
Sri

**Comment by cabailey** [comment]
@nikki-c  I've been asked to reject the PR because it was felt that this information belonged in the existing section about meetings and external users. Since we have the information about where this information is stored for external users, what it is exactly you think is missing or needs modifying?  Is it to make the reference to where messages are stored for meetings also include chat messages? 

I also wasn't sure what you meant by "calls" and "compliance records" - retention policies for Teams supports data from chat and channel messages only.  It's a copy of these that can be retained for compliance reasons but they are not "records", which have a specific meaning for compliance.  For example, you can use a retention label to declare an item a record, but this isn't something that's currently supported for Teams messages.

**Comment by yogkumgit** [comment]
@nikki-c Hope explanation shared by cabailey is helpful for you. He asked you a few clarifications also but we haven't had any response from you so we are going to close this issue.  If you see a documentation update is required, please feel free to reopen the issue. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
