### ISSUE TITLE
Teams chat history in Cloud mailboxes

### ISSUE THREAD

**Issue by abdkha** [MicrosoftDocs/microsoft-365-docs#4124]
[Enter feedback here]
Why do we have to use this option when searching for IM between users in the tenant when all our mailboxes are cloud-based, however we are in hybrid mode still. Can you please update section to state this clearly or link to another article that specifies to this situation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0bb4d7-d9fa-ae92-d3ca-246147d1434a
* Version Independent ID: 7ba20db3-55e2-3d29-2d6c-6f68a6b577a8
* Content: [Search for Teams chat data for on-premises users - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@abdkha Thanks for feedback, but not sure I understand or what you want stated more clearly. If you don't have on-premises users  who use Teams or who are not synched to AAD in your cloud organization, then you can leave the checkbox un-selected as it's not applicable. If users who use Teams only have a cloud-based mailbox in Exchange Online, then this checkbox won't have any affect. 

Note that this checkbox corresponds to the -IncludeUserAppContent parameter for the New-ComplainceSearch cmdlet (which is the corresponding cmdlet for the search UI). Here is a link to the cmdlet ref topic with a little more info about the checkbox functionality: https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearch

If you did have on-premises users in your org, who use Teams and whose identity is synced to AAD, and if you configured a search to search all Exchange mailboxes in the org, then selecting the checkbox would also search the cloud-based storage for these on-premises users.

This checkbox/parameter is also necessary to search for chat content for guest usesrs, as doucumented here: https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation#search-for-content-for-guest-users

**Comment by abdkha** [comment]
Hi Mark, thanks for the reply. So my situation is like this:
1. Users homed in On-Prem AD and identities synced to AAD.
2. Exchange hybrid will all mailboxes in Cloud (hybrid just because identities are to stay on-prem)
3. SfB 2015 On-Prem with Teams enabled

When we do a content search without this parameter checked, we get 0 Teams IM Chat history results for a particular user. But results appear when the -IncludeUserAppContent parameter is checked. My question is why do we have to check this parameter because Teams Chat history is actually stored in Cloud mailboxes for our on-premises users. I am wondering if this is a bug or is this intentional?...

**Comment by markjjo** [comment]
@abdkha Thanks for the additional details. I was misunderstanding your issue but I think I get it now: Your on-premises users haver regular cloud-based mailboxes in Exchange Online, so why isn't Teams content returned when searching those mailboxes without using the parameter. I'm not sure why this is the case. I will ping the engineering team to see if I can get an answer. Maybe it's because they are still on-premises users and therefore chat content is stored in same cloud-based storage  that is used for on-premises users who don't have an EXO mailbox? 

I'm curious, in Exchange Online PowerShell (using Get-Mailbox or Get-MailUser), are these on-premises users returned as RecipientType = UserMailbox or RecipientType = MailUser ??

**Comment by markjjo** [comment]
@abdkha One more question: Are the on-premises users assigned EXO licenses?

**Comment by markjjo** [comment]
Hi @abdkha I wasn't able to find anything about your situation. The expected behavior is that if a user's primary mailbox is a cloud-mailbox in EXO, then Teams chat connect would be stored in that mailbox. Maybe there is something specific to your environment/deployment (e.g. a previous migration of on-premises mailboxes to the cloud?) that results in the behavior of having to select the "IncludeUserAppContent" checkbox to return content from Teams 1:1 chats for these users. I would suggests you open a ticket with MS Support so they can investigate if you need to determine why this is happening. Sorry I couldn't provide more specific info.

**Comment by abdkha** [comment]
Hi Mark,

I appreciate you getting back to me with some insight and next steps. You are correct – this must be investigated further to find the root cause. Perhaps it’s our hybrid setup where something may be amiss..
Anyhow thank you for your time 😊

Regards,
Abdul
