### ISSUE TITLE
Microsoft Graph Change Notifications Failing

### ISSUE THREAD

**Issue by ivanmaria** [MicrosoftDocs/microsoft-365-docs#4189]
Intermittently facing issue such as not receiving webhook notification or sometimes webhook subscription is not working i.e. getting subscription request timed out error.

In our setup, we have blocked all inbound traffic and whitelisted only those IPs that are mentioned in the following page:
https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide

I have listed down few of the IPs which seems to be from Microsoft that are being blocked by the firewall. 
40.80.233.14
40.80.232.118
40.118.60.82
40.80.239.196
and more...

It there any change in the list of IPs?

**Comment by msbemba** [comment]
@ivanmaria Thank you for your feedback. We are currently checking these details with Author and PG and will update you shortly.

Thanks
Sri

**Comment by ivanmaria** [comment]
Hi @msbemba, awaiting for the update.

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by ivanmaria** [comment]
Hi @kelleyvice-msft, I am waiting to hear from you. Thanks

**Comment by msbemba** [comment]
@ivanmaria It usually takes a few days to verify and confirm this information with the product group. We have informed the author and you will receive an update once it is made available to us.

Thanks
Sri

**Comment by kelleyvice-msft** [comment]
@ivanmaria, sorry for the delay; I've been on a leave of absence since March. I'm sure you've figured out how to resolve your issue by now, but if not, here's some information that should help.

The article you reference only contains endpoints that are not already provided by the IP and URL web service. To get the most current list of endpoints you'll need to add to your allow list, you can either use the web service (https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide) or the topic https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges. While it is possible you will also need to add endpoints from the topic you referenced, using the methods I outlined above should resolve your issues.

Kelley
