### ISSUE TITLE
More details on how retention works / behaves for M365 groups

### ISSUE THREAD

**Issue by leenana365888** [MicrosoftDocs/microsoft-365-docs#4207]
In relation to retention for M365 groups, it would be great if this page explains:

- What happens to the group object in AAD?
- What happens to content in the associated Planner, Stream group, Yammer group, etc.?
- Is the retention for the backend SharePoint site and the group mailbox considered together or separately?  For example, if there is a retention policy of 1 year and the last email received in the group mailbox is 22 Feb 2021 but the last document created in the backend SP site is 31 Jan 2021.  Does it mean that the site cannot be deleted until 21 Feb 2022?  Or it can be deleted on 31 Jan 2022?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef663fdc-1776-3c73-7743-332796c284e6
* Version Independent ID: ceb29788-39be-8c30-b92a-7a22243ebe83
* Content: [Create and configure retention policies to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@leenana365888  Thanks for your questions - I know that retention when you select the Microsoft 365 Groups location can be a bit confusing because it covers email and files.  The group is the container just like a SharePoint site is a container or a mailbox is a container, so retention setting will never delete the group itself.  For emails that are associated with the group, see "How retention works for Exchange" (https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-exchange) .  For files that are associated with the group, see "How retention works for SharePoint and OneDrive" (https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint).   If there is a conflict of retention settings, the principles of retention apply: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention#the-principles-of-retention-or-what-takes-precedence

**Comment by yogkumgit** [comment]
@cabailey Thank you very much for sharing this explanation. @leenana365888 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
