### ISSUE TITLE
Not a sufficient answer.

### ISSUE THREAD

**Issue by jshimota01** [MicrosoftDocs/microsoft-365-docs#4233]
This is not the information that was here previously.  Removing tools for troubleshooting and putting sales pages is crap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27cfde59-3218-db66-b5a9-73c4268f65fb
* Version Independent ID: 50628765-ec46-37a0-ad4d-55816cb78379
* Content: [Upgrade your Office 2010 to Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/upgrade-users-to-latest-office-client?redirectSourcePath=%252fen-us%252farticle%252fSet-up-Office-2010-desktop-programs-to-work-with-Office-365-for-business-3324b8b8-dceb-45e2-ac24-c642720108f7&view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/upgrade-users-to-latest-office-client.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/upgrade-users-to-latest-office-client.md)
* Service: **o365-administration**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jshimota01 Thank you for your feedback Since Microsoft does not provide Bug fixes or technical support for Office 2010 it is advisable to upgrade the Office suite. Is there any in particular that you would like to see in this document? 

Note that We still have Support and recovery assistant (SARA) available for troubleshooting technical issues on Office 2010.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jshimota01 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
