### ISSUE TITLE
Deleting inactive mailboxes with org-wide retention policies applied

### ISSUE THREAD

**Issue by LukeAllinson-NS** [MicrosoftDocs/microsoft-365-docs#4246]
Hello,

This is partially related to another issue I have logged (https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4243) where we are managing inactive mailboxes and Security & Compliance policies which apply to all mailboxes.

This article (https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-an-inactive-mailbox?view=o365-worldwide) provides instructions for deleting an inactive mailbox when a litigation hold is applied, or an in-place hold is applied (and this lists the get-mailboxsearch cmd-let which is now deprecated in favour of the newer compliance cmd-lets).

There are no instructions however for removing an organisation-wide policy from an inactive mailbox.
An inactive mailbox cannot be excluded from an organisation policy (as it cannot be be selected in the GUI or added in PowerShell) and the "IgnoreLegalHold" parameter has now been removed from the Remove-Mailbox cmd-let; indeed the following article (https://docs.microsoft.com/en-us/office365/troubleshoot/holds/ignorelegalhold-not-available) says that an inactive mailbox must be excluded but again doesn't say how to do this for a global (All Mailboxes) policy

Many Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c129f4e-664c-971f-e438-18ae3eb87f17
* Version Independent ID: e63b5be8-3c3c-2592-72bf-3f00cca0e525
* Content: [Delete an inactive mailbox - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-an-inactive-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/delete-an-inactive-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@LukeAllinson-NS Thanks for feedback. You might try this cmdlet in EXO PowerShell:

 Set-Mailbox -ExcludeFromOrgHolds <hold GUID without prefix or suffix>

which is documented here: https://docs.microsoft.com/en-us/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox?view=o365-worldwide&preserve-view=true#next-steps

also see https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailbox

I'll look into adding that procedure to this topic on deleting an inactive mailbox.

Also as an FYI, [we do recommend using an explicit retention policy exclusively for inactive mailboxes](https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365#inactive-mailboxes-and-microsoft-365-retention-policies), which may help make them easier to manage after the fact. 

I'm also looking into your other github issue you logged against the change hold duration for inactive mailbox topics.

Note also that even though In-Place Holds have been deprecated, you can still use the Remove-MailboxSearch cmdlet to remove an in-place hold so that an inactive mailbox can be deleted. Get-MailboxSearch can also be used to get info about in-place holds.

**Comment by LukeAllinson-NS** [comment]
Thanks so much for the quick response Mark.

I will review the links you sent and let you know how I get on.

Kind Regards
Luke


Luke Allinson
Microsoft 365 Architect
Microsoft Business Group
D:    +44 20 8132 4416
✉   
Luke.Allinson@newsignature.com
🌐   https://mbg.cognizant.com
Cognizant
Microsoft Business Group
#NS1001

**Comment by markjjo** [comment]
Closing. Info about removing inactive mailboxes from both org-wide and explicit retention policies added to this topic on deleting inactive mailboxes.
