### ISSUE TITLE
DKIM CNAME or TXT record type.

### ISSUE THREAD

**Issue by plecavalier** [MicrosoftDocs/microsoft-365-docs#4277]
In my experience (mostly Google related) DKIM requires TXT record types not CNAME. Even in the O365 admin portal in the domain DNS settings section the page refers to creating TXT record types yet this docs refers to CNAME. Which is it? And how can you publish the public key for DKIM using strictly CNAME if it is to be a CNAME record type?

**Comment by yogkumgit** [comment]
@plecavalier Please mention, which document you are referring to. Thanks

**Comment by plecavalier** [comment]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#Publish2CNAME

**Comment by msbemba** [comment]
@plecavalier  It will be a CNAME pointing to the key in your provider's DNS like the case with Microsoft 365. You publish a public key to your domain's DNS records that receiving servers can then use to decode the signature and with m365 it is strictly using CNAME 

Host name:            selector1._domainkey
Points to address or value:    selector1-<domainGUID>._domainkey.<initialDomain>
TTL:                3600

Host name:            selector2._domainkey
Points to address or value:    selector2-<domainGUID>._domainkey.<initialDomain>
TTL:                3600

You have also mentioned the DNS settings Page mentions it as TXT record type, Could you provide a screenshot of what you see on the settings page? We can look at it and make changes to the document if need be.

Hope this helps!

Thanks
Sri

**Comment by plecavalier** [comment]
You say: You publish a public key to your domain's DNS records

How do you publish a key in CNAME? It must be TXT but nowhere in the docs
does it mention to create a TXT RR for the public key. That's why I'm so
confused. I went ahead and created one anyway and it is working now.

Thanks, Phil

**Comment by msbemba** [comment]
@plecavalier Thank you for the update. Did you create a TXT record? Let us know if there is any update required in this document.

Thanks
Sri

**Comment by plecavalier** [comment]
I did yes. And only then did it work.

**Comment by msbemba** [comment]
Thank you for the feedback. Could you provide more information on the TXt record you created so that we can test and update the document.

 

Thanks,

Sri

**Comment by plecavalier** [comment]
Yes gladly. Here you go.

Host
selector1-pauktuutit-ca._domainkey.pauktuutit.ca

Value
v=DKIM1; k=rsa;
p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDeZCMz9p4lU22AjEbhFa0bO/ikP1kAPFeBTJK4pm8nfhQnLMQerS5D3RhQTt1hvU/KYsT+VLTMXaXm1oJ/me/JlWd6T7SRYJm8xmKBiA0RVTIrN3FH6GhZXgoa4+WljO6wIztA32fBPWlRu0LpNV9gQFAAe42Ar+KicMiEidLGgwIDAQAB;
n=1024,1450512990,1466324190

Host
selector2-pauktuutit-onmicrosoft-com._domainkey

Value
v=DKIM1; k=rsa;
p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCu2I0wXu1GGv0yQDk6cZGvOY3Y6kunR/q7mJnxRYL20PjRexQejf+b4cStdT7ReQhGX3lT2sRSy/JU38OwJMTFwpvWKaOOHlkkSg1RTGyHQj33h6a9ZBfgzCPdSXMfQ8N7ZoayFPvN26gg26MjSgx8M9Vnr7YgZSId+zbWIRWLJQIDAQAB;

Thanks, Phil

**Comment by msbemba** [comment]
Adding @MSFTTracyP for visibility

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by chrisda** [comment]
Coming on to this very late, but DKIM for Microsoft 365 custom domains definitely use CNAME records that you create at your domain's DNS hosting service (which might be the domain registrar itself).

Thanks for the feedback.

Closing
