### ISSUE TITLE
Rename a custom Anti-Phishing Policy

### ISSUE THREAD

**Issue by PhilipHaglund** [MicrosoftDocs/microsoft-365-docs#4323]
You can't rename a custom Anti-Phishing Policy.
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide#policy-settings

![image](https://user-images.githubusercontent.com/14297750/109978154-df4f0500-7cfd-11eb-9326-06feace239df.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@PhilipHaglund, nice catch.

When you create anti-phishing policies in the Security & Compliance Center (SCC), an anti-phish policy and an anti-phish rule with the same name values are created. And you're correct that you can't rename an existing anti-phishing policy in the SCC (the Name property is grayed out).

But, if you use the [Set-AntiPhishRule](https://docs.microsoft.com/powershell/module/exchange/set-antiphishrule) cmdlet in Exchange Online PowerShell to rename the anti-phish rule, that new value is shown as the name of the anti-phishing policy in the SCC. But, the name of the corresponding anti-phish policy (visible using the [Get-AntiPhishPolicy](https://docs.microsoft.com/powershell/module/exchange/get-antiphishpolicy) does not change, and there's no Name parameter available on the [Set-AntiPhishPolicy](https://docs.microsoft.com/powershell/module/exchange/set-antiphishpolicy) cmdlet. I also confirmed that if you delete the renamed anti-phishing policy in the SCC, it's smart enough to delete both the anti-phish policy and the corresponding anti-phish rule, even though the names are no longer the same.

I was unaware until I fully tested all of this. Rather than get into all of that PowerShell crap, I changed the sentence to this:

> You can't rename the default anti-phishing policy. After you create a custom anti-phishing policy, you can't rename the policy in the Security & Compliance Center.

Technically accurate, but it doesn't get into the minutiae. Frankly, I wouldn't want my anti-phish policies and anti-phish rules in PowerShell to have different names; too confusing.

Thanks for the feedback.

Closing
