### ISSUE TITLE
Incorrect Permissions information

### ISSUE THREAD

**Issue by jasontenpenny** [MicrosoftDocs/microsoft-365-docs#4352]
Unless y'all have made changes in the last couple of years, Global Admins do not have the necessary permissions to create PST imports. I accessed the page from my global admin account, and it said I needed the Mailbox Import Export role. I had to go add that separately, even though I was a global admin. This means that I had to wait longer than I intended to to begin my import, because the permissions indicated in this article are not correct. My global admin account was created back in 2015, so it's possible that y'all have changed what permissions global admin has. But if that's the case, it would be nice to have something that indicates that accounts older than X date will need extra permissions granted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jasontenpenny Apologies for the inconvenience of having to wait for the synchronization of the new role assignment before you could create a PST Import job. As you note the the Mailbox Import Export role is not assigned by default to global admin. And to my knowledge it has never been assigned to the Organization Management role group in EXO, which means it isn't assigned to global admin. This has been the case since PST Import was first released; admins have always had to assign themselves the Mailbox Import Export role. I think the reason is because this is powerful role.
