### ISSUE TITLE
https://protection.office.com/ does not have "Alerts" under "Home" on the left

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/microsoft-365-docs#4372]
Alert policy settings says to go to https://protection.office.com and then select Alerts > Alert policies.
When I go there, I don't see "Alerts" 
I was looking for a way to stop the 'Show Sharing' alerts that I started getting too much of.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance centers - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Ofer-Gal Not sure what you mean by "Alert policies settings says to go to...". As per the topic "To view alerts, go to https://protection.office.com and then select Alerts > View alerts." The direct URL is https://protection.office.com/viewalerts. Alerts triggered by alert policies are displayed on the View alerts page. Note that you also need to be member of certain role groups to view alerts triggered by different policies, as per [this table](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies#rbac-permissions-required-to-view-alerts). I guess it might be possible that if you're not a member of any of those role groups, the View alert page might not be available to you. If you are an end user, you might have to ask an admin to change whatever policy is triggering these alerts or to edit the policy so that you're not sent a notification.

**Comment by Ofer-Gal** [comment]
Thanks. I asked my admin for explanation. but my remark is about the documentation.
I say that if I need to be in a certain role to see a link, it should state that in the documentation.
Otherwise it looks like bad documentation that leads you nowhere.

**Comment by markjjo** [comment]
@Ofer-Gal Added RBAC roles required to view and manage alert policies. Updated article will be published by end of day.
