### ISSUE TITLE
Paying by bank account is not available in some countries or regions.

### ISSUE THREAD

**Issue by walvis79** [MicrosoftDocs/microsoft-365-docs#4429]
[Enter feedback here]
Hello team, could you please update this article with more details about "where exactly bank accounts are not available as payment method option" 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82583c48-08e6-9acb-657b-ce1fe44e76a5
* Version Independent ID: cbdcf652-3a68-4fa3-9f3b-92c518e0b710
* Content: [Paying for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/pay-for-your-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@walvis79  Thank you for your feedback. I'm checking this information with the author and will update the document accordingly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please help us in resolving this issue.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Gentle reminder, please reply. Thanks

**Comment by cmcatee-MSFT** [comment]
This information is included at the very top of the article:

**IMPORTANT**
As of January 26, 2021, new bank accounts are no longer supported for customers in Belgium, France, Italy, Luxembourg, Portugal, Spain, and the United States. If you’re an existing customer in one of those countries, you can continue paying for your subscription with an existing bank account, and you can add new subscriptions to it, but only as long as the bank account is in good standing.

Closing this issue, since no action is needed.
