### ISSUE TITLE
How to search for Forms using Ediscovery ?

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/microsoft-365-docs#4441]
Hi,
I found no explaination how to search for Forms from ediscovery, to find if a form is capturing somebody's name for example (GDPR) ? 

I want to look for Forms using "Jeff ANGAMA" in the data collected by any user that has creating a form. If I search "Jeff ANGAMA" across everything, I have too many results from email for example, and i can't filter down to Forms results.

Ediscovery is usable for Forms, according to Microsoft forms documentation, this shall be possible : https://support.microsoft.com/en-us/office/gdpr-information-e9fe9fac-20cf-4298-a138-d6a1b8dc6108 

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jeffangama Here is a little more information about where Forms content is saved in a user's mailbox from [this topic](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-is-stored-in-exo-mailbox?view=o365-worldwide):


Microsoft 365 app | Description |  
-- | -- | --
Forms | Forms and responses to a form are stored in files that are attached to email messages and stored in a hidden folder in the mailbox of the user who created the form. Forms created before April 2020 are stored as a PDF file. Forms created after 2020 are stored as a JSON file. Responses to a form are stored in a CSV file. When you export content from Forms in a PST file, this data is located in the ApplicationDataRoot folder in a subfolder named with the following globally unique identified (GUID): c9a559d2-7aab-4f13-a6ed-e7e9c52aec87.

You can try narrowing your search results (searching for just your name will return a lot of results as you mentioned).  You only have to search mailboxes, not sites as Forms compliance content is stored in mailboxes. Here are some tips and results based on my brief testing.

Because the form and the responses are attached to an email, you can use the attachmentnames property. Here is what I came up with to return response csv files and forms json (or .txt) files. 

attachmentnames:Form* OR attachmentnames:Export*

- This query returned forms items because the name of the json file is prefixed with "Form" and a response CSV file is prefixed with  "Export". (this csv file also contains "Response" in the filename so you could use that as well. 
- You can't preview these items. You have to export them (in my case to a PST file) and then I opened PST in Outlook desktop to view. Here is a screenshot of the folder structure. Note the long names are GUIDS for the Form:

![image](https://user-images.githubusercontent.com/36746813/111706446-8e600600-87ff-11eb-8a47-faddd85d11ea.png)

Also, here is the header from the response CSV file. You could also probably search for the keywords "Form responder" . Cells in this column would identify the responder.

![image](https://user-images.githubusercontent.com/36746813/111706640-dc750980-87ff-11eb-978d-53a649e19a57.png)

I hope this helps some.  This is too much detail to be documented in the content search documentation, but I'll reach out to the Forms teams and suggest they update their documentation with a more prescriptive guidance.

**Comment by jeffangama** [comment]
Hello,

1/ I've still a lot of results (a lot of email), when I set the keywords as :
![image](https://user-images.githubusercontent.com/6776269/112125360-a222b800-8bc3-11eb-9476-9a92699ae50f.png)

2/ In the Excel results, can we see the Forms data (question asked, answered provided by users) or do we have to take ownership of the form for that (we need to know the person's email who created the form)

Thank you for your answers

**Comment by markjjo** [comment]
@jeffangama Here's some info about deleting Forms content in response to a GDPR deletion request: https://docs.microsoft.com/en-us/compliance/regulatory/gdpr-dsr-office365#forms

I assume deleting the form will also delete the responses file (or that owner can delete the response file). Not sure if deleting the form or the response in Forms will delete the compliance record in the ApplicationDataRoot folder in Outlook. You might have to check with the Forms teams or test.

Here is a topic on deleting Forms: https://support.microsoft.com/en-us/office/delete-a-form-or-recover-a-deleted-form-2207e468-ce1b-4c4a-a256-caf631d87af0?ui=en-US&rs=en-US&ad=US

**Comment by jeffangama** [comment]
Assuming a customer ask you, please delete my data under the name "ANGAMA Jeff".
I assume we'll use ediscovery to find where are the forms with this name. Then take the ownership of the form and then delete it indeed.

**Comment by bubhat** [comment]
@markjjo - If I place the mailbox on hold - will it retain the forms data in mailbox?
