### ISSUE TITLE
Difference between "Mailbox intelligence" and "Mailbox intelligence based impersonation protection"

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/microsoft-365-docs#4466]
Please update this page to better explain the difference between "Mailbox intelligence" and "Mailbox intelligence based impersonation protection"
For example the former says is is based on user email patterns with their frequent contacts, and the latter says it is based on "each user's individual sender map." That sounds a lot like "user email patterns" and so we are seeking a better description of how they are different, so that we can make a good choice on whether to enable one versus the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide#impersonation-settings-in-atp-anti-phishing-policies)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@chrisda, everyone agrees that the interactions between those two settings are confusing. I'll attempt to explain:

The **Mailbox intelligence** setting turns mailbox intelligence on or off. Mailbox intelligence is the AI that learns your contact history.

The **Mailbox intelligence based impersonation protection** setting, **when turned on**, allows you to specify an action for mailbox intelligence detections of impersonation attempts (likely, a lack of communication history with the messages sender who resembles a protected user or protected domain, but that's not important; the important fact is: the "this is an impersonation attempt" signal is coming from mailbox intelligence).

As you can see in the admin center, **Mailbox intelligence** must be turned on to see/turn on/turn off **Mailbox intelligence based impersonation protection** and (optionally) set an action.

**Mailbox intelligence** = ON while **Mailbox intelligence based impersonation protection** = OFF means mailbox intelligence is still happening, but no action is taken on messages if mailbox intelligence says "this is an impersonation attempt". Even so, **Mailbox intelligence** = ON while **Mailbox intelligence based impersonation protection** = OFF can still help reduce false positives. For example, if a frequent contact resembles a protected user in the policy (same name, similar email addresses, etc.), mailbox intelligence can say, "Even though this looks an impersonation attempt of a protected user, I say that it isn't, because these guys have been communicating regularly via email over the last several months".

Another issues that's confusing: the admin center allows you to turn off **Mailbox intelligence based impersonation protection**, but still configure an action, which makes no sense. That action dropdown box and surrounding text should be hidden or grayed out if **Mailbox intelligence based impersonation protection** = OFF. I understand this is being looked at.

For reference, **Mailbox intelligence** = ON + **Mailbox intelligence based impersonation protection** = OFF is functionally equivalent to **Mailbox intelligence** = ON + **Mailbox intelligence based impersonation protection** = ON + Action = No action, if that's of any interest.

I updated the topic with these clarifications. It should publish later today F 3/19.

**Comment by yogkumgit** [comment]
@itguysocal Hope this comment is helpful for you. If you see any other  documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
