### ISSUE TITLE
Cloudflare CNAME Records

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#4469]
In regards to setting up multiple domains.  Cloudflare will not let you enter duplicate CNAME records.  I can only have selector1._domainkey and selector2._domainkey listed once.  Once I go to add a selector1 or selector2 for the other domain we get the error "CNAME record with that host already exists. (Code: 81053)"

Not sure if you can recommend steps for Cloudflare in this document?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#Publish2CNAME)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
It's not possible for us to include steps for every DNS provider in this article, but this is a technical issue and will need a case opened with Cloudflare. You should ask them if they need TXT records or CNAME records in their case. And to spell out the full steps so that you can keep them for your records. Failing that, you may want to open a ticket with Microsoft Support and ask if they can reach out to Cloudflare support. Again, the exact steps needed should be recorded if this is not already a known issue. You and Support should keep those steps for your records. I'm sorry to hear about this trouble you're having. Please do go to Support to see if the solution is already known, or if some troubleshooting can resolve your issue.
