### ISSUE TITLE
MFA does not work as expected based on the information in this document.

### ISSUE THREAD

**Issue by abrookewood** [MicrosoftDocs/microsoft-365-docs#4516]
It is not very well explained that setting up MFA using this document will **not** result in all users being forced to provide an MFA token when logging on. In order to do that, you either need to use Conditional Access Policy, or you need to enable Legacy MFA on a per-user basis which the document explicitly suggests that you turn off. This page has further information: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults#protecting-all-users

This can also be verified by creating a brand new non-admin user, registering for MFA etc and then logging on to Office 365 in a separate browser or via a Private Tab. The user will be asked for their username & password, but not the MFA token!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multi-factor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@abrookewood Thank you for your feedback. After users complete Multi-Factor Authentication registration, they'll be prompted for additional authentication whenever necessary. Users will be prompted primarily when they authenticate using a new device or application, or when performing critical roles and tasks.  We have linked the document - https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults under the Security defaults section so that gives more information.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @abrookewood Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
