### ISSUE TITLE
FAQ about importing PST files - this articel is unclear and ambiguous in respect of large messages and duplicate imports

### ISSUE THREAD

**Issue by osirisx3** [MicrosoftDocs/microsoft-365-docs#4530]
[Enter feedback here]
"How does the PST import process handle duplicate email items?

The PST import process checks for duplicate items and doesn't copy the items from a PST file to the mailbox or archive if a matching item exists in the target folder in the target mailbox or target archive. If you reimport the same PST file and specify a different target folder (using the TargetRootFolder property in the PST import mapping file) than the one you specified in a previous import job, all items in the PST file will be reimported."

**This is not true.  Duplicates do appear in several circumstances - exactly what circumstances are not disclosed. However, reimporting a failed PST results in duplicates.**

"Is there a message size limit when importing PST files?

Yes. If a PST file contains a mailbox item that is larger than 150 MB, the item will be skipped during the import process."

This is ambiguous.  Is there anyway at all to import items 150MB or larger or is this just not possible at all?

Both these issues are causing quite a bit of pain with a migration. It would be great if we could get the answers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7b7a25a-4cf8-1b51-0c40-6afa334ca537
* Version Independent ID: 0033b96f-ee7b-0e9f-5287-4a5371ce3734
* Content: [FAQ about importing PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/faqimporting-pst-files-to-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/faqimporting-pst-files-to-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/faqimporting-pst-files-to-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by osirisx3** [comment]
Hello and thanks for your response, very much appreciated.

The documents you referred to are the ones I pasted the extracts from and don't appear to answer the question I posed. I wonder is there a PowerShell script that can remove duplicate messages etc. in a mailbox where a PST import has created duplicates?

How about importing messages bigger than 150MB?  How can we import those to the mailbox for compliance purposes?

**Comment by osirisx3** [comment]
As above

**Comment by markjjo** [comment]
@osirisx3 Thanks for feedback. Firstly, 150MB is the message size limit for Exchange Online (see https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits). That is why it is the stated limit for PST Import. I think adding this bit (max message size) to the FAQ would help address the ambiguity. We say item is skipped but not why. It's skipped because it exceeds the max message size. 

As for duplicates, I would suggest you contact MS Support so that they can look into the "several circumstances" where duplicates are appearing in your situation and help you with your migration.

For a little more background, you might take a look at the [New-MailboxImportRequest](https://docs.microsoft.com/en-us/powershell/module/exchange/new-mailboximportrequest) cmdlet help topic. This cmdlet is called/runs in the background when you create and start a PST Import job in the Microsoft 365 compliance center. Taking a quick look at the ConflictResolutionOption parameter, I would assume that if our FAQ is correct, this parameter is configured with the KeepTargetItem value.

**Comment by osirisx3** [comment]
Thanks for the excellent and very helpful feedback, Mark. 

At least now we know that 150MB is the largest that can be stored, we can look at alternative storage methods for compliance reasons. Just the addition of that one piece of information to the documentation would have saved hours of searching and directed us along alternate paths!

I did already check out the "New-MailboxImportRequest cmdlet help topic" - thanks for the suggestion - however it appears that it is not supported in Exchange online - and I had advice to that effect separately also.  I am assuming - rightly or wrongly - that this advice applies to MS365 as well.

**_Note: This cmdlet is no longer supported in Exchange Online. To import a .pst file in Exchange Online, see Use network upload to import PST files._**

Are you suggesting this command does in fact still do the job in MS365 or am I missing something?

We really appreciate the time you have taken for your reply, and it's been a huge help confirming the steps I have already taken to get the answers - that is worth gold! Thanks!

**Comment by markjjo** [comment]
@osirisx3 Sorry, I missed that bit about the cmdlet not being supported in EXO. Yes, that would still apply in Microsoft 365. We want you to use the PST import feature in the compliance center UI to import PST files.

If you do contact support, and the documentation about duplicates needs to be updated based on your case, support can contact me to request a document update. Thanks!

**Comment by osirisx3** [comment]
No worries, mate, your responses were most helpful in steering me in the right direction. Thanks and cheers  Dave
