### ISSUE TITLE
 Insider risk settings > Analytics missing

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/microsoft-365-docs#4669]
This settings is no longer available under settings:
Insider risk settings > Analytics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5147f5e8-a267-ee55-de12-d80ab29804c2
* Version Independent ID: 945fc70f-1861-d2e9-4d46-f56eafb53766
* Content: [Insider risk management settings - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-settings?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-settings.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@gb5757870 Thank you for your feedback. I was able to test this and the option is available. Since this is under preview not all tenants might have not this option. Once this is out of preview and live, you should be able to see this option on insider risk management settings.

![image](https://user-images.githubusercontent.com/45987684/114765890-56f36380-9d83-11eb-930e-425ca90a86df.png)

Hope this helps!

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @gb5757870 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
