### ISSUE TITLE
Clarify URL when creating the lable

### ISSUE THREAD

**Issue by alschneiter** [MicrosoftDocs/microsoft-365-docs#4754]
Please update the documentation when creating the label itself in the compliance portal.
You need to include the KEY name you have provided within "TestKeys" section of the **appsettings.json** into the url. For example:
https://pocdke1.azurewebsites.net/**KEYNAME**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide#clone-the-dke-github-repository)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@alschneiter Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4873. Once the author approves, the document will be udpated.

Thanks
Sri

**Comment by tiburd** [comment]
@alschneiter and @yogkumgit 

To me, it looks like this information might be incorporated in [the article](https://docs.microsoft.com/microsoft-365/compliance/double-key-encryption) now:
![image](https://user-images.githubusercontent.com/54688693/130693317-25d9ada7-3056-47a7-98c8-93bf76e8f211.png)

@alschneiter - can you please confirm whether your issue is now resolved? If it is, we can close [this related PR](https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4873).  Please @ mention me in your reply.

Thank you!

**Comment by KCCross** [comment]
@msbemba can you please take a look and see where we're at with this one? I've merged the PR. Please continue to test. Closing this comment in the meantime.
