### ISSUE TITLE
Sensitivity Label Domain Limit

### ISSUE THREAD

**Issue by FrankMcGovern** [MicrosoftDocs/microsoft-365-docs#4852]
Is there an upper limit to how many domains can be added to a sensitivity label's assigned permissions?

If not count limit, is there a size limit to the label itself by adding a ton of domains?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd3497a-c02a-5fd6-12db-3a093f0fe17c
* Version Independent ID: 2ef81556-61b0-47ae-d8fc-3d9aa5240c51
* Content: [Restrict access to content using sensitivity labels to apply encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@FrankMcGovern  When you apply the label to a document or email, the encryption service creates a policy ("publishing license") for that piece of content, based on the domains/groups/users and the permissions you have specified for them. There is a size limit to what's supported but it doesn't nicely map to the number of domains/groups/users - there are other factors such as the length of these names and the number of usage rights specified.  Unfortunately, there's no way to tell at the point you configure the permissions whether the resulting policy will be exceeded (because it's not created at this point but when the encryption is applied). If the size is exceeded, the encrypted content won't open. 

It's very rare that customers exceed the limit and that usually happens when they specify hundreds of individual users - which can be fixed by using groups instead. And groups are always easier to manage. If you are specifying domains in the 100s, make a point of doing your own test before deploying this label to users: Apply the label and using a different account on a different computer, make sure one of the authorized users can successfully open it.

**Comment by FrankMcGovern** [comment]
@cabailey - Thank you for the insight. I think it would be wise to discuss this on the Docs page.

**Comment by cabailey** [comment]
@FrankMcGovern  This limitation impacts very few customers and we're looking at creating a KB for it. One argument I've heard against entering so many addresses is that "a secret shared with so many people is no longer a secret" and you might find the "any authenticated user" setting is a better option. For further advice, I recommend posting your requirement on the MIP Yammer group: https://www.yammer.com/askipteam
