### ISSUE TITLE
How do I tag meeting invites?

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/microsoft-365-docs#4861]
Yall have alot of good stuff. but where are the labels for meeting invites? its just as sensitive as literally anything.

Example:
Meeting invite:
Subject: were selling our company

no tags .... OH NOOOOOOOOOOOOOOOOOOOOOOOOOOOO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@SquirrelAssassin   Thanks for your feedback!  Meeting invites don't support sensitivity labels at this time, which is why you won't find this as a documented scenario. In Office apps, sensitivity labels are supported by files and emails, and for Teams these labels are supported for the team site. I agree applying sensitivity labels to meetings would be great addition and while we're transitioning from UserVoice, I recommend you fill out the following form for this MIP feature request: https://customervoice.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRxOwaHW_l8dCpIFVq3iLzSFUQzA0NVJNMktLOE5KRzVYS1VaU0VDVlZURS4u
