### ISSUE TITLE
10 auto labeling policies will not be enough by any means

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/microsoft-365-docs#4902]
We want to make labels that are restricted to <mycompany.com and yourcompany.com> and auto label EVERYTHING that goes into a SharePoint site.  Then block all attachments from going to yourcompany.com through email rules.  We will have 100+ of these auto labeling requirements (one per vendor).  How can I request a increase for this for our tenant? 

We all know that DLP has generally failed as a tool because its to hard to control accuracy for detection and is just a annoyance to anyone outside of IT.  However using AIP to only allow access to documents between two or more companies and the ability to revoke that access is just AMAZING.  

Were one month into deploying AIP and the requests are increasing to 1 or 2 deployments a week.  Were starting to have to tell the business they have to manually tag before uploading and that's already showing potential for staff to upload files without it being tagged prior.  Please dont let AIP fail again... please.

And in no way would we across 200 SharePoint sites ... would we use more then 2000 documents a day (my guess is 200 a day is high) ... we just need to apply 100 labels across 100 SharePoint sites automatically based on our regex data classification that matches everything.    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Automatically apply a sensitivity label to content in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@SquirrelAssassin  If your request for auto-labeling is about scaling rather than functionality, this is currently under development and if you have an immediate need to unblock deployments, open a ticket with Microsoft Support.  If your request is to change or add functionality, use the following form: https://customervoice.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRxOwaHW_l8dCpIFVq3iLzSFUQzA0NVJNMktLOE5KRzVYS1VaU0VDVlZURS4u

If you haven't found it already, you might find it beneficial to join the MIP Yammer group, where feedback about the product is encouraged and shared by customers, and changes often announced: https://www.yammer.com/AskIPTeam

Nothing to add or change to this documentation at this time, so I'll close this issue.

**Comment by SquirrelAssassin** [comment]
Did you say yammer?  Can I get a adult in here?
