### ISSUE TITLE
Is it possible to list all potential safety tips that could be exposed to users based on Malware, Phishing and Spam on this page?

### ISSUE THREAD

**Issue by sinnamingrrl** [MicrosoftDocs/microsoft-365-docs#4908]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1daade0-c937-6daf-cdc5-e6e23214426d
* Version Independent ID: 49836613-b9a3-fc37-ffc8-3589dda16d45
* Content: [Safety tips in email messages - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safety-tips-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safety-tips-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safety-tips-in-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@sinnamingrrl, I'm already in the process of trying to track this down now..

**Comment by chrisda** [comment]
@sinnamingrrl, that safety tips topic has been removed, since there is overwhelming evidence that the "Enable safety tips" setting in anti-spam policies (which this topic was based on back in 2017) apparently does nothing anymore, and there basically are no more safety tips as described in the topic.

However, in anti-phishing policies, there are specific safety tips that are alive and well, and easily identifiable:

- [First contact safety tip](https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#first-contact-safety-tip)
- [Impersonation safety tips](https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#impersonation-settings-in-anti-phishing-policies-in-microsoft-defender-for-office-365):
  - **Show tip for impersonated users**
  - **Show tip for impersonated domains**
  - **Show tip for unusual characters**
- Not safety tips in the literal sense, but there's also [Unauthenticated sender identification](https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#unauthenticated-sender):
  - **Show (?) for unauthenticated senders for spoof**
  - **Show "via" tag**

Thanks for the feedback.

Closing.
