### ISSUE TITLE
Change SAS Key

### ISSUE THREAD

**Issue by flodorf1** [MicrosoftDocs/microsoft-365-docs#4917]
Please add details if the SAS key can be changed or manually expired... For migrations between providers it would be great to let a 3rd party upload directly to a customers Azure ingestion storage... After the upload the access key should be revoked ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#before-you-import-pst-files)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@flodorf1 Thanks for the feedback. Altering in any way the SAS key that is generated by network upload wizard is not supported. The SAS key is generated to upload PST files to a Microsoft-provided Azure Storage area. When a corresponding PST Import job is created, the service looks for the uploaded PST files in the storage area specified by the SAS key. Import job would fail because PST files wouldn't be located in the expected location. I'll pass your feedback on to the engineering team.
