### ISSUE TITLE
How long do you have to wait after making permission changes?

### ISSUE THREAD

**Issue by mymebenha** [MicrosoftDocs/microsoft-365-docs#4943]
When you make changes to a group that was used to assign permissions, it takes over 24 hours for the changes to become effective.  It should mention how long we have to wait.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Learn about sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@mymebenha  Hi, thanks for your feedback.  Can you clarify when you say "changes to a group that was used to assign permissions", you're referring to configuring encryption for a label, and are the changes a different group or the same group but group membership changes?

**Comment by yogkumgit** [comment]
@mymebenha Kindly answer Carol's query. Thanks

**Comment by cabailey** [comment]
@mymebenha  Thanks for the clarification - important because there is a difference in whether you're changing the group specified in the label, or keeping the same group but changing the group membership.  The changes shouldn't take that long, so you might want to open a support ticket for investigation.  The way this works is that when you configure a sensitivity label for encryption, it creates a template for the Azure Rights Management service with the assigned people/groups and their permissions.  That service does cache the group membership for performance, but documented as up to 3 hours, here:  https://docs.microsoft.com/azure/information-protection/prepare#group-membership-caching-by-azure-information-protection

That 3 hours is a maximum and easily falls within our guidance to wait for 24hrs when making changes to sensitivity labels, so if it's taking longer than 24hrs, that's not expected.  Have you checked your Azure AD replication latency?  That's going to be a backend dependency on getting the updated group membership and if you can't see anything amiss there, a support engineer could help investigate the delay.

Here's an FAQ that might also be helpful that directly addresses changing the permissions: https://docs.microsoft.com/azure/information-protection/faqs-rms#ive-protected-a-document-and-now-want-to-change-the-usage-rights-or-add-usersdo-i-need-to-reprotect-the-document

**Comment by cabailey** [comment]
Closing.
