### ISSUE TITLE
Mailbox getting this error and it has an E3 license

### ISSUE THREAD

**Issue by AESAdmin-JD** [MicrosoftDocs/microsoft-365-docs#5042]
I realize the error says it has no license but in the portal it is shown with an E3 office license

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00421a8e-42cf-c393-f91d-da1b7d7cc7da
* Version Independent ID: de00b816-762d-2171-eb7f-1ce6a55ec189
* Content: [Getting a mailbox not found error in Outlook on the web - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/mailbox-not-found-error?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/mailbox-not-found-error.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/mailbox-not-found-error.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@AESAdmin-JD Thank you for your feedback. The error that you receive could be due to an issue in the backend while provisioning a mailbox. If this is a new mailbox and the issue persists over 24 hours, it is recommended to contact the support team via the need help option on the admin center.

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @AESAdmin-JD Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
