### ISSUE TITLE
Suggested that best practice to keep UPN and email the same

### ISSUE THREAD

**Issue by johnwc** [MicrosoftDocs/microsoft-365-docs#5171]
Can you explain why you say this is best practice. When working with security of organizations, it has always been best practice to keep these different to keep hackers from trying to brute force login via known email addresses. When the UPN is not the same, along with using a sub-domain for the UPN, the brute force attacks drop to zero.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42a1bfc-8920-c16d-f4c9-d29b401b7f6c
* Version Independent ID: 979b71da-fdff-238d-41fb-472f1591e51e
* Content: [Change a user name and email address - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/change-a-user-name-and-email-address?view=o365-worldwide#tip-keep-the-persons-old-email-address)
* Content Source: [microsoft-365/admin/add-users/change-a-user-name-and-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/change-a-user-name-and-email-address.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@johnwc Thank you for your feedback. While the Brute force attack can be dropped to zero, In some environments, it’s just not feasible to change the UPN due to user confusion.

1. Users will need to understand what their UPN is and that it is the login for all things Office 365 related. There are some prompts that will say “enter your email” but they will in fact need to use their UPN (for example, office sign in)

2. Most ActiveSync clients will automatically configure using Autodiscover. When your UPN matches your email, you basically just enter your email and password. When they don’t match, you enter your email and password, then you’ll get prompted to enter your login (UPN) to actually authenticate.

3. All Versions of Office and OneDrive prompt the user for their email address and again, they really mean the UPN.

CC: @kwekuako 
Hope this helps!

Thanks
Sri

**Comment by johnwc** [comment]
Every organization that we've worked with viewed the simple things you pointed out as a employee education issue. The security issue on the other hand was always a higher concern than teaching users how to login with their UPN.

Best practices usually do not prioritize user education issues over security issues.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @johnwc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by johnwc** [comment]
@yogkumgit the comment is not helpful because it does not exhibit best practice. It exhibits a better user experience recommendation. It should be updated and made clear what the best practice is for secure accounts, but is MS recommendation to keep the UPN and email address the same for better user experience.
