### ISSUE TITLE
Missing URL {Tenant}-admin.sharepoint.com

### ISSUE THREAD

**Issue by aakrol** [MicrosoftDocs/microsoft-365-docs#5187]
Hi 

In the KB article and in the tenant specific JSON there is a missing URL to access the admin portal.

{Tenant}-admin.sharepoint.com

Can the KB be updated and the tenant specific admin up dated.

Regards
AK
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
I believe this issue was resolved via internal email on 6/2 with the following explanation from engineering: Why does the HTML web page show FQDNs like <tenant>.sharepoint.com but the web service returns *.sharepoint.com?
The HTML web page at  http://aka.ms/o365ip shows <tenant> as a convenience to the reader to indicate that this token should be replaced by the customers tenant name such as contoso.sharepoint.com. In the web service there is a parameter called TenantName as documented at  http://aka.ms/ipurlws. If the TenantName parameter is passed then the result will include the customers tenant, otherwise the result will include an asterisk so that it is compatible with proxy servers as a wildcard for all tenants. Since the web service output is expected to be read by a machine, we do not include the token <tenat>.
