### ISSUE TITLE
Label change replication expectations

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/microsoft-365-docs#5277]
There are a couple of places that describe the need to wait for changes to replicate.  In the Section "Publish sensitivity labels by creating a label policy" it has different expectations for Office app built in labeling and Office on the Web.  Please add an explicit statement regarding the Unified Labelling client, especially if the expectation is similiar to built-in or Web.  

Also, it woudl be useful/helpful to SC&C administrators if there was an affirmation that the change replication is complete (there does seem to be a field in the Powershell output for this but its not clear if its reliable).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57908eea-077f-363c-8d51-3b8335914f4c
* Version Independent ID: 0d1421f1-b546-677f-ef3b-7e3da294b5ef
* Content: [Create and publish sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
As more apps & services adopt sensitivity labels, it gets tricky to document in one place all the different timings and ensure accuracy when different engineering teams own them.  In this case, the general advice of wait for 24 hours should be the catch-all (for example, also applies to Azure Purview).  If apps/services other than the ones listed have shorter timelines, their documentation can include that.  For the Azure Information Protection unified labeling client, it gets particularly complicated because they have different timings depending on the component (eg Office apps vs the scanner).  The one place I've seen them all listed is in the Policy update row in the detailed comparisons table: https://docs.microsoft.com/azure/information-protection/rms-client/use-client#detailed-comparisons-for-the-azure-information-protection-clients  I'll look at adding a link to make this easier to find but I don't want to duplicate this information in case it changes and I'm not informed.

I have repeatedly asked if there is a way for customers to confirm whether replication is complete and haven't got a positive answer. I also asked if that PowerShell output is reliable for this purpose and the lack of confirmation leads me to conclude that it's not.  Not the answer you wanted to hear, but explains why this check isn't in the docs.

**Comment by cabailey** [comment]
I've added a note & link for the unified labeling client & confirmed with engineering that there is currently no customer-supported method to confirm policy distribution/update,  I recommend you use the MIP UserVoice request form for this: https://aka.ms/MIP/uservoice
