### ISSUE TITLE
Can minimum and maximum timing be clarified for "Delete-only after 1 day"?

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/microsoft-365-docs#5301]
In [Example 3: Delete-only after 1 day](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide#example-3-delete-only-after-1-day), it states that "a delete action after 1 day could take 16 days before the message is permanently deleted".  Can it be clarified how the 16 days is calculated?  It seems like it should be 15 days:  7 days max for retention process to move the message to the SubstrateHolds folder  + 1 day in the SubstrateHolds folder + 7 days max for retention process to permanently delete the message.  Is it because the "minimum of 1 day in the SubstrateHolds folder" is 24 to 48 hours?

Also, can the minimum time be listed before the message is permanently deleted?  Would it be 3 days/72 hours (1 day minimum for retention process to move the message to the SubstrateHolds folder  + 1 day minimum in the SubstrateHolds folder + 1 day minimum for retention process to permanently delete the message)?  It would also help to give more information about the retention process timer job(s), such as why it's 1-7 days instead of 0-7 days (i.e., why the 1 day delay) and whether it's run against each mailbox approximately every 7 days or if it's random. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
If it's helpful, here's an example with hours - we didn't add this to the documentation because it felt like too much information for most people:

Message is sent 4/13 9:15 am

Message is considered expired starting 4/14 12:00 am

The typical time frame is this happens between 4/14 and 4/21, let's say 4/21 8 pm - at this point the message is soft-deleted and goes into SubstrateHolds folder

The message will need to stay in SubstrateHolds folder for a day minimum, won't be eligible for permanent deletion until 4/22 12:00 am

The typical time frame to re-process this mailbox will be 4/22 - 4/29, let's say we process 4/29 at 10 pm, then that's when the message is permanently deleted and it's no longer eDiscoverable

**Comment by yogkumgit** [comment]
@VShrubowich Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
