### ISSUE TITLE
Presence of IP addresses means that they are the *only* IP addresses for listed FQDNs, right?

### ISSUE THREAD

**Issue by jjpb-github-work** [MicrosoftDocs/microsoft-365-docs#5331]
Something isn't made explicit that is extremely important to know: if, for a particular ID, FQDNs and IP addresses are specified, does that mean that the FQDNs are guaranteed to resolve to an IP address in the given list?

Here's what I mean.

For ID 1, there is a single FQDN:  outlook.office365.us .
There are man IP address blocks listed below it.    I think it's safe to assume that this means that outlook.office365.us will ALWAYS resolve to something in the group of IP addresses listed in the same cell, with the understanding that updates may be made.

However, note that for ID 5, there is the same, single FQDN (outlook.office365.us) and there are NO IP addresses listed at all.
Is it safe for me to guess that the IP address list in ID 1 is also guaranteed here?    That assumption seems reasonable, but it's never safe to assume.   It would seem best to either duplicate the IP address list here or put "same IP list as for ID 1" or something like that.

By contrast, ID 4 contains no IP addresses at all.   I believe this means that I have no way of knowing what the FQDNs in ID 4 will resolve to.  Thus, I cannot allow direct connectivity to these IP addresses via my firewall, and access to these endpoints will need to be provided by a web proxy or some other mechanism that uses names rather than IP addresses. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0043b9f3-d91c-569f-1efc-720e4162c5e7
* Version Independent ID: 0289deef-82e4-5f56-7258-ab574c8d0e70
* Content: [Office 365 U.S. Government GCC High endpoints - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@LauraWi Gentle reminder.

**Comment by kelleyvice-msft** [comment]
@jjpb-github-work, thanks for reaching out, and apologies for the delay. I'll take your points in order.

- When a URL is listed with IPs, the URL will always resolve to one of the listed IPs. And yes, listed IPs may change in future web service updates, which will be reflected here.
- In the case of ID 5 (the same URL as ID 1), since it is the same URL, it will resolve to the same IPs. The URL is duplicated in a separate row to show the specific ports for which traffic falls under the **Default** category rather than the **Optimize** category (which applies to the ports listed in ID 1).
- The URLs listed in ID 4 fall under the **Default** category and can therefore be routed through a web proxy with no critical performance impact. It's my understanding that this is true for any ID where only URLs are listed.

Please reply back if this does not answer your questions or if you need additional clarification. -Kelley
