### ISSUE TITLE
eDiscovery "Review" permission confusion

### ISSUE THREAD

**Issue by jianhsieh** [MicrosoftDocs/microsoft-365-docs#5422]
[Enter feedback here]

For document Assign eDiscovery permissions in the Microsoft 365 compliance center, the only mention about "Review" permission is to let users access review sets in "Advanced eDiscovery". Customer had the impression that they do not need "Review" for "Core" eDiscovery, therefore removed review. We need "Review" for eDiscovery without a doubt, but there is no document that states this, which confuses customer. Could we add this information that "Review" will be required for both Core and Advance somewhere? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94e0469-2c5c-2063-8c3e-7722ceb53577
* Version Independent ID: e99eb8aa-b3b7-8791-aba4-998e209694b5
* Content: [Assign eDiscovery permissions in the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/assign-ediscovery-permissions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/assign-ediscovery-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/assign-ediscovery-permissions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jianhsieh Thanks for reaching out. Engineering confirmed the the Review role is not used or does to provide access to Core eDiscovery cases. So the existing documentation is correct, in that Review role is only relevant for Advanced eDiscovery. Since you are internal MSFT support, I would suggest you reach to the eDiscovery escalation team with any more questions.
