### ISSUE TITLE
The client ID 170000000000570 is disabled

### ISSUE THREAD

**Issue by geektbee** [MicrosoftDocs/microsoft-365-docs#5740]
On Page: https://docs.microsoft.com/en-us/microsoft-365/lti/teams-classes-with-canvas?view=o365-worldwide

... there's a section labeled "Canvas Admin". Before Step 1, there's a Client ID given to us. Upon going through the motions to Step 4, an error message returns "The client ID 170000000000570 is disabled."

Also, when going through the steps, Step 1 seems to need an additional piece of the procedure. It ought to say something closer to "Admin settings > Apps > View App Configurations"

**Comment by msbemba** [comment]
@geektbee Thank you for your feedback. 

Before you can add the Teams LTI tool using the Client ID as an admin you need to go to the Developer Key listing in the main account, switch to the inherited keys, load all the keys and then enable the Teams one.

Otherwise, when adding the App you get a message about the Client ID being disabled.

We have added this to the document via PR  https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5765

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @geektbee Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
