### ISSUE TITLE
AzCopy commands outdated

### ISSUE THREAD

**Issue by dab-vie** [MicrosoftDocs/microsoft-365-docs#5817]
The command in the "Upload" section of this article is no longer correct. The use of "/Source:<path>" and "/Destination:"<path>" is no longer feasible. Instead, it's the following: 

**AzCopy.exe cp "<sourcepath>" "<destinationpath>" --recursive=true**  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@dab-vie Thank you for your feeback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5831

Once the author approves, the document will be live.

Thanks
Sri

**Comment by markjjo** [comment]
@dab-vie @msbemba @yogkumgit The PST Import tool supports only AzCopy v8. This is the version of azcopy that can be download via the link in the network upload workflow of the PST import tool. That's why we document the v8 syntax. You can use azcopy v10 to upload PST files, but documentation only supports v8.

For more info, see this issue: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1801
