### ISSUE TITLE
Large Case Functionality & Limits

### ISSUE THREAD

**Issue by Breaker119** [MicrosoftDocs/microsoft-365-docs#5843]
My apologies if I am misunderstanding the preview state of large-format cases. Based on my experience trying out the option, Indexing of custodians does not work (jobs never complete) and the review set option to export "Loose files and PSTs" is always greyed out.

If these are expected behaviors they should be added to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af746d87-b86d-ed50-8a0d-173d377b85d1
* Version Independent ID: 29c484b6-5c9b-5244-fc05-2cf5f5c8d76e
* Content: [Large cases in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-ediscovery-large-cases?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/advanced-ediscovery-large-cases.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/advanced-ediscovery-large-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Breaker119 Thanks for the heads up. I checked with engineering, and exporting PST files from large cases is not yet supported, but it will be in the near future. I will add that info to the article in a known issues section. The advanced indexing issue is not expected behavior. Would suggest that you contact MS Support if it continues to be stuck. They might ask for for the job ID of the indexing job.

**Comment by markjjo** [comment]
@Breaker119 I also just found out that advanced indexing isn't turned on/supported for large cases. So, the fact that indexing of custodians doesn't work/complete is expected behavior. Eventually, this will be turned on, but until then I will also add this info to the topic. Sorry for suggestion to contact support. I'll try to remember to follow up in this github when PST export and advanced indexing is supported in large cases.

**Comment by Breaker119** [comment]
Awesome! Thanks for the response. Not a huge deal and I didn't even realize Large Case format was preview when I chose it. I had more custodians than normal so I thought that would be safe. I ended up recreating the case several times and it worked with a normal case. Turns out I only had about 400GB of content.

Jason Heiser

________________________________

**Comment by markjjo** [comment]
@Breaker119 Thanks for understanding. PST export and advanced indexing will be eventually be supported when large case format is released to general availability. Other than the increased limits, one other reason to try or test the large case format preview is the new and imported HTML transcript for conversation threading for Teams chats (which is also in preview). Here's an overview to the Teams workflow using large case: https://docs.microsoft.com/en-us/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery?view=o365-worldwide
