### ISSUE TITLE
azcopy commands are incorrect

### ISSUE THREAD

**Issue by IanWatkinson** [MicrosoftDocs/microsoft-365-docs#5888]
The newer version of azcopy uses the following:

azcopy copy [source] [destination] [flags]

please include how to rate-limit: 
--cap-mbps=[int]

Thanks
Ian

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@IanWatkinson Thanks for feedback. Azcopy v8 is only supported version for PST Import because it is the version that can be downloaded from within the network upload workflow of the PST Import tool. You can use v10, but it's unsupported. Please see https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5817 for more info.
