### ISSUE TITLE
Mailbox Intelligence options not clearly documented

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/microsoft-365-docs#589]
What is the actual difference between these two options: "Enable mailbox intelligence" and "Enable mailbox intelligence based impersonation protection". The effect of enabling these is not clearly enough described in the documentation to be able to make an informed choice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#learn-about-atp-anti-phishing-policy-options)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@ArttuArstila - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@ArttuArstila  Thank you for your feedback. While the table shows general information on when to use some of the Anti-phishing Policies, I'll try to brief you on the two in particular that you are talking about.

1) Mailbox intelligence:- 
This feature uses machine learning to determine a user’s email patterns with their contacts. With this information, the AI can better distinguish between genuine and phishing emails.If any of their contacts are spoofed, ATP anti-phishing will inform you that you aren’t speaking to the person you think you are.

2)Mailbox intelligence-based impersonation protection:-
It’s a common spear-phishing technique to impersonate a JHi level employee or a board member with the goal of gaining information or money from someone who reports to them.

This pays special attention to these individuals and will intercept any email that looks like it could have been sent by them, but really hasn’t. This is achieved through machine learning models together with highly intelligent impersonation detection algorithms.

So the difference is that Mailbox intelligence catches Spoofing and the Mailbox intelligence-based impersonation protection catches accounts that are impersonated.

I have made a change in the document so that we have clarity on mailbox intelligence. The changes can be tracked via PR https://github.com/MicrosoftDocs/microsoft-365-docs/pull/624. Once again thank you for the feedback and making our Docs look better.

Hope this helps!

Thanks
Sri

**Comment by danmyhre** [comment]
Can you please add some examples?  Do you mean to say that the "mailbox intelligence based impersonation" is only applied to people you have added to the "Add users to protect" tab of the policy editor?

**Comment by msbemba** [comment]
@danmyhre That is correct. This applies only to the users added to the "Add users to the protect Tab:.

![anti-phishing impersonation policy settings](https://user-images.githubusercontent.com/45987684/67637075-545e2f00-f8ad-11e9-9a6d-c742c2c6de0c.png)

You can also find more information on our community doc

https://techcommunity.microsoft.com/t5/Security-Privacy-and-Compliance/Enhancements-to-the-Office-365-ATP-admin-experience/ba-p/218569

Hope this helps!

Thanks
Sri

**Comment by ArttuArstila** [comment]
Thanks for the comments! I checked that PR and it is bit more understandable now. What I would still like to see is what @danmyhre commented - what is the exact relation of these two settings: "users to protect" vs. "mailbox intelligence based impersonation"

**Comment by msbemba** [comment]
@ArttuArstila Thank you for the response. I think the two settings have clarity now.

Thanks
Sri

**Comment by MisterBendo** [comment]
Our team had similar questions and concerns.  After opening a ticket with Microsoft support I was able to ascertain the following information.  Enabling the Intelligent Mailbox Protection will identify three categories of impersonation and change the CAT stamp in the mailbox header from CAT:NONE to CAT:DIMP (domain impersonation,) CAT:GIMP (graphic impersonation,) or CAT:UIMP (user impersonation.)
There may be other categories.  These categories can not be capture at the transport rule level since categorization stamping occurs after transport rules are processed.
