### ISSUE TITLE
Error after copying links to consent URI

### ISSUE THREAD

**Issue by Jeberoni** [MicrosoftDocs/microsoft-365-docs#5912]
Hi Team,

I have the exact same issue the following as the following that was raised previously -

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3836#issue-779128086

The script crashes at with the "Send-AdminConsentUri : Could not retrieve a token for invitation manager api call" error and appears to be failing when attempting to send the email
Removing the -UseAppAndCertGeneratedForSendingInvitation switch prompts for credentials, which also fails after authentication

Based on the aforementioned issue that was raised, I can't see specifically how it was resolved. I have MFA setup on the the admin account being used

**Comment by msbemba** [comment]
@Jeberoni Thank you for your feedback. The previous issue reported was due to a connection to the Azure ad before the script was run. 

We are here to take your feedback and improve docs.microsoft.com, but we do not have the option to provide you support. If you still have problems I have to suggest you that open a support ticket.
If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in the future.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Jeberoni 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
