### ISSUE TITLE
Default Label Policy - Existing Documents and Office Online

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#5968]
Documentation states that when using the AIP Unified Labeling Client, that existing documents will receive a default sensitivity label (if configured). While this is true of Office Client Applications, this does not work with Office Online. This may cause confusion to some admins, not understanding that AIP does not influence Office Online apps.

![image](https://user-images.githubusercontent.com/80067837/129103894-d169aaed-b5cf-4bb4-8140-8bc3c825eb85.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Learn about sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide#what-label-policies-can-do)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@SeanTGeoghegan  Yes, we do see some people confused about which platforms the AIP client supports - I suspect AIP customers who equate that client with sensitivity labels.  For example, references to "the AIP client for Mac" is actually quite common (there has never been an AIP client for Mac!)  This is a tricky one for docs, because even if we said "the AIP client for Windows", that could be incorrectly interpreted as there are AIP clients for other platforms.  At the beginning of the article that has instructions to enable sensitivity labels for Office for the web, we clarify up front that sensitivity labels are built-in: "Enable built-in labeling for supported Office files in SharePoint and OneDrive so that users can apply your sensitivity labels in Office for the web."

**Comment by yogkumgit** [comment]
@SeanTGeoghegan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
