### ISSUE TITLE
Doc clarification

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/microsoft-365-docs#5974]
Hi,

this important information: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5960
should be stated out in the docs somewhere. E.g. in an Info Box.

Regards 
Jakob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Yes, we already have this called out: "Because of the first principle of retention, permanent deletion is always suspended if the same item must be retained because of another retention policy, or it is under eDiscovery holds for legal or investigative reasons."

In articles that explain how retention policies work, it's off topic to explain how other features work - what's included in a Litigation Hold (older feature than eDiscovery holds).  This would be good information to know even if not using retention policies.  I suggest you open a GitHub Issue for the relevant articles, such as the PowerShell page you referenced that enables it for a mailbox.
