### ISSUE TITLE
Missing a lot of details

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#608]
This page needs more details on specifically what this will support.  For example: accessing web apps?  accessing ntfs file shares?  accessing other resources secured with AD?

How does authentication work?  What sort of credential prompts will the user get?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00ba9775-1242-af4d-a9c0-8979cc5d57dc
* Version Independent ID: 5063400b-fe96-79f4-e37f-6c89e26ee9d0
* Content: [Access on-premises resources from an Azure AD-joined device in Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/access-resources)
* Content Source: [microsoft-365/business/access-resources.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/access-resources.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by j0rt3g4** [comment]
Hello @danmyhre 
On the text:
"resources like Line Of Business (LOB) apps, file shares, and printers" those are the resources they can get access to.

**How does authentication work? What sort of credential prompts will the user get?**
Authentication works on cloud since it's synchronized on-premises and O365 over AD Connect, if a user is on an Azure Domain Joined computer trying to access a shared file on the on-premises server, it will log in to the cloud and the token will be passed by to access the resources, and it's valid for cloud services as well as local services.

**Comment by danmyhre** [comment]
So it is only for modern (OAuth) based on-premises applications?  So almost nothing?  File shares, LOB apps, printers, etc all rely on Active Directory for authentication.

**Comment by j0rt3g4** [comment]
Hi @danmyhre @mypil 
In my opinion, is a lot, but if you think that is something missing please go ahead and open a UserVoice request to add more features at  https://office365.uservoice.com/

**Comment by danmyhre** [comment]
I think this fact should be added to the top as a highlighted note - that this is only for OAuth and NTLM and Kerberos is not supported.  Thanks!

**Comment by j0rt3g4** [comment]
Updated on PR #785

**Comment by mypil** [comment]
@danmyhre - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/31331fb5001a58f5823c675451457b733cbcb133.  


Thank you for your contribution to make the docs better! Much appreciated!
