### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/microsoft-365-docs#6181]
according to this, also business Standard users have the right to use bookings:
https://docs.microsoft.com/en-us/microsoftteams/bookings-app-admin#prerequisites-for-using-the-bookings-app-in-teams

the current article only lists Business Premium. 

Not to mention that the licensing tables that we can download from here:
https://transform.microsoft.com/modernwork/download?assetname=assets%2FModern_Work_Licensing_Deck.pptx&download=1&download=1
do not actually list Firstline SKU-s as including Bookings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb53eb7-85a1-6aa0-dfd1-e2b54586008a
* Version Independent ID: 5532470a-a47d-e3bd-4e74-02b2c822cae1
* Content: [Microsoft Bookings](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-overview?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/bookings/bookings-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-overview.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@teomonda Thank you for your feedback. Both the documents now includes Business standard. The reviewed the license table that is available at https://transform.microsoft.com/modernwork/download?assetname=assets%2FModern_Work_Licensing_Deck.pptx&download=1&download=1 and this is not a part of our Document repository. So I have left feedback on that page so that the concerned team can update.

Hope this helps!

@yogkumgit There are no changes required in this document at the moment.

Thanks
Sri

**Comment by teomonda** [comment]
thank you for the quick intervention!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @teomonda Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
