### ISSUE TITLE
I need to change country of the organization

### ISSUE THREAD

**Issue by mendrinos** [MicrosoftDocs/microsoft-365-docs#6196]
It's unbelievable I cannot change country.
My organization shutted down in the UK many years ago, and now I want to use a new country as the billing address and **I am not allowed.**

There should be a streight forward way to change country on your account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecea09f5-957a-4674-0449-def4a1de21a4
* Version Independent ID: 53c2bbeb-daf8-56cd-f821-aa6e7e2fee92
* Content: [Change your organization's address, technical contact, and more - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/change-address-contact-and-more?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/change-address-contact-and-more.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/change-address-contact-and-more.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@mendrinos Thank you for your feedback. You are right, You can't change the country or region for your subscription. That's because the country or region where your organization is headquartered determines which services are available to you, the taxes and billing currency, and the location of the data center. 

To change your organization's country in  M365, sign up for a new account, choose the desired country or region, and purchase a new subscription. After which the support team can help you in migrating data to the new subscription.

Hope this helps!

Thanks
Sri
