### ISSUE TITLE
This doc seems to be missing a section for "Folder Protection"

### ISSUE THREAD

**Issue by zebulonsmith** [MicrosoftDocs/microsoft-365-docs#6354]
When configuring ASR from Intune, one of the last items available is "Enable Folder Protection." What enabling this does is not made clear anywhere, from what I can see. 

The 'Learn More' link from the Intune configuration page takes us to the Policy CSP page for the same, but that only tells us how to turn it on, not what it actually does. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c664e229-9294-6515-f586-12a1f0348308
* Version Independent ID: a97f107c-fd36-143a-ea68-ee2248f11362
* Content: [Attack surface reduction rules](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules?view=o365-worldwide#per-rule-descriptions)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@zebulonsmith Thank you for your feedback. 
 You can find information about Enable folder protection from SR Profile settings page -https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-asr-profile-settings

CSP: EnableControlledFolderAccess

Not configured (default) - This setting returns to its default, which is no read or writes are blocked.
Enable - For untrusted apps, Defender blocks attempts to modify or delete files in protected folders, or write to disk sectors. Defender automatically determines which applications can be trusted. Alternatively, you can define your own list of trusted applications.
Audit mode - Windows events are raised when untrusted applications access controlled folders, but no blocks are enforced.
Block disk modification - Only attempts to write to disk sectors are blocked.
Audit disk modification - Windows events are raised instead of blocking attempts to write to disk sectors.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @zebulonsmith Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
