### ISSUE TITLE
Forwarding Report is no longer working and is missing from dashboard

### ISSUE THREAD

**Issue by bcihak** [MicrosoftDocs/microsoft-365-docs#6393]
The Forwarding Report is missing from Reports->Dashboards.  Also the direct URL (https://protection.office.com/reportv2?id=MailFlowForwarding) no longer works.  Has this been relocated in M365, if so where?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041a2c32-e0b9-77e9-766c-3b4f5b07ff3a
* Version Independent ID: 597960ea-f734-09c7-eea8-aab24a06c9f8
* Content: [View mail flow reports in the Reports dashboard - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-mail-flow-reports?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/view-mail-flow-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-mail-flow-reports.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bcihak, the topic in question says this:

## Forwarding report

> [!NOTE]
> The **Forwarding report** is now available in the EAC. For more information, see [Auto forwarded messages report in the new EAC](https://docs.microsoft.com/exchange/monitoring/mail-flow-reports/mfr-auto-forwarded-messages-report).

The main reporting page in the EAC is <https://admin.exchange.microsoft.com/#/reports/mailflowreportsmain>.

The direct Auto forwarded messages report is <https://admin.exchange.microsoft.com/#/reports/autoforwardedmessages>

**Comment by bcihak** [comment]
Thank you for the updated link!  When will the online docs get updated?

**Comment by chrisda** [comment]
@bcihak, I see. My mistake. The information I provided was from this topic <https://docs.microsoft.com/microsoft-365/security/office-365-security/view-email-security-reports>, which was converted to the Microsoft 365 Defender portal. The topic in question for this issue was not converted from the Security & Compliance Center (SCC) on purpose.

I thought the reports in the SCC would remain static until the Security & Compliance Center eventually goes away, at which point we would take down the whole topic. But, it looks like they did me dirty and removed some reports, including the Forwarding Reporting. I updated the topic with redirect information for any reports that no longer exist.

Thanks for the feedback.

Closing
