### ISSUE TITLE
Bypass ETRs (SCL -1) and Enhanced Filtering for Connectors versus Secure by Default

### ISSUE THREAD

**Issue by rodsmsft** [MicrosoftDocs/microsoft-365-docs#6427]
I believe it would be clearer to explicitly call out the effects of Exchange Transport Rules (ETRs) set with SCL -1 and Enhanced Filter for Connectors versus Secure by Default (which configurations are honored), when the MX is **not** pointing to EOP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472b3a0c-7ad8-8245-9b57-29431490370b
* Version Independent ID: 8671f04a-b7b3-402c-1e65-59a52c1cdaf5
* Content: [Secure by default in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-by-default?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/secure-by-default.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/secure-by-default.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@rodsmsft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6547
Once the author approves, the change will be live.

Thanks
Sri

**Comment by chrisda** [comment]
@rodsmsft, fundamentally, "secure by default" means "regardless of configured overrides, high confidence phishing email is now always handled by the action for high confidence phishing verdict in anti-spam policies (Quarantine message or Redirect message to email address; Move message to Junk Email folder is no longer available)."

The "always quarantine malware" behavior is not new; you've never been able to bypass malware filtering (overrides never worked on malware messages). Malware has always been quarantined; the only thing you could control is whether recipients and/or senders were notified.

So, if your MX record points somewhere else, you would almost certainly have the SCL=-1 mail flow rule (transport rule); otherwise, all messages would be double-scanned.  You should have Enhanced Filtering for Connector for better reporting and spoof detection, but it's not required.

Even in that configuration, malware is always quarantined, and high confidence phishing messages are either quarantined or redirected to a specified recipient (depending on how the first anti-spam policy that the recipient is defined in is configured).

Does this make sense?
