### ISSUE TITLE
Update in ip subnet requested

### ISSUE THREAD

**Issue by nitin-gan** [MicrosoftDocs/microsoft-365-docs#6629]
It has been found that few IP Subnets are not added in this list for Teams device and MS 365 updates which is required for error-free working of Teams meeting rooms and MS 365 feature and services updates.

Please add them to this list so that other EDL providers can update their list as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
@nitin-gan, thanks for reaching out. Can you confirm whether this is still a problem? There have been several updates to the endpoints web service since this issue was opened. If you are still having problems, please let me know and provide some examples of missing subnets, and I will reopen the issue and investigate.
