### ISSUE TITLE
In-Place Archive Doc Request

### ISSUE THREAD

**Issue by bcihak** [MicrosoftDocs/microsoft-365-docs#6754]
[Enter feedback here]
Can a section be added to clearly define what Clients and/or Protocols can access an In-place archive.  Would also like to know which Client/Protocols would allow access or even syncing of the In-Place Archive to occur if at all. 

Also what are the security ramifications or risk to data if un an unauthorized user were to access an M365 account that had an In-Place Archive enabled to that archived data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
* Version Independent ID: 3b513017-641c-38ae-3938-03a9ee3a6923
* Content: [Enable archive mailboxes in the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-archive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by bcihak** [comment]
duplicate request

**Comment by bcihak** [comment]
Any update on this request

**Comment by cabailey** [comment]
We had a change of writer for this article, so I'm only just seeing this GitHub Issue.  We have an open item to clarify client support, which will capture some of this request, so closing it.  

There is no syncing for archive mailboxes and you can't access them via ActiveSync - so would have to be via MAPI/HTTP(S), but this detail would be covered with clarified client support.  The security risks for an archive mailbox are no different than a standard mailbox stored in Exchange Online, except probably lower because they remain online & can't be downloaded.
