### ISSUE TITLE
Missing URLs

### ISSUE THREAD

**Issue by adettenb** [MicrosoftDocs/microsoft-365-docs#6800]
I noticed a couple URLs that I see using my personal Microsoft account were missing.
For example:
* onedrive.live.com
* outlook.live.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
@adettenb, thanks for reaching out. I believe this is by design, as the endpoints referenced in this topic are specific to M365 for enterprises for whom access to personal live.com features are likely not part of their network considerations. Certainly enterprises can choose to add these endpoints to their allow lists if they choose, but either way it will not impact their enterprise M365 features, which is the scope of the content in question.

Thank you,

Kelley
