### ISSUE TITLE
Compliance DLP Template - Inconsistent High Volume

### ISSUE THREAD

**Issue by dltmurphy** [MicrosoftDocs/microsoft-365-docs#6820]
After my PR (#6725) was rejected that fixed the `Min` and `Max` count (assuming so MS can keep the credit of fixing?), the GDPR template is now inconsistent with the rest of the page. All of the `High Volume` templates have `Max count any` except for GDPR which has `Max count 500`

**Comment by yogkumgit** [comment]
@chrfox please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
Hi @dltmurphy
The max count of 500 is what is in the UI. I tried to edit your PR to make that change, but I did not have permissions to do so. The only option was to work your feedback in through a different PR so that everyone could benefit from it. I am grateful that you pointed this issue out and I was not trying to take credit away from you.
I'll look into all the max counts in the templates in the UI and edit the content accordingly. Thanks, chrfox@microsoft.com

**Comment by dltmurphy** [comment]
Hi @chrfox 

`any` is a catch all which allows any max limit to be reached. Changing from `any` to `500` will mean if the volume limit is ever increased beyond 500, administrators who explicitly set `500` rather than `any` will have to update their policies to capture the higher volume alerts. It will increase the workload of administrators for something that can be avoided by keeping it as I had it in my PR at `any`

In terms of needing to do your own PR as you didn't have permissions to mine, you just had to ask and engage with me so we could have this conversation and either merged my PR or I would have ticked the box that gives you the permission to go the `500` route, instead of doing what you have done again by closing it and moving on.

![image](https://user-images.githubusercontent.com/6512845/140997434-b3137f50-f5ba-47d1-ac46-c6ec970febf1.png)
