### ISSUE TITLE
Can you force the timer job to run?

### ISSUE THREAD

**Issue by rcmpgi** [MicrosoftDocs/microsoft-365-docs#6833]
For example, can you use Start-ManagedFolderAssistant to make items in SubstrateHolds get purged sooner than 7 days?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@rcmpgi  After asking about this, I was told we don't recommend doing this. The system is already scheduled to run the assistant daily and when it takes more than a day, it's because more important operations (like sending and receiving email) are working on the mailbox or it could be busy. Manually running the assistant to run will cause the system to try to override this and could overwhelm the mailbox causing the assistant (and everything else) to take longer. Our recommendation is to let the system manage it, and manually run this command in specific one-off cases - for example, if asked to do so by Support.

**Comment by rcmpgi** [comment]
Ok thanks for the info. Was just wondering how long it'd take to remove >6000 items from a SubstrateHolds folder now that there's no retention policy assigned to the user. There's zero holds of any sort and yet 48hrs later not a single item has been deleted. Maybe time for another support ticket?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

Robin Clive-Matthews
IT Manager
PROTECTION GROUP INTERNATIONAL
Unit 40
|Equinox South|Great Park Road|Bristol|BS32 4QL
T: +441174573590
E: ***@***.***
W: www.pgitl.com
This email is only intended only for the addressee(s) named above. As the email may contain confidential or privileged information, if you are not the intended recipient any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. Any opinions or statements contained within this email are expressly those of the individual and not necessarily PGI. We cannot accept liability for any loss or damage caused by software viruses that may be contained herein. PGI - Protection Group International Limited is a company incorporated in England and Wales with company number 07967865 and registered at 13 -14 Angel Gate, London, EC1V 2PT.

**Comment by cabailey** [comment]
@rcmpgi  We can't offer technical support through this channel, so yes, I recommend you open a support ticket so they can look into this specific case for you.  Closing.
