### ISSUE TITLE
Requesting info for port and protocol

### ISSUE THREAD

**Issue by npatellumeta** [MicrosoftDocs/microsoft-365-docs#6847]
For any CVE info that we get from this end point, how do we get port and protocol information related to CVEs? Do we not get any network vulnerabilities from this end point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fde81ac4-accc-9a93-90fb-62bbe9a66326
* Version Independent ID: 130d79fe-73d0-14f6-3b44-e9cbae763837
* Content: [Vulnerability methods and properties](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/vulnerability?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/vulnerability.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/vulnerability.md)
* Product: **m365-security**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by yogkumgit** [comment]
@DulceMontemayor Please help us in resolving this issue. Thanks

**Comment by DulceMontemayor** [comment]
@yogkumgit, i'll ask some of the PMs here to provide the reply, Thanks!

**Comment by brownivy** [comment]
Hi @DulceMontemayor - this request is in support of a mutual customer of ours. Is there any chance we could connect with someone familiar with the data available from Defender Endpoint? If network port and protocol data is not available, that would be incredibly helpful to know so that we can go back and work with our customer on alternatives. Thank you!

**Comment by DulceMontemayor** [comment]
Hi all, 

Apologies for the delay as our SMEs and PMs were busy. Here's the reply in a nutshell:

"Currently, TVM only checks for vulnerable installed applications and doesn’t map CVEs into open ports – i.e. If a CVE can be exploited over the network, we can only say if the machine is vulnerable but cannot infer if it’s in risk due to the port being open."

Thanks!
Dulce

**Comment by npatellumeta** [comment]
No problem at all. Thanks for your response. I do understand how it can become challenging to map CVEs into open ports for application vulnerabilities. But how about network vulnerabilities? Does TVM not support network vulnerabilities?

**Comment by yogkumgit** [comment]
@DulceMontemayor , please answer,

**Comment by DulceMontemayor** [comment]
Following up again with SMEs @yogkumgit . Sinead will be responding soon as the SMEs respond. For any TVM-related questions, moving forward, please tag and email  Sinead O'Sullivan (Sinead.OSullivan@microsoft.com) who works with TVM SMEs and stakeholders on documentation. Thank you!

**Comment by siosulli** [comment]
hi @yogkumgit, we received an update from the PM and he has confirmed that yes we do support the detection of network vulnerabilities on Devices (e.g. Windows/Linux/Mac/Mobile) and on network devices (e.g. Router, Switches, FireWall, etc.).

if you need anything else, let me know. 

cc: @DulceMontemayor

**Comment by npatellumeta** [comment]
Thanks for your response. So what's the API end point to retrieve network vulnerabilities (containing port and protocol) and where in the documentation can i find it?

**Comment by DulceMontemayor** [comment]
We have this section in the documentation, does this help: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-devices?view=o365-worldwide
