### ISSUE TITLE
useless

### ISSUE THREAD

**Issue by Miracle-bot-creator** [MicrosoftDocs/microsoft-365-docs#6886]
[Enter feedback here]

this can't work if you have 2FA and lost it
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9fe16db-f502-6d93-8e0a-d4b892064416
* Version Independent ID: 1ecf27fd-ed6c-f387-b56a-80673117e480
* Content: [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/get-help-support.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please help us in resolving this issue. Thanks

**Comment by cmcatee-MSFT** [comment]
@Miracle-bot-creator The article in question has since been moved and updated. If you're not able to log in due to having lost your 2FA credentials, you can use the numbers listed in the [Phone support](https://docs.microsoft.com/microsoft-365/admin/get-help-support?view=o365-worldwide) section of the article.
