### ISSUE TITLE
the PS to apply label to SPO site used wrong cmdlet

### ISSUE THREAD

**Issue by frankchen76** [MicrosoftDocs/microsoft-365-docs#6945]
Hi for code sample below to apply label to all SPO sites, we should use Set-SPOSite instead of Set-SPOTenant. 
$sites | ForEach-Object {**Set-SPOTenant** $_.url -SensitivityLabel $Id}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#use-powershell-to-apply-a-sensitivity-label-to-multiple-sites)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@frankchen76  Why did you conclude that we should use Set-SPOSite instead of Set-SPOTenant - did you try as documented and it didn't work?  See similarly posted issue https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4611 and the response from the PM owner.

**Comment by frankchen76** [comment]
that's interesting. When I looked at the PS, the script was trying to enumerate all site collections. $sites | ForEach-Object {Set-SPOTenant $_.url -SensitivityLabel $Id}. It looks like we need to use **Set-SPOSite** $.url -SensitivityLabel $Id to apply the label for each site instead of Set-SPOTenant. When I checked [Set-SPOTenant](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps) which doesn't have -SensitivityLabel parameter. -SensitivityLabel is only available for [Set-SPOSite](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps). you know what, I actually run Set-SPOTenant and Set-SPOSite with -SensitivityLabel, both cmdlets actually worked. :-) which is very interesting. If Set-SPOSite and Set-SPOTenant both can do the same thing, I believe Set-SPOSite would make more sense. If we don't add additional description there, people will ask the same questions.

**Comment by cabailey** [comment]
@frankchen76  We document "by design" and after it's tested/confirmed by engineering. What we document has support implications. If you can't get the documented command with Set-SPOTenant to work, you're guaranteed support from Microsoft - they will investigate and help you get it working, or report a bug to engineering to fix. If you use Set-SPOSite instead for this single command to apply a sensitivity label to multiple sites and it doesn't work, the first thing a Microsoft support engineer will ask you to do is try the command as documented. But if it works for you, feel free to use it. I have passed on your feedback to engineering but won't change the documentation until I have confirmation from them that Set-SPOSite as an alternative for this specific scenario also works and will be supported.

**Comment by frankchen76** [comment]
@cabailey, thank you so much for your note. I'll close this issue and info my customer to use Set-SPOTenant to follow the document.
