### ISSUE TITLE
"Microsoft Rule Package." unable to export 

### ISSUE THREAD

**Issue by mezzofix** [MicrosoftDocs/microsoft-365-docs#700]
After creating new rule packages I'm unable to export the built-in labeled   "Microsoft Rule Package."

```
PS C:\Users\xxxxx> Get-DlpSensitiveInformationTypeRulePackage

Invariant Name         Localized Name         Publisher             Encrypted Exportable
--------------         --------------         ---------             --------- ----------
Microsoft Rule Package Microsoft Rule Package Microsoft Corporation False     True
AdamCustomRulePack2    AdamCustomRulePack2    Adam                  False     True
Adam CustomRulePack    Adam CustomRulePack    Adam                  False     True
```

```
> > PS C:\Users\xxxxxx> $ruleCollections = Get-DlpSensitiveInformationTypeRulePackage -Identity "Microsoft Rule Package"
> > The operation couldn't be performed because object 'Microsoft Rule Package' couldn't be found on 'FfoConfigurationSession'.
> >     + CategoryInfo          : NotSpecified: (:) [Get-DlpSensitiv...TypeRulePackage], ManagementObjectNotFoundException
> >     + FullyQualifiedErrorId : [Server=BN3NAM04WS014,RequestId=5f5e486b-041f-4d5a-984a-88458d3e497f,TimeStamp=11/7/2019 2:08:05 PM] [FailureCategory=Cmdlet-ManagementObjectNotFoundException] C0E6F8D4,Microsoft.Office.CompliancePolicy.Tasks.GetDlpSensitiveInformationType
> >    RulePackage
> >     + PSComputerName        : nam04b.ps.compliance.protection.outlook.com
> 
```
**EDIT** I've used the same **Publisher Id** in the customer rule packs as the one in the built-in XML since it was not mentioned to generate a new GUID for it as well https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell Might this be the issue? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1391cf1-588f-a4a9-8692-8c07cf1e459a
* Version Independent ID: d57337a5-d0f3-de26-2259-6b7fa7613d05
* Content: [Customize a built-in sensitive information type](https://docs.microsoft.com/en-us/microsoft-365/compliance/customize-a-built-in-sensitive-information-type)
* Content Source: [microsoft-365/compliance/customize-a-built-in-sensitive-information-type.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customize-a-built-in-sensitive-information-type.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@mezzofix - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mezzofix** [comment]
Why has this been closed ?!

**Comment by mypil** [comment]
@mezzofix - Please understand that this site is a product documentation site and not a support nor a feature request site.  As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

Is there something within this article that you suggest to be added or edited? If yes, please share the appropriate text and where it should be placed, so a Pull Request can be created to get it added.

Otherwise, for technical queries or troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a service ticket. Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

For user feedback on product feature requests, you can submit via **[User Voice](https://office365.uservoice.com/)**. I know the product teams are always looking for user feedback on how to make Office 365 better. You might find others have made a similar request that you can add to, or you can open a new one.

I hope this gets you pointed in the right direction. If you do find that it is a documentation error though, feel free to comment back and we'll gladly look into fixing it.  

Thank you.
