### ISSUE TITLE
What an utter joke MS is!!!

### ISSUE THREAD

**Issue by richardbranson** [MicrosoftDocs/microsoft-365-docs#7026]
So your admin has to change / check about 20 different things in 10 different places just to allow users outside an organisation to chat. Seriously MS employ some user experience people!!! FFS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147fb47a-99b2-f8ef-9ca6-35696d49c3fb
* Version Independent ID: b2f1b521-f231-48c2-b61f-f71bf9248d1c
* Content: [Collaborate with guests in a team](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-as-team?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-as-team.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-as-team.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@richardbranson Thank you for your feedback. Since Microsoft Teams is integrated with Exchange and SharePoint these changes will need to be made as mentioned in the document. I understand your concern about making these changes in multiple places, I'd recommend you leave feedback to our product group via the main feedback portal -https://feedbackportal.microsoft.com

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @richardbranson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
