### ISSUE TITLE
Report button greyed out.

### ISSUE THREAD

**Issue by lemondave** [MicrosoftDocs/microsoft-365-docs#7031]
[Enter feedback here]

I've gone through the steps in this document and my users can now see the Add-ins in Outlook (latest O365 version, 2110, Build 14527.20276).  However, when they attempt to report a message as either Phishing or Junk the report button is not available.
We have the correct licensing and both a coworker and I have run through the doc several times to see if I missed a step.  Still not working for us. 

![image](https://user-images.githubusercontent.com/42473068/144136569-cb96ae5f-0e39-4604-bda8-a1dbe453d216.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nkeibler81** [comment]
We are having this exact same issue

**Comment by msbemba** [comment]
@lemondave Thank you for your feedback. This is more of a support request and needs to be handled by our Support team. Please open a support ticket via the need help section on the admin center.

Thanks
Sri

**Comment by lemondave** [comment]
I already have. They seem stumped. As there are two of us reporting the
issue, it would be nice to have a troubleshooting section added.

**Comment by msbemba** [comment]
@lemondave Thank you for the response. I can confirm that the steps are accurate, so I'd have them report this as a bug to the product group or escalate within the team to provide a resolution. After the support team resolves, if there are changes that you had to make, please let us know so that can be documented.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lemondave Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Wazza22** [comment]
Morning - I am experiencing the same issue for myself and 2 other colleagues. I have raised the query with support too who are unable to find an answer. I have M365E5 licences. We experience the same issue when using Outlook client and Outlook Web.

**Comment by lemondave** [comment]
Support came back with steps that contradict the steps in this document.  They asked us to verify the ReportJunkEmailEnabled setting in our OwaMailboxPolicy and set it to True.  The steps in the documentation call for changing this setting to False.  Once I flipped this setting back to True, the problem went away.  


From Support:
To continue troubleshooting this issue, please connect to Exchange Online PowerShell, run the cmdlet below to locate the relevant policy:
Get-OwaMailboxPolicy | Format-Table Name,ReportJunkEmailEnabled

Check if the policy is set to false and set it to through by running the cmdlet below:
Set-OwaMailboxPolicy -Identity "OwaMailboxPolicy-Default" -ReportJunkEmailEnabled $True

**Comment by lemondave** [comment]
> @msbemba Thank you very much for the contribution and sharing this explanation. @lemondave Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

Feels odd that this was closed before waiting to hear the outcome of my open support ticket.

**Comment by nkeibler81** [comment]
Thanks @lemondave - this worked for me too. Punished for following the documentation, why am I not surprised?

**Comment by larryb821** [comment]
@lemondave thank you. your solution worked for me too!

**Comment by csabaoszkar85** [comment]
Hi guys,
I face the same issue, and I followed all of your instructions pinned over here.
First off, to recap, I run an on-prem Exchange server, where I wasn't able to add the Phishing button from MS Store, so created an XML file and uploaded that one. It seems to work fine except the part that the report button is greyed out in Outlook (both in the client ver. 2311 and also in the OWA). So I ran the above-mentioned PowerShell command in Exchange Management Shell on the server to check for the junk email setting and it is set on $True. So, not sure if having an on-prem Exchange would cause this issue or some of the implemented policies (since I started here I have found a lot of "funny" policies implemented, but if that's the wish of the management, my hands are tied).
Any further help will be appreciated.
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/153727847/37977e8d-211a-4ee6-a58f-a24c277f0fab)
