### ISSUE TITLE
Comparison Table Conflicts with Blog Announcement

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/microsoft-365-docs#7235]
The blog announcement stated that Defender for Business was included in the Business Premium SKU
"Included as part of Microsoft 365 Business Premium, our comprehensive security and productivity solution that brings together Microsoft Teams and Office 365 with the essential security tools for small- and medium-sized businesses"
https://techcommunity.microsoft.com/t5/small-and-medium-business-blog/introducing-microsoft-defender-for-business/ba-p/2898701

However, the comparison table in this article makes it appear that Business Premium does not include these features like EDR. This contradicts the blog article so we are seeking clarification on the intent of Microsoft: is EDR going to be included in Business Premium or not? If not, please correct the Blog article, otherwise if so, please correct this documentation.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 587ea70a-04b9-bdc8-f774-419607a07c47
* Version Independent ID: 587ea70a-04b9-bdc8-f774-419607a07c47
* Content: [Compare Microsoft Defender for Business to other Microsoft 365 plans](https://docs.microsoft.com/en-us/microsoft-365/security/defender-business/compare-mdb-m365-plans?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/compare-mdb-m365-plans.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/compare-mdb-m365-plans.md)
* Product: **m365-security**
* Technology: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@itguysocal Thank you for your feedback. This article compares security features and capabilities in Defender for Business to Microsoft 365 Business Premium while Defender for Business is in preview. When Defender for Business becomes generally available, it will be included in Microsoft 365 Business Premium (which should have been mentioned in the blog). 

Since we don't have access to the blog and only control the documents, I'll pass this feedback to the author to take it forward.

For now, there are no changes needed in the document 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @itguysocal Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
