### ISSUE TITLE
Exporting RMS protected messages is no longer supported

### ISSUE THREAD

**Issue by airmnichols** [MicrosoftDocs/microsoft-365-docs#7277]
This documentation states that exporting RMS protected messages is supported and messages will be decrypted as a part of the export process, however it appears that is not the case. 

I was unable to export RMS protected (Encrypted) messages, support stated that this is not supported. 
RMS protected messages are not discoverable in eDiscovery, therefore they can't be exported. 

Reference Office 365 support case #28805669

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38718be-6244-3988-7851-7c8c5625dd9f
* Version Independent ID: 4581a9e4-b838-c1a9-93a8-d52630128195
* Content: [Decryption in eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery-decryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-decryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-decryption.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@mikenri Thank you for your feedback. I'm currently testing and will work with the author to check if things have changed.

Thanks
Sri

**Comment by markjjo** [comment]
@mikenri Is your issue related to AIP Client encrypted documents on a local computer that were then uploaded to SharePoint Online or OneDrive? (I am unable to access the support case that you referenced). If so, then yes, engineering confirmed AIP Client encrypted docs are not supported for eDiscovery decryption.  Only docs encrypted by the SPO/OD service (via sensitivity labels) are supported. We are working on updating the documentation with this info. Adding @msbemba for visibility.

**Comment by mikenri** [comment]
The situation was my organization acquired another organization that was already an Office 365 customer. 
The acquired organization had encrypted some E-mail using Office 365 Message Encryption. 
We migrated all the non-encrypted mail to new mailboxes in our tenant. 

Our goal was to export a decrypted copy of the encrypted E-mail messages for future reference if needed. 

My understanding is that Office 365 Message Encryption is built on RMS. 

This documentation seems to indicate you should be able to export them:  https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery-decryption?view=o365-worldwide#decrypting-rms-protected-email-messages-and-encrypted-file-attachments-using-content-search-or-core-ediscovery


But Office 365 support indicated it's not possible to export encrypted E-mail messages.

**Comment by markjjo** [comment]
@mikenri Thanks for response and sending the search query you're using. The documentation does state that OME encrypted items aren't supported. Not sure if that is relevant to your case or not. Curious if the export includes an Errors.csv or UnindexedItems.csv report provides any info about docs not exported? Also, is there a link to your support case that you can send me? That would be helpful when I follow up with engineering in terms of whether or not or how to update the documentation based on your scenario. Thanks.

**Comment by mikenri** [comment]
@markjjo 

The documentation states that OME encrypted emails with custom branding aren't supported. 
But in this case, custom branding was not applied. 

The export doesn't include an errors.csv or unindexeditems.csv
All it has is an Export Summary CSV and a trace.txt file. 

Link to support case:  

https://admin.microsoft.com/#/support/request?requestId=5ea6746c-4463-442c-83a0-fbd7aed47f3d

**Comment by markjjo** [comment]
Thanks @mikenri. Will look into this and follow up on this github issue.

**Comment by yogkumgit** [comment]
@markjjo Kindly update. Thanks

**Comment by KCCross** [comment]
Forwarding this one to Samson Chan.

**Comment by KCCross** [comment]
@samschan-ms - The ediscovery decryption content states that "Any rights-protected (RMS-protected) email messages included in the results of a Content search will be decrypted when you export them. Additionally, any file that's encrypted with a [Microsoft encryption technology](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption?view=o365-worldwide) and is attached to an email message that's included in the search results will be decrypted when it's exported." The documentation identifies this as default behavior. This is in direct contradiction to the statement here that indicates that OME encrypted mail is not supported by eDiscovery because it isn't unencrypted during export. Let's work this out.

**Comment by mikenri** [comment]
My experience was that I had an administrator account in Tenant A but any encrypted messages were not present in an eDiscovery export.

**Comment by samschan-ms** [comment]
@ninacchen can you comment on whether current behavior or documentation is correct, for exporting encrypted mail?

**Comment by ninacchen** [comment]
Export should decrypt content if the user has RMS decrypt role, did we confirm the encrypted item is in the result of the search first?

**Comment by yogkumgit** [comment]
@samschan-ms Please reply and resolve. Thanks

**Comment by samschan-ms** [comment]
@ninacchen - It sounds like tenant A has a bunch of encrypted mail and when the admin tries to export, it returns no result.  According to you, if the admin has export rights, then it should decrypt the mail.  I have also stated that if you replicated the mail from tenant A mailbox into tenant B mailbox, then eDiscvoery export would not work because the encryption originate from tenant A and tenant B would not be able to decrypt the mail.

@airmnichols  were you trying to export the email from the old tenant, or the new tenant?
