### ISSUE TITLE
Licensing requirements

### ISSUE THREAD

**Issue by LL-chill** [MicrosoftDocs/microsoft-365-docs#730]
Please be explicit about which licenses are eligible for retention (inactive mailboxes). Previously, In-Place Hold and Litigation Hold required Exchange Online Plan 2 or Online Archiving.

Please be explicit about the requirements for inactive mailboxes created by retention policies.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies](https://docs.microsoft.com/en-au/microsoft-365/compliance/retention-policies#more-information)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@LL-chill  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LauraWi** [comment]
Hi @LL-chill, the Service Descriptions are the authoritative centralized location for licensing information. We try to limit how much of that gets duplicated into topics because it is challenging to maintain it accurately. https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feature-availability-across-exchange-online-standalone-plans
