### ISSUE TITLE
why disable built-in labels?

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/microsoft-365-docs#7388]
Why is there guidance on disabling built-in labels in Office apps when the AIP unified labeling client is installed? 
I don't understand the use case for this. For example, if you don't want built-in labels enabled, why not just avoid assigning a policy to the user? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Manage sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#office-built-in-labeling-client-and-the-azure-information-protection-client)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@itguysocal  The guidance on this page isn't to disable built-in labels in Office apps when the AIP unified labeling client is installed, but the other way around because "If users have the Azure Information Protection client installed on their Windows computers, by default, built-in labels are turned off in Office apps that support them."  There are many advantages of using built-in labeling rather than an add-in, and the instructions explain how to do that.

If you don't want any apps to display sensitivity labels to users, yes, you wouldn't assign a sensitivity label policy to them. But the Group Policy "Use the Sensitivity feature in Office to apply and view sensitivity labels" hides sensitivity labels for Windows Office desktop apps only. It doesn't prevent labels from displaying in other apps - Power BI being one example. It's an unusual configuration after you've assigned a label policy to users, but one we've been asked to support to provide flexibility for rolling out sensitivity labels across apps.

**Comment by cabailey** [comment]
Seems this can be closed now?

**Comment by itguysocal** [comment]
yes thanks again for the helpful clarification.
