### ISSUE TITLE
Undocumented DelayReleaseHoldApplied

### ISSUE THREAD

**Issue by anarii** [MicrosoftDocs/microsoft-365-docs#739]
This hold and Set-Mailbox parameter -RemoveDelayReleaseHoldApplied seem to be completely undocumented currently. Caused a lot of issues for us during a Mailbox to MailUser conversion because the hold seems to be invisible everywhere else than Exchange PS and removing Exchange license from mailboxes having this parameter set as True didn't actually remove the mailbox from Exchange Online. Set-Mailbox -identity &lt;identity&gt; -RemoveDelayReleaseHoldApplied will set this as False for the mailbox. It seems that when trying to disable a mailbox with this attribute set as True will cause serviceinstance (exchange) errors on MsolUser objects and the mailboxes are reported to be on In-Place Hold.

How and when this hold gets applied also needs to be documented here just like DelayHoldApplied. The Set-Mailbox command also should be updated to include this parameter here:

https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailbox?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4119f918-a0b2-4bdc-535e-11d2c476f675
* Version Independent ID: 1520175d-398b-4df1-86db-8ba6b26260df
* Content: [How to identify the type of hold placed on an Exchange Online mailbox](https://docs.microsoft.com/en-us/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox)
* Content Source: [microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@anarii Thanks for the heads up about this mailbox property/cmdlet parameter. The quick answer is this mailbox property applies to non-Exchange/email content that is stored in the mailbox, like Teams content. Whereas the DelayHoldApplied applies to Outlook/OWA content in the mailbox. Each of the properties are related to a different mailbox assistant that processes the mailbox with the Managed Folder Assistant runs. So in your scenario as you pointed out, the remote mailbox was considered on hold because DelayReleaseHoldApplied was set to True and you worked around this by setting the value to False. 

We will update this topic with this info and add DelayReleaseHoldApplied parameter description to Set-Mailbox. One new bit of info is to run Export-MailboxDiagnosticLogs -Identity <MailboxIdentity> -ComponentName **SubstrateHoldTracking** to see the non-Exchange/email hold history on a mailbox.

Thanks again for the heads up. I'll respond to this GitHub issue when the updated content is published.

**Comment by markjjo** [comment]
New content about DelayReleaseHoldApplied is published: https://docs.microsoft.com/en-us/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox#managing-mailboxes-on-delay-hold

**Comment by Chamu734** [comment]
Is there any document to read logs of Export-MailboxDiagnosticLogs -Identity -ComponentName SubstrateHoldTracking

**Comment by markjjo** [comment]
@Chamu734 Unfortunately, no. I would assume that the SubstrateHoldTracking component is related to and would display information about "cloud-based content (generated by non-Outlook apps such as Microsoft Teams, Microsoft Forms, and Microsoft Yammer) that's stored in a user's mailbox. Cloud data generated by a Microsoft app is typically stored in a hidden folder in a user's mailbox."
