### ISSUE TITLE
Determine the reason why the message was marked as spam

### ISSUE THREAD

**Issue by GAWAMA** [MicrosoftDocs/microsoft-365-docs#740]
Your documentation fails to enumerate the spam rules that are applied as enumerated in the SFS portion of the message headers. As a result legitimate email service sending mail to Exchange backed email services is handicapped in ensuring they are following the rules on how to keep their email content from being flagged as spam, even if the email is sourced and sent internally from and to their organization. We need these SFS rules enumerated and elaborated on to ensure productive and functional spam management and remediation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbab747e-1a43-037e-09ca-9c402deec602
* Version Independent ID: 1c6d8e28-034d-24d6-5732-b96475411d6b
* Content: [How to prevent false positives from happening in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/prevent-email-from-being-marked-as-spam#feedback)
* Content Source: [microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@GAWAMA  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@GAWAMA - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/8fa3de2165ee14b7a83b1d8ea66fdcbf7e572992. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by crankedguy** [comment]
Hi,

sorry for opening this again but I cannot see that the issue from the OP has been solved. He was talking about enumerations for the SFS headers specifically. No one knows what the numbers mean. And since one of your latest updates all MS Exchange servers I send an email to classify my private and corporate mails as spam. Somehow ridiculous depending on the fact that I am managing email servers since years and nowhere else mails from the server are spam.
So, without knowing all the numbers in the SFS header, and what they mean, I will never find out why Microsoft thinks that my mails are spam.
Where can one find out about them?
