### ISSUE TITLE
Delegate rather than Full control 

### ISSUE THREAD

**Issue by tathmann** [MicrosoftDocs/microsoft-365-docs#7427]
In Outlook you can designate someone as delegate rather than Full Control, is that possible to do with this powershell command?  Can Can I substitute Delegate for Full Control in the command arguments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fcbd22b-e14b-fe97-7b7f-eb672e84d382
* Version Independent ID: f9a024d7-6600-4922-02b5-2c8ceeae13ab
* Content: [Add staff to Bookings](https://docs.microsoft.com/en-us/microsoft-365/bookings/add-staff?redirectSourcePath=%252farticle%252f23ee9b4c-0241-40ff-b663-67a309c378f8&view=o365-worldwide)
* Content Source: [microsoft-365/bookings/add-staff.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/add-staff.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@tathmann Thank you for your feedback. Since your question is more on Outlook,  this can be done directly on the application.

Full access is granted via the admin center. However, if you would like to grant different delegate permissions, You can click on File-->Account settings-->Deleegate access-->Add to select the person you want to delete and you will see the window to grant different levels of access

![image](https://user-images.githubusercontent.com/45987684/150349858-45d886d0-8f81-400b-982b-9e8992cda4db.png)

Hope this helps!

Thanks
Sri

**Comment by tathmann** [comment]
No, this is for Bookings. This is from the page of how to setup someone to manage bookings but not be on the list of people to book meetings with. The example was only to give someone full control, I want to know if it could be done with "delegate", instead. The form seemed to give the page I was submitting from so I didn't think I had to spell all that out

Troy Athmann
________________________________

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@tathmann Thank you for the feedback. The available permissions is just full access for now. If there are any new access levels introduced, we will update the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tathmann Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
