### ISSUE TITLE
end user revoking does not work

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/microsoft-365-docs#7482]
We have tried every version of sending a encrypted message to external parties and not a single time have we seen from OWA a way to revoke any message sent.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cd0b42-9f8f-265f-1f4b-f5b73f811cfc
* Version Independent ID: f400b434-c016-7ee5-ef38-b57b90dcab95
* Content: [Revoke email encrypted by Advanced Message Encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/revoke-ome-encrypted-mail?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/revoke-ome-encrypted-mail.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/revoke-ome-encrypted-mail.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@SquirrelAssassin Thank you for your feedback.

You can revoke a mail that you sent to a single recipient that uses a social account such as gmail.com or yahoo.com. In other words, you can revoke an email sent to a single recipient that received the link-based experience.

You cannot revoke a mail that you sent to a recipient that uses a work or school account from Office 365 or Microsoft 365 or a user that uses a Microsoft account, for example, an outlook.com account.

If you have sent to a social account such as gmail.com or yahoo.com and still do not see an option to revoke from OWA, I'd recommend you contact Microsoft support via the need help section on the M365 Admin center.

Thanks
Sri

**Comment by SquirrelAssassin** [comment]
I don't know what link-based experience is, please define.  Are you saying if I send a link to a attachment and not a attachment? 

Also your saying I can revoke a email to a non-microsoft account but not a microsoft ... the company that made these.  So the company that made this cannot revoke emails to the same company that made this?

And are you saying that I get more value using a free account then a payed corporates account.  

What your saying sounds insane.... no matter how you frame it.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@SquirrelAssassin Thank you for the response

Accounts in any other domain: Messages sent to these recipients can be revoked because the actual message is not delivered to their mailboxes. Instead, they receive a notification directing them to the OME portal. These notifications are called link-based messages. Recipients must authenticate with the OME portal by signing in or using a one-time passcode to access the protected content.
Revocation is possible for link-based messages because you can guarantee to block access at the OME portal. Revocation of messages delivered to other Office 365 domains or Outlook.com would require the ability to interfere with mail flow in those domains, and that’s not possible today.

You can leave product feedback on our Portal here- https://feedbackportal.microsoft.com

Thanks
Sri

**Comment by SquirrelAssassin** [comment]
I don’t allow offline access.  Every time they open the email don’t they have to hit a rms server to open the item.  Just revoke the ability at the rms side.

**Comment by msbemba** [comment]
@SquirrelAssassin This is a new feature request or we can call it product feedback. I request you to please provide feedback on our Main feedback portal -  https://feedbackportal.microsoft.com so that one of our Product engineers can review and provide you feedback on whether this can be implemented.

Thanks
Sri

**Comment by SquirrelAssassin** [comment]
I’m going to go with recall is a feature of outlook you have to support throughout all items you add.  You added labels and didn’t think it through and now I’m giving you a option to fix it.
