### ISSUE TITLE
File Name Format and Duplicate Files Information

### ISSUE THREAD

**Issue by bvksphub** [MicrosoftDocs/microsoft-365-docs#751]
1. We noticed that exported native file name has guid without any original file name which makes hard to find specific file. Is this expected? for eg: "ea019a3b4f92c6c3b2392bac0ba2aa12e244f3074f3c0689d33f4fc08fa25917"  of powerpoint file. I have checked Core eDiscovery and it generates file with original name.

2. Does any report helps to identify duplicate files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bbdb9ae-bbde-ae26-f608-479e529fb6d9
* Version Independent ID: b3bab9c7-3802-9fd5-b438-969195817cc5
* Content: [Download export jobs](https://docs.microsoft.com/en-us/microsoft-365/compliance/download-export-jobs)
* Content Source: [microsoft-365/compliance/download-export-jobs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/download-export-jobs.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@bvksphub  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@bvksphub Question #1: Yes, exporting items with the File_ID (unique identifier for items within a review set) is the expected behavior. The items original filename is identified in the Native_File_Name column in the Export_load_file.csv. See this topic for a definition the columns in this csv file: https://docs.microsoft.com/en-us/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery

Question #2: In the Export csv file, you might try filtering on the Similarity_Percent column. The higher the value, the more similar the documents (-1 denotes unique documents). For example, you might filter on all values that aren't -1 for the Similarity_Percent column that filter on other columns to isolate duplicates. Note that you have to [run Analysis on the review set](https://docs.microsoft.com/en-us/microsoft-365/compliance/analyzing-data-in-review-set) to populate the Similarity_Percent values. You could also tag duplicates in the review set after running analysis and then export the tags so that you can filter on them in the export csv file.
