### ISSUE TITLE
What does "ZAP not enabled" mean and where is anything else ZAP-related

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#7556]
ZAP is proving to be difficult to see if/when it worked, or I just can't seem to understand the Threat Protection report.  The only mention of ZAP on the actual report and here is "ZAP not enabled".  Well definitely ZAP is enabled for all recipients in the org where I'm working, and there's nothing other than "ZAP not enabled"  Then I come here to try and get help but it's just a verbatim reading from the screen when we're looking at the TPS report, nothing really added to explain anything, more like described video for the visual impaired.

This article - https://docs.microsoft.com/microsoft-365/security/office-365-security/zero-hour-auto-purge#how-to-see-if-zap-moved-your-message - says we can use the Threat Protection Report to know if/when ZAP did stuff.   How do we do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e7112fd-cc48-c218-6e7f-1b8f76644aaa
* Version Independent ID: e285a0da-bcdc-eae7-6bd5-54fe5dab2ef4
* Content: [View email security reports - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-email-security-reports?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/view-email-security-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-email-security-reports.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeremyTBradshaw, that TPS report reference is incorrect as you mentioned, because the only ZAP information it contains is **ZAP not enabled** as you said.

It's the [Mailflow view for the Mailflow status report](https://docs.microsoft.com/microsoft-365/security/office-365-security/view-email-security-reports#mailflow-view-for-the-mailflow-status-report) that contains **ZAP removed** information.

I updated the ZAP topic accordingly.

Thanks for the feedback.

Closing.
