### ISSUE TITLE
Incomplete instructions for DKIM

### ISSUE THREAD

**Issue by tommylux** [MicrosoftDocs/microsoft-365-docs#7567]
Regarding page:
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#steps-to-create-enable-and-disable-dkim-from-microsoft-365-defender-portal

There doesn't appear to be an option on the portal corresponding to the instruction:
"Step 2: Click on Create DKIM keys".

Therefore, I do not know how you can create DKIM keys using this documentation.
![image](https://user-images.githubusercontent.com/19841675/151957194-c99f4a83-6546-439a-9260-e8cfc9081ce0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@tommylux Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7489. However, the author is reviewing it. the document will be updated once the change is approved.

You can follow the below steps to enable DKIM

Step 1: Click on the domain you wish to configure DKIM on DKIM page 

DKIM page in the Microsoft 365 Defender portal with a domain selected.

Step 2: Slide the toggle to Enable. You will see a pop-up window stating that you need to add CNAME records.

Slide the toggle to Enabled to enable DKIM.

Step 3: Copy the CNAMES shown in the pop up window

Step 4: Publish the copied CNAME records to your DNS service provider.

On your DNS provider's website, add CNAME records for DKIM that you want to enable. Make sure that the fields are set to the following values for each:

Record Type: CNAME (Alias)
> Host: Paste the values you copy from DKIM page.
Points to address: Copy the value from DKIM page.
TTL: 3600 (or your provider default)
Step 5: Return to DKIM page to enable DKIM.

Slide the toggle to Enabled to enable DKIM.

If you see CNAME record doesn't exist error, it might be due to:

Synchronization with DNS server, which might take few seconds to hours, if the problem persists repeat the steps again
Check for any copy paste errors, like additional space or tabs etc.
If you wish to disable DKIM, toggle back to disable mode


Hope this helps!

Thanks
Sri

**Comment by tommylux** [comment]
Thanks Sri, I think I see this message if the keys were already enabled previously, but a new error indicates the CNAMEs to add anyway, so I think it's all ok.

**Comment by msbemba** [comment]
@tommylux That is correct. It should be OK and will let you enable DKIM.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tommylux Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
