### ISSUE TITLE
Clarification required on retention settings

### ISSUE THREAD

**Issue by bubhat** [MicrosoftDocs/microsoft-365-docs#7576]
This article says:
_"Because of the principles of retention, you can use retention labels to supplement a retention policy for specific SharePoint, OneDrive, or Exchange items that need to be retained longer, or deleted sooner than the specified settings in a retention policy for the same location."
Wanted clarification if we can delete items with labels sooner, if retention policy is already set on items.
Example: If there is a retention policy of 5 years on a mailbox, can I assign a label to a folder such that its deleted after 2 years?
I have looked at retention flowchart and it looks like longest retention period wins. If that is the case, then this statement in the article that you can delete items sooner is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bfafff9-649f-fe14-6317-b0d81a8aa8ee
* Version Independent ID: 6bfafff9-649f-fe14-6317-b0d81a8aa8ee
* Content: [Create retention labels for exceptions to your retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-labels-information-governance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-retention-labels-information-governance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-retention-labels-information-governance.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bubhat   You don't say what the configured retention action is in the retention policy for your example, just the time period  ("... a retention policy of 5 years"). If the configured action is to retain, then yes, that always takes priority (the first principle of retention).  But if the configured action of the retention policy is delete-only, a retention label that deletes will take priority over the retention policy because of the third principle of retention. "Explicit wins over implicit for deletions" (https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#the-principles-of-retention-or-what-takes-precedence).

**Comment by bubhat** [comment]
Thanks.



Thanks,
Bhavana Bhatia

________________________________

**Comment by cabailey** [comment]
Issue addressed & made minor wording change for clarity. Closing.
