### ISSUE TITLE
Step 6 incorrect and should be removed

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/microsoft-365-docs#7664]
For step 6 in the article:
"Step 6 - Remove and delete the Microsoft 365 license from a former employee"

This is incorrect to remove licensing from a user before deletion, this will cause both Litigation hold and Compliance Retention policies to fail.  They require licensing to be **intact** upon deletion so an inactive mailbox can be created:
https://docs.microsoft.com/en-us/microsoft-365/compliance/create-and-manage-inactive-mailboxes?view=o365-worldwide#create-an-inactive-mailbox 

Furthermore even if Litigation hold or Compliance Retention policies are not in use, there is no benefit to removing a license since it is still reclaimed anyways when the account is deleted.

Thanks
Sam

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ssmiller60 Thank you for your feedback. I have added a statement in the document stating that if the mailbox is to be preserved for compliance or legal reason it must be assigned an Exchange Online Plan 2 license (or an Exchange Online Plan 1 license with an Exchange Online Archiving add-on license) so that a hold can be applied to the mailbox before it's deleted. After the user account is deleted, any Exchange Online license associated with the user account will be available to assign to a new user.

This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7693

Once the author approves, the document will be live.

Thanks
Sri

**Comment by ssmiller60** [comment]
Thanks Sri that's better than what was there before, but why is removing
the license even mentioned for the process, there is no reason to do it at
all?

Sam

**Comment by msbemba** [comment]
@ssmiller60 Thank you for the response. I think the removal of licenses is required if the organization wants to convert it to a shared mailbox (Step 3) and release the license for re-use.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@ssmiller60 The license cannot be removed from Step 3 as steps 4 & 5 need the license intact. While the scope is smaller, I can confirm these are the correct steps in order to remove a former employee. 

CC: @kwekuako 

Thanks
Sri

**Comment by ssmiller60** [comment]
Thanks! Seems like even more reasons to not mention license removal.
Looking forward to your response.

Sam

**Comment by msbemba** [comment]
@ssmiller60  Thank you for the response. The idea behind converting these shared mailboxes is also to ensure that there are no licenses assigned to them and the license can instead be reused with a new hire. While I agree with you that not all organizations will use this approach, this is a feature available in Microsoft 365 so that they don't have to pay for a terminated employee's mailbox.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ssmiller60 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
