### ISSUE TITLE
Missing instructions on how to delete a review set.

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#7753]
[Enter feedback here]
Cannot find this info anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8100182-f644-9e72-1d7c-db04160b7dc3
* Version Independent ID: fac80152-095a-3b46-d1ff-80eb3139b529
* Content: [Manage review sets in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/managing-review-sets?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/managing-review-sets.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/managing-review-sets.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Canis-Lupis Thanks for question. You can't delete a review set. You have to delete the Advanced eDiscovery case the review set is located in. This is referenced in the article on deleting cases (in the context of a data spillage scenario): https://docs.microsoft.com/en-us/microsoft-365/compliance/close-or-delete-case?view=o365-worldwide#delete-a-case

I can add a note in this topic that you logged the github issue against, since I assume that this is where you expected to find the information. Thanks.
