### ISSUE TITLE
Online support not working

### ISSUE THREAD

**Issue by MS-Mudman** [MicrosoftDocs/microsoft-365-docs#7826]
[Enter feedback here]

Microsoft has really gotten terrible over the years, cannot even got proper support.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Version Independent ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Content: [Get support - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-support.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@MS-Mudman Thank you for your feedback. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MS-Mudman Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
