### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by accuracysoftware** [MicrosoftDocs/microsoft-365-docs#7960]
Thank you for documenting the retention and deletion limits.

There is an information that I would like to know about, and I believe it has to be in this document:

This request is related to any Privacy or regulatory request,
When do the records are effectively deleted from the system after the disposition is approved?
Does the disposition deletes the records from everywhere including backups?

The requirement that we need to meet is located in the ISO standard (2020):
_R2.1.6 - if required by a disposition authority, ensure that the destruction of records results in the complete obliteration or inaccessibility of the contents of all records (including all components of each record and any backup copies) as authorized, and that they cannot be restored through operating system features or specialist data recovery techniques._

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd1c8027-2370-524b-ccce-e5cca0600685
* Version Independent ID: c08eb86e-d979-fe1c-e473-61409fcadbcb
* Content: [Limits for retention policies and retention label policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-limits?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-limits.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-limits.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@accuracysoftware  Hi, you'll find the answer of 7 days in the documentation for disposition: https://docs.microsoft.com/en-us/microsoft-365/compliance/disposition

Approve disposal:
... The item is marked as eligible for permanent deletion, which then happens within 7 days.

Timelines are documented in context of the configuration, rather than a limit, such as the maximum number of items supported. Backups as separate items will need to have the same label applied as the originals if they should also be disposed - they will go through their own disposition review.

**Comment by yogkumgit** [comment]
@accuracysoftware Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
