### ISSUE TITLE
Providing scripted credentials or PSSession credentials for Connect-MSCommerce

### ISSUE THREAD

**Issue by elliotsegler** [MicrosoftDocs/microsoft-365-docs#799]
Is it possible to provide credentials non-interactively for scripts for the Connect-MSCommerce cmlet in a similar fashion to the MSOL or EO powershell modules?

There doesn't appear to be an input for a credentials object...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by michaelcurnutt** [comment]
Thank you for your feedback and comment.

At this point we don't support providing credentials non-interactively but we will consider this for future releases.

**Comment by mypil** [comment]
@elliotsegler - From our understanding, the issue you raised has been answered by michaelcurnutt. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by ds6** [comment]
@michaelcurnutt Is there any plan for this any time soon? I have a unified single shell for all 365 realms whereby I pass credentials to each service, and having to log in more than once is at least mildly annoying.

**Comment by andikrueger** [comment]
At the moment there is no official supported way to be able to use credentials. I did some digging for a solution and came across the fact, that there was a change in the Assembly `Microsoft.IdentityModel.Clients.ActiveDirector`. This change was made in August 2017. They moved the authentication methods, that support credentials into extension methods, so that the authflow with credentials can only be used within WinRT applications. Prior to the change the credential could be used on other platforms too. https://azure.microsoft.com/en-us/blog/adal-net-3-17-0-released-2/

Basically there are three ways to enable authentication with credentials again.
1. Use another version of `Microsoft.IdentityModel.Clients.ActiveDirector`. The easiest way to get an older version is to use the one provided by the `Microsoft.PowerApps.Administration.PowerShell`. They use the following version `Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.29.0.1078, Culture=neutral, PublicKeyToken=31bf3856ad364e35` to connect to the cloud services. To load this dll, there is the need to modify `MSCommerce.psm1` a bit. I implemented a solution a while ago: https://github.com/TenantStarterKits/Microsoft365QuickStart/blob/master/Modules/MSCommerceAlpha/MSCommerceAlpha.psm1#L93-L115 This will allow users to pass in some Credentials to be used. It basically loads an older version of said dll. Also you would need to remove the signature of the module file.
2. You could build the `microsoft-authentication-library-for-dotnet` library for yourself and sideload the extension methods into the runtime of the module. It would still require to modify the `MSCommerce.psm1`, but would not load an older version of the dll at all.
3. Replace the dlls provided by MSCommerce all together with the older ones or some custom build ones. Doing so would require less modifications to the `MSCommenrce psm1` file as all dlls will be automatically be loaded. This change requires a modification of the module data file so that the extension methods are loaded right at the beginning.
