### ISSUE TITLE
Sensitivity labels for containers with Office CDN is poorly documented

### ISSUE THREAD

**Issue by OlgKis** [MicrosoftDocs/microsoft-365-docs#8004]
The article states "Sensitivity labels for containers aren't supported with Office 365 Content Delivery Networks (CDNs)." But it doesn't explain how it will actually work in practice, if company uses CDN and want to start using sensitivity labels as well. What will happen if a label is applied to a site with CDN origin? Will the behavior differ for private and public origins? What will happen if the page on the site contains assets from CDN, that is located on a site with sensitivity label applied?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@OlgKis  Not supported statements means don't use, or use at your own risk - you can't expect the official documentation to include details on what happens if something isn't supported. One of the reasons is we have to support what we document & we don't continue to test what isn't supported.  

However, in this case, I can share that CDNs don't honor the switch from Azure AD group classifications to sensitivity labels for containers, which happens when you enable sensitivity labels for containers. You can learn a bit more about this from the following section https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#classic-azure-ad-group-classification and "After you enable sensitivity labels for containers, the group classifications from Azure AD are no longer supported by Microsoft 365 and won't display on sites that support sensitivity labels."  

Without that switch being honored by CDNs, sites will continue to show any Azure AD group classifications and won't show sensitivity labels. Note that this restriction is only for container labels and not for sensitivity labels that you apply to documents in those containers.

**Comment by yogkumgit** [comment]
@OlgKis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Stealth7777** [comment]
The sensitivity labels documentation will be updated as CDN supports both Sensitivity labels and site classifications. @SanjoyanM as the owner for Sensitivity Labels.

**Comment by cabailey** [comment]
@Stealth7777  Let's cover this with internal processes rather than public GitHub Issues.

**Comment by Stealth7777** [comment]
Sure thing. Just wanted to clarify the response here as it was out of date.

**Comment by OlgKis** [comment]
Thanks a lot for the update @Stealth7777 
It's good to know this is now supported!
