### ISSUE TITLE
'*.manage.microsoft.com' should be moved to 'Allow' category?

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/microsoft-365-docs#8068]
As per discussion with a PM, we do not allow inspection of management traffic to our cloud services. Therefore, we should consider moving '*.manage.microsoft.com' endpoint from 'Default' to 'Allow' category since it is documented that SSL inspection is incompatible with endpoints in 'Allow' category.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks.

**Comment by dwhitney7** [comment]
Re-upping this request - per public [docs page on Intune side](https://docs.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints), the manage.microsoft.com domain is explicitly not supported to be SSL inspected, which does not align with the Default categorization seen on this page.

**Comment by dwhitney7** [comment]
Hi @kelleyvice-msft, any update you can share regarding plans to address the discrepancy noted in this issue? Thanks!

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
