### ISSUE TITLE
Sensitivity column display delay

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/microsoft-365-docs#8163]
Hello there, can you provide some details about the below mentioned statement? What means can take a while? Currently we have a customer which is waiting for more than one week to display the sensitivity label in the SharePoint column? Any min and max duration based on your experience?

![image](https://user-images.githubusercontent.com/39616319/161009315-39e73ddd-dc4d-46a9-bf2d-79ca050de7d0.png)
"For performance reasons, when you upload or save a document to SharePoint and the file's label doesn't apply encryption, the Sensitivity column in the document library can take a while to display the label name. "
https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?msclkid=be94b4b3b0c911ec89b251c907084d6a&view=o365-worldwide#limitations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?msclkid=be94b4b3b0c911ec89b251c907084d6a&view=o365-worldwide#limitations)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by SRE93** [comment]
@cabailey the only limitation that matches is the limitation that it can take some time when labels without encryption are applied to be displayed.
But as mentioned, more than one week should not be the case?
I tried it in our dev tenant and a day after uploading the labeled but unprotected files are showing up in sensitivity column. Any suggestions how much time we have to wait for a 12.000 user tenant?

**Comment by cabailey** [comment]
@SRE93  As explained previously, there are too many unknown variables to provide a maximum time, but for the file that's taken more than a week, I do recommend trying to open it in Office on the web. For example, it might have been encrypted client-side before a label without encryption was applied.  If that's the case, it won't open in Office on the web because SharePoint can't process the encrypted file, which means it can't populate the Sensitivity column no matter how long you wait. 

There is nothing more that we can add to the docs here & GitHub Issues aren't designed for technical support, so closing this issue.
