### ISSUE TITLE
There is a broken link under TAC at MessagingPolicies

### ISSUE THREAD

**Issue by kristofftan** [MicrosoftDocs/microsoft-365-docs#8186]
There is a broken link under TAC at MessagingPolicies, Under Messaging policies' option "Users with full chat permissions can delete any message", I found a link is broken under learn more.

The link URL: https://admin.teams.microsoft.com/invalidpath

![图片](https://user-images.githubusercontent.com/48010214/161229408-4176cc1b-a1b7-4be7-944f-c0fb305616c1.png)

**Comment by msbemba** [comment]
@kristofftan Thank you for your feedback. We handle modifications with Microsoft docs and since this is not related to any document we would not be able to fix this. However, this issue seems like it is with a link in the Teams admin center. You can submit your feedback in the feedback section on the admin center.

Hope this helps!

Thanks
Sri
