### ISSUE TITLE
In-Place Archiving of Shared Mailbox works without license

### ISSUE THREAD

**Issue by stvnw** [MicrosoftDocs/microsoft-365-docs#8211]
The article states:

*Shared mailboxes don’t require a separate license. However, if you want to enable In-Place Archive or put an In-Place Hold or a Litigation Hold on a shared mailbox, you must assign an Exchange Online Plan 1 with Exchange Online Archiving or Exchange Online Plan 2 license to the mailbox.*

This is not entirely accurate since it is possible to enable In-Place Archiving on a shared mailbox *without* a license assigned to the mailbox. Furthermore, Managed Folder Assistant will happily migrate messages into the archive mailbox according to the retention policy. The impact of this on message retention and access is not clear.

For example, starting with the mailbox `olduser` that has no license applied and no archive mailbox:

    PS /> Get-EXOMailbox olduser -Archive

    Get-EXOMailbox: Error while querying REST service. HttpStatusCode=404 ...

We can enable In-Place Archiving:

    PS /> Enable-Mailbox olduser -Archive

Success, the mailbox has now been created:

    PS /> Get-EXOMailbox olduser -Archive

    ExternalDirectoryObjectId : 5ec19d62...
    UserPrincipalName         : olduser@domain.com
    DisplayName               : Old User
    EmailAddresses            : {SPO:SPO_9839df9a...
    PrimarySmtpAddress        : olduser@domain.com
    RecipientType             : UserMailbox
    RecipientTypeDetails      : SharedMailbox
    Identity                  : olduser
    ...

We can start MFA:

    PS /> Start-ManagedFolderAssistant -Identity olduser

And after a little while confirm messages are being migrated:

    PS /> Get-EXOMailboxStatistics olduser

    DisplayName          : Old User
    MailboxGuid          : 469c940d...
    DeletedItemCount     : 1658
    ItemCount            : 7209
    TotalDeletedItemSize : 34.34 MB (36,007,887 bytes)
    TotalItemSize        : 1.648 GB (1,769,691,899 bytes)

This leads to some questions:

- Is this the intended behaviour?
- What will happen if a license is never assigned? Will the messages remain indefinitely or will they be deleted and when?
- Is there a way to view the archived mailbox on the client side in this state?

(The requirement for a license is also referred to [here](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-storage-limits) and [here](https://docs.microsoft.com/en-us/microsoft-365/admin/email/remove-license-from-shared-mailbox) although they disagree on what is the minimum.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b3fbbe-fde3-fd52-f9cd-d8fca56a1494
* Version Independent ID: 73d71ee8-579d-78b5-a8cd-48d7ec51ebb8
* Content: [Convert a user mailbox to a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@stvnw Thank you for your feedback. This is not the intended behavior. By design, the shared mailbox needs  Exchange Online Plan 1 with Exchange Online Archiving or Exchange Online Plan 2 license to the mailbox. So to answer your questions

Is this the intended behavior? - No and this looks like a bug and will be reported to PG. You can also do it via the need help section on the admin center.
What will happen if a license is never assigned? Will the messages remain indefinitely or will they be deleted and when? - Since this is a bug, I don't think there is a definite answer to this question and it will follow the normal user mailbox scenario once the bug is fixed.
Is there a way to view the archived mailbox on the client-side in this state?- Since this is a bug, I don't think there is a definite answer to this question, and it will follow the normal user mailbox scenario once the bug is fixed.

@SKjerland This looks like a product bug as we are able to enable Archive without any license on the mailbox. Could you please pass this on to PG?

@yogkumgit  There are no changes required in the document as this is a product bug.

Thanks
Sri
