### ISSUE TITLE
article not updated as per updated link

### ISSUE THREAD

**Issue by drksilenc** [MicrosoftDocs/microsoft-365-docs#8295]
There is no combined security and compliance tab they are different sections can you please update this to show live products not something from 6 months ago...

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041a2c32-e0b9-77e9-766c-3b4f5b07ff3a
* Version Independent ID: 597960ea-f734-09c7-eea8-aab24a06c9f8
* Content: [View mail flow reports in the Reports dashboard - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-mail-flow-reports?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/view-mail-flow-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-mail-flow-reports.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@drksilenc Thank you for your feedback. I was able to locate the reports in[Office 365 Security & Compliance](https://protection.office.com/)

Could you specify which report is not available in the security and compliance center?

![image](https://user-images.githubusercontent.com/45987684/165794008-e2b50c59-8e6b-4269-96e8-01678ba05d81.png)

Thanks
Sri

**Comment by chrisda** [comment]
@drksilenc, that mail flow reports topic is on life support. All of the reports within it now exist in the Microsoft 365 Defender portal or the Exchange admin center (EAC) as reflected in the topic.

Furthermore. changes to the reports in the Defender portal are reflected in the Security & Compliance Center, except for the 'widgets' themselves.

I contend that topic is current and up-to-date Feel free to prove me wrong.

**Comment by drksilenc** [comment]
I dont have security and compliance i have 2 different sections. 1 is security 1 is compliance neither show that view.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chrisda** [comment]
So, it looks like that topic can now be eliminated, because none of the reports mentioned within it have widgets on the Dashboard page anymore:

- Connector report
- Exchange transport rule report
- Forwarding report
- Mailflow status report
- Sent and received email report
- Top senders and recipients report

Note that this topic isn't meant to be an overview of the Dashboard; that's covered in [Security dashboard in the Security & Compliance Center](https://docs.microsoft.com/microsoft-365/security/office-365-security/security-dashboard) (which probably needs updates, too).

This mail flow reports topic was a bucket for email-related reports, and was a companion to similar [email security reports](https://docs.microsoft.com/microsoft-365/security/office-365-security/view-email-security-reports) and [Defender for Office 365 reports](https://docs.microsoft.com/microsoft-365/security/office-365-security/view-reports-for-mdo) that have since been converted to Microsoft 365 Defender portal topics. As described earlier, we purposefully did not convert this topic because most of the reports went away or were moved into the EAC.

I thought that the Security & Compliance Center would just wither and die, but I found out recently that a) they are selectively removing things from it, and b) changes to reports in the Defender portal also affect the corresponding reports in the Security & Compliance Center.

![image](https://user-images.githubusercontent.com/33166947/165803571-a7bd87e0-212d-47e2-8bea-4d6257b8a634.png)

**Comment by yogkumgit** [comment]
@drksilenc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
