### ISSUE TITLE
significant typo

### ISSUE THREAD

**Issue by Arne-RFA** [MicrosoftDocs/microsoft-365-docs#8303]
"Specifies the priority and recipient filters (who the policy applies to) for a outbound spam filter policy."

As only users, Groups, and Domains **in the tenant** can be specified (and there is no method to add an external recipient domain), the line should be.

"Specifies the priority and sender filters (who the policy applies to) for a outbound spam filter policy."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure outbound spam filtering - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Arne-RFA, fixed. Copy and paste error (all other policies deal with recipients, because they're inbound).

I also took the time to find any related references to 'recipient' and change them to 'sender' in the topic (there were quite a few).

In the future, you too can make fixes like this yourself without opening an Issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
