### ISSUE TITLE
Clarify behavior for removing "container" labels

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/microsoft-365-docs#8333]
As per the title, can you please update the "Removing and deleting labels" section in the document to clarify what happens when you (try to) remove a label with active container assignments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57908eea-077f-363c-8d51-3b8335914f4c
* Version Independent ID: 0d1421f1-b546-677f-ef3b-7e3da294b5ef
* Content: [Create and publish sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide#removing-and-deleting-labels)
* Content Source: [microsoft-365/compliance/create-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Investigating

**Comment by cabailey** [comment]
@michevnew  Apologies this has taken awhile because we investigated all scenarios for deleted labels (vs removed from policy).  It seems it can take SharePoint longer than our usual 24hrs to stop enforcing the settings from the now deleted label and this information is now added to the section: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide#removing-and-deleting-labels

**Comment by michevnew** [comment]
Thanks Carol.
