### ISSUE TITLE
Policy priority order & multple matches

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/microsoft-365-docs#834]
Section - https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies#the-priority-by-which-rules-are-processed - for multiple matches - shows a screenshot of multiple policies HOWEVER the text speaks towards multiple rule matches (not multiple policy matches as shown in the screenshot). Please consider adding verbiage that states the expected behavior when multiple policies match

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Overview of data loss prevention](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies#feedback)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi -  @CHDAFNI-MSFT 
Thanks for your suggestion.  I don't have the answer to this at my immediate disposal. If you know what the expected behavior is, the quickest way to get it into the content would be for you to click the edit button on the topic, make the edits and submit a pull request. I'll be able to review your suggested changes and verify them with the product team and move them into the publishing pipeline.

**Comment by chrfox** [comment]
Hi @CHDAFNI-MSFT 
It was the screenshot that was wrong, not the text.  Screenshot updated and republished
