### ISSUE TITLE
Safe Senders

### ISSUE THREAD

**Issue by labanex** [MicrosoftDocs/microsoft-365-docs#8366]
This article is an effective way of setting up Safe Senders in EOP, but there are other sections in Microsoft 365 that can also set Safe Senders.
Like using the features of Microsoft 365 Security/Defender > Policies and Rules > Anti-Spam > Inbound Policies. This is a section that can also allow safe senders. What I recommend is a link in a NOTE that can link admins to the articles that explains inbound policies in the Anti-Spam policies. Connection Filtering could also be explained if they are using a third-party software in-house and they want to receive emails from this software with IP addresses. Connection Filtering is also heavily used by software like Salesforce which has several IPs for safe listing. In the article that explains Anti-Spam in Defender would also be useful if there is a link back to this article as well. Sometimes using both would allow recipients to ensure safe passage of emails not going to junk. I've seen on a few occassions that setting one or the other does not work all the time. A note stating this in the article would help a lot of admins of finding solutions to False Positive emails, especially since submitting false positive emails dates expire at certain times.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by adamlavery** [comment]
Thanks to Antonio from Microsoft Support for posting this. To reiterate, this presents 4 options (in recommended order) for setting up organisation level safe senders. But the reality is that this needs to be done in multiple places. Adding as transport rule to allow safe senders by bypassing spam filtering doesn't work. Mails can still be junked by another part of spam filtering. For example:

Transport rule sets SCL=-1 (bypass):

```
x-forefront-antispam-report:
 CIP:159.183.142.157;CTRY:US;LANG:en;SCL:-1;SRV:;IPV:NLI;SFV:SKN;H:wfbtvzwd.outbound-mail.sendgrid.net;PTR:wfbtvzwd.outbound-mail.sendgrid.net;CAT:NONE;SFS:;DIR:INB;

```

But another part of filtering still junks it:

```
X-Microsoft-Antispam-Mailbox-Delivery:
 kl:1;ucf:0;jmr:0;auth:0;dest:J;OFR:SpamFilterAuthJ;ENG:(910001)(944506458)(944626604)(920097)(825001)(250001)(930097)(3100021);RF:JunkEmail;

```

If the various parts of Microsoft spam filtering were properly integrated (as they should be) then we should only need to set safe senders in one place, not multiple. But as it seems the various teams don't talk to each other we end up having to configure each part of spam filtering to stop false junking of important emails. 

This article needs to present **everything** we need to do to ensure safe senders mails are never blocked or junked.

**Comment by chrisda** [comment]
@labanex, in your request:

> What I recommend is a link in a NOTE that can link admins to the articles that explains inbound policies in the Anti-Spam policies.

That information is already in the topic: it's option 4 [Use allowed sender lists or allowed domain lists](https://docs.microsoft.com/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365#use-allowed-sender-lists-or-allowed-domain-lists):

> The least desirable option is to use the allowed sender list or allowed domain list in anti-spam policies. You should avoid this option _if at all possible_ because senders bypass all spam, spoof, and phishing protection, and sender authentication (SPF, DKIM, DMARC). This method is best used for temporary testing only. The detailed steps can be found in [Configure anti-spam policies in EOP](configure-your-spam-filter-policies.md) topic.

@adamlavery, you're right, there are some parts of the spam filtering stack that you simply can't bypass: malware and high confidence phishing. I would contend that the intent of this topic isn't to describe every combination that's required to bypass email filtering (what can be bypassed). The intent is: if you need to bypass, then use the technologies described in the order described (individually, not cumulatively).

Regarding other asks/requests, the best way forward for both of you would be to modify the topic as you see fit and add whatever you like. All you need is a GitHub account, which you obviously have since you're creating Issues.

The instructions are here:

<https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>

**Comment by adamlavery** [comment]
@chrisda thanks for responding quickly, but I would disagree with your contention. This topic **should** describe how to allow senders. As end users we're not really that interested in how Microsoft have implemented their spam filtering stack. We just need to know what to do to allow mails when the filters repeatedly get it wrong. Submitting for analysis in the hope the filters get better (for a while!) is not the answer; too late - an important mail might have already been missed resulting in a lost order or prospect.

As for implementing individually not cumulatively, experience shows this is not correct. Antonio also knows from personal experience that just setting transport rules doesn't work. See my example mail header. SCL said bypass but something else still junked it. Nothing in the header tells us why it was junked but I can say for absolute certain it was not malware or even low confidence phishing - just a normal, everyday website enquiry. We've had a issue open with Microsoft now for 8 weeks and still nobody has explained why the sample email was junked, despite being whitelisted in transport rules. And it's still happening.

Finally, I content that it's not Microsoft's customers that should be writing these articles. It's the people who wrote the spam filter stack that need to explain clearly and concisely how to work the system to overcome the increasingly prevalent false positive junking of normal business emails.

What should happen is that all of the teams responsible for the "spam filtering stack" get together around a table and agree on  how to implement a single, global safe-senders list that all parts of the system honour. Notwithstanding malware and high-confidence phishing (usually from compromised accounts) which should always be flagged. 

Until this happens we have to configure the various parts of the stack to stop junking mails. To do that properly we need clear instructions and that has to come from the keyboards of the people who know the system in detail, not from customers guessing how it works.

Thanks

**Comment by chrisda** [comment]
@adamlavery, I contend that the Safe Senders article is current as to the available and recommended methods for skipping what can be skipped in the filtering stack. As you alluded to, it's possible that just because you allow something in one place (say, transport rule with SCL=-1) that it isn't caught somewhere else in the filtering stack. What if that "please allow this" message contained malware or was deemed to be high confidence phishing?

If the Microsoft filters get it wrong (false positive or false negative), the recommendation is to report the message to Microsoft for analysis as described [here](https://learn.microsoft.com/microsoft-365/security/office-365-security/submissions-admin).

As described in the original Safe Senders article, the [Tenant Allow Block](https://learn.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list-about) list is now the recommended one-stop place for any/all filtering exceptions for senders, URLs and files (again, skipping what can be skipped).

Thanks for the feedback.

Closing.
