### ISSUE TITLE
Get notified on updates of Office365 IP address ranges

### ISSUE THREAD

**Issue by rpnoll1977** [MicrosoftDocs/microsoft-365-docs#8373]
We were told by microsoft support to watch this page for changes. A change in certain IP addresses / ranges listed here would cause failure of our systems. How can i get notified when the page changes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Other endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
I will look into this.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. For information on how to get notified when there are updates to the Office 365 endpoints web service, see https://docs.microsoft.com/microsoft-365/enterprise/managing-office-365-endpoints#change-management-for-office-365-ip-addresses-and-urls. There are multiple methods listed. -Kelley

**Comment by rpnoll1977** [comment]
Thanks you for your reply. Sorry i was asking for change notifications for the page mentioned in my initial post. The page is about addresses __not__ covered by your web service and RSS.

If necessary, i can give you more details on why this is an issue to our operations and delaying our migration to O365.

**Comment by kelleyvice-msft** [comment]
@rpnoll1977, I've reopened the issue. I'd be interested to get more information about why this is a blocking issue. There are ongoing initiatives to make the web service more inclusive, which may solve this problem at some future time, but if there are customers who can't migrate because of this issue, the engineering team will want to know and understand why. -Kelley

**Comment by rpnoll1977** [comment]
You can see microsoft support case 30008818 for the backgrounds why we need to watch that page.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
