### ISSUE TITLE
Nobody from tech support is picking up

### ISSUE THREAD

**Issue by chungweijian** [MicrosoftDocs/microsoft-365-docs#8385]
Hi, I've tried calling 3 times, but all 3 times i was waiting in the silence, and then the line just got cut off. 

• ANI (Caller's telephone number) - +6 03 4145 6279
• Date of call - 22/04/2022
• Time of call with time zone - between 9.30am - 9.50am
• Options, selected if any - chose the option where i need tech support for emails linked to my organisation's domain
• Experience of call (no answer, got recording then disconnected, etc.) - no answer.

**Comment by msbemba** [comment]
@chungweijian Thank you for your feedback. I'm sorry to hear that. The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

Hope this helps!

Thanks
Sri
