### ISSUE TITLE
bulk add Alias email address

### ISSUE THREAD

**Issue by SpangleIT** [MicrosoftDocs/microsoft-365-docs#8418]
I was hoping this pasge would also include how to bulk add alias email adresses for a single user, or at least a link of where this can be done

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99474cca-d2bc-d602-71ba-5c20e894429a
* Version Independent ID: 5aa17d74-a77f-82ed-48db-ff10413784bb
* Content: [Add several users at the same time to Microsoft 365 - Admin Help - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/add-several-users-at-the-same-time?WT.mc_id=365AdminCSH_SupportCentral&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/add-several-users-at-the-same-time.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/add-several-users-at-the-same-time.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@SpangleIT Thank you for your feedback. The document pertains to adding users in bulk to M365, so that is why you do not see information about adding aliases.

Adding aliases via the M365 admin center cannot be performed in bulk. Here is the document that talks about adding aliases -https://docs.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide#add-email-aliases-to-a-user

There are scripts that can be created to perform the action via Powershell. If you'd like to get a script, I'd recommend working with the support team via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by SpangleIT** [comment]
Thank you for you feedback

I will give admin centre a try, I have found a few help pages but they assume a certain level. Where I probably need a little more detailed (worked examples).

I have about 200 aliases to add to a single email account

Kind regards
Malcolm
Spangle IT


Phone: 01708 700817      DDI 01621 838050
Spangle.it
SpanglePICS.co.uk
Spangleit.co.uk

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SpangleIT Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
