### ISSUE TITLE
Can I buy a single SharePoint Syntex licence?

### ISSUE THREAD

**Issue by Darrelo365** [MicrosoftDocs/microsoft-365-docs#8462]
Hi, can I buy a single Syntex licence if I wanted to do document metadata capture at scale - millions of documents?

I might have misunderstood the product and what I can do with a single user licence. Can I create apx 20-25 models and apply them to one or more libraries and it will process what's currently in there (millions of docs) and the what's added (tens of thousands per month)? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998f446c-aacf-4d7c-fdc0-fc5c5073d20e
* Version Independent ID: 587f92c0-7f44-6ebf-1fac-403b84722969
* Content: [Licensing for SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/syntex-licensing)
* Content Source: [microsoft-365/contentunderstanding/syntex-licensing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/syntex-licensing.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Darrelo365 Thank you for your feedback. Yes, you can purchase 1 SharePoint syntex license. Since it is an add-on license it requires the user to have a license for M365.  This information has been added to the document.

As long as you have the license, you can create models and apply them to multiple document libraries. 

If you have further queries regarding the licensing, I'd recommend you contact our support team who can answer all your questions. The support team can be contacted via the need help option on the admin center.

Hope this helps

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Darrelo365 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
