### ISSUE TITLE
Backscatterer has an expired certificate

### ISSUE THREAD

**Issue by ildjarnisdead** [MicrosoftDocs/microsoft-365-docs#851]
The link to the backscatterer.org website results in a warning, because the certificate of the site has expired in 2018, which leads me to believe that the backscatterer.org website is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955d52db-5da8-5845-28ea-f78b2a85b688
* Version Independent ID: 6dacde19-dfbf-4305-27b7-b0ecd3bcb9ac
* Content: [Backscatter messages and EOP](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/backscatter-messages-and-eop)
* Content Source: [microsoft-365/security/office-365-security/backscatter-messages-and-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/backscatter-messages-and-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ildjarnisdead, the issue is nothing more than a global sweep through our content to replace 'http' links with 'https'. The backscatterer.org website is alive and well; they just appear to use http instead of https.

I also took the opportunity to edit the topic a bit (a lot, but it was short).

Thank for the feedback.
