### ISSUE TITLE
Should we or Should we not perform full scan

### ISSUE THREAD

**Issue by ahmedbadawy80** [MicrosoftDocs/microsoft-365-docs#8529]
Hi,
The full scan is really a challenge for me to understand if we should schedule on weekly/monthly basis specially for servers or nor?
The Microsoft Architects we work with aren't sure also. Some say yes perform the scans for Tier0 servers only, others aren't on board of full scanning.
nevertheless, none agreed on performing a full scan on all all tiering model.

Any idea or recommendation or definite recommendation from MS as even our Architects don't agree on single point of view

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72be33f7-fd1f-3b0c-00c0-8d448a2cfdd3
* Version Independent ID: 0cf78d5c-8c46-8088-36c4-70fcdaf142ff
* Content: [Schedule regular quick and full scans with Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/schedule-antivirus-scans?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/schedule-antivirus-scans.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/schedule-antivirus-scans.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @ahmedbadawy80. Thank you for posting your question here. In general, we recommend scheduling quick scans as opposed to full scans, because full scans can involve a lot of time and system resources. However, as you have mentioned, not everyone agrees with one single approach. Each organization is different, and it's difficult to say for sure which scan type is best for your organization. The documentation does mention that the Quick Scan is the recommended choice, because it does help provide strong coverage. Perhaps a more important factor here is whether real-time protection is enabled, and whether you're using cloud protection.

I hope this helps answer your question. Please let me know if you have any other questions.
