### ISSUE TITLE
Not Useful

### ISSUE THREAD

**Issue by ramoriusvt** [MicrosoftDocs/microsoft-365-docs#8533]
Not useful.

After logging in, The Help and Support option isn't there. Neither is Contact Support.

So, not useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Version Independent ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Content: [Get support - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?redirectSourcePath=%252fen-us%252farticle%252fget-support-or-advice-18948a4c-3eb1-4b30-b1bc-a4cc29eb7655&view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-support.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@ramoriusvt Thank you for your feedback. I have tested and the help and support option is available in the admin center.

![image](https://user-images.githubusercontent.com/45987684/168830113-472bcd45-982e-4802-87a3-16d2fb841ccd.png)


If you continue to have this problem, please use the phone support option (https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide#phone-support)  and let them know, so that they can fix this issue from the backend.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ramoriusvt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
