### ISSUE TITLE
Some remarks/questions about the documentation

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/microsoft-365-docs#856]
Category\EOP anti-spam policy settings: Should the Phishing email settings be mentioned here? and I didn't find any specific setting for High Confidence Phish email detection
Category\Safe link settings: Does disabled mean that the check box is selected, or does it mean that the checkbox should be enabled, since the setting is called: "Do not track when users click safe links and Do not let users click through safe links to original mail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Office 365 ATP security settings, recommendations, Sender Policy Framework, Domain-based Message Reporting and Conformance, DomainKeys Identified Mail, steps, how does it work, etc](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
Thank you for noting that there is some phishing data in anti-spam right now. That's noted. This document is a work in progress, and changes are being considered even now. Some Phish functions will remain in the anti-spam section because it resides in the antispam policy now. Finally, 'disabled' in your example means you should not check the box. I hope this helps! Thanks for your comment here!
