### ISSUE TITLE
Viva Suite URLs/IPs

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/microsoft-365-docs#8695]
Hi team, can we get list of URLs/IPs used by the Viva Suite (all Viva modules) ? Thanks.

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I'll investigate why Viva endpoints have not been added to the web service. It seems like they should be. -Kelley

**Comment by soyalejolopez** [comment]
Great, thank you Kelley 👍
________________________________

**Comment by meliss0215** [comment]
Hi @kelleyvice-msft do you have an update on this? This request has been open since May. Thanks!

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
