### ISSUE TITLE
Add better Service Account explanation for Audit Log search

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#871]
I see several entries with user 'Service Account' in an audit log search. The service account user did execute these activities:

- SearchDataInsightsSubscription
- SearchDomainMxRecord
- SearchDomainTrafficStatus
- AggregateActivityData
- SearchActivityData
- SearchReportSubmissionAggregation

Please provide in detail documentation about service accounts in this context. I'm aware what service accounts are (accounts with no active Office 365 licenses and a specific role) but this doesn't explain why I see these activities in the audit log although there are no service accounts. I suspect there is a non-documented reason for this behavior because the docs mention this and it looks like Microsoft is aware of noisy logs so it is unlikely a technical defect/issue with the product:

>Many of these cmdlets are related to maintaining the Exchange Online service and are run by Microsoft datacenter personnel or service accounts. These cmdlets aren't logged because they would result in a large number of "noisy" auditing events. 

Related to this:
https://social.technet.microsoft.com/Forums/windowsserver/en-US/bd07c93b-3d81-4969-8a57-e45beecf8d59/audit-log-operations?forum=onlineservicesadministrationcenter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#feedback)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@GiantCrocodile The operations that you list are related to collecting data insights so that these insights can be presented, for example, when viewing insights dashboards such as the ones under Reports in the Security & Compliance Center. For these events, RecordType = 52 and the value for UserID is, as you cite, "Service Account". 

We'll look into adding more info about this audit schema in this topic: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema -- This topic also may have info helpful to the other GitHub issue you opened related to service accounts.

**Comment by GiantCrocodile** [comment]
Thank you!
