### ISSUE TITLE
Steps for finding local script incorrect

### ISSUE THREAD

**Issue by plylechapman** [MicrosoftDocs/microsoft-365-docs#8768]
Since the change to the security.microsoft.com portal, the steps for finding and downloading the Local Script are inaccurate.

In fact, I still can't find it at all.  Please advise.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f044e756-d5d8-5db6-edbb-f042b1b22b3c
* Version Independent ID: 5d016fa2-3407-e757-1595-118728158c46
* Content: [Onboard Windows devices using a local script](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-script?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-script.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-script.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@plylechapman Thank you for your feedback. I was able to test this in multiple tenants and the steps are accurate. 

![image](https://user-images.githubusercontent.com/45987684/171808362-d7e31b76-17e6-43c1-bc6a-83d0958e4086.png)


If you continue to have an issue locating the script, it could be due to lack of permissions or a bug in the tenant. I'd recommend you to contact Microsoft via the need help section on the admin center. so that one of our support engineers can help you.

Hope this helps!

Thanks
Sri

**Comment by plylechapman** [comment]
Correct; you can close.  Sorry for the confusion.

The issue is that the newly integrated portal has "Endpoints" on the main screen as well as under Settings.
