### ISSUE TITLE
Sandbox subscription cancelled

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/microsoft-365-docs#8772]
once the sandbox subscription was cancelled, can users still access the environment created in LCS? Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a91e3ae5-842c-fb3d-8c27-d8001122aee8
* Version Independent ID: ddccec72-7088-4207-60cb-986a35becb67
* Content: [Cancel your business subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/cancel-your-subscription?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/cancel-your-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/cancel-your-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@jlabustro Thank you for your feedback. This is more of a Dynamics 365 question and is answered here -https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/subscription-overview

If you don't deallocate and delete the existing environments before you suspend the subscriptions, the environments will remain in a Deployed state. However, if you try to access the full details of these environments, you will receive an error message.

If this doesn't answer your question, I'd recommend you reach out to the support team via the need help section on the admin center so that they can help out.

If not, you can also raise a feedback request on this page -https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/get-started/subscription-overview so that this can be added to the FAQ section on this Dynamics Document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jlabustro Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
