### ISSUE TITLE
problem in CSV sample 

### ISSUE THREAD

**Issue by tamiyatxt1** [MicrosoftDocs/microsoft-365-docs#8784]
[Enter feedback here]
https://docs.microsoft.com/en-us/microsoft-365/compliance/import-hr-data?view=o365-worldwide#configuring-a-single-csv-file-for-multiple-hr-data-types

There is a sample CSV here.
The number of comma in the header line and following lines are different.
This causes "internal server error" on uploading CSV file.
If administrators create CSV file by referring this page, admins will see the error.
As this is one example I found, please check other examples.

HRScenario,EmailAddress,ResignationDate,LastWorkingDate,EffectiveDate,Remarks,Rating,OldLevel,NewLevel
Resignation,sarad@contoso.com,2019-04-23T15:18:02.4675041+05:30,2019-04-29T15:18:02.4675041+05:30,,,,
Resignation,pilarp@contoso.com,2019-04-24T09:15:49Z,2019-04-29T15:18:02.7117540,,,,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b68cfa-058a-8536-fb6a-b54e8fffa626
* Version Independent ID: dbcba365-2858-8cff-4f30-8a8a0068ac71
* Content: [Set up a connector to import HR data - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/import-hr-data?view=o365-worldwide#configuring-a-single-csv-file-for-multiple-hr-data-types)
* Content Source: [microsoft-365/compliance/import-hr-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/import-hr-data.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@tamiyatxt1 Thank you for your feedback. I was able to upload the file with the same Example. Also, I was able to validate the data in a CSV. 

This is how the example looks when validated

![image](https://user-images.githubusercontent.com/45987684/171842150-5bc6050b-6c12-4978-a3f6-8f7fdac6ff21.png)


Note that the extra commas mean that the filed/text box is empty.

If you continue to have trouble with this, Please contact Microsoft via the need help section on the admin center. So that a support engineer can help you fix the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tamiyatxt1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
