### ISSUE TITLE
country code wrong?

### ISSUE THREAD

**Issue by fixx-er** [MicrosoftDocs/microsoft-365-docs#8862]
for Mexico is it not supposed to be **52** 4738 6567 and not 55 for the number
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bf838db-2d83-3e38-d983-eacd9115c49f
* Version Independent ID: 4b1bf198-0fd6-8931-154d-69f5ba0fd7e5
* Content: [Support information for Mexico - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/mexico?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/mexico.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/mexico.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by RAJU2529** [comment]
@yogkumgit . I conformed country code is 52 for Mexico in Google search

**Comment by msbemba** [comment]
@fixx-er Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8894

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba It seems me a duplicate PR. Please keep one of them and delete the other.

**Comment by yogkumgit** [comment]
@fixx-er closing as per author's comment.

**Comment by cmcatee-MSFT** [comment]
@fixx-er Thanks for reporting this concern. You're correct in that the country code for Mexico is 52. However, the area code for Mexico City is 55. Since the alternate phone number is a local call, the country code is not needed, and the number as given is correct. If you can't complete the call using the number given, please let me know so I can have our team investigate any possible telcom issue with it. Thanks!

**Comment by fixx-er** [comment]
very good then
________________________________
