### ISSUE TITLE
Limitations of Sensitivity Labels & Configuration

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#8866]
Documentation for Limitations of Sensitivity Labels is found in a separate document - https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide

Currently it lists out multiple limitations of SPO/OneDrive, but we'd like to have this in a consolidated location for the overall Sensitivity Label configuration/setup docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57908eea-077f-363c-8d51-3b8335914f4c
* Version Independent ID: 0d1421f1-b546-677f-ef3b-7e3da294b5ef
* Content: [Create and publish sensitivity labels - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@SeanTGeoghegan   Thank you for your feedback. We currently have no plans to do this but keep limitations specific to the scenario. Customers have a choice whether to enable each labeling scenario, and need to know in context any limitations rather than send them to another page each time.

**Comment by SeanTGeoghegan** [comment]
@cabailey Thank you for the update! In that case, could the section - https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide#additional-label-settings-with-security--compliance-powershell - have further clarification that LocaleSettings is specific to Office Applications, as the "Example configuration" section below it alludes to? Or have the "Office apps" be designated as "Office Desktop apps"? (unsure what the correct nomenclature is)

**Comment by cabailey** [comment]
@SeanTGeoghegan  I will look into this a bit more but to my knowledge, these language settings weren't designed for Office applications, desktop or otherwise, but a valid label configuration available to all platforms and all labeling scenarios. Then, it's up to each labeling scenario to support it or not.  If it doesn't and you have a good business justification why it's needed, file a DCR so the relevant engineering team can take it into consideration when they plan future work. I can see why you would want a callout here to more specifically identify which apps support this configuration but there are two doc strategies why we don't do that:

1. When we have an important technical detail, like a support statement, we try to document it once as the single and authoritative statement.  When it's in multiple places in the docs, it's very difficult to keep all references updated when things change (and they do, often in this space!). Then you end up with contradictions, which are problematic not just for that single support statement but all the docs, because if one statement can't be trusted, by extension customers begin to distrust everything.

2. We don't know, and don't control, the list of applications/services that support these multi-language label settings. New labeling scenarios are lighting up all the time - not just in Microsoft (such as SQL support recently announced) but our vendor partners using the MIP SDK.  I wouldn't know if they support these settings so to document they're only supported by "x" would be misleading/untrue. To list specific labeling scenarios here that don't support them would imply if not listed, they do support them.

We could say "These multi-language label settings might not be supported by all apps and platforms that you use" but that applies to every label setting. As with all configurations, test them with the apps used by your organization and check the documented limitations for the labeling scenarios you're using.
