### ISSUE TITLE
Teams Phone, IP Addresses, and Endpoints

### ISSUE THREAD

**Issue by rclaytgit** [MicrosoftDocs/microsoft-365-docs#9018]
We are testing Policy CCX 600 deskphones with dedicated Teams configurations.  One issue we've run into is that the login process fails unless we allow IP addresses associated with teams.events.data.microsoft.com and mobile.pipe.aria.microsoft.com through our corporate firewall.  Those endpoints are not included in the list of Office 365 U.S. Government GCC High endpoints.

The IP addresses for those domains also change frequently and we are unable to find a list of all IP address ranges needed so that we can add appropriate exceptions.  Can the document be updated to include those domains as well as the associated IP address ranges used for those two domains?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0043b9f3-d91c-569f-1efc-720e4162c5e7
* Version Independent ID: 0289deef-82e4-5f56-7258-ab574c8d0e70
* Content: [Office 365 U.S. Government GCC High endpoints - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I am contacting the appropriate engineering resources and will reply back when I have information. -Kelley

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
