### ISSUE TITLE
Requirement clarification regarding MDE

### ISSUE THREAD

**Issue by rucam** [MicrosoftDocs/microsoft-365-docs#9054]
In the section **Requirements for managing tamper protection in Endpoint Manager** is states that _Your devices must be onboarded to Microsoft Defender for Endpoint_.  This implies that MDAV (or maybe even MDB) customers can't use TP over MEM. Is this the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f31e7b39-b7c3-188a-0b2a-02ff10a5be6d
* Version Independent ID: 44940a13-0a2d-e281-560b-cb4d8a5d1ccf
* Content: [Protect security settings with tamper protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@rucam Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9133

Even with Microsoft Endpoint Manager Tamper Protection enabled, your admins need to have the ability to continually review your security posture. Otherwise, you won’t fully benefit if you cannot see the tamper attempts or report them. Since this is not a must to onboard it to MDE, I have updated the document accordingly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rucam Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
