### ISSUE TITLE
Transfer domain is not available

### ISSUE THREAD

**Issue by cakriwut** [MicrosoftDocs/microsoft-365-docs#9103]
[Enter feedback here]
The **transfer domain** link is not available anywhere. Is the functionality still exist or has been replaced? 
Suggest to add screenshot or RBAC prerequisites if any. 

Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82907a2-5f0a-b909-0e15-f7b90768664b
* Version Independent ID: 33c36d45-0ec6-3225-9ad2-f3d040406d2d
* Content: [Transfer a domain from Microsoft to another host - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/transfer-a-domain-from-microsoft-to-another-host?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/transfer-a-domain-from-microsoft-to-another-host.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/transfer-a-domain-from-microsoft-to-another-host.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@cakriwut Thank you for your feedback. The Transfer domain option is available when you had initially purchased our domain through Microsoft and it is more than 60days after you purchase the domain. Only a global admin can add, manage and transfer domains. I have added this to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9126

If you are a global administrator and still do not see the transfer option, I'd request you to contact Microsoft via the need help section in the admin center so that a support engineer will be able to assist you in fixing this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cakriwut Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
