### ISSUE TITLE
Endpoints for AADConnect Health agent missing

### ISSUE THREAD

**Issue by NuAlex** [MicrosoftDocs/microsoft-365-docs#9128]
This page is missing the endpoints for AADConnect Health agent which is part of Azure AD Connect Classic Sync (ADSync) product.
AADConnect Health agent is a very important tool for supportability of Azure AD Connect, lack of connectivity will cause the health agent to not be able to upload important metrics that Microsoft can use for better support Customers.

Please add the URLs for Connect Health that are documented here: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-health-agent-install#outbound-connectivity-to-the-azure-service-endpoints
Let me know if you have any questions.

Thanks,
/Nuno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise]()
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
