### ISSUE TITLE
Power Platform

### ISSUE THREAD

**Issue by amscsamdev** [MicrosoftDocs/microsoft-365-docs#9176]
Since Power Platform is a seeded license with M365 could there be url references added on this page to these additional required domains needing to be made available to end user access points in order for those products to function properly.  Ex. https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45a2f60-4f5f-2ee3-5a2a-aeccf6c8b767
* Version Independent ID: 2335370f-07a5-0ef1-1c9d-54c1c36e449b
* Content: [Office 365 US Government DOD endpoints - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I will find the appropriate engineering resource to make this change and update the issue when I have any new information. -Kelley

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
