### ISSUE TITLE
Support for Windows Server 2019 and 2022

### ISSUE THREAD

**Issue by nbsol1** [MicrosoftDocs/microsoft-365-docs#9181]
For adding device tags by setting a registry key value, is there a plan to add support for Windows Server 2019 and 2022? And is there any other way to set the tag for these devices without having to do it manually? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51c29286-b601-4dad-0e65-227c8d045ee4
* Version Independent ID: 2af4acf9-4089-5dff-d628-16b8425e0a57
* Content: [Create and manage device tags](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-tags?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machine-tags.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine-tags.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@nbsol1 Thank you for your feedback. 

You can add device tags using API -https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/add-or-remove-machine-tags?view=o365-worldwide

I don't see the plan to add support for Windows Server 2019 and 2022 in the roadmap. I'd recommend you post this question in our main feedback portal - https://feedbackportal.microsoft.com , So that our Dev or product group engineer will be able to respond.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@nbsol1 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
