### ISSUE TITLE
Cloud App Security encrypted files are not to be opened

### ISSUE THREAD

**Issue by AlexSchwerzmann** [MicrosoftDocs/microsoft-365-docs#922]
If you have Cloud App Security encrypting some files automatically by governance action, they can't be opened with Office Online. Following an answer in a Microsoft Case, Engineers are working to provide this functionality next year.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?source=docs#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by cabailey** [comment]
@AlexSchwerzmann Thanks for sharing your experience.  I'll look into this to see if this limitation should be added to this page.

**Comment by daesimps** [comment]
I have the same experience.  If Cloud App Security labels a file through a policy it can no longer be opened in Office Online.  You get the same error that you used to get before enabling this preview - "Sorry, Word can't open this document in a browser because it's protected by Information Rights Management (IRM). To view this document, please open it in the desktop version of Microsoft Word."
