### ISSUE TITLE
Changes to safe-links and the TABL

### ISSUE THREAD

**Issue by idontknowwhattocallit** [MicrosoftDocs/microsoft-365-docs#9237]
Recent changes to safe-links to move blocked URLs into the TABL have changed the way safe-links functions.  If a user is sent an email that contains a blocked URL, the email itself will be blocked with the email categorized as high-confidence phishing.  The intended recipient will not be able to release the email nor click on any links in the email.  The email section of this page should be re-written to reflect the current functionality of this product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@idontknowwhattocallit, the current note in the topic says this:

> You can now manage block URL entries in the [Tenant Allow/Block List](https://docs.microsoft.com/microsoft-365/security/office-365-security/allow-block-urls#use-the-microsoft-365-defender-portal-to-create-block-entries-for-urls-in-the-tenant-allowblock-list). The "Block the following URLs" list is in the process of being deprecated. We'll attempt to migrate existing entries from the "Block the following URLs" list to block URL entries in the Tenant Allow/Block List. Messages containing the blocked URL will be quarantined.

Is this incorrect?

I know that in the Tenant Allow/Block List content says blocked URLs are identified as phishing, not high confidence phishing.

Comments?

**Comment by idontknowwhattocallit** [comment]
They are definitely marked as high-confidence phishing, and the description of how safelinks currently functions for email is now out of date.  Safe Links no longer blocks URLs in emails, it blocks the entire email instead.

"Safe Links immediately checks the URL before opening the website:

If the URL is included in the Block the following URLs list, a [blocked URL warning] opens."

**Comment by dhairyya** [comment]
I dont get the question here. Are we talking about email delivery or blocking at time of click?
the time of click blocking information is accurate and safe links is checking Tenant allow/block list as there is no block list in safelinks. 

@chrisda  could you please update the email section of safelinks to reflect this?

**Comment by idontknowwhattocallit** [comment]
Email delivery.  Emails are blocked if they contain a URL listed in the TABL.  Microsoft has assured me over the last four months that this is intentional behavior and not a bug.

**Comment by chrisda** [comment]
@dhairyya, I'm having trouble parsing both what needs to be changed/added and where to do it. If you can, please make whatever changes you see fit directly in the topic and @ include me in the comments of the PR.

@idontknowwhattocallit, you, too, are free to directly modify the topic with whatever changes you want. Super-easy instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md). @ include me in the comments.

**Comment by johnwhirsch** [comment]
I may be having the same issue the original poster was describing, I'll share our specific scenario. We want to block every link to "sites.google.com/~" by default. But, we have vendors with a link in their email that links to a sites.google.com page. 

Since the migration from SafeLinks -> TABL, these emails now get sent to quarantine with the following categorizations:
**Quarantine reason:** High Confidence Phish
**Policy type:** Anti-spam policy
**Threats** None
**Blocked by organization policy:** Tenant Allow/Block List URL blocked

We do not want these emails blocked, which is why we chose to block sites.google.com in SafeLinks rather than via a mail flow rule (in the before times). Now, we can't receive emails with sites.google.com unless we remove it from our TABL since there is no way to create an exception.

What I would love to see is the ability to add URLs with an "allow" action and have the TABL apply the most specific rule. In example:
Block: sites.google.com/~
Allow: sites.google.com/cheapvendorwebsite/~

**Comment by idontknowwhattocallit** [comment]
@johnwhirsch This is the new behavior, and they've finally clarified their documentation months after changing it.  Support insists this is working as intended, however I did manage to convince them to change the behavior of blocked domains in the TABL to match the behavior of blocked URLs.
