### ISSUE TITLE
Text within rule undermines advice of article

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/microsoft-365-docs#928]
The strong advice in "Create safe sender lists in Office 365" is to use transport rules instead of the allow senders list ("This option should be avoided if at all"). Yet when you create a transport rule, save it, and then go back into it, you see this questionable reference:

https://i.imgur.com/oYtS8zi.png

While it's technically true, I think it should be rewritten to convey the general advice. Otherwise, people will just click the link and do it the other way instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79bb5c3-e92a-583b-337a-1a038e50f064
* Version Independent ID: 253ccf77-2d74-dd95-2686-a8fcdc424c7a
* Content: [Create block sender lists in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365#feedback)
* Content Source: [microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MaratMussabekov** [comment]
Hello @rpodric,
For sure, this reference should be changed as it contradicts the general recommendation and could lead to creation of unsafe allow lists.

Dear @MSFTTracyP, @mypil,
This issue isn't related to the documentation and should be addressed to the product team (Exchange Server/Exchange Online team).

Thank you

**Comment by mypil** [comment]
@MSFTTracyP - Can you please share your insights for this issue?

Thank you.

cc: @kenwith

**Comment by MSFTTracyP** [comment]
The strong advice in the article "Create block sender lists in Office 365" is to choose the appropriate method(s) in your environment:

When creating a Block list it's important to pick the appropriate method based on the scope of the impact (how many people will be impacted), so that it matches the breadth of the blocking method. The options listed below are ranked by both scope and breadth. The list goes from narrow to broad, but read the specifics for full recommendations.

- Outlook Blocked Senders
- Anti-Spam policy: Sender/Domain Block lists
- Exchange Transport Rules (ETRs also called mail-flow rules)
- Anti-Spam policy: IP Block Lists

And, stated in another article, called "Create safe sender lists in Office 365":

You should always restrict your Allow lists because they bypass many security measures. You must recheck all Allow lists as a part of your standard maintenance, so that you are aware of who is permitted to bypass. The recommendation is to use restrictive ETRs where possible.

- Exchange Transport Rules (ETRs also called mail-flow rules)
- Outlook Safe Senders
- Anti-spam policy: IP Allow Lists
- Anti-spam policy: Sender/Domain Allow Lists

There are also many warnings that the admin must understand the risk allows and bypasses create to security. Mentioning that there are other methods of creating allows or blocks after the fact does not abrogate the thinking and judgement that admins make about which is right for their environment as a result of reading these articles.
