### ISSUE TITLE
Ip address missing for streaming.realtimetelemetry.teams.microsoft.com

### ISSUE THREAD

**Issue by triumfas** [MicrosoftDocs/microsoft-365-docs#9335]
Hi,

streaming.realtimetelemetry.teams.microsoft.com resolves to 20.40.202.5 and that IP or IP range is missing in O365 endpoint list.
When this IP is blocked - Teams meetings live data is not showing up in admin.teams.microsoft.com and also Teams client application cannot send live data info to the cloud.

**Comment by yogkumgit** [comment]
@triumfas Please let us know which document you are referring to. Thanks

**Comment by triumfas** [comment]
Referring to this document: https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
It should fall under ID 12 which includes "*.teams.microsoft.com"

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by triumfas** [comment]
Hi,
@yogkumgit @kelleyvice-msft - any updates regarding this?

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
