### ISSUE TITLE
Microsoft Defender for Endpoint for WSL

### ISSUE THREAD

**Issue by cpinotossi** [MicrosoftDocs/microsoft-365-docs#9409]
Does defender support wsl?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 944b7b97-efbf-e83d-9330-a825d901819d
* Version Independent ID: 6c49c1c5-a178-0c9d-4768-fef1507b1a55
* Content: [Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@cpinotossi Thank you for your feedback. As of now, the Microsoft defender for endpoint is not supported in WSL. However, you can leave your feedback on our main feedback portal - https://feedbackportal.microsoft.com/ so that one of our dev/product group engineers will be able to provide more information on whether this is in pipeline.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@cpinotossi Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
