### ISSUE TITLE
Steps for removing yourself from the blocked senders list cannot be followed

### ISSUE THREAD

**Issue by samueloakley** [MicrosoftDocs/microsoft-365-docs#9449]
I'm not sure this is the correct place for this feedback, but the blocked senders delist portal at https://sender.office.com/ doesn't seem to be working as described in the linked docs page.

The form cannot be fully completed due to what seems like a timeout error and the email address given to manually request a delisting (delist@messaging.microsoft.com) cannot be delivered to as the email system isn't responding.

Do we know if the delist portal is still maintained? If not, could the documentation be amended to reflect this?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390d461b-7fce-d4ac-1c90-97b7b81dc0c2
* Version Independent ID: 9f8c7285-627f-13c6-1c7a-88fa7e14ed86
* Content: [Remove yourself from the blocked senders list and address 5.7.511 Access denied errors - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@samueloakley Thank you for your feedback. The delist portal is still maintained. If there are errors pertaining to removing yourself from the blocked senders, I'd recommend you contact support via the need help section on the admin center.

Also, the feedback about the products can be provided directly on the main feedback portal- https://feedbackportal.microsoft.com/  so that a dev/product engineer will be able to answer and address it.

Hope this helps!

Thanks
Sri

**Comment by samueloakley** [comment]
@msbemba Thank you I will raise an issue there.
