### ISSUE TITLE
Elevated permissions required to install AzureAD module?

### ISSUE THREAD

**Issue by mathieuric** [MicrosoftDocs/microsoft-365-docs#9491]
Hi,

Is there a specific reason why [Step 1](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide#step-1-install-the-required-software) requires an elevated session to install the AzureAD module?

Installing the module and connecting to AAD in the CurrentUser's scope works fine.

Here's how I did it:

```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Install-Module -Name AzureAD -Scope CurrentUser
Import-Module -Name AzureAD
Connect-AzureAD
```

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55574af9-0105-dcd1-7eb0-77513df4e54f
* Version Independent ID: 5fe2849b-d39a-4d75-a5ce-e8f577c9a161
* Content: [Connect to Microsoft 365 with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by DMoenks** [comment]
I would suppose the "requirement" for an elevated PowerShell session simply results from the introductory sentence, referencing a one-time per-computer install, which would actually need an elevated session.
As per-user installs work as well and the difference between per-computer and per-user installations are a generic PowerShell topic rather than a specific AzureAD module topic, it might help to remove the mentioning of per-computer installs and elevated sessions and instead simply refer to [Install-Module](https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-5.1) for installation options.

**Comment by msbemba** [comment]
@mathieuric Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9522

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mathieuric Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
