### ISSUE TITLE
Add information related to licensing requirements to deploy the AIP Scanner

### ISSUE THREAD

**Issue by flmihai91** [MicrosoftDocs/microsoft-365-docs#9524]
Currently, there is a lot of confusion in terms of licenses required to configure the AIP Scanner and its different capabilities. While we know that the scanning in discovery mode is E3 and auto-labelling is E5, scenarios like assigning a default label via the scanner creates a lot of confusion.

In a particular scenario with one of my customers, after the CSAM involved someone from the Licensing team, that person confirmed that the Scanner has an E3 minimum requirement.

Could you please update the documentation to avoid this level of confusion?
It might be worth adding a licensing requirements section in the AIP Scanner docs as well:
https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner-prereqs

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Automatically apply a sensitivity label in Microsoft 365 - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@flmihai91 At the top of this page, and all pages for sensitivity labels, is a link to the authoritative licensing information. Specifically for sensitivity labeling scenarios, see the "Sensitivity labeling" section: https://docs.microsoft.com/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-sensitivity-labeling 

If you don't find your licensing questions addressed there, leave feedback on that page so it goes to the right people.  They are the people who own licensing.  Licensing statements elsewhere, including in the technical documentation, could be out of date, so it's always best to go to the authoritative source.  With new licensing options frequently becoming available and sometimes changing, that's why I no longer include licensing statements in the technical documentation - even with the best of intentions, they quickly become out of date and potentially, inaccurate.
