### ISSUE TITLE
browser usage card missing

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#9560]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f954abb9-d978-b70d-c136-623a76317ddc
* Version Independent ID: d4a88bcd-ac54-ca82-9b9a-0e22da92b74b
* Content: [Microsoft 365 admin center browser usage reports - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/browser-usage-report?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/browser-usage-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/browser-usage-report.md)
* Service: **o365-administration**
* GitHub Login: @sarahwxy
* Microsoft Alias: **waxiaoyu**

**Comment by msbemba** [comment]
@gkens Thank you for your feedback. I was able to test and find the Microsoft Browser usage card on the page https://admin.microsoft.com/Adminportal/Home?#/reportsUsage

![image](https://user-images.githubusercontent.com/45987684/188430428-ca7ff304-f53c-478a-840e-a619ce233832.png)


If you continue to have this problem, Please click on the need help option on the admin center to raise a support ticket so that a Microsoft engineer can fix this issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @gkens Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
