### ISSUE TITLE
Consideration callout for Set-RetentionCompliancePolicy for Managing Changes to Policies

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#9576]
In working with Retention Policies, making many changes to a policy at once, it has come up that looping is not the supported or recommended way to make changes to a policy. This is due to the Note" on the cmdlet documentation - https://docs.microsoft.com/en-us/powershell/module/exchange/set-retentioncompliancepolicy?view=exchange-ps.

Can a "Considerations" section be added to this PS Cmdlet List document that outlines the correct way to make multiple changes to a policy, without using looping? For Example:

**_
#User List with "Name" and "Email" fields. "Email" field should be populated with primary SMTP Address.
$users = Import-CSV C:\Documents\UsersList.csv
Set-RetentionCompliancePolicy -Identity "Email - Contoso Policy - 7 Year" -AddExchangeLocation $users.Email
_**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d81d6dc-9ac9-62f8-8a28-12a18988527e
* Version Independent ID: 2d81d6dc-9ac9-62f8-8a28-12a18988527e
* Content: [Identify the available PowerShell cmdlets for retention - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-cmdlets?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-cmdlets.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-cmdlets.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@SeanTGeoghegan Thank you for your feedback & I will consider it for a future update, but I think it's outside the scope of this article that's "to identify the main PowerShell cmdlets that are available for retention policies and retention labels that you might need for configuration at-scale, automated scripts, or advanced configuration scenarios". Details and recommendations for individual cmdlets belong with their respective cmdlet help documentation, otherwise it risks duplication and misalignment - which is then very confusing for customers.
