### ISSUE TITLE
What this command will do Execute-AzureAdLabelSync

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/microsoft-365-docs#961]
Its mentioned in Step 4 that we need to run this command. Could you please describe what actions are taken by this command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **krowley**

**Comment by cabailey** [comment]
@prashant1380  As the cmdlet name suggests, it synchronizes labels from your admin labeling center (such as Office 365 Security & Compliance Center) to Azure AD, so that they can be used by Office 365 groups that are stored in Azure AD. This is required because Azure AD can't make a call to retrieve the labels, so the labels are pushed there by using this cmdlet.  After running it once after the feature is enabled, the synchronization happens automatically.

We've added some additional context in the documentation, so I'll go ahead and close this issue. Thanks for your question!
