### ISSUE TITLE
Potential clarification needed in Audit Log documentation

### ISSUE THREAD

**Issue by joebloggs12** [MicrosoftDocs/microsoft-365-docs#9655]
This page has potentially confusing statements:

"If 50,000 results are found, you can probably assume that there are more than 50,000 events that met the search criteria. You can either refine the search criteria and rerun the search to return fewer results, or you can export all of the search results by selecting Export results > Download all results."

This could imply that you can download more than 50,000 events - If there are more than 50,000 events refine search criteria or export all (all 50,000 or all results that meet criteria?) of the search results.

And then later in the document:

"You can download a maximum of 50,000 entries to a CSV file from a single audit log search. If 50,000 entries are downloaded to the CSV file, you can probably assume there are more than 50,000 events that met the search criteria. To export more than this limit, try using a date range to reduce the number of audit log entries. You might have to run multiple searches with smaller date ranges to export more than 50,000 entries."

This is clearer than the first statement.

As a sidenote - this seems like quite a small limitation, is there any way this can be increased?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?redirectSourcePath=%252fen-US%252farticle%252fSearch-the-audit-log-in-the-Office-365-Protection-Center-0d4d0f35-390b-4518-800e-0c7ec95e946c&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@joebloggs12 Thank you for your feedback. You can export all of the 50,000 search results by selecting **Export results** \> **Download all results**. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9726

Once the author approves, the changes will be live.

Meanwhile, since you have product feedback to increase the limitation - I'd recommend you post this on our main feedback portal -https://feedbackportal.microsoft.com/ . One of our Dev/Product engineers will be able to provide you information on why there's a limit and/or provide more information on when this limitation will be changed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @joebloggs12 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
