### ISSUE TITLE
ID 130 is not added in the article to while list the URL in network. 

### ISSUE THREAD

**Issue by maykul** [MicrosoftDocs/microsoft-365-docs#9666]
We are redirected to this page from https://docs.microsoft.com/en-us/power-platform/admin/enable-profile-card

As mentioned in this article Note : https://docs.microsoft.com/en-us/power-platform/admin/enable-profile-card

"To view the complete endpoint requirements for connectivity from a user's machine to Microsoft 365 for profile cards to be displayed in Unified Interface, see [Microsoft 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#microsoft-365-common-and-office-online) **ID 130**."

Highlighted **ID 130** is not available in this article : https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online

Please update ID 130 in this article to avoid this discrepancy. 

We have a  VIP customer affected by this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
