### ISSUE TITLE
Passive mode AND EDR in block mode?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#9676]
What should `Get-MpComputerStatus | select AMRunningMode` display in case Windows Defender is in Passive mode (e.g. McAfee is the primay AV solution) and Defender is in EDR block mode (which seems to be the default?)
Should it display **Passive** or **EDR Block Mode**? How can we tell the difference between **Normal** or **Passive** in case **EDR Block Mode** is displayed? Is the existence of the registry key `HKLM\SOFTWARE\Policies\Microsoft\Windows Advanced Threat protection\ForceDefenderPassiveMode` with value 1 enough proof of Passive mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61024433-366d-5ea3-4a3f-0cdd5cdcd900
* Version Independent ID: 348d3fc9-0937-b3a6-897e-09d1236d7019
* Content: [Microsoft Defender Antivirus compatibility with other security products](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide#requirements-for-microsoft-defender-antivirus-to-run-in-passive-mode)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@andrePKI Thank you for your feedback. 

You can use PowerShell to confirm that EDR in block mode is turned on with Microsoft Defender Antivirus running in passive mode.
When you execute the cmdlet  Get-MPComputerStatus|select AMRunningMode

If Microsoft Defender Antivirus is in active mode, you will see Normal instead of EDR Block Mode
If Microsoft Defender Antivirus is in passive mode, you will see  EDR Block Mode

The existence of a registry key is also enough proof for passive mode. For more information, see  Endpoint detection and response (EDR) in block mode - https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/edr-in-block-mode?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by andrePKI** [comment]
Yes that helps, thank you. Could it be clarified in the document also?

**Comment by msbemba** [comment]
@andrePKI  I have added the document [EDR in block mode](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/edr-in-block-mode?view=o365-worldwide) to the related articles for reference. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @andrePKI Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
