### ISSUE TITLE
ID 22 incorrect IPs

### ISSUE THREAD

**Issue by bradbrill** [MicrosoftDocs/microsoft-365-docs#9765]
ID 22 lists the Live Events endpoints as:

endpoint1-proddodcecompsvc-dodc.streaming.media.usgovcloudapi.net [52.181.180.135/32]

endpoint1-proddodeacompsvc-dode.streaming.media.usgovcloudapi.net [52.182.53.6/32]

 

What we are observing traffic and DNS records pointing to is as follows:

 

endpoint1-proddodeacompsvc-dode.streaming.media.usgovcloudapi.net [52.181.167.113]

endpoint1-proddodcecompsvc-dodc.streaming.media.usgovcloudapi.net [52.182.52.226]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45a2f60-4f5f-2ee3-5a2a-aeccf6c8b767
* Version Independent ID: 2335370f-07a5-0ef1-1c9d-54c1c36e449b
* Content: [Office 365 US Government DOD endpoints - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue,. thanks

**Comment by kelleyvice-msft** [comment]
Working with the endpoints PM to resolve.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
