### ISSUE TITLE
b2clogin.com needed to be added

### ISSUE THREAD

**Issue by mcnaugha** [MicrosoftDocs/microsoft-365-docs#9893]
Please can you add b2clogin.com to help others avoid the failed training course we had today.

Ref: [https://learn.microsoft.com/en-us/azure/active-directory-b2c/b2clogin](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd333ae2-34f6-4afd-cdb1-db72303a5736
* Version Independent ID: 5fc52fe8-dade-b8b7-7126-c4e7dd902e62
* Content: [Office 365 IP Address and URL web service - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-ip-web-service.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-ip-web-service.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.
