### ISSUE TITLE
missing 

### ISSUE THREAD

**Issue by funzel1** [MicrosoftDocs/microsoft-365-docs#9927]
[Enter feedback here]
Hi,
topic "The number of weeks that the notifications will be sent"   missing in configuration details (incl. max value)
Also missing if nobody  taking ownership, how retrigger notifications if max weeks of notifications expired ->Faq article?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44c73a40-30f1-78f4-9130-37790d58fcda
* Version Independent ID: 44c73a40-30f1-78f4-9130-37790d58fcda
* Content: [Manage ownerless Microsoft 365 groups and teams - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/ownerless-groups-teams?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/ownerless-groups-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/ownerless-groups-teams.md)
* Service: **microsoft-365-business**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@funzel1 Thank you for your feedback.

The number of weeks the notification is sent has been  to the document ->

![image](https://user-images.githubusercontent.com/45987684/197368236-b5335afb-ddfe-4e29-9c35-b8c9d0d74129.png)


We have also added the information about what happens if nobody takes ownership (Faq article - https://learn.microsoft.com/en-us/exchange/troubleshoot/groups-and-distribution-lists/ownerless-group-policy#what-occurs-if-the-notification-period-ends-and-members-dont-respond)

Assume that the notification period is four weeks. After four weeks, the notifications are no longer sent. In [Microsoft Purview compliance portal](https://go.microsoft.com/fwlink/p/?linkid=2077149), admins can see which ownerless group is unattended in the [audit log](https://learn.microsoft.com/en-us/microsoft-365/compliance/set-up-basic-audit#step-3-search-the-audit-log) by selecting the Unattended ownerless group activity. If an audit log is generated, admins can see an alert in the compliance portal. In this scenario, Microsoft 365 groups don't take any further action. Admins have to take further action on their own to resolve the status of ownerless groups, such as contacting group members directly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @funzel1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by funzel1** [comment]
Hello @yogkumgit @msbemba 
thanks for your feedback. We now thinkig about requesting  a product change having the possibility to retrigger group notifications. 
Option could be also showing it in the admin console..
Pureview is an area which is restricted from access view and also not an option for a large count of affected groups
