### ISSUE TITLE
21Vianet Company Name Change

### ISSUE THREAD

**Issue by hw2B440** [MicrosoftDocs/microsoft-365-docs#9936]
21Vianet changed their name last year:
https://www.reuters.com/markets/companies/VNET.OQ/
https://markets.businessinsider.com/news/stocks/21vianet-looks-for-new-chapter-with-name-change-1030857057
https://www.sec.gov/Archives/edgar/data/1508475/000110465921124591/tm2129602d1_ex99-1.htm
Can this article be updated please?
Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec9d22a-5645-f235-2279-64b9194f87e6
* Version Independent ID: e9e0e8f0-e599-3db3-309e-e90c0e43d879
* Content: [Office 365 operated by 21Vianet - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/services-in-china/services-in-china?view=o365-21vianet)
* Content Source: [microsoft-365/admin/services-in-china/services-in-china.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/services-in-china/services-in-china.md)
* Service: **microsoft-365-business**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@hw2B440 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9965

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by SKjerland** [comment]
@hw2B440 - I'm the owner of this article and I want to thank you for bringing this to our attention. I've reached out to our Legal team to get confirmation on the name change and to get guidance on documentation updates. Once I hear back from them, we'll make the required changes to this article and all others that are impacted. I'll go ahead and keep this issue open until we have a resolution in place, as directed by our Legal team.

**Comment by SKjerland** [comment]
@hw2B440 - Our Legal team confirmed that we have not been instructed by our contacts at 21Vianet to change the name in our documentation. They cautioned that just because a company buys controlling interest in another company, it doesn't necessarily mean that the purchased company is rebranded. In fact, it often is not. So, per instructions from our Legal team, we will not be updating the name. Thank you, again, for bringing it to our attention so we could look into it further. 
CC: @msbemba, @yogkumgit
