### ISSUE TITLE
URL title is incorrect

### ISSUE THREAD

**Issue by manderson97** [MicrosoftDocs/microsoft-365-docs#9938]
URL title is incorrectly showing Configure Microsoft 365 retention settings to automatically retain or delete content - Microsoft Purview (compliance)

It should be showing: Common settings for retention policies and retention label policies - Microsoft Purview (compliance)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 592d6717-d670-14a8-acbe-c648958ca208
* Version Independent ID: 9bc46fd9-50e1-1e58-4852-22068e2980ae
* Content: [Configure Microsoft 365 retention settings to automatically retain or delete content - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-settings?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
These are different by design, as is often the case:  The first one is the metadata title that displays in Search results, so no existing context.  That's why it has a reference to Microsoft 365 and includes the explanation why you would want to configure the settings.  The second is what is displayed on the page where it's in context of other information such as the TOC in the left nav, and comes after other articles that explain what retention policies and retention label policies are.
