### ISSUE TITLE
Microsoft Defender for Business 

### ISSUE THREAD

**Issue by hasuzuki0005** [MicrosoftDocs/microsoft-365-docs#9950]
[Thank you for the article! Please help to include whether Microsoft Defender for Business is eligible for this function or not. Our customers and partners are keen to know.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb9a6dfb-2853-20fc-bd6c-2f636945b328
* Version Independent ID: 60586381-2d76-32bc-8e44-342ee36ada1c
* Content: [Onboard Windows devices in Azure Virtual Desktop](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@hasuzuki0005 Thank you for your feedback. Currently, Microsoft Defender for Business is not eligible for this function. If you would like to know more about the roadmap, Please leave your feedback on our main feedback portal (https://feedbackportal.microsoft.com/) so that one of our dev/product engineers will be able to provide more details on whether this will be eligible in the future or not.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@hasuzuki0005 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by hasuzuki0005** [comment]
Sure, thank you for your response and guidance.

Thanks,
Hajime
