### ISSUE TITLE
Enabling archives in the compliance purview portal no longer exists

### ISSUE THREAD

**Issue by joelgilbert86** [MicrosoftDocs/microsoft-365-docs#9996]
The ability to enable archive mailboxes in the compliance purview portal has been removed with change announced in MC422154

This article still states you can use it and should be updated to reflect this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
* Version Independent ID: 3b513017-641c-38ae-3938-03a9ee3a6923
* Content: [Enable archive mailboxes for Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-archive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@joelgilbert86 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10011

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by cabailey** [comment]
@joelgilbert86  Thank you for letting me know your tenant no longer sees the Archive tab in the compliance portal. I don't yet have confirmation from engineering that this is the case for all tenants (these changes rarely happen immediately for all tenants but in a phased deployment). Since the message center post says "from October 2022" (no specific date), I'll wait until I have that confirmation before removing the instructions for the compliance portal so we don't leave some customers without documentation if they choose to use this portal while they can.

In the meantime, as we transition, I've changed the wording from "Currently, you can use either the Microsoft Purview compliance portal or the new Exchange admin center (EAC) to enable or disable archive mailboxes." to: 

"Configuration to enable or disable archive mailboxes is moving from the Microsoft Purview compliance portal to the new Exchange admin center (EAC). Until this move is complete for all tenants, this page includes instructions for both admin experiences."
